### ISSUE TITLE
V3.1.2 - TH16 with ds18b20 sensor

### ISSUE THREAD

**Issue by muriloscosta** [bwp91/homebridge-ewelink#100]
**What issue do you have? Please be as thorough and explicit as possible.**

I have 5 TH16 at my home, 4 of them have AM2301 sensors that can read temperature and humidity, and only has a ds18b20 sensor, that measures temperature only, it has no humidity readings.

All TH16 with AM2301 are fine with V3.1.2, but the one with ds18b20 (TH16 Cozinha) is not working properly, the temp reading is fine, but the switch is not functioning.

At V3.0.0, TH16 with ds18b20 only issue is that it shows an alarm at apple homekit icon, I believe due to humidity reading failure, but switch works fine.

**Details of your setup.**
Do you use Homebridge or HOOBS?

Homebridge

Which version of Homebridge/HOOBS do you have?

Homebridge v1.2.3
Node.js v12.18.4
Npm v6.14.8

Which version of this plugin (homebridge-ewelink) do you have?

homebridge-ewelink v3.1.2

**Please paste any relevant logs below. It helps if you can turn `debug` and `debugReqRes` in the package settings for more thorough logging.**
> If you are posting an error then it is helpful for me to also see the previous few lines as this can show the cause of the error.

0|homebridge  | [9/27/2020, 3:15:25 PM] [eWeLink] [TH16 Cozinha] could not be updated as TypeError: Cannot read property 'Switch' of undefined
0|homebridge  |     at deviceThermostat.internalThermostatUpdate (/usr/local/lib/node_modules/homebridge-ewelink/lib/device/thermostat.js:15:58)
0|homebridge  |     at Characteristic.<anonymous> (/usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:612:65)
0|homebridge  |     at Characteristic.emit (events.js:315:20)
0|homebridge  |     at Characteristic.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/EventEmitter.js:60:38)
0|homebridge  |     at Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:369:23)
0|homebridge  |     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:967:36
0|homebridge  |     at Array.forEach (<anonymous>:null:null)
0|homebridge  |     at Bridge.Accessory._this._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:835:18)
0|homebridge  |     at HAPServer.emit (events.js:315:20)
0|homebridge  |     at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/EventEmitter.js:60:38)
0|homebridge  |     at HAPServer._this._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/HAPServer.js:731:23)
0|homebridge  |     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/HAPServer.js:240:39)
0|homebridge  |     at IncomingMessage.emit (events.js:315:20)
0|homebridge  |     at endReadableNT (_stream_readable.js:1220:12)
0|homebridge  |     at processTicksAndRejections (internal/process/task_queues.js:84:21)
0|homebridge  | .
0|homebridge  | [9/27/2020, 3:15:25 PM] [eWeLink] [TH16 Cozinha] requesting previous state to revert Homebridge state.
0|homebridge  | [9/27/2020, 3:15:29 PM] [eWeLink] [TH16 Cozinha] could not be updated as TypeError: Cannot read property 'Switch' of undefined
0|homebridge  |     at deviceThermostat.internalThermostatUpdate (/usr/local/lib/node_modules/homebridge-ewelink/lib/device/thermostat.js:15:58)
0|homebridge  |     at Characteristic.<anonymous> (/usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:612:65)
0|homebridge  |     at Characteristic.emit (events.js:315:20)
0|homebridge  |     at Characteristic.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/EventEmitter.js:60:38)
0|homebridge  |     at Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:369:23)
0|homebridge  |     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:967:36
0|homebridge  |     at Array.forEach (<anonymous>:null:null)
0|homebridge  |     at Bridge.Accessory._this._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:835:18)
0|homebridge  |     at HAPServer.emit (events.js:315:20)
0|homebridge  |     at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/EventEmitter.js:60:38)
0|homebridge  |     at HAPServer._this._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/HAPServer.js:731:23)
0|homebridge  |     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/HAPServer.js:240:39)
0|homebridge  |     at IncomingMessage.emit (events.js:315:20)
0|homebridge  |     at endReadableNT (_stream_readable.js:1220:12)
0|homebridge  |     at processTicksAndRejections (internal/process/task_queues.js:84:21)
0|homebridge  | .
0|homebridge  | [9/27/2020, 3:15:29 PM] [eWeLink] [TH16 Cozinha] requesting previous state to revert Homebridge st

**Comment by bwp91** [comment]
Hi, thanks for this report.
I am aware that the "DS18B20" sensor cannot read humidity and I have made provisions in the code to now display a humidity sensor accessory in HomeKit if this sensor is being used.
Looks like something isn't quite working.
Easiest way for me to look into this would be if you were happy to share the device with my ewelink account? Would you be happy to do this?

**Comment by muriloscosta** [comment]
sure, please let me know your ewelink id

**Comment by bwp91** [comment]
Which continent are you from? (need to know for sharing purposes!)

**Comment by muriloscosta** [comment]
Brazil, South America

**Comment by bwp91** [comment]
Okay please share to country code 55 
email ben_sa@thepotterfamily.uk

**Comment by muriloscosta** [comment]
done

**Comment by bwp91** [comment]
This has been fixed in v3.1.3 :)
