### ISSUE TITLE
Sonoff POW v1 and S26 show 2 separate devices

### ISSUE THREAD

**Issue by composerkaumann** [bwp91/homebridge-ewelink#104]
**What issue do you have? Please be as thorough and explicit as possible.**

Sonoff S26 shows up as 2 separate Accessories- switch and power point. Same goes for POW ver. 1. All others S20, Basic2 etc. show 1 Accessory. In both cases- switch accessory switches nothing, the working one us power accessory. Very annoying and messes up automations.

**Details of your setup.**
Do you use Homebridge or HOOBS?

Homebridge 1.2.3 and Homebridge Ewelink 3.2.1 (running on Synology Docker)

**Comment by bwp91** [comment]
Hi,
If you update to v3.2.2 then the "switch" accessory should be removed thus just showing the "outlet" accessory for all your outlets.
You'll then be able to set up your automations again (which yes I know is very annoying!)

**Comment by bwp91** [comment]
Did it work?

**Comment by composerkaumann** [comment]
for S26 yes
for POW v1 I still see a switch and power  outlet acceasories

===============
Tõnis Kaumann
mailto:music@music.ee
http://www.music.ee
ph. +372 56222285

**Comment by composerkaumann** [comment]
sorry
I also see pow and s26 all with 2  accessories still in 3.2.3, restarted hb also

===============
Tõnis Kaumann
mailto:music@music.ee
http://www.music.ee
ph. +372 56222285

**Comment by bwp91** [comment]
Editing your comments to remove your website and phone number that perhaps came from an email signature

**Comment by bwp91** [comment]
Could i message you directly on the homebridge discord channel?
https://discord.gg/7X36mdw

**Comment by bwp91** [comment]
I'm almost certain this issue has been fixed from talking on the homeridge discord. 
This is my reason for closing the issue.
Further issues please feel free to reopen with your comments!
