### ISSUE TITLE
iFan03 problem

### ISSUE THREAD

**Issue by DarkSyler21** [bwp91/homebridge-ewelink#106]
**What issue do you have? Please be as thorough and explicit as possible.**

when activating the Fan on full speed (99%) when pressing the tile from the home page getting this massages:
10/5/2020, 1:15:14 PM [eWeLink] Web socket closed [1006].
10/5/2020, 1:15:14 PM [eWeLink] Web socket will try to reconnect in five seconds.
and all accessories stop working. I only have iFan03 and L1 led strip and nothing works. it does show like its working but nothing happens.

**Details of your setup.**
Do you use Homebridge or HOOBS?

HOOBS

Which version of Homebridge/HOOBS do you have?

3.2.6
Which version of this plugin (homebridge-ewelink) do you have?

3.3.2

**Please paste any relevant logs below. It helps if you can turn `debug` and `debugReqRes` in the package settings for more thorough logging.**
> If you are posting an error then it is helpful for me to also see the previous few lines as this can show the cause of the error.

after reset the services it strats working again and a few minutes later when trying the same thing it stops working again with same problem

**Comment by bwp91** [comment]
Hi, just want to check a couple of things first.

* Are you using homebridge-ewelink or homebridge-ewelink-max plugin? Looking back at your [previous issue](https://github.com/bwp91/homebridge-ewelink/issues/78) at the time you had homebridge-ewelink-max installed. If you are now using this plugin (homebridge-ewelink) then have you uninstalled ewelink-max plugin?
* Do you use a "shared" ewelink account for Homebridge, by this I mean - have you set up a second ewelink account and shared your devices to it to use in Homebridge?

**Comment by Idan212** [comment]
> Hi, just want to check a couple of things first.
> 
> * Are you using homebridge-ewelink or homebridge-ewelink-max plugin? Looking back at your [previous issue](https://github.com/bwp91/homebridge-ewelink/issues/78) at the time you had homebridge-ewelink-max installed. If you are now using this plugin (homebridge-ewelink) then have you uninstalled ewelink-max plugin?
> * Do you use a "shared" ewelink account for Homebridge, by this I mean - have you set up a second ewelink account and shared your devices to it to use in Homebridge?

Hi yeah I changed because I’ve found it unreliable and causing trouble to my service. 
Now I’m using yours.

As for the second thing this is how I’m using it. The account on my phone is different than the account I’ve setup in HOOBS.

**Comment by bwp91** [comment]
And you’ve uninstalled the max version?
Out of interest, would you try using your “phone” ewelink account details in the plugin to see if this helps?

**Comment by Idan212** [comment]
> And you’ve uninstalled the max version?
> Out of interest, would you try using your “phone” ewelink account details in the plugin to see if this helps?

Yes I’ve uninstalled it and verified via config it’s not there. 
I can check sure I’ll keep you updated. 
But as I read it should cause problems later when trying login to the app, no?

**Comment by bwp91** [comment]
> But as I read it should cause problems later when trying login to the app, no?

This definitely used to happen.
Doesn’t seem to anymore. I’ve used the same details for my phone and homebridge now for many weeks with no “log out” issues

**Comment by Idan212** [comment]
> > But as I read it should cause problems later when trying login to the app, no?
> 
> This definitely used to happen.
> Doesn’t seem to anymore. I’ve used the same details for my phone and homebridge now for many weeks with no “log out” issues

ok as you said no problem on the app.
having different issue with the plugin:
10/5/2020, 2:31:56 PM [eWeLink] [LightFan] could not be updated as unknown parameters received.
10/5/2020, 2:31:58 PM [eWeLink] [LightFan] could not be updated as unknown parameters received.
10/5/2020, 2:32:05 PM [eWeLink] [LightFan] could not be updated as unknown parameters received.
10/5/2020, 2:32:07 PM [eWeLink] [LightFan] could not be updated as unknown parameters received.
10/5/2020, 2:32:11 PM [eWeLink] [LightFan] could not be updated as unknown parameters received.
10/5/2020, 2:32:13 PM [eWeLink] [LightFan] could not be updated as unknown parameters received.
10/5/2020, 2:32:29 PM [eWeLink] [LightFan] could not be updated as unknown parameters received.
10/5/2020, 2:32:34 PM [eWeLink] [LightFan] could not be updated as unknown parameters received.
10/5/2020, 2:32:36 PM [eWeLink] [LightFan] could not be updated as unknown parameters received.
10/5/2020, 2:33:10 PM [eWeLink] [LightFan] could not be updated as unknown parameters received.
10/5/2020, 2:33:19 PM [eWeLink] [LightFan] could not be updated as unknown parameters received.
10/5/2020, 2:33:34 PM [eWeLink] [LightFan] could not be updated as unknown parameters received.
10/5/2020, 2:33:35 PM [eWeLink] [LightFan] could not be updated as unknown parameters received.
10/5/2020, 2:33:39 PM [eWeLink] [LightFan] could not be updated as unknown parameters received.
10/5/2020, 2:33:43 PM [eWeLink] [LightFan] reported [offline] via [WS].
10/5/2020, 2:33:43 PM [eWeLink] [LightFan] could not be updated as unknown parameters received.
10/5/2020, 2:33:47 PM [eWeLink] [LightFan] could not be updated as it is unreachable. It's status will be corrected once it is reachable.
10/5/2020, 2:33:47 PM [eWeLink] [LightFan] Homebridge state will be synced once the device comes back online.
10/5/2020, 2:33:47 PM [eWeLink] [LightFan] could not be updated as it is unreachable. It's status will be corrected once it is reachable.
10/5/2020, 2:33:47 PM [eWeLink] [LightFan] Homebridge state will be synced once the device comes back online.
10/5/2020, 2:33:54 PM [eWeLink] [LightFan] could not be updated as it is unreachable. It's status will be corrected once it is reachable.
10/5/2020, 2:33:54 PM [eWeLink] [LightFan] Homebridge state will be synced once the device comes back online.
10/5/2020, 2:33:56 PM [eWeLink] [LightFan] could not be updated as it is unreachable. It's status will be corrected once it is reachable.
10/5/2020, 2:33:56 PM [eWeLink] [LightFan] Homebridge state will be synced once the device comes back online.
10/5/2020, 2:34:15 PM [eWeLink] [LightFan] could not be updated as it is unreachable. It's status will be corrected once it is reachable.
10/5/2020, 2:34:15 PM [eWeLink] [LightFan] Homebridge state will be synced once the device comes back online.
10/5/2020, 2:34:17 PM [eWeLink] [LightFan] could not be updated as it is unreachable. It's status will be corrected once it is reachable.
10/5/2020, 2:34:17 PM [eWeLink] [LightFan] Homebridge state will be synced once the device comes back online.
10/5/2020, 2:34:21 PM [eWeLink] [LightFan] reported [online] via [WS].
10/5/2020, 2:34:53 PM [eWeLink] [LightFan] could not be updated as unknown parameters received.
10/5/2020, 2:34:54 PM [eWeLink] [LightFan] could not be updated as unknown parameters received.
10/5/2020, 2:35:13 PM [eWeLink] [LightFan] could not be updated as unknown parameters received.
10/5/2020, 2:35:14 PM [eWeLink] [LightFan] could not be updated as unknown parameters received.
10/5/2020, 2:35:25 PM [eWeLink] [LightFan] could not be updated as unknown parameters received.
10/5/2020, 2:35:25 PM [eWeLink] [LightFan] could not be updated as unknown parameters received.
10/5/2020, 2:35:35 PM [eWeLink] [LightFan] could not be updated as unknown parameters received.
10/5/2020, 2:35:36 PM [eWeLink] [LightFan] could not be updated as unknown parameters received.
10/5/2020, 2:43:55 PM [eWeLink] [LightFan] could not be updated as unknown parameters received.
10/5/2020, 2:43:57 PM [eWeLink] [LightFan] could not be updated as unknown parameters received.

every commend gives that error.
and as you can see in the middle it got offline for a second there when went to control via the app got back online

**Comment by bwp91** [comment]
Could I message you on the [Homebridge Discord](https://discord.gg/7X36mdw)?

**Comment by Idan212** [comment]
> Could I message you on the [Homebridge Discord](https://discord.gg/7X36mdw)?

sure its DarkSyler there
massaged you.

**Comment by bwp91** [comment]
iFan issues have been fixed and will be available in the upcoming v3.4.0 release :)
