### ISSUE TITLE
Web socket error logging

### ISSUE THREAD

**Issue by imtitanic** [bwp91/homebridge-ewelink#107]
**What issue do you have? Please be as thorough and explicit as possible.**

First of all: hi.

Second, I don't know if this error is about my ethernet connection but, since a few days ago an error (of the web socket) appears constantly on the homebridge logs and my OCD is feel very attacked. 

Ps. Devices still work fine on Home App so that's confusing me more.

**Do you use Homebridge or HOOBS?**

_Homebridge_ 

**Which version of Homebridge/HOOBS do you have?**

_v1.1.6_

**Which version of this plugin (homebridge-ewelink) do you have?**

_v3.3.0_

**Logs**

> [2020-10-4 19:42:22] [eWeLink] Web socket closed [1006].
> [2020-10-4 19:42:22] [eWeLink] Web socket will try to reconnect in five seconds.
> [2020-10-4 19:42:47] [eWeLink] Web socket error - [Error: connect ECONNABORTED 50.18.84.251:8080
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
>  {
>   errno: 'ECONNABORTED',
>   code: 'ECONNABORTED',
>   syscall: 'connect',
>   address: '50.18.84.251',
>   port: 8080
> }].
> [2020-10-5 5:01:38] [eWeLink] Web socket closed [1006].
> [2020-10-5 5:01:38] [eWeLink] Web socket will try to reconnect in five seconds.
> [2020-10-5 5:24:25] [eWeLink] Web socket closed [1006].
> [2020-10-5 5:24:25] [eWeLink] Web socket will try to reconnect in five seconds.
> [2020-10-5 5:24:41] [eWeLink] Web socket error - [Error: getaddrinfo ENOTFOUND us-pconnect2.coolkit.cc
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
>  {
>   errno: 'ENOTFOUND',
>   code: 'ENOTFOUND',
>   syscall: 'getaddrinfo',
>   hostname: 'us-pconnect2.coolkit.cc'
> }].
> [2020-10-5 5:24:41] [eWeLink] If this was unexpected then please try restarting Homebridge.
> [2020-10-5 5:24:41] [eWeLink] Web socket closed [1006].
> [2020-10-5 5:24:41] [eWeLink] Web socket will try to reconnect in five seconds.

**Comment by bwp91** [comment]
Hi,
Would you be happy to try out a pre-release version of this plugin? It hides more of the logs.
If you're happy to go ahead, then in the Homebridge terminal please run this command:
`sudo npm i -g homebridge-ewelink@beta`

**Comment by imtitanic** [comment]
i'm in, but to run the command i need uninstall the stable version or doesn't matter?

**Comment by bwp91** [comment]
You don’t need to uninstall the existing plugin, if you run that command it will just update it!
