### ISSUE TITLE
Add capability to set the startup setting of a switch

### ISSUE THREAD

**Issue by ttz642** [bwp91/homebridge-ewelink#108]
Similar to the set switch on or off by sending the required json to the appropriate url it's possible to set the switch default power on setting.

@bwp91 ,
Any way to directly email you directly, I have been using [ewelink-api](https://github.com/skydiver/ewelink-api) and ended up doing a couple of hacks to not have to rely on the WAN and really just operate locally. I wrote a filter to parse tcpdump output, wasn't aware of the node-dns-sd package at the time.

I'm not really wanting to install homebridge for my application but I'd like to be able to use your code so I'd possible like to make some suggestions to make the code a bit more stand-alone or at least include some code to make it possible to use as a library and not just as a homebridge plugin.

I only use the cloud to install and update the devices and then operate locally.

--
Steve

**Comment by bwp91** [comment]
Hi Steve,
Please feel free to message me directly on the Homebridge Discord channel 
https://discord.gg/7X36mdw
Happy to talk to you on there if you want!

**Comment by bwp91** [comment]
The feature you have suggested for this plugin (setting the power-on status) although possible via LAN mode, there is no “nice” way of implementing this in Homebridge/HomeKit.
There’s no way of implementing extra configurable options for accessories.
So for this reason I am going to close this issue. 
But i am definitely happy and willing to talk to you on the discord channel about implementing it in other ways 👍
