### ISSUE TITLE
WebSocket close logs (Reason 1006) every 3 minutes

### ISSUE THREAD

**Issue by shexbeer** [bwp91/homebridge-ewelink#11]
Hi, iam new to this project and want to thank you all for your efforts.
Had a little problem with ewelink on homebridge.
Getting error logs every 3 minutes regarding WebSocket closed abnormally (Reason 1006)
Is this a known issue in ewelink implementation or is this a acual error?

Here are the logs:
```
(.........)
Feb 10 21:41:04 HomebridgePi3 homebridge[18432]: [2018-2-10 21:41:04] [eWeLink] WebSocket was closed. Reason [1006]
Feb 10 21:41:09 HomebridgePi3 homebridge[18432]: WebSocketClient: reconnecting...
(.........)
Feb 10 21:43:50 HomebridgePi3 homebridge[18432]: WebSocketClient: retry in 5000ms 1006
Feb 10 21:43:50 HomebridgePi3 homebridge[18432]: [2018-2-10 21:43:50] [eWeLink] WebSocket was closed. Reason [1006]
(.........)
Feb 10 21:46:35 HomebridgePi3 homebridge[18432]: WebSocketClient: retry in 5000ms 1006
Feb 10 21:46:35 HomebridgePi3 homebridge[18432]: [2018-2-10 21:46:35] [eWeLink] WebSocket was closed. Reason [1006]
(.........)
Feb 10 21:49:20 HomebridgePi3 homebridge[18432]: WebSocketClient: retry in 5000ms 1006
Feb 10 21:49:20 HomebridgePi3 homebridge[18432]: [2018-2-10 21:49:20] [eWeLink] WebSocket was closed. Reason [1006]
(.........)
```

I should mention that everything works, but this logs make me think about some problems laying behind the scenes

**Comment by cecildaniel2003** [comment]
I have the exact same issue. Sometimes nothing happens but the home bridge accessories switch on and off in the app without actually changing the status of the relays.

**Comment by num1jug** [comment]
I have this issue also. Any insights after a year?
