### ISSUE TITLE
Cannot read property on sensor.js

### ISSUE THREAD

**Issue by imtitanic** [bwp91/homebridge-ewelink#114]
Hi!, I don't know if this is affecting the plugin because everything looks good (apparently) but it's appears on the log

**Details of your setup.**

**Homebridge:** v1.1.6

**Plugin:** v3.7.0

**Log:**

> [2020-10-20 12:46:34] [eWeLink] eWeLink sync complete. Don't forget to ⭐️  this plugin on GitHub if you're finding it useful!
> (node:952) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'updateCharacteristic' of undefined
>     at C:\Users\Homebridge Server\AppData\Roaming\npm\node_modules\homebridge-ewelink\lib\device\sensor.js:39:19
>     at Map.forEach (<anonymous>:null:null)
>     at deviceSensor.externalUpdate (C:\Users\Homebridge Server\AppData\Roaming\npm\node_modules\homebridge-ewelink\lib\device\sensor.js:32:26)
>     at eWeLinkPlatform.initialiseDevice (C:\Users\Homebridge Server\AppData\Roaming\npm\node_modules\homebridge-ewelink\lib\ewelink-platform.js:492:62)
>     at C:\Users\Homebridge Server\AppData\Roaming\npm\node_modules\homebridge-ewelink\lib\ewelink-platform.js:99:44
>     at Map.forEach (<anonymous>:null:null)
>     at C:\Users\Homebridge Server\AppData\Roaming\npm\node_modules\homebridge-ewelink\lib\ewelink-platform.js:99:26
>     at eWeLinkPlatform.eWeLinkSetup (C:\Users\Homebridge Server\AppData\Roaming\npm\node_modules\homebridge-ewelink\lib\ewelink-platform.js:122:9)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> 
> (node:952) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:952) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by bwp91** [comment]
Hi @imtitanic 
Can I confirm that you're using a DW2 device with a garage door setup?

**Comment by imtitanic** [comment]
Yep.

```
"groups": [
                {
                    "deviceId": "1000d24e48",
                    "type": "garage",
                    "setup": "oneSwitch",
                    "operationTime": 150,
                    "sensorId": "1000e38b7b"
                }
            ]
```

**Comment by bwp91** [comment]
Do you only see this error when you restart Homebridge?
I have an idea why you might be seeing this. When you restart Homebridge and the list of ewelink devices appear in the logs "initialising", what is initialised first? The sensor or the garage door device?

**Comment by imtitanic** [comment]
> Do you only see this error when you restart Homebridge?

Yeap, only when I restart.

> what is initialised first? The sensor or the garage door device?

Sensor

```
[2020-10-20 13:26:02] [eWeLink] [9] eWeLink devices loaded from the Homebridge cache.
[2020-10-20 13:26:02] [eWeLink] [6] primary devices loaded from your eWeLink account.
**[2020-10-20 13:26:02] [eWeLink]  → [Sensor de portón] initialised but LAN mode unavailable as device doesn't support it.**
[2020-10-20 13:26:02] [eWeLink]  → [Ventilador myFan] initialised and found locally with IP [192.168.101.115].
[2020-10-20 13:26:02] [eWeLink]  → [RF Bridge] initialised and found locally with IP [192.168.101.116].
[2020-10-20 13:26:02] [eWeLink]  → [Interruptor] initialised and found locally with IP [192.168.101.114].
[2020-10-20 13:26:02] [eWeLink]  → [Luz de Entrada ] initialised and found locally with IP [192.168.101.112].
**[2020-10-20 13:26:02] [eWeLink]  → [Puerta Eléctrica] initialised and found locally with IP [192.168.101.113].**
[2020-10-20 13:26:02] [eWeLink] eWeLink sync complete. Don't forget to ⭐️  this plugin on GitHub if you're finding it useful!
```

**Comment by bwp91** [comment]
I think my suspicions are correct. The sensor is being initialised before the garage door. When the sensor initialises, it also updates the state of the garage door, which at that exact moment of time doesn't exist in Homebridge yet.

In other words, we need the garage door to initialise *before* the sensor, so the garage exists in Homebridge when the sensor updates it.

I have applied a potential fix in v3.8.0. Please update and let me know if you still receive the error

**Comment by imtitanic** [comment]
After update message doesn't appear anymore.

... but now appears "initialised but LAN mode unavailable as device is unreachable" in every device and I don't know if are my devices or the plugin. haha

**Comment by bwp91** [comment]
@imtitanic are you still getting this `initialised but LAN mode unavailable as device is unreachable` for every device?
Could it have been a network problem at the time?

**Comment by imtitanic** [comment]
> Could it have been a network problem at the time?

I guess was that, because after rebooting (several times) finally all my devices got LAN mode.

Also I put the ip directly using ipOverride.

**Comment by bwp91** [comment]
LAN mode isn't *only* initialised when Homebridge starts by the way.
Whilst the plugin is running it can detect devices (including IP changes) and enable LAN mode as and when it can.

> Also I put the ip directly using ipOverride.

Just make sure they have a static IP from your router so the device IP never changes!
