### ISSUE TITLE
Sonoff T1 3 gang wall light switch

### ISSUE THREAD

**Issue by Andreew14** [bwp91/homebridge-ewelink#12]
Hi,

is is possible somehow to control Sonoff T1 UK: 3 Gang WiFi & RF 86 Type Smart Wall Touch Light Switch ?
https://www.itead.cc/sonoff-t1.html
I can see that accessory on Homekit but cannot be control?
Thank you

**Comment by MrTomAsh** [comment]
Please let me know what model is your HomeKit showing and I can try to add support for the 3 Gang one.

I've marked in a circle the model field.

My current code from issue #14 supports up to 2 gang switches. 

![img_1282](https://user-images.githubusercontent.com/368743/37567973-a0684270-2ac6-11e8-894e-5e5c9de71e99.jpg)

**Comment by luchobene** [comment]
I have the same problem, can you help me solve it? 
![20180330_214643000_ios_li](https://user-images.githubusercontent.com/37942986/38155325-a90174e8-3466-11e8-8163-50d096d2fd23.jpg)

**Comment by luchobene** [comment]
hi, has updated all the content of MrTomAsh / homebridge-ewelink and it is already working correctly

thank you

**Comment by aremishevsky** [comment]
can someone approve this PR?
https://github.com/MrTomAsh/homebridge-ewelink/pull/3

**Comment by FlyingKiwiJosh** [comment]
Also same issue with PSF-B04-GL 

Sonoff T1 UK3C

**Comment by brunokelo** [comment]
I have the same problem, the accessory appears as unknown.
