### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Stetocasa** [bwp91/homebridge-ewelink#120]
Hi Ben, adding the log, I don't know how explain the issue 

![image](https://user-images.githubusercontent.com/70729310/97540691-4bbe9e00-19c4-11eb-9ccb-667c01266d0c.jpeg)

**Comment by bwp91** [comment]
Which version of ewelink plugin are you using?

**Comment by bwp91** [comment]
Reviewing your logs again, it seems that HOOBS is trying to load the plugin twice. Could it be that you somehow have the two different versions of the plugin installed?

**Comment by Stetocasa** [comment]
> Reviewing your logs again, it seems that HOOBS is trying to load the plugin twice. Could it be that you somehow have the two different versions of the plugin installed?

I come back to hoobs factory reset, was a very disaster yesterday. How can I Really clean up ? I canceled the plug-in but the icons remaining inside hk

**Comment by bwp91** [comment]
> I come back to hoobs factory reset, was a very disaster yesterday. How can I Really clean up ? I canceled the plug-in but the icons remaining inside hk

You'll have to contact HOOBS support for this. If the icons are still in home app after a factory reset then it seems like a cache issue. I'm not an expert on how HOOBS works so you'll have to get in touch with them :)

**Comment by Stetocasa** [comment]
> > I come back to hoobs factory reset, was a very disaster yesterday. How can I Really clean up ? I canceled the plug-in but the icons remaining inside hk
> 
> 
> 
> You'll have to contact HOOBS support for this. If the icons are still in home app after a factory reset then it seems like a cache issue. I'm not an expert on how HOOBS works so you'll have to get in touch with them :)

What do you think about nose version? On log is reported that the plug-in request 12.19

**Comment by bwp91** [comment]
This just a warning not an error. it has no effect on the plugin

**Comment by Stetocasa** [comment]
> This just a warning not an error. it has no effect on the plugin

I come back to factory status again, do you know on terminal how clear the cache of the raspberry? Hoobs would be a normal raspberry

**Comment by bwp91** [comment]
A quick google brings up this:
https://www.reddit.com/r/HOOBS/comments/emzhdx/how_do_i_clear_cache_in_the_new_hoobs/
Perhaps this would work?

**Comment by bwp91** [comment]
Did you get this working?

**Comment by Stetocasa** [comment]
> Did you get this working?

Yes we can close the issue

**Comment by bwp91** [comment]
Fab. Glad it's working :)
