### ISSUE TITLE
Configurable device types

### ISSUE THREAD

**Issue by dkrushev** [bwp91/homebridge-ewelink#121]
**Please explain your feature request in one sentence.**
I would like to be able to change the type of my devices from outlet to switch.

**Any particular Sonoff devices that this relates to?**
PowR2

**Anything else?**
Thank you for your continuous work on this plugin.

**Comment by bwp91** [comment]
Hi @dkrushev 
This is definitely something i can look into. if you don't mind me asking, what's the reason behind this?
is there something a switch can do that an outlet can't?

**Comment by dkrushev** [comment]
My PowR2 is switching on/off my water heater, so conceptually it makes more sense for me do be visualized as switch rather than an outlet. Different people would use it differently and making it configurable will address different preferences.

**Comment by bwp91** [comment]
I understand.
I could add a config option to expose certain outlet devices as switches.
However it would mean that these certain accessories would lose the "outlet" features such as the energy consumption in Eve, ability to make automations from the OutletInUse characteristic, etc.
I'll have a work on this today

**Comment by bwp91** [comment]
If you're happy to try out the new beta, v3.10.0-4, I have added a configuration option in the "Device Specific" section, where you can put the device ID of your outlet(s) that you want to expose as switches. Restart HB and they should appear as switches.

**Comment by dkrushev** [comment]
How do I install beta?
Also you mentioned energy consumption. Is this possible to be monitored in HomeKit?

**Comment by bwp91** [comment]
> How do I install beta?

Which platform are you running Homebridge on?

> Also you mentioned energy consumption. Is this possible to be monitored in HomeKit?

No, the energy consumption specific to the Eve app. But the energy consumption is only available for devices exposed as outlets, if you change the device type to a switch, then it won't be availably anyway

**Comment by dkrushev** [comment]
Homebridge is running on Raspberry.

**Comment by bwp91** [comment]
you should be able to run this command in the homebridge terminal:

`sudo npm -g i homebridge-ewelink@beta`

and it will install v3.10.0-4. 

Once updated, restart Homebridge, then go to the plugin settings, "Device Specific" section, add the outlet device ID to the "Outlet As Switch" section, save, restart Homebridge again, and it should be as you want!

**Comment by dkrushev** [comment]
It is done and is working as expected. Thank you!

**Comment by bwp91** [comment]
Awesome. When v3.10.0 is released properly it will appear as an update in Homebridge. Until then just carry on using the beta version.
Glad I could get this sorted!
