### ISSUE TITLE
Issues with Multi Gang Switches (2 Gang / 3 Gang)

### ISSUE THREAD

**Issue by irg33k** [bwp91/homebridge-ewelink#122]
**What issue do you have? Please be as thorough and explicit as possible.**
My living room Lights and Fan and hooked up to a single 3 Gang Switch Sonoff. 
The problem is, by default it creates 4 switches; Light 1, Light 2, Fan & All (Control all channel ON/OFF). 
Every time I asked Siri to switch off the Living Room, it will never switch off all channels due to the existence of All Channel ON/OFF existed. It glitched. It will switch off Light 1, Light 2, Fan, and then randomly another channel will be ON again.
...

**Details of your setup.**
Do you use Homebridge or HOOBS?
HOOBS
...

Which version of Homebridge/HOOBS do you have?
3.2.9
...

Which version of this plugin (homebridge-ewelink) do you have?
3.8.4
...

**Please paste any relevant logs below. It helps if you can turn `debug` and `debugReqRes` in the package settings for more thorough logging.**
> If you are posting an error then it is helpful for me to also see the previous few lines as this can show the cause of the error.
10/29/2020, 8:23:19 PM [eWeLink] [Dining Area SW3] Homebridge state will be synced once the device comes back online.
10/29/2020, 8:23:19 PM [eWeLink] LAN message received.
{
  "deviceid": "**hidden**",
  "params": {
    "switches": [
      {
        "switch": "off",
        "outlet": 0
      },
      {
        "switch": "on",
        "outlet": 1
      },
      {
        "switch": "off",
        "outlet": 2
      },
      {
        "switch": "off",
        "outlet": 3
      }
    ],
    "updateSource": "LAN",
    "online": true
  }
}
10/29/2020, 8:23:19 PM [eWeLink] [Dining Area] LAN update received and will be refreshed.
10/29/2020, 8:23:19 PM [eWeLink] WS message received.
{
  "deviceid": "**hidden**",
  "params": {
    "switches": [
      {
        "switch": "off",
        "outlet": 0
      },
      {
        "switch": "on",
        "outlet": 1
      },
      {
        "switch": "off",
        "outlet": 2
      },
      {
        "switch": "off",
        "outlet": 3
      }
    ],
    "online": true,
    "updateSource": "WS"
  }
}
10/29/2020, 8:23:19 PM [eWeLink] [Dining Area] reported [online] via [WS].
10/29/2020, 8:23:19 PM [eWeLink] WS message sent. This text is yellow for clarity.
{
  "action": "query",
  "apikey": "ed47b86a-68c3-40cb-b0ae-97bf66f865a6",
  "deviceid": "**hidden**",
  "params": [],
  "sequence": "1603974199059",
  "ts": 0,
  "userAgent": "app"
}
10/29/2020, 8:23:19 PM [eWeLink] [Dining Area] WS update received and will be refreshed.
10/29/2020, 8:23:19 PM [eWeLink] WS message received.
{
  "deviceid": "**hidden**",
  "params": {
    "switches": [
      {
        "switch": "off",
        "outlet": 0
      },
      {
        "switch": "on",
        "outlet": 1
      },
      {
        "switch": "off",
        "outlet": 2
      },
      {
        "switch": "off",
        "outlet": 3
      }
    ],
    "lock": 0,
    "online": true,
    "updateSource": "WS"
  }
}
...

**Comment by bwp91** [comment]
Hi @irg33k 
The "All on/off" accessory can be removed from HOOBS by using the "Hide Light/Switch Channels" configuration option.

**Comment by irg33k** [comment]
> Hi @irg33k
> The "All on/off" accessory can be removed from HOOBS by using the "Hide Light/Switch Channels" configuration option.

I have included the channel ID inside the configuration; 10008bd354SW0.
However, the problem still persists as if the channel still exists ("All on/off" already hidden inside Homekit) when giving the command through Siri.

**Comment by bwp91** [comment]
Out of interest which product model is the device in question?

**Comment by irg33k** [comment]
> Out of interest which product model is the device in question?

I'm using the Sonoff TX3C (V3.4.1) - 3 Gang [T0UK3C].
https://sonoff.tech/product/wifi-smart-wall-swithes/tx-series

**Comment by irg33k** [comment]
> Out of interest which product model is the device in question?

The problem also happens on my Sonoff TX2C (V.3.4.1) - 2 Gang [T0UK2C].
https://sonoff.tech/product/wifi-smart-wall-swithes/tx-series

**Comment by irg33k** [comment]
I was wondering, is it possible this problem occurred because there is no delay in triggering the command for Ch1,2,3 at the same time? Because I can hear the Sonoff's relays all clicking at the same timing. 
I remembered that the other plugin that I used previously had a few millisecond delays between triggers.

**Comment by bwp91** [comment]
> I was wondering, is it possible this problem occurred because there is no delay in triggering the command for Ch1,2,3 at the same time? Because I can hear the Sonoff's relays all clicking at the same timing.
> I remembered that the other plugin that I used previously had a few millisecond delays between triggers.

Could be? Good thinking.
This is the reason why i added the “All on/off” accessory in the first place, as it just sends one command to turn on/off all the channels, rather then multiple commands at the same time.

**Comment by irg33k** [comment]
> > I was wondering, is it possible this problem occurred because there is no delay in triggering the command for Ch1,2,3 at the same time? Because I can hear the Sonoff's relays all clicking at the same timing.
> > I remembered that the other plugin that I used previously had a few millisecond delays between triggers.
> 
> Could be? Good thinking.
> This is the reason why i added the “All on/off” accessory in the first place, as it just sends one command to turn on/off all the channels, rather then multiple commands at the same time.

I recorded a video of my problem if I failed to explain my problem clearly; 
https://youtu.be/kYKTwOY8U7c

*Sorry. English is not my native language.

**Comment by irg33k** [comment]
> > I was wondering, is it possible this problem occurred because there is no delay in triggering the command for Ch1,2,3 at the same time? Because I can hear the Sonoff's relays all clicking at the same timing.
> > I remembered that the other plugin that I used previously had a few millisecond delays between triggers.
> 
> Could be? Good thinking.
> This is the reason why i added the “All on/off” accessory in the first place, as it just sends one command to turn on/off all the channels, rather then multiple commands at the same time.

Is there any other way that I can switch off a room with just a Siri command?

**Comment by bwp91** [comment]
How about if you “unhide” the SW0 accessory, name this one “Office Lights”, then name the individual accessories “Office Light One” and “Office Light Two”.

**Comment by bwp91** [comment]
And there’s no other “confliction” going on i mean for example HomeKit scenes, automations, eWeLink scenes, etc?

**Comment by irg33k** [comment]
> How about if you “unhide” the SW0 accessory, name this one “Office Lights”, then name the individual accessories “Office Light One” and “Office Light Two”.

This method works. 
But the problem will happen again when I said: "Switch off Office" instead of "Switch off Office Lights".
My office consists of a few other devices; Office Lights, Office Working Light, 3D Printer, Air-Conditioner.
Previously when I ran this command, all of the devices will be turned off.

**Comment by irg33k** [comment]
> And there’s no other “confliction” going on i mean for example HomeKit scenes, automations, eWeLink scenes, etc?

I have checked with my Homekit Scene, Automation, eWeLink Scenes, IFTTT etc. 
There's no confliction.

**Comment by bwp91** [comment]
> Office Lights, Office Working Light, 3D Printer, Air-Conditioner.

Are they ewelink devices?

> Previously when I ran this command, all of the devices will be turned off.

I don't understand how this has stopped working? How did it work before? If you said "turn office off" how did siri know to turn all the devices off, via a scene?

**Comment by irg33k** [comment]
> ff, via a scene?

Because I added all the devices into the "Office" room in Homekit. 
Siri will turn off the whole room.
And yes, they are all eWeLink Devices except for the one controlling the Air-Conditioner (Broadlink).

**Comment by bwp91** [comment]
Although there are many possible work arounds, the root of the issue is that this plugin is trying to make many requests to different devices (and the same device in the case of the multi-gang devices).

I'll have a think about how I can implement a slight delay between updates.

**Comment by irg33k** [comment]
> Although there are many possible work arounds, the root of the issue is that this plugin is trying to make many requests to different devices (and the same device in the case of the multi-gang devices).
> 
> I'll have a think about how I can implement a slight delay between updates.

Thank you very much.
I really appreciated your help!
Been pulling my hair throughout the day.

**Comment by bwp91** [comment]
Could I message you on the [Homebridge Discord](https://discord.gg/7X36mdw)?

**Comment by bwp91** [comment]
So an update.

In the version 3.10.0 I have just released, there is a small delay/queue when updating multiple **different** devices at the same time. Meaning, for example, if you asked Siri to turn the office off then the plugin will queue the updates for your ewelink devices rather than sending out multiple requests at the same time (which seemed to cause problems).

This, however, does not resolve the updating of multiple channels of a single device. A solutions, albeit not ideal, would be two keep the SW0 accessory inside the "Office" room in Home app, but move the individual SW1, SW2, into a different room. Then you could ask Siri to "turn off the office" and it will send one update to the TX device, turning all the channels off.
