### ISSUE TITLE
RGB-CCT light bulb

### ISSUE THREAD

**Issue by Pyrotechnik192** [bwp91/homebridge-ewelink#127]
**Please explain your feature request in one sentence.**
...Hi, can you add this light bulb please: 
https://www.aliexpress.com/item/4001346658595.html?spm=a2g0s.9042311.0.0.6b6c4c4dCLd5r4

and can you look at this zigbee switch from tuya too? It can be added to the sonoff app thru the sonoff zigbee bridge without issues and it works with ewelink:
https://www.aliexpress.com/item/1005001507142671.html?spm=a2g0s.9042311.0.0.6b6c4c4dCLd5r4

Thank you for your response
Jozef

**Comment by bwp91** [comment]
Hi @Pyrotechnik192 
For me to add new devices i need them to be shared with my ewelink account, is this something you’d be happy to do?
thanks!

**Comment by Pyrotechnik192** [comment]
Hi @bwp91 
Can you send me private e-mail to ** so we can talk about the details?

**Comment by bwp91** [comment]
Closing this as RGB support for the mentioned bulb will be available in v3.10.0.
