### ISSUE TITLE
homebridge-ewelink@3.9.0 needs node >=12.19.0

### ISSUE THREAD

**Issue by migabc** [bwp91/homebridge-ewelink#129]
Hi,
I'm trying to install homebridge-ewelink but I got this error:

pi@raspberrypi:~ $ sudo npm -g install homebridge-ewelink
npm WARN notsup Unsupported engine for homebridge-ewelink@3.9.0: wanted: {"homebridge":">=1.1.0","node":">=12.19.0"} (current: {"node":"11.15.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: homebridge-ewelink@3.9.0

+ homebridge-ewelink@3.9.0
added 72 packages from 83 contributors in 31.392s
pi@raspberrypi:~ $

I then tried to upgrade node and I got this error:

pi@raspberrypi:~ $ curl -sL https://deb.nodesource.com/setup_15.x | sudo -E bash -
. . .
pi@raspberrypi:~ $ sudo apt-get install -y nodejs
. . .
The following packages have unmet dependencies:
 nodejs : Depends: libstdc++6 (>= 5.2) but 4.9.2-10+deb8u2 is to be installed
E: Unable to correct problems, you have held broken packages.
pi@raspberrypi:~ $ 

This problem occurs when I try to install any node version >=12.
No issue with node version <=11 (but homebridge-ewelink needs node >=12.19.0)

Any help appreciated

**Comment by bwp91** [comment]
Hi @migabc 

If you’re using the homebridge pi image, you can update node easily by running this command in the homebridge terminal:
`sudo hb-service update-node`
This should bring you up to node 14.15.0 

See
https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-Service-Command#update-nodejs

**Comment by migabc** [comment]
pi@raspberrypi:~ $ sudo hb-service update-node
sudo: hb-service: command not found

I'm running basic homebridge (not Hoobs nor Homebridge Config UI X)
Therefore I do not have the hb-service

**Comment by bwp91** [comment]
Ah okay. 

You could try [n](https://www.npmjs.com/package/n)?

**Comment by migabc** [comment]
I tried installing with n but I got this error:

pi@raspberrypi:~ $ sudo n latest

  installing : node-v15.0.1
       mkdir : /usr/local/n/versions/node/15.0.1
       fetch : https://nodejs.org/dist/v15.0.1/node-v15.0.1-linux-armv7l.tar.xz
node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by node)
node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by node)
node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by node)
/usr/local/bin/node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/local/bin/node)
/usr/local/bin/node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/local/bin/node)
/usr/local/bin/node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/local/bin/node)
   installed :  (with npm )

Note: the node command changed location and the old location may be remembered in your current shell.
         old : /usr/bin/node
         new : /usr/local/bin/node
To reset the command location hash either start a new shell, or execute PATH="$PATH"

pi@raspberrypi:~ $

**Comment by bwp91** [comment]
This is getting a quite outside the scope of my support now, with regards to updating node.

From your original post, it looks like you are currently running node v11.15.0. The homebridge-ewelink plugin should work with this version, so you shouldn't encounter any issues with this plugin on your current node version.

On a side note, however, I would recommend googling the errors you are receiving to get your node version up to a minimum of v12, recommended v14, but not v15.

**Comment by migabc** [comment]
Thanks for your help on this.

homebridge-ewelink doesn't seem to run with node v11.15.0

Homebridge fails to startup with this error:

Nov  1 15:30:15 raspberrypi homebridge[10085]: [11/1/2020, 3:30:15 PM] Error: The requested platform 'eWeLink' was not registered by any plugin.

**Comment by bwp91** [comment]
Is homebridge the only thing you run on your raspberry pi? if so perhaps it might be a safe solution to "start over" reflash your sd card with the homebridge pi image with more up-to-date versions of everything?

**Comment by migabc** [comment]
I'm running other stuff besides homebridge 

Anyway, I have all the up-to-date wanted versions of all my plugins

pi@raspberrypi:~ $ date; npm outdated -g --depth=0                                    
Sun Nov  1 17:08:49 WET 2020
Package                   Current  Wanted  Latest  Location
hap-nodejs                 0.4.53  0.4.53   0.8.2  global
homebridge                 0.4.53  0.4.53   1.1.6  global
homebridge-camera-ffmpeg   0.1.19  0.1.19   3.0.3  global
node-gyp                    3.8.0   3.8.0   7.1.2  global
pi@raspberrypi:~ $

**Comment by migabc** [comment]
It seams that this plugin requires a beta homebridge version

I'm running the last wanted version of homebridge (0.4.53) and I get this error:

Nov  2 11:39:31 raspberrypi homebridge[1484]: [11/2/2020, 11:39:31 AM] ERROR LOADING PLUGIN homebridge-ewelink:
Nov  2 11:39:31 raspberrypi homebridge[1484]: [11/2/2020, 11:39:31 AM] Error: Plugin /usr/lib/node_modules/homebridge-ewelink requires a HomeBridge version of >=1.1.0 which does not satisfy the current HomeBridge version of 0.4.53. You may need to upgrade your installation of HomeBridge.
Nov  2 11:39:31 raspberrypi homebridge[1484]: at Plugin.load (/usr/lib/node_modules/homebridge/lib/plugin.js:57:11)

Can you please confirm?

**Comment by bwp91** [comment]
The version of homebridge you currently have installed is v0.4.53 which is quite an old version.
The current version of homebridge is v1.1.6, which you can verify [here](https://www.npmjs.com/package/homebridge). This is not a beta version, it is the current version.

I would definitely recommend updating to the latest version of Homebridge, in fact, a lot of your plugins are out of date:

```
hap-nodejs 0.4.53 0.4.53 0.8.2 global
homebridge 0.4.53 0.4.53 1.1.6 global
homebridge-camera-ffmpeg 0.1.19 0.1.19 3.0.3 global
node-gyp 3.8.0 3.8.0 7.1.2 global
```

**Comment by migabc** [comment]
When I issue the "npm outdated -g --depth=0" command it shows that the Wanted version for homebridge is 0.4.53

How can I update to a version ahead of the Wanted version?

sudo npm update -g --unsafe-perm homebridge

will not update because I'm already on the Wanted version

**Comment by bwp91** [comment]
try

`sudo npm i -g --unsafe-perm homebridge`

this should update homebridge to the latest version

**Comment by sebbo187** [comment]
Here's how to update Node safely:

```
sudo systemctl stop homebridge
sudo npm i npm@latest -g
sudo npm cache clean -f
sudo npm install -g n
sudo n lts
```

After that you are on Node 14 which is the current LTS Version (long-term-support). You could alternately use `sudo n 12.17.0` as last command. This was the last lts version and is fully supported until 2022 (I always recommend the LTS version in order to get full support for a long time, like name already says).

*First command does only fit if homebridge is running as systemd service, you know best how to stop your own homebridge I guess.. ;-)

**Comment by sebbo187** [comment]
Beside that here's a winking advice related to your way to check plugin updates straight out of the documentation of npm:

> wanted is the maximum version of the package that satisfies the semver range specified in package.json. If there's no available semver range (i.e. you're running npm outdated --global, or the package isn't included in package.json), then wanted shows the currently-installed version.

;-)

**Comment by bwp91** [comment]
@migabc 
did you get this resolved?

**Comment by migabc** [comment]
Not yet :-(

I was hoping the other plugin author (homebridge-ewelink-max) would fix the "400-Bad Request" error.

Or, alternatively you (the author of this plugin) could make a code change to allow homebridge-ewelink to run under homebridge 0.4.53

I tried to swap the homebridge-ewelink-max for your homebridge-ewelink plugin but your plugin requires HomeBridge version >=1.0.0 and I'm currently using homebridge v0.4.53 (because I'm also using homebridge-knx which only runs on this stable version of homebridge)

So it seems I am stuck :-(

pi@raspberrypi:~ $ date; npm outdated -g --depth=0
Sat Nov 7 08:55:53 WET 2020
Package Current Wanted Latest Location
homebridge 0.4.53 0.4.53 1.1.6 global
homebridge-camera-ffmpeg 0.1.19 0.1.19 3.0.3 global

pi@raspberrypi:~ $ date; npm list --depth=0 -g
Sat Nov 7 09:31:26 WET 2020
/usr/lib
├── hap-nodejs@0.8.2
├── homebridge@0.4.53
├── homebridge-bmw-connected@1.0.0
├── homebridge-broadlink-rm@3.6.22
├── homebridge-camera-ffmpeg@0.1.19
├── homebridge-ewelink-max@0.1.24
├── homebridge-gpio-blinds@1.0.0
├── homebridge-gpio-device@0.4.6
├── homebridge-knx@0.3.27
├── homebridge-yeelight-wifi@2.2.2
├── node-gyp@7.1.2
├── npm@6.14.8
└── request@2.88.2

pi@raspberrypi:~ $

Any help appreciated

**Comment by bwp91** [comment]
> because I'm also using homebridge-knx which only runs on this stable version of homebridge

I just checked their repo page and it says:

> homebridge-knx Version 0.3
This can only be used with homebridge >=0.4.28 and Node >=10.19.0

So surely this package would work with the latest version of homebridge, or at least >=1.0.0?

**Comment by migabc** [comment]
Yes it sais that in the rep page of homebridge-knx, but unfortunately it doesn't work with homebridge 1.0 or higher

https://github.com/snowdd1/homebridge-knx/issues/182

**Comment by bwp91** [comment]
Which ewelink devices do you have?

**Comment by migabc** [comment]
sonoff basic and POW

**Comment by bwp91** [comment]
You could try my old plugin,

homebridge-ewelink-sonoff

but,
i don’t provide support for this anymore and i can’t guarantee it will work

**Comment by migabc** [comment]
Thanks!

What are the platform settings in config.json for this plugin?
Does it use the same platform settings as the homebridge-ewelink?

**Comment by bwp91** [comment]
Yes, `countryCode`, `username` and `password`. 
If you want to dig deeper you can see the available config options for this plugin at
https://github.com/bwp91/homebridge-ewelink-sonoff/blob/master/config.schema.json

**Comment by migabc** [comment]
It works fine with homebridge-ewelink-sonoff :-)

Thanks for your help on this

**Comment by bwp91** [comment]
Excellent. Glad we found a solution. I'll close this issue now as resolved!

**Comment by migabc** [comment]
Ok, thx again
