### ISSUE TITLE
Can anyone confirm this is working?

### ISSUE THREAD

**Issue by elig0n** [bwp91/homebridge-ewelink#13]
Specifically for light switches

**Comment by MrTomAsh** [comment]
My version of the code from the issue #14 works with 1 and 2 gang switches.

**Comment by elig0n** [comment]
I have model PSF-A01-GL . Will it work ? 
What is the webSocketApi ?

**Comment by MrTomAsh** [comment]
How many switches are in the gang? If only 1 it should work without any issues.

To obtain your webSocketApi use the instruction from README file.

**Comment by elig0n** [comment]
I do not see wss with charles ( maybe because I use Android ? )
