### ISSUE TITLE
v.3.10 Install Error: Fakegato

### ISSUE THREAD

**Issue by Phoenix-DH** [bwp91/homebridge-ewelink#131]
When trying to update I receive the following message (screenshot attached).

Maybe it is related to the fact thst I got already a plugin (eveatmo) which uses fakegato?

...

**Details of your setup.**
Do you use Homebridge or HOOBS?
Homebridge
...

Which version of Homebridge/HOOBS do you have?
homebridge-ewelink v3.9.0, trying to update to homebridge-ewelink v3.10.0
...

Which version of this plugin (homebridge-ewelink) do you have?
homebridge-ewelink v3.9.0, triing to update to homebridge-ewelink v3.10.0
<img width="615" alt="Screenshot 2020-11-03 at 16 30 30" src="https://user-images.githubusercontent.com/44058592/98011881-c0e10780-1df8-11eb-8c0c-42ada8f94b6f.png">

**Comment by bwp91** [comment]
Hi, which platform are you running homebridge on? 

> Maybe it is related to the fact thst I got already a plugin (eveatmo) which uses fakegato?

Shouldn’t be. v3.9.0 and indeed previous versions of this plugin have used fakegato, ie, it’s not new to the plugin

**Comment by Phoenix-DH** [comment]
I am running a PI4 with Buster.
I installed 3.9.0 a few days ago without problems.
Was moving from another plugin.

**Comment by bwp91** [comment]
From the homebridge terminal, what happens if you type this command?

`git --version`

**Comment by Phoenix-DH** [comment]
Once tried in homebridge terminal and normal ssh connection, in both scenarios:
bash: git: command not found

Strange ...
Is something missing?

**Comment by bwp91** [comment]
A quick fix I believe would be to install `git`. Although in the long run it's something I will need to look into properly so it doesn't affect other users.

Try these in the command line to install `git`:

`sudo apt update`

`sudo apt install git`

then confirm it's installed:

`git --version` should say git version 2.20.1 (or something like that)

then please try installing the plugin again

**Comment by Phoenix-DH** [comment]
Yes and yes and yes 🙌🏻 

Working, thanks!
