### ISSUE TITLE
v3.10.0 update npm ERR! code ENOENT

### ISSUE THREAD

**Issue by platini76** [bwp91/homebridge-ewelink#134]
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/bwp91/fakegato-history.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2020-11-03T20_37_06_018Z-debug.log

**Comment by bwp91** [comment]
hi @platini76 
which platform are you running homebridge on?

**Comment by platini76** [comment]
Linux mint

**Comment by bwp91** [comment]
Quick fix is to install `git`, please type these commands into the command line:

`sudo apt update`

`sudo apt install git`

Then try installing/updating the plugin.

**Comment by platini76** [comment]
Thanks man for your precious help and stay safe un this bad moment!

**Comment by bwp91** [comment]
> Thanks man for your precious help and stay safe un this bad moment!

Thank you and yourself!
