### ISSUE TITLE
KOMEITO 1515 Diffuser

### ISSUE THREAD

**Issue by brano-osif** [bwp91/homebridge-ewelink#136]
**Please explain your feature request in one sentence.**
Hi!
I just migrated from [homebridge-ewelink-max](https://www.npmjs.com/package/homebridge-ewelink-max) to this package but I got warning that my device (Diffuser Komeito 1515) is not supported yet. 

Is there any possibility that you will support this device?

**Comment by bwp91** [comment]
Hi, yes adding support for this device should be possible.
It’s just no one has requested it yet!
Easiest way would be if you were happy to share it to my ewelink account?

**Comment by brano-osif** [comment]
Yep, what will be the best way to do this? Do you got any contact info so we can get in touch?

**Comment by bwp91** [comment]
We can message on the [Homebridge Discord](https://discord.gg/7X36mdw)?

**Comment by bwp91** [comment]
Support added in v3.11.1
