### ISSUE TITLE
Devices return to the default name with updates

### ISSUE THREAD

**Issue by edmarts** [bwp91/homebridge-ewelink#138]
Every time the plugin is updated, the devices return to the default name and all scenarios created with the categorized devices mess up and return to the default.

**Comment by edmarts** [comment]
And mess up all the homekit app too

**Comment by bwp91** [comment]
Hey. Thanks for for the comment.
This shouldn't happen with *every* update.
The last update v3.11.0 changed some things which were detailed in the [release notes](https://github.com/bwp91/homebridge-ewelink/releases/tag/v3.11.0).
Whenever there are "breaking changes" I write them in the release notes.
Otherwise you shouldn't be finding that *every* update resets your accessories.

**Comment by edmarts** [comment]
But isn't there a way to not reset devices in updates? I have more than 50 devices and it gets complicated whenever you have to update the plugin and have to rename them all and put each one in your room.

**Comment by bwp91** [comment]
If you indeed find that _every_ update resets _all_ your devices, then something is very wrong. As this should not happen. And this seems very specific to your situation, as I have not heard of this behaviour before.

As I said before, any "breaking" changes I always put in the release notes. In fact, v3.11.0 should not have reset accessory names and rooms. Just automations and scenes for the mentioned devices.

How do you update your plugins?

**Comment by edmarts** [comment]
I always update directly through the homebridge, when he informs me that there is a plugin to update, I go to the plugins page and click on update ... simple as that

Really, not all updates happen, but some do and then messes up

**Comment by luizjunior** [comment]
[EDIT: more info]
I'm running v3.11.1 (the same with  v3.12.0-5 beta), every time my homebridge resets the following happens:
- OK: devices are keeping names
- PROBLEM: reseting type (light, fan, switch)
- PROBLEM: "Include in Favorites" option is returning to ON mode
- PROBLEM: created groups are being deleted
- PROBLEM: switches are removed from automation

**Comment by imtitanic** [comment]
Hi, same here.

After restart homebridge this happened. Lights from T3 Smart Switch return to 'switch' instead 'lights' and delete from automatizations.

But in the case of a Sonoff basic as fan, sonoff mini as light and sonoff 5v as garage door, they dont change.

**Comment by bwp91** [comment]
@luizjunior @imtitanic 

this happens everytime you restart homebridge?

could one of both of you get me some logs of when you do a homebridge restart?

**Comment by bwp91** [comment]
Also, please post your config, removing your ewelink username and password :)

**Comment by edmarts** [comment]
And, when I change a device name on ewelink... nothing happens on homebridge
Even when I update and restart the homebridge, the device name remains the old one, in addition to mess up all the homebrige and automations

**Comment by bwp91** [comment]
> could one of both of you get me some logs of when you do a homebridge restart?

> Also, please post your config, removing your ewelink username and password :)

**Comment by imtitanic** [comment]
_Aquí tienes_, @bwp91 

**Log:**
> [2020-11-9 10:53:33] [eWeLink] Initializing eWeLink platform...
> [2020-11-9 10:53:33] [eWeLink] Plugin [v3.11.1] initialised. Syncing with eWeLink...
> [2020-11-9 10:53:33] [eWeLink] Sending HTTP getHost() request.
> [2020-11-9 10:53:34] [eWeLink] HTTP API host received [us-apia.coolkit.cc].
> [2020-11-9 10:53:34] [eWeLink] Sending HTTP login() request.
> [2020-11-9 10:53:37] [eWeLink] Web socket host received [us-pconnect3.coolkit.cc].
> [2020-11-9 10:53:38] [eWeLink] Sending WS login request.
> [2020-11-9 10:53:40] [eWeLink] [8] eWeLink devices loaded from the Homebridge cache.
> [2020-11-9 10:53:40] [eWeLink] [5] primary devices loaded from your eWeLink account.
> [2020-11-9 10:53:40] [eWeLink]  → [Ventilador myFan] initialised and found locally with IP [192.168.101.115].
> [2020-11-9 10:53:40] [eWeLink]  → [RF Bridge] initialised and found locally with IP [192.168.101.116].
> [2020-11-9 10:53:41] [eWeLink]  → [Interruptor] initialised and found locally with IP [192.168.101.114].
> [2020-11-9 10:53:41] [eWeLink]  → [Luz de Entrada ] initialised and found locally with IP [192.168.101.112].
> [2020-11-9 10:53:41] [eWeLink]  → [Puerta Eléctrica] initialised and found locally with IP [192.168.101.113].
> [2020-11-9 10:53:41] [eWeLink] eWeLink sync complete. Don't forget to ⭐️  this plugin on GitHub if you're finding it useful!

 
**Config:**
```
         {
            "name": "eWeLink",
            "countryCode": "52",
            "username": "***@***",
            "password": "****",
            "debug": true,
            "debugReqRes": false,
            "disableHTTPRefresh": false,
            "disablePlugin": false,
            "hideDevFromHB": "1000be58f4",
            "hideChanFromHB": "1000ceee01SW0",
            "inUsePowerThreshold": 0,
            "hideTHSwitch": false,
            "lowBattThreshold": 25,
            "sensorTimeDifference": 120,
            "hideZBLDPress": false,
            "resetRFBridge": false,
            "groups": [
                {
                    "deviceId": "1000d24e48",
                    "type": "garage",
                    "setup": "oneSwitch",
                    "operationTime": 150
                }
            ],
            "bridgeSensors": [
                {
                    "type": "motion",
                    "sensorTimeLength": 60
                }
            ],
            "nameOverride": [
                {
                    "fullDeviceId": "1000b5e19dSWX",
                    "deviceName": "Luz de Entrada"
                },
                {
                    "fullDeviceId": "1000ceee01SW1",
                    "deviceName": "Luz de Cochera"
                },
                {
                    "fullDeviceId": "1000ceee01SW2",
                    "deviceName": "Luz de Sala"
                },
                {
                    "fullDeviceId": "1000ceee01SW3",
                    "deviceName": "Luz de Comedor"
                },
                {
                    "fullDeviceId": "1000d8ff6eSWX",
                    "deviceName": "Ventilador myFan"
                }
            ],
            "ipOverride": [
                {
                    "deviceId": "1000b5e19d",
                    "deviceIP": "192.168.101.112"
                },
                {
                    "deviceId": "1000d24e48",
                    "deviceIP": "192.168.101.113"
                },
                {
                    "deviceId": "1000ceee01",
                    "deviceIP": "192.168.101.114"
                },
                {
                    "deviceId": "1000d8ff6e",
                    "deviceIP": "192.168.101.115"
                },
                {
                    "deviceId": "1000bd59cc",
                    "deviceIP": "192.168.101.116"
                }
            ],
            "platform": "eWeLink"
        }
```

**Comment by bwp91** [comment]
Gracias @imtitanic 
Just to confirm, the lights return to switches, and delete from automations every time you restart Homebridge?

**Comment by edmarts** [comment]
In my case it happens like this:
- when I update the plugin (not every time) it changes the name of the devices, restoring the name registered in ewelink
- but in ewelink i already changed the devices names but in homebridge it always takes the old name

As the names change, the automations stop working because they no longer find the devices.

**Comment by imtitanic** [comment]
> Gracias @imtitanic
> Just to confirm, the lights return to switches, and delete from automations every time you restart Homebridge?

Yep but only the devices from T3 Switch

![d76dbe2d-2e9c-40d4-a288-4b852444b1f6](https://user-images.githubusercontent.com/68301159/98582349-18abc280-2280-11eb-95a8-31c98c6e477c.jpg)

**Comment by bwp91** [comment]
I am totally stumped. I am running v3.11.1 on my raspberry pi, I have T1-1C, T1-2C and T1-3C around my house. And I have them all displayed as lights in the Home app.

And never when I restart Homebridge do they reset their room, type (back to switch) or their automations.

**Comment by imtitanic** [comment]
look, this is whats happen when restart homebridge

https://youtu.be/bRGX1y3-Kh4

**Comment by bwp91** [comment]
@imtitanic thank you for this. Which version of the plugin are you running?

**Comment by imtitanic** [comment]
> @imtitanic thank you for this. Which version of the plugin are you running?

**homebridge** v1.1.6
**homebridge-ewelink** v3.11.1

**Comment by bwp91** [comment]
@imtitanic in your case, if you remove the three accessories from the homebridge cache all at once does this work?

**Comment by imtitanic** [comment]
> in your case, if you remove the three accessories from the homebridge cache all at once does this work?

This worked partially, now only one of the three is back to being a "Switch" after restart.

**Comment by bwp91** [comment]
Could you send me a screenshot of your accessory page in Homebridge?

**Comment by imtitanic** [comment]
well, this is weird hahah, shouldn't there be something?

![Screen Shot 2020-11-09 at 15 12 03](https://user-images.githubusercontent.com/68301159/98602610-f7f26580-229d-11eb-82f6-669444ef9a18.png)

**Comment by bwp91** [comment]
@imtitanic are you on the [Homebridge Discord](https://discord.gg/7X36mdw)? might be easier to message there.

@edmarts @luizjunior I believe if I can find a solutions from one of you three then it will work for all.

I'm really trying to get this sorted!

**Comment by edmarts** [comment]
As I said, my case is a little different. When I restart the homebrige, stay normal, it does not change the devices. Only when there is a big update on the plugin, they change the devices names that I defined in the homebrige and takes the names that are in the ewelink application.

And here is another problem, he takes old names that were on ewelink. I already changed the names in ewelink and even so when the homebrige loads, he takes names that no longer exist.
![1](https://user-images.githubusercontent.com/2656908/98694783-a6ef7980-2350-11eb-9ec9-c2e2df4262ba.png)

**Comment by bwp91** [comment]
With regards to device names:

* When a device is initially added, it takes the name from the eWeLink app and assigns this as the name in Homebridge and Home app (unless you have a nameOverride set in the configuration)
* The names are then independent I mean, if you change a name in Homebridge, it won't update eWeLink or Home app, or if you change a name in Home app, it won't update in Homebridge or eWeLink.

In your picture, the actual device name is Hall Sensor (this device at some point would have been called this in the ewelink app and when it was added to Homebridge it would have taken this name). The "Bathroom Sensor" name is more like a label for Homebridge, to show the device name as something different.

So, if a device name is ever changed back to how it is in the ewelink app, it means it has been removed and readded to Homebridge (happens when you remove a device from the Homebridge cache). This is the only explanation as in my plugin code it is the only time a device name is set.

In some recent updates to enable functionality for new features there have been times when removing a device from the cache has been necessary. But it's never forced.

> As I said, my case is a little different. When I restart the homebrige, stay normal, it does not change the devices. Only when there is a big update on the plugin, they change the devices names that I defined in the homebrige and takes the names that are in the ewelink application.

Could it be the case that you have been removing the accessories from the cache after certain updates?

> And here is another problem, he takes old names that were on ewelink. I already changed the names in ewelink and even so when the homebrige loads, he takes names that no longer exist.

The plugin doesn't check for device name updates each time is loads. If you want to update this "Hall Sensor" name then the device will need to be removed from the cache (so it is removed and readded). Any custom name in Homebridge and Home app are like labels for the device.

**Comment by edmarts** [comment]
hmmm got it ... and how do I remove it from the cache and add the device again?

**Comment by bwp91** [comment]
https://github.com/bwp91/homebridge-ewelink/wiki/How-to-remove-an-accessory-from-the-cache

Is a guide if you’re using homebridge config ui and have homebridge installed as hb-service.

If the option isn’t there then it’s a bit more complicated!

**Comment by edmarts** [comment]
Yes, it's works for me!! Thanks!!

**Comment by bwp91** [comment]
me alegro!!
@luizjunior have you tried removing devices from the cache? do you by any chance hide the SW0 switch for your multi channel devices? it sounds like you may be having the same issue as @imtitanic

**Comment by luizjunior** [comment]
> me alegro!!
> @luizjunior have you tried removing devices from the cache? do you by any chance hide the SW0 switch for your multi channel devices? it sounds like you may be having the same issue as @imtitanic

My is exactly the same from the video of @imtitanic ...
@bwp91 I will try removing devices from cache... I did not hide the SW0 switch...

**Comment by bwp91** [comment]
> I will try removing devices from cache...

Let me know if it fixes anything.

Just out of interest also, which version of iOS are you running @imtitanic and @luizjunior ?

**Comment by imtitanic** [comment]
sorry for the delay, @bwp91 

I do that (delete cache and unhide) but nothing changes and today when I wake up look that "Luz de Comedor" changed to 'Switch' without restart homebridge.

> (...) which version of iOS are you running @imtitanic (...) ?

My homekit's hub is an iPad with iPadOS 14.2

**Comment by luizjunior** [comment]
> > I will try removing devices from cache...
> 
> Let me know if it fixes anything.
> 
> Just out of interest also, which version of iOS are you running @imtitanic and @luizjunior ?

I'm not using hb-service but I removed everything under accessories and persist folder. Changed the username and pin numbers from config, removed the central from home app, then add it again with the new numbers...
Now everything is keeping light/switch/fan settings even when restarting Homebridge.
I still need to test automations, but I'm hopeful everything will be fine.
Next time I update the plugin, I will check if everything keeps the settings.

**Comment by bwp91** [comment]
Hi, 
Any of you still encountering issues?

**Comment by imtitanic** [comment]
Hi, @bwp91 

> Any of you still encountering issues?

Here. Still happens to me.

> I removed everything under accessories and persist folder. Changed the username and pin numbers from config, removed the central from home app, then add it again with the new numbers...

In a few days I will buy an raspberry and I doing this

**Comment by luizjunior** [comment]
> Hi,
> Any of you still encountering issues?

I can confirm everything is fine now when homebridge restarts... including automation.
