### ISSUE TITLE
Support for S55 outdoor socket?

### ISSUE THREAD

**Issue by fhivet** [bwp91/homebridge-ewelink#139]
Hi,

Sorry to write this here, I looked for an other way to contact the creator of this plugin but didn't find anything.

Does this plugin support the Sonoff S55 waterproof socket? 

Here is a link to the product I plan to buy : https://www.amazon.fr/Sonoff-TPe-FR-Prise-femelle-étanche/dp/B08BZGCKJ7/ref=sr_1_6?__mk_fr_FR=ÅMÅŽÕÑ&dchild=1&keywords=prise+sonoff&qid=1604582557&sr=8-6

Thanks

**Comment by bwp91** [comment]
Hi @fhivet 
Yes this device should definitely work with the plugin.
Edit: if it doesn't then I can definitely make it work.
Hope this helps :)

**Comment by fhivet** [comment]
Just a feedback. Everything work, only thing is the outlet appears as a switch, or a light, or a fan. Anyway to fix this?

**Comment by bwp91** [comment]
Hi @fhivet 
In the eWeLink app, if you go into the Device Settings and scroll to the bottom of the page, what does it say for the `Model`?

**Comment by fhivet** [comment]
S55R1

**Comment by bwp91** [comment]
Great thank you.

Would you be happy to [follow this guide](https://github.com/bwp91/homebridge-ewelink/wiki/Beta-Version) to install a beta version, v3.12.1-0, to see if this fixes things?

If you install this and then restart Homebridge, you should find the device immediately appears as an outlet in Homebridge and (with a potential couple of minutes delay) as an outlet in the Home app.

Let me know how it goes or if you need any more assistance!

**Comment by fhivet** [comment]
Everything is perfect now!

**Comment by bwp91** [comment]
As it should be!
You're fine to stay on this beta for now. When v3.12.1 is properly released then it will appear as an update in Homebridge/HOOBS whichever platform you use and you can update then.
Thanks
