### ISSUE TITLE
Multiple devices

### ISSUE THREAD

**Issue by UKenGB** [bwp91/homebridge-ewelink#140]
**What issue do you have? Please be as thorough and explicit as possible.**
Not so much an issue as a question. I want to setup multiple Mini and Basic Switches, but I can find no suggestion how to do that. Some advice as to how multiple switches can be configured would be much appreciated. They're set up and functioning in eWeLink, it's just the Homebridge config I'm asking about.

**Details of your setup.**

Do you use Homebridge or HOOBS?
Homebridge

Which version of Homebridge/HOOBS do you have?
v1.1.6

Which version of this plugin (homebridge-ewelink) do you have?
not yet installed

**Please paste any relevant logs below. It helps if you can turn `debug` and `debugReqRes` in the package settings for more thorough logging.**
> If you are posting an error then it is helpful for me to also see the previous few lines as this can show the cause of the error.

...

**Comment by bwp91** [comment]
Hi @UKenGB 

The plugin requires your eWeLink email address and password to obtain a device list from your account. Then each device is set up as an accessory in Homebridge/HomeKit without any further configuration needed.
Device status is synchronised between Homebridge and eWeLink app on a real-time basis, so changes through Homebridge will appear in the eWeLink app, and changes outside Homebridge ie manual use, function through ewelink app/alexa/google etc will appear in Homebridge.

There are [further configuration options](https://github.com/bwp91/homebridge-ewelink/wiki/Configuration) available but don't really apply to "simple" devices like the Basic and Mini.

Hope this helps
Ben

**Comment by UKenGB** [comment]
That’s brilliant Ben, thanks. I was pondering this while lying in bed this morning and realised this was probably how it would work. But good to have you confirm it. Thanks again.

Got some wiring to do today. :)

**Comment by UKenGB** [comment]
One other point. When adding a new device in eWeLink, will that be auto added to HomeKit/Home.app or does Homebridge need to be restarted?

**Comment by bwp91** [comment]
It should be added as soon as Homebridge gets a notification about it eg the first time it is switched on/off through the ewelink app. New devices should be added "on the go" but as with anything if it doesn't work then restart Homebridge.

You've probably a lot of time for wiring with lockdown number two eh!

**Comment by UKenGB** [comment]
Yes, but being retired gives me plenty of time. Always busy though.

You’re in the South of UK? Anywhere near Surrey?


Ken  G i l l e t t

_/_/_/_/_/_/_/_/

**Comment by bwp91** [comment]
Hampshire!

**Comment by UKenGB** [comment]
Ah, not so far then.

Another quick question if I may. Is there any disadvantage to having dynamically assigned IP addresses?

For some devices it’s best to have it static, but I’m thinking that with these Sonoff switches, it probably doesn’t matter as eWeLink doesn’t seem to need to know the IP address in order to connect to a device, so if it changes, should still work, but does the IP address get passed back for HomeKit to use in order to communicate with the device?

I can set up static addresses if required, but it’s less faff if I don’t have to. To be honest, they mostly never change anyway, but unless I set up a static address, I cannot guarantee it won’t change. Will that matter?


Ken  G i l l e t t

_/_/_/_/_/_/_/_/

**Comment by bwp91** [comment]
I don't own the basic/mini device myself, but I assume they would work with LAN mode, which means the plugin is able to control these devices directly over your home network.

When the plugin initialises, it scans your network for compatible eWeLink devices and obtains the IP address for each. If a device IP changes then the plugin will update it's IP address only when it gets an update (e.g. controlling the device manually or through eWeLink app). The plugin doesn't perform a regular scan to detect IP changes.

If the IP does change and the request to the device fails, the plugin will fallback to using the cloud connection so the device will still update.

As I said I'm not sure if the mini/basic support LAN mode (I suspect they would as they are popular devices). If you have the time to assign them static IPs, I guess there could be a performance improvement in the cases that it would change IP. But it won't affect the functionality of the plugin at all.

**Comment by UKenGB** [comment]
Ok that makes sense. I’ll leave them on dynamic and see if there's any problem in the future. I doubt it anyway as most devices just seem the get the same address forever. Unless I change the DHCP address range, but I’ll worry about that if and when.

So far the Minis seem to be working fine (more than can be said for HomeKit/Siri in general), but I did have a problem naming the devices in eWeLink. I included colons (:) which is allowed there, but Home does NOT allow and that caused much messing about trying to get the names changed globally to something acceptable as there are 3 places the name can be set. eWeLink, Homebridge and Home, which raised another question:-

When the accessories are first added to Homebridge, the names are taken from that set up in eWeLink and no doubt Home.app takes that same name (a bit unsure there due to my : error). But after that, what then? Is the name ever again sync’d between eWeLink and Homebridge? It seems not, but is there any way to force Homebridge to re-read the eWeLink name, or is it possible to update the eWeLink name from Homebridge?

Once correctly named of course this is unlikely to happen again, but naming is of course quite important for it all to make sense around the home and until that has been fully understood and decided on, sometimes changes need to be made and it would be handy to be able to set the name in one place and have that sync’d everywhere. Any way to do that?


Ken  G i l l e t t

_/_/_/_/_/_/_/_/

**Comment by bwp91** [comment]
> but Home does NOT allow and that caused much messing about trying to get the names changed globally to something acceptable as there are 3 places the name can be set

I didn't realise HomeKit didn't allow colons in device names - I guess because I have never tried it myself! Did the plugin give any error when trying to add the devices with colons in names?

Regarding device names, this is the process:

1. When adding a new device to Homebridge, the plugin will take the name from eWeLink and use this for the device name in both Homebridge and HomeKit.
2. The names then become independent of each other (in all three places: ewelink, homebridge and homekit)
* Homebridge is unable to change any device name in HomeKit (for any plugin in fact), without effectively removing and re-adding the device (which is not viable)
* Device name syncing is something I have chosen to not implement - I'm sure there are many users that hardly use the eWeLink app, have outdated device names and wouldn't want these overriding their updated Homebridge names.

**Comment by UKenGB** [comment]
I used names like Switch:light:bedroom as a virtual path, but HomeKit uses the room location anyway to refer to a device so my naming scheme was unnecessary. The names did appear in Homebridge (which has no problem) and also in Home, but I was unable to edit them in the latter without removing the colons (error otherwise about using special characters and then Home leaves you apparently stuck, not hung but no screen response) and that then seemed to cause problems as data was obviously cached elsewhere so names would display as I had typed (no colons) and then revert back, before my eyes. Irritatingly it doesn’t save what you do as you do it. I set up a lot of names and moved accessories to the appropriate rooms but then got hit by the colon gremlin, had to close Home and on restarting, none of the changes had been saved so I had to do them all again. My experience oh HomeKit is mostly having to do the same thing over and over again.

I think part of the problem is my setup. Not that I’m doing anything wrong, just Home.app typically NOT behaving as it should. I use a household iCloud account for all this sort of stuff and that account set up the home, but shares it to me, with full editing rights. This process is terribly flawed in Home. I first discovered that if I set up an Automation, it would be displayed and possibly work, if I then left the Automations display and then returned, it would have vanished. Not hidden, literally it no longer existed. If I was really quick, I could sometimes see it when returning to Automations, but it would then simply vanish from the screen. Only when logged in to the household account (and its iCloud account) and setting up Automations there do they actually stay put.

This is not the only instance of Home(Kit) being deeply flawed. It is singularly the WORST piece of Apple software I’ve ever had occasion to use in nearly 40 years working with the Mac. A lot of Home’s UI design is atrocious and then most of HomeKit doesn’t even actually do what it is supposed to. Automations and/or scenes that worked yesterday, don’t today. When trying to activate a scene from my Watch (that previously ran ok), Siri told me I had not yet set up any accessories. It’s so bad it’s a joke, albeit an unfunny one. If it wasn’t for Homebridge I’d have given up. But I digress.

I intend to use eWeLink as little as possible. It does work well (better than Home IMO) but I want the integration HomeKit offers and may one day provide (oops, there I go again). I’ll just use eWeLink to setup devices that need it, then rely on HomeKit (risky though). However, it still makes sense to have the correct names so I know which device I’m dealing with in each environment.

Ideally, I think all names should be the same. Would it be possible for names as specified in Home to update Homebridge and then to update eWeLink? If so, an option to enforce that would be perfect, then those who do or do not want that can both be happy.

**Comment by bwp91** [comment]
In an ideal world, I would love to have names syncing between all three places. But it is something I have chosen not to do now as they way I'd need to implement it would involve resetting device names in HomeKit - something every user would not be happy with.

The way I see it is best to spend some time giving the device the same name in all three places manually. 

Personally, I have my device names set up as I want in the Home app, and haven't even bothered changing them in Homebridge and eWeLink, as it's very rare that I actually use these to control devices.

**Comment by UKenGB** [comment]
Yes, I get that. It’s not a big deal as like you, I drive everything through Home.app so to a certain extent Homebridge and eWeLink names are irrelevant, but it helps me to immediately understand what’s what if they are the same. It is pretty much a one-off though and once the names are set as required, they don’t need to be changed.

I have a few lights now being successfully controlled and the plug outlets just arrived this morning so I can bring those under Home control now and so far, Sonoff stuff is all working great. So well done.

I’d like to ask you (as someone with HomeKit experience) about another HomeKit issue I’m pondering - Doorbell cameras.

I have a cheap one I hoped to bring into HomeKit. It’s a very common one that uses the XSHcam app, but I have been totally unable to determine any way to access either snapshots or streams and without that information I am unable to set it up in Homebridge. I realise this is outside the purview of your plug-in, but can you suggest how to obtain streams etc from these rather ‘locked-in’ cameras or recommend a doorbell/cam that can work with Homebridge or even a reasonably priced HomeKit compatible one?

The latter is a rare beast as HomeKit ones like Netatmo are well over £200 and when a non HomeKit equivalent can be had for a tenth of that, I struggle to justify that outrageous expense. The Nest Hallo (or Hello, or whatever it’s called) would probably be suitable as it is slim and would fit the space beside the door and I believe could work using the Nest plug-in that I already use, but again, outrageously expensive.

I just wondered if you had any recommendations or suggestions about these devices.


Ken  G i l l e t t

_/_/_/_/_/_/_/_/

**Comment by bwp91** [comment]
Depending on the model of the camera you have, you may be able to use [homebridge-camera-ffmpeg](https://github.com/Sunoo/homebridge-camera-ffmpeg), and find out the parameters needed for the stream from the [iSpy database](https://www.ispyconnect.com/sources.aspx). Some devices also support some sort of motion detection so the plugin can create a motion sensor in HomeKit too.

I can't really make a suggestion as I am used to my Ring doorbell which generally works well!

**Comment by bwp91** [comment]
Gonna close this issue. @UKenGB of course if you have anymore questions please do reach out to me on here or on the HB discord.
Thanks!
