### ISSUE TITLE
unable to control Sonoff in these few days

### ISSUE THREAD

**Issue by w90900323** [bwp91/homebridge-ewelink#141]
I've have install and using homebridge-ewelink-max v0.1.24 plugin few months (it works normally), but I found it won't work since last week.
The case is that I can see the devices at iOS "Home" app, but I can't switch on/off the device throughs "Home" app.

I found the following log in homebridge when I switch on/off using iOS "Home" app

-----------------------------------------------------------------------------

```
[7/11/2020, 6:13:21 pm] [eWeLink] Sending login request [{"action":"userOnline","userAgent":"app","version":6,"nonce":"xxxxxxxxxx","apkVesrion":"1.8","os":"ios","at":"xxxxxxxxxxxxxxxxxxx","apikey":"xxxxxxxxxxxxxx","ts":"xxxxxxxxxxxx","model":"iPhone10,6","romVersion":"11.1.2","sequence":xxxxxxxxxxxxxx}]
[7/11/2020, 6:13:21 pm] [eWeLink] WebSocket messge received:  {"error":400,"reason":"Bad Request","apikey":"xxxxxxxxxxxxxxxxxx","sequence":"xxxxxxxxxxxxx","actionName":"userOnline"}
```

-----------------------------------------------------------------------------

What can I do to fix the error? 

Many thanks

**Comment by bwp91** [comment]
Hi @w90900323 

Please note that I am not the author/owner of homebridge-ewelink-max and am unable to fix errors with this plugin.
I can redirect you to similar issues people have been facing with homebridge-ewelink-max:

* https://github.com/howanghk/homebridge-ewelink/issues/120 and
* https://github.com/howanghk/homebridge-ewelink/issues/121

Mainly the solution being to install my own plugin homebridge-ewelink.

Hope this helps

**Comment by w90900323** [comment]
> Hi @w90900323
> 
> Please note that I am not the author/owner of homebridge-ewelink-max and am unable to fix errors with this plugin.
> I can redirect you to similar issues people have been facing with homebridge-ewelink-max:
> 
> * [howanghk#120](https://github.com/howanghk/homebridge-ewelink/issues/120) and
> * [howanghk#121](https://github.com/howanghk/homebridge-ewelink/issues/121)
> 
> Mainly the solution being to install my own plugin homebridge-ewelink.
> 
> Hope this helps

Many thanks, it works now
