### ISSUE TITLE
Sonoff TH10/16 Switch (Power On/Off) is shown as Temperature. So the Icon doesnt change color if power is turned to on.

### ISSUE THREAD

**Issue by Dominik-1980** [bwp91/homebridge-ewelink#143]
In the original Homekit App by Apple the Switch Status Power On or Power Off is written on the Symbol, but if the Status is On, the Symbol doesn’t change color to white. That’s because the Switch is shown as Temperature.

**Comment by bwp91** [comment]
Hi,
have you tried the home app option to “show as separate tiles”? then you should have a power switch tile that behaves exactly as you are asking about.

**Comment by Dominik-1980** [comment]
Hey Ben,

there is no option „show as separate titles“. I am on iOS 14.2.
iOS 14 does automatically group temperature and humidity sensors under a separate icon on the top of the screen.
On the switch is written „eingeschaltet“ (i am from Germany). But the symbol in the corner shows that icon as temperature sensor. So the icon color doesn’t change if it is on or off...
In previous versions of the homebridge-ewelink plugin everything was displayed correctly. Even in iOS 14.2. I did an update since some weeks and in the current version there is this issue...

**Comment by bwp91** [comment]
Would you be happy to share this device to my ewelink account so i can look into this more easily?
thanks

**Comment by Dominik-1980** [comment]
How can I do this?

**Comment by bwp91** [comment]
Through the ewelink app try sharing to:
country code 44 (uk)
email bwp91@icloud.com

**Comment by Dominik-1980** [comment]
Done!

**Comment by bwp91** [comment]
Can I turn it on/off?

**Comment by Dominik-1980** [comment]
Yes. You can do what you want. Nothing is connected to this device. It is just for your testing.

**Comment by bwp91** [comment]
Are you running homebridge? homebridge-config-ui? hoobs?

**Comment by Dominik-1980** [comment]
Homebridge with Homebridge-Config-UI. Everything updated to latest version yesterday. Running on a Raspberry PI 3B.

**Comment by bwp91** [comment]
Fab.
Can I get you to use [this guide](https://github.com/bwp91/homebridge-ewelink/wiki/Beta-Version) to install a beta version, v3.12.0-6, and then
Use [this guide](https://github.com/bwp91/homebridge-ewelink/wiki/How-to-remove-an-accessory-from-the-cache) to remove the current TH10/16 device from the homebridge cache, so it is readded.

**Comment by Dominik-1980** [comment]
I am on 4.32.0
Do i have to downgrade?
I don’t want this.

**Comment by bwp91** [comment]
No, it’s a beta version of this plugin :)

**Comment by Dominik-1980** [comment]
:-)) Okay. I've installed the latest beta v3.12.0-6.
Everything is the same. But Homebridge loaded the cache.
The Menu to clean the cache doesn't show on my Homebridge-ui. 
I realised that my Homebridge is not running as a service. 
I will try to change this. I hope it isn't to complicated. I'll try this in 1 or 2 hours. 
When I got it, i'll write here a message...

**Comment by Dominik-1980** [comment]
It worked. One time. Now I am in trouble. I've installed the hb-service but i have systemd too. Than I hab 2 instances of Homebridge running. One on port 8181 and one on port 8581 (the new one with hb-service). The Config-UI showed me the new options. On HomeKit nothing worked any more. So I deleted the HomeBridge in the Home App and scanned the QR-Code in Config-UI I've started with hb-service. Now I could install the new Items. The Buttons worked now. When I restarted my Raspberry. I'm back on the old version of Homebridge. I've to deleted this anyway and use the new one. I've deleted the systemd/homebridge.serrvice and nothing works any more. :-(

**Comment by Dominik-1980** [comment]
I think I got it running. Now with hb-service. I had fear because my whole house is controlled over the Homebridge. Now it works again and I've new options in the Config-UI Interface. Great. Now your ewelink devices are shown correctly. Thank you!!

**Comment by bwp91** [comment]
Amazing :) Glad it’s working for you!
