### ISSUE TITLE
There is no option "Display as fan" for T1 C2 / C1 switches

### ISSUE THREAD

**Issue by VictorKrasnov** [bwp91/homebridge-ewelink#144]
There is no option "Display as fan" for T1 C2 / C1 switches in HomeKit setting for these devices.

It was possible to change type of switch from light to fan when I used homebridge-ewelink-max plugin.

**Comment by bwp91** [comment]
Hi, which version of the plugin are you using?
This was one of the questions in the issue template :)

**Comment by VictorKrasnov** [comment]
Well... I restarted homebridge, now T1 look like switches, not like lightbulbs. The problem solved. Anyway, sorry for bothering you.

**Comment by bwp91** [comment]
It’s no bother at all :)
Glad you got it working!
