### ISSUE TITLE
Sonoff not working

### ISSUE THREAD

**Issue by Relliks44** [bwp91/homebridge-ewelink#146]
**What issue do you have? Please be as thorough and explicit as possible.**
I cant controll my sonoff through homebridge.
...

**Details of your setup.**
Do you use Homebridge or HOOBS?
Homebridge
...

Which version of Homebridge/HOOBS do you have?
homebridge-ewelink-max@0.1.24
...

Which version of this plugin (homebridge-ewelink) do you have?
homebridge-ewelink-max@0.1.24
...

**Please paste any relevant logs below. It helps if you can turn `debug` and `debugReqRes` in the package settings for more thorough logging.**
> If you are posting an error then it is helpful for me to also see the previous few lines as this can show the cause of the error.

`Nov 12 18:36:05 raspberrypi homebridge[4135]: [11/12/2020, 18:36:05] [eWeLink] WebSocket messge received:  {"error":400,"reason":"Bad Request","apikey":"c2385316-2582-41a2-94f3-1828087e0d30","sequence":"1605206165057","actionName":"userOnline"}
Nov 12 18:36:06 raspberrypi homebridge[4135]: [11/12/2020, 18:36:06] [eWeLink] Requesting power state for [Computer]
Nov 12 18:36:06 raspberrypi homebridge[4135]: [11/12/2020, 18:36:06] [eWeLink] API reported that [Computer] is Off
Nov 12 18:36:10 raspberrypi homebridge[4135]: [11/12/2020, 18:36:10] [eWeLink] Requesting power state for [Computer]
Nov 12 18:36:10 raspberrypi homebridge[4135]: [11/12/2020, 18:36:10] [eWeLink] API reported that [Computer] is Off
Nov 12 18:36:10 raspberrypi homebridge[4135]: [11/12/2020, 18:36:10] [eWeLink] Setting power state to [on] for device [Computer]
Nov 12 18:36:10 raspberrypi homebridge[4135]: [11/12/2020, 18:36:10] [eWeLink] WebSocket messge received:  {"error":406,"sequence":"1605206170830"}
Nov 12 18:36:10 raspberrypi homebridge[4135]: [11/12/2020, 18:36:10] [eWeLink] WebSocket was closed. Reason [1006]
Nov 12 18:36:15 raspberrypi homebridge[4135]: WebSocketClient: reconnecting...
Nov 12 18:36:15 raspberrypi homebridge[4135]: [11/12/2020, 18:36:15] [eWeLink] Sending login request [{"action":"userOnline","userAgent":"app","version":6,"nonce":"160520617591300","apkVesrion":"1.8","os":"ios","at":"8ab741f7e919e2aeed3f4f42cf0d8f23a91d8a51","apikey":"c2385316-2582-41a2-94f3-1828087e0d30","ts":"1605206175","model":"iPhone10,6","romVersion":"11.1.2","sequence":1605206175913}]
Nov 12 18:36:15 raspberrypi homebridge[4135]: [11/12/2020, 18:36:15] [eWeLink] WebSocket messge received:  {"error":400,"reason":"Bad Request","apikey":"c2385316-2582-41a2-94f3-1828087e0d30","sequence":"1605206175913","actionName":"userOnline"}`

...

**Comment by bwp91** [comment]
Hi @Relliks44 

Please note that I am not the author/owner of homebridge-ewelink-max and am unable to fix errors with this plugin.
I can redirect you to similar issues people have been facing with homebridge-ewelink-max:

* https://github.com/howanghk/homebridge-ewelink/issues/120 and
* https://github.com/howanghk/homebridge-ewelink/issues/121

Mainly the solution being to install my own plugin homebridge-ewelink.

Hope this helps
