### ISSUE TITLE
On a regular basis switches, through homebridge cease to work

### ISSUE THREAD

**Issue by motogon** [bwp91/homebridge-ewelink#147]
**What issue do you have? Please be as thorough and explicit as possible.**

On a regular basis switches, through homebridge cease to work 
(In the original appendix ewelink problems are not present)

reboot HOOBS solves a problem, but not for a long time

...

**Details of your setup.**
Do you use Homebridge or HOOBS?

HOOBS in docker

Which version of Homebridge/HOOBS do you have?

HOOBS 3.2.6

Which version of this plugin (homebridge-ewelink) do you have?

3.12.0

**Please paste any relevant logs below. It helps if you can turn `debug` and `debugReqRes` in the package settings for more thorough logging.**
> If you are posting an error then it is helpful for me to also see the previous few lines as this can show the cause of the error.

At a problem:
14.11.2020, 14:34:49 [eWeLink] WS login failed [Unknown parameters received
{
  "error": 406,
  "apikey": "17e6aa41-8735-4456-bc23-xxxxxxxxxx",
  "sequence": "1605353xxxxxxx",
  "actionName": "userOnline"
}].

After reboot HOOBS:
14.11.2020, 14:51:03 [eWeLink] Sending WS login request.
14.11.2020, 14:51:20 [eWeLink] Web socket closed - [1006].
14.11.2020, 14:51:20 [eWeLink] Web socket will try to reconnect in five seconds.
14.11.2020, 14:51:25 [eWeLink] Sending WS login request.

**Comment by bwp91** [comment]
Hi @motogon 

Do you use a second ewelink account for this plugin? Or do you use your main ewelink account credentials?

**Comment by motogon** [comment]
main ewelink account

**Comment by bwp91** [comment]
I have seen this `"error": 406,` before when being logged into two Homebridge instances at the same time with the same ewelink credentials. could this be the case?

**Comment by motogon** [comment]
I have a single copy of Homebridge,
And the original ewelink app was not used at that time

**Comment by bwp91** [comment]
Another couple of questions,

* Are you trying to control any switches that are shared to your main ewelink account?

* Do you have the latest version of the ewelink app on your phone and have you logged in recently?

**Comment by motogon** [comment]
>     * Are you trying to control any switches that are shared to your main ewelink account?

Yes

>     * Do you have the latest version of the ewelink app on your phone and have you logged in recently?

Yes

**Comment by bwp91** [comment]
> Are you trying to control any switches that are shared to your main ewelink account?
Yes

This is what might be causing the issue. Is there any way you can setup these "shared" devices in your main ewelink account?

**Comment by motogon** [comment]
New in logs:

[eWeLink] Sending WS login request.
14.11.2020, 15:37:25 [eWeLink] Web socket host received [eu-pconnect4.coolkit.cc].
14.11.2020, 15:37:25 [eWeLink] Web socket gracefully closed.
14.11.2020, 15:37:26 [eWeLink] Sending WS login request.
14.11.2020, 15:37:26 [eWeLink] WS login failed [Error: Unknown parameters received
{
  "error": 406,
  "apikey": "17e6aa41-8735-4456-bc23-xxxxxxx",
  "sequence": "1605357xxxxxxx",
  "actionName": "userOnline"
}
    at /hoobs/node_modules/homebridge-ewelink/lib/ewelink-ws.js:97:17
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)].
14.11.2020, 15:37:26 [eWeLink] WS unknown command received.
{
  "error": 406,
  "apikey": "17e6aa41-8735-4456-bc23-xxxxxx",
  "sequence": "1605357xxxxxx",
  "actionName": "userOnline",
  "params": {}
}

**Comment by motogon** [comment]
>  Is there any way you can setup these "shared" devices in your main ewelink account?

I understood correctly:
I need to create an additional ewelink account and make shared devices in my main ewelink account for it.
And in HOOBS, specify the parameters of the new account?

**Comment by bwp91** [comment]
> I need to create an additional ewelink account and make shared devices in my main ewelink account for it.
And in HOOBS, specify the parameters of the new account?

No, this isn't what I mean.

I mean, you ideally should have all your ewelink devices set up in your main ewelink account. You said earlier that there are some devices "shared" to your main ewelink account (ie they were set up in a different account and have been shared to your main ewelink account)

**Comment by motogon** [comment]
> I mean, you ideally should have all your ewelink devices set up in your main ewelink account

I probably misunderstood you and answered :(

All my ewelink devices are configured in my main ewelink account, I only have one ewelink account.

**Comment by bwp91** [comment]
Which ewelink devices do you have?

**Comment by motogon** [comment]
1 - sonoff mini 
1 - dimmer KingArt King-M4

**Comment by bwp91** [comment]
And your internet connection is stable? Errors with the web socket can appear if your internet connection drops

**Comment by motogon** [comment]
I did not notice any problems, I use the gpon channel

**Comment by bwp91** [comment]
Could I message you directly on the [Homebridge Discord](https://discord.gg/7X36mdw)?

**Comment by motogon** [comment]
> Could I message you directly on the [Homebridge Discord](https://discord.gg/7X36mdw)?

yes , my nick dend

**Comment by motogon** [comment]
ok
thanks
