### ISSUE TITLE
Negative temperature TH16

### ISSUE THREAD

**Issue by ghost** [bwp91/homebridge-ewelink#148]
When Sonoff TH16 show in ewelink Negative temperature in Homekit i got accessory not responding for temp
Most likely the plug-in does not correctly transmit negative temperature values

* Homebridge v1.2.3
* Homebridge-ewelink v3.13.0
* Sonoff TH16

**Comment by bwp91** [comment]
Hi @FindVPS 

I have made a couple of changes to the plugin that I would like you to test.

1. Please use [this guide](https://github.com/bwp91/homebridge-ewelink/wiki/Beta-Version) to update to a beta version of the plugin - the version you'll need is v3.13.3-1.
2. Then use [this guide](https://github.com/bwp91/homebridge-ewelink/wiki/How-to-remove-an-accessory-from-the-cache) to remove the TH16 accessory from the Homebridge cache, this is necessary for it to be readded to Homebridge.

After doing this you should find that negative temperatures are correctly shown in Homebridge.

Let me know!

**Comment by ghost** [comment]
Now all is ok - temp (-1) is show) Thank you!

**Comment by bwp91** [comment]
Perfect!
