### ISSUE TITLE
Charles App Auth Token not Displayed

### ISSUE THREAD

**Issue by ghost** [bwp91/homebridge-ewelink#15]
Hi gbro115, 
Can you give us a full walkthrough through de Charles App, and iPhone Config.
I Tried it for about 10 Times, with different Configs, but de Auth Token is not shown up in Charles.

Thx a lot if you do so

Here are my Screenshots:
<img width="931" alt="bildschirmfoto 2018-03-18 um 22 15 15" src="https://user-images.githubusercontent.com/37530033/37581778-42c35ed2-2b4a-11e8-8d8d-a91741be506c.png">
<img width="817" alt="bildschirmfoto 2018-03-18 um 22 15 07" src="https://user-images.githubusercontent.com/37530033/37581779-42dd46f8-2b4a-11e8-99fd-6d9e5713c4a6.png">
<img width="525" alt="bildschirmfoto 1" src="https://user-images.githubusercontent.com/37530033/37581780-42f9c15c-2b4a-11e8-9bdd-bde161b5a155.png">
<img width="580" alt="bildschirmfoto 2" src="https://user-images.githubusercontent.com/37530033/37581782-43149324-2b4a-11e8-9005-20e48209bc27.png">

**Comment by DJay-X** [comment]
Same problem here, also with macOS, iOS. I go back and forth without any success finding the Auth Token. Thanks in advance for any help.

**Comment by jwhits** [comment]
I just had to re add the new authorisation bearer, as the new update of the eWeLink app made me log back in.

It took me awhile to find it but here mine was.
<img width="891" alt="screen shot 2018-03-26 at 8 35 31 pm" src="https://user-images.githubusercontent.com/4166668/37899026-0e219d00-3136-11e8-888f-5715afad8942.png">

Here is the thread that I used initially to set up Charles to be able to get the bearer. 
https://github.com/gbro115/homebridge-ewelink/issues/1

From you screenshots, I think you need to set all your pots to 8080 and make sure you have set the ssl proxy in Charles as well.

**Comment by lawrencedchan** [comment]
@BobbySlope I am not able to get the token too.
@jwhits how could you re-add the new authorisation bearer?
<img width="1671" alt="screen shot 2018-05-08 at 10 40 47 pm" src="https://user-images.githubusercontent.com/39067655/39763894-e2e52dd0-5310-11e8-9df8-a91333725914.png">

**Comment by jwhits** [comment]
@lawrencedchan Did you do all the initial set up on your phone and Charles? As per instructions in this thread https://github.com/gbro115/homebridge-ewelink/issues/1#issuecomment-353937981

In Charles the bearer is under the HTTPS version of the link you selected, I don't see that in your screenshot

**Comment by mofolo** [comment]
You need to also install the SSL Certificate on your iOS device as well as going into General > About > Trusted Certificate and turn on the Charles certificate

**Comment by immSysEngg** [comment]
@BobbySlope @lawrencedchan 

I have been trying to do the same with Charles and EweLink App...the instructions I have read so far are in general correct but they miss the steps required to accomplish the results. Here is my take on it...hopefully this might help you

**My Setup**
MacBook Pro, macOS Mojave 10.14.4
iPhone XS Max, iOS 12.3.1
Charles Application...hopefully you already downloaded it (https://www.charlesproxy.com/download/)

**MacBook Pro Steps**
1. Download Charles, Drag and Drop in Application Folder
2. Run Charles by double clicking on its icon
3. Usually at launch, Charles will perform proxy configuration...let it do that
4. Open Proxy Menu, and click on proxy 
![Proxy](https://user-images.githubusercontent.com/51437384/59017580-515e9580-885d-11e9-93cd-226abc0f16fb.jpg)
5. Click on Proxy Settings and verify your settings with these
![HomeBridge 2019-06-06 at 1 46 43 PM](https://user-images.githubusercontent.com/51437384/59019654-e5326080-8861-11e9-8291-b9d1203f0f97.jpg)
![HomeBridge 2019-06-06 at 1 46 56 PM](https://user-images.githubusercontent.com/51437384/59019661-e794ba80-8861-11e9-96f2-840e5d4dfc85.jpg)
6. Usually Charles will auto configure (step 3) Proxy with port 8888...that should be ok. However I have found that port 8080 gives you the least headache. Please change the proxy port to 8080 and ensure "Enable transparent.." is checked

**iPhone Steps**
1. Go to Settings -> WiFi...tap on "i" in front of your WiFi name
![Unknown](https://user-images.githubusercontent.com/51437384/59020592-bd43fc80-8863-11e9-9b31-789ec16aca1f.jpg)
2. Go To the Botton and click on "Configure Proxy"
![Unknown-2](https://user-images.githubusercontent.com/51437384/59020668-e795ba00-8863-11e9-9aee-3b0b99306db5.jpg)
3. Select Manual and make sure your settings matches these (for Server use the IP of Mackbook where Charles is running)
![Unknown-3](https://user-images.githubusercontent.com/51437384/59020742-0ac06980-8864-11e9-8b97-e80f3e6ae2b4.jpg)

**Check Charles is WORKING PROPERLY**
1. Ensure Charles is running
2. Launch EweLink App
3. You should see the "http addresses" in Charles....don't worry they will have unknown at this time
![Chalres1](https://user-images.githubusercontent.com/51437384/59021165-c84b5c80-8864-11e9-9055-58689cd665f2.jpg)
4. Please note the http addresses "coolkit" in it...usually three of them  (in my case : "as-api", "as-ota", "api"....please note yours may have different region like "eu-api", "eu-ota"). Note these
![Chalres1](https://user-images.githubusercontent.com/51437384/59021251-ee70fc80-8864-11e9-87a6-29a7bbc1d8e8.jpg)
5. Now open SSL Proxy Settings in Charles
![SSL Settings](https://user-images.githubusercontent.com/51437384/59021612-8d95f400-8865-11e9-97b1-946113b6d134.jpg)
6. Using the ADD button...add the three addresses (step 4) in "SSL Proxying" and "Client Certificates"
![HomeBridge 2019-06-06 at 2 16 01 PM](https://user-images.githubusercontent.com/51437384/59021760-e2396f00-8865-11e9-9d61-01637768ba2c.jpg)
![HomeBridge 2019-06-06 at 2 16 08 PM](https://user-images.githubusercontent.com/51437384/59021763-e4033280-8865-11e9-8f89-d06798e4c4bb.jpg)
7. Now Open "Proxy->Access Control Settings" in Charles...Please ADD IP address of your iPhone here where the EweLink App is running
![HomeBridge 2019-06-06 at 2 19 10 PM](https://user-images.githubusercontent.com/51437384/59024615-b4572900-886b-11e9-8bb1-f0d76cfdbec7.jpg)

**VERY CRITICAL STEP**
1. Open "Proxy->Web Interface Settings" in Charles
![HomeBridge 2019-06-06 at 2 31 30 PM](https://user-images.githubusercontent.com/51437384/59022744-d0f16200-8867-11e9-8e1f-0158e0b74c56.jpg)
2. IF YOU DO NOT DO THIS, YOU WILL NOT BE ABLE TO INSTALL **CHARLES SSL CERTIFICATE** ON iPhone...most instructions miss this and try to launch **SSL Certificate http address** on iPhone, which will obviously fail with "page not found". PLEASED ADD YOUR iPhone IP address here and CHECK the "Allow Anonymous access.."
![HomeBridge 2019-06-06 at 2 34 34 PM](https://user-images.githubusercontent.com/51437384/59022993-42c9ab80-8868-11e9-982c-7a8ebd631c38.jpg)

**SSL CERTICATE on iPHONE**
1. Open Safari and type in this http address "https://chls.pro/ssl". Note "https" not "http"
2. Safari Should prompt your for "website wants to download profile" or something like that
3. Go head and allow it
4. Go to Settings->General->Profile....and install the Charles profile
![Unknown-1](https://user-images.githubusercontent.com/51437384/59023688-bb7d3780-8869-11e9-86ed-492c7b37c777.jpg)
5. One the Certificate is installed, Please go to Settings-> General->About->Certificate Trust Settings (at the bottom) and allow full access by turning on the option
![Unknown-11](https://user-images.githubusercontent.com/51437384/59023834-039c5a00-886a-11e9-8b34-a768e2cd623e.jpg)

**ALL IS SET UP NOW...LET's GET THE BEARER VALUE**
1. Launch Ewelink App on iPhone
2. Check Charles Window on Mackbook
![HomeBridge 2019-06-06 at 2 49 29 PM](https://user-images.githubusercontent.com/51437384/59024012-65f55a80-886a-11e9-90ba-2490b9a59490.jpg)
3. You should see "BLUE ICON" in front of "coolkit" http addresses. Also note the addresses we haven't added in SSL Settings in Charles they have plain icon like a "lock"
4. Now click on "xx-ota..." address, inside click on item having "queryinfo" string (there may be more than one...just select first one. Select HEADERS on the write side window. You should see the BEARER value for your Ewelink account in front "AUTHORIZATION" header
![HomeBridge 2019-06-06 at 2 54 07 PM](https://user-images.githubusercontent.com/51437384/59024436-5591af80-886b-11e9-9567-95fcf8e2e37d.jpg)


I hope this helps...works perfectly for me

**Comment by immSysEngg** [comment]
Please note a vital information for making Ewelink plugin work.....

Pugin requires JSON file configuration like this:
            "platform" : "eWeLink",
            "name" : "eWeLink",
            "authenticationToken" : "--------------", 
            "apiHost" : "xx-api.coolkit.cc:8080",
            "webSocketApi" : "xx-pconnect3.coolkit.cc"

Values:
- authenticationToken is obtained from Charles
- apiHost, webSocketApi addresses are working as of now....replace xx with your region eg "eu", "us", "as" etc

Another important point
- use homebridge-ewelink-plus plugin instead as it can support multiple channel Smart panels (2 gang, 3 gang, 4 gang etc)

**Comment by mofolo** [comment]
Use eWeLinkMax and it will do all of this for you. All you need to do is provide your mobile and password. Easy.

https://www.npmjs.com/package/homebridge-ewelink-max
