### ISSUE TITLE
Request for ability to split dual channel device in to different device types

### ISSUE THREAD

**Issue by shanelilley** [bwp91/homebridge-ewelink#150]
* **Please explain your feature request in a one or two sentences.**
Two channel devices might want a "switch" for one and a "irrigation" for the other. It would be great to discern between the two in the config. 

* **Is your feature request related to a problem? Please describe.**
Not a problem at all - purely an enhancement :) 

* **Any particular eWeLink devices that this relates to?**
2 channel relay switch

* **Anything else?**
So to give you the scenario - I have a two channel out the back of my house with the need for one channel to operate a soleniud for watering, and the other to be a switch for lighting at night. Instead of "wasting" a channel on a dual channel device, or having to have two separate devices, if we dould separate them out, that would be awesome! This is purely an enhancement request though. 

Kind regards,
Shane

**Comment by bwp91** [comment]
Hey, could I message to you on the [Homebridge Discord](https://discord.gg/7X36mdw)?

**Comment by shanelilley** [comment]
Sure thing! I am online. Jaggadaz#1791 

Kind regards,
Shane
