### ISSUE TITLE
This plugin and eWelink's ToS

### ISSUE THREAD

**Issue by ScriptNewbie** [bwp91/homebridge-ewelink#152]
I mean in 2.2 "(...) The User shall not operate the Software through other software or create any derivative of the software in any form (...) or accessing the software through unauthorised third party tools/services" also "The user shall not copy(...) any data generated during the interaction between client and server". I see this plugin interacts with ewelink by api.coolkit.cc, but this api don't seem to be open for anyone. So was it created by reverse engineering connection between mobile apps and server, or is this api open? Thanks for your answer :)

**Comment by bwp91** [comment]
Hi @ScriptNewbie 
I am unaware of how the plugin was originally developed as the current state is a fork of another project.
The CoolKit API is documented on another github repo, and they are aware of this project.
The choice of whether you’d want to use this plugin is completely up to you.
Thanks

**Comment by ScriptNewbie** [comment]
Ok, once again thanks for your answer.
