### ISSUE TITLE
Error on installation in iobroker.ham 

### ISSUE THREAD

**Issue by entavio** [bwp91/homebridge-ewelink#155]
### What issue do you have? Please be as thorough and explicit as possible.

In iobroker.ham the installation of homebridge-ewelink fails with an error 

ERR! notsup Unsupported engine for homebridge-ewelink@3.15.0: wanted: {"homebridge":"^1.1.0","node":"^14.15.1"} (current: {"node":"12.20.0","npm":"6.14.8"}) npm ERR! notsup Not compatible with

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 
Homebridge HAM in iobroker 

* Which version of Homebridge/HOOBS do you have?
HAM in version 3.2 

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

v3.15.0 

* Do you use your main eWeLink credentials or do you use a secondary eWeLink account for Homebridge?
 
Main credentials 

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @entavio 
Your current version of nodejs is v12.20.0 and you will need to update to v14.15.1.
Does the installer not give an option to continue anyway?

**Comment by entavio** [comment]
Hi @bwp91 

ok sometimes it seems to be easier ... i have updated now but i believe beyond the goal i am now on v15.xx and get another error. do not know whether a downgrade is possible and useful

**Comment by bwp91** [comment]
You should aim to downgrade to node v14, Homebridge does not support v15 at this time

**Comment by entavio** [comment]
You know the commands for downgrade, because reinstall of v14xx says i am already on v15?!

**Comment by bwp91** [comment]
Which platform are you running homebridge / iobroker on? I have absolutely no experience with iobroker

**Comment by entavio** [comment]
In a docker image

**Comment by bwp91** [comment]
I’m not sure about docker. There must be some guide or an answered question somewhere from a google search?

**Comment by entavio** [comment]
@bwp91  ok perfekt i uninstalled nodejs v15 and installed v14.15.1 

No it works again... so plz close :-)

**Comment by bwp91** [comment]
Ah glad you got it working 👍🏻 
💡 maybe iobroker needs a ewelink plugin!

**Comment by entavio** [comment]
yes maybe from you ?! 😉
