### ISSUE TITLE
Garage door with sensor ID spinning for about 20 minutes

### ISSUE THREAD

**Issue by yghelmut** [bwp91/homebridge-ewelink#156]
### What issue do you have? Please be as thorough and explicit as possible.
I successfully installed a Sonoff Basic with the DW2 sensor. While the sensor works fine and return accurate information, in the iOs Home app the spinner indicating that the task of opening/closing the door is in progress spins around for at least 20 minutes. The config json below was modified to try:
- Minimize sensorTimeDifference to 10 seconds
- Define operationTime to 0.1 second

Even in that case, it spins for minutes/hours... 

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 
Yes, with config-ui on a raspberry zero W

* Which version of Homebridge/HOOBS do you have?
v.1.16

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?
Latest version

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.
Sonoff Basic RF2
Sonoff DW2 Sensor

* Do you use your main eWeLink credentials or do you use a secondary eWeLink account for Homebridge?
Main credentials

### Please paste any relevant logs below.

```
{
            "name": "eWeLink",
            "countryCode": "33",
            "username": "****",
            "password": "****",
            "debug": false,
            "debugReqRes": false,
            "disableHTTPRefresh": false,
            "disablePlugin": false,
            "inUsePowerThreshold": 0,
            "lowBattThreshold": 25,
            "sensorTimeDifference": 10,
            "hideZBLDPress": false,
            "groups": [
                {
                    "deviceId": "1000b80f2a",
                    "type": "garage",
                    "setup": "oneSwitch",
                    "operationTime": 1,
                    "sensorId": "1000f15bdd"
                }
            ],
            "bridgeSensors": [
                {
                    "sensorTimeLength": 1
                }
            ],
            "platform": "eWeLink"
        }
```

**Comment by bwp91** [comment]
Hi @yghelmut 
The logs could be a good indication of what is going on/wrong.
Please turn on "Debug Logging" and "Request & Response" logging from the plugin settings.
It would be useful to see the logs from when you open/close the garage onwards.
Also, I would recommend setting the `operationTime` to something more realistic for a garage, eg 100 (for 10 seconds).
Without the logs, it's almost impossible for me to figure out what's going on.
Thanks

**Comment by yghelmut** [comment]
Hi, thanks for your quick reply. Just realized that the DW2 sensors where offline (without telling anyone they went offline) since they don't support anything else than a Wifi B signal...
Problem solved, and the issue is not due to any plugin bug.

Thanks for what you created (and maintain) !!!

**Comment by bwp91** [comment]
Fab. Glad it's sorted!
