### ISSUE TITLE
th10 with temperature sensor problem when the temperature is below -0 celsius

### ISSUE THREAD

**Issue by urmo53** [bwp91/homebridge-ewelink#157]
Hi
th10 with temperature sensor problem when the temperature is below -0 celsius, then homekit cannot show the temperature, the sensor says no response.
However, Eve correctly shows the temperature value in history

**Comment by bwp91** [comment]
Hi @urmo53 
Please try removing the device from the Homebridge cache so it is readded.
I recently made an update to the plugin to allow for negative temperatures, but it requires the above step to get it working.
The Eve history will be preserved.
If this doesn't work I will look into this further.
Thanks

**Comment by urmo53** [comment]
Thank you its working!!

**Comment by bwp91** [comment]
Great, glad you got it working!
