### ISSUE TITLE
Sonoff MicroUSB Smart WiFi Adaptor

### ISSUE THREAD

**Issue by dewbertdc** [bwp91/homebridge-ewelink#158]
* **Please explain your feature request in a one or two sentences.**
I’ve just bought a Sonoff MicroUSB Smart WiFi Adaptor to control some LED lights behind my TV. Looks like this plugin doesn’t support them in eWelink. Is there a plan to add support?

* **Is your feature request related to a problem? Please describe.**

* **Any particular eWeLink devices that this relates to?**
Sonoff MicroUSB Smart WiFi Adaptor

* **Anything else?**

**Comment by bwp91** [comment]
Hi, the USB adaptor should be supported already. When you restart Homebridge what messages appear in the logs related to ewelink and this device?

**Comment by dewbertdc** [comment]
Thanks for the quick reply.  Here's the error I'm getting...

[12/3/2020, 3:15:21 PM] [eWeLink]  → [Media Room Bias Lights] could not be initialised as Cannot read property 'helpers' of undefined.

**Comment by bwp91** [comment]
Please try the just released v3.16.2!

**Comment by dewbertdc** [comment]
You're a rockstar - all good now!  Thank you - your work on this and the wemo plugin are so useful!

**Comment by bwp91** [comment]
Ah pleasure! And thank you very much for your support too :-)
I'll close this issue now. Any further problems do let me know!

**Comment by bwp91** [comment]
I'm thinking now... would it be helpful to have this shown as a switch rather than an outlet? Then you could display it as a light in the Home app

**Comment by dewbertdc** [comment]
Either way is fine, the Home app lets me change the device type to "Light" the way it is now.  My Sony TV has some wacky USB ports that turn on and off all by themselves, so this lets me automate the LEDs in Home to turn on and off with the TV.  I had this working with a WeMo, but it was too bulky to have behind the set.

**Comment by dedyushin** [comment]
WOW! Thanks a lot, faced the same issue today and now the problem solved! You are great!
