### ISSUE TITLE
Sonoff Micro USB

### ISSUE THREAD

**Issue by dedyushin** [bwp91/homebridge-ewelink#159]
* **Please explain your feature request in a one or two sentences.**

Hello! I am looking for support of Sonoff Micro USB wifi controller. It doesn't recognized by HB and HK.  

* **Is your feature request related to a problem? Please describe.**

* **Any particular eWeLink devices that this relates to?**

Sonoff Micro USB WiFi controller

* **Anything else?**

**Comment by bwp91** [comment]
Duplicate of #158. Please follow the conversation there. thanks
