### ISSUE TITLE
TH10/16 Temperature Offset

### ISSUE THREAD

**Issue by Dominik-1980** [bwp91/homebridge-ewelink#160]
### What issue do you have? Please be as thorough and explicit as possible.

Just a question, no bug.
Is it possible to adjust the degrees shown in Homekit?
My TH16 shows 2 degrees celsius less than the real temperature is...

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 

Homebridge 

* Which version of Homebridge/HOOBS do you have?

1.1.6

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

latest

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

TH16

* Do you use your main eWeLink credentials or do you use a secondary eWeLink account for Homebridge?

Main

**Comment by bwp91** [comment]
Hi @DrDoom666 
Do you have any other TH devices? or just this one?

**Comment by Dominik-1980** [comment]
I have 3 TH10/16

Greets

Von meinem iPhone gesendet

**Comment by bwp91** [comment]
* Please [update to beta version](https://github.com/bwp91/homebridge-ewelink/wiki/Beta-Version) 3.16.3-2, then restart Homebridge.
* Then add this line to the config.json:
`"thOffsetTwo": "100XXXXXX",`
where 100XXXXXX is the device id of the TH10/16 device that you want to offset
* Then restart Homebridge and see if it works

Please note I do not own a TH10/16 device myself, so am unable to test the changes I have made, meaning, there might be errors or it doesn't work properly at first.

So please let me know how you get on!

**Comment by Dominik-1980** [comment]
Works great!!
Thank you!!

Is it possible to adjust other devices +1, +2, -1, -2 ?

**Comment by bwp91** [comment]
What I implemented was a hard-coded quick solution to the sensor you mentioned in your original message.
Surely these TH devices are meant to be accurate anyway? If you’re having to offset others then it seems the sensors aren’t doing their job properly?

**Comment by bwp91** [comment]
I will close this issue now as hopefully the fix will help the sensor that is reading 2 degrees lower than it should.
I will look into implementing a way for it to be more flexible, ie, allowing different sensors to offset by +/- different temperatures.
Keep an eye out for this on a future version :)

**Comment by bwp91** [comment]
Opening this again as I found some time to try and implement something better.

@DrDoom666 please would you:

* update to another beta, v3.16.4-0
* restart Homebridge
* remove the `"thOffsetTwo": "100XXXXXX",` line from your config
* add this to your config, where `100#######` is the device id and `2` is the offset (can be any number inc. negative)
```
"thTempOffset": [
  {
    "deviceId": "100#######",
    "offset": 2
  }
],
```
* restart Homebridge again and test :)

For multiple devices you should use this as a template:
```
"thTempOffset": [
  {
    "deviceId": "100#######",
    "offset": 2
  },
  {
    "deviceId": "100#######",
    "offset": 1
  },
  {
    "deviceId": "100#######",
    "offset": -2.5
  }
],
```

**Comment by Dominik-1980** [comment]
Great work! I will test it tomorrow and give you feedback!
Now I have to go to bed. It is late in good old germany. ;-)

**Comment by Dominik-1980** [comment]
It works!! :-)

**Comment by bwp91** [comment]
Ah i’m glad. Hope it’s helpful!
