### ISSUE TITLE
TH10/16 device as full thermostat 

### ISSUE THREAD

**Issue by urmo53** [bwp91/homebridge-ewelink#161]
Hello again

th10 works as a temperature sensor and switch separately also, but if i set my th10 as a thermostat but it doesn't work. it also does not show the current temperature it shows that 0.0

I tried it on both Hoobs and Homebridge, both with the latest version.

I also use the latest Ewelink plugin

here is the log after i turned th10 into a thermostat

08/12/2020, 16:45:06 HOOBS listening on port 80.
08/12/2020, 16:45:14 Loaded plugin 'homebridge-ewelink'
08/12/2020, 16:45:15 [12/8/2020, 7:45:14 AM] Registering platform 'homebridge-ewelink.eWeLink'
08/12/2020, 16:45:15 Loading 1 platforms...
08/12/2020, 16:45:15 [eWeLink] Initializing eWeLink platform...
08/12/2020, 16:45:15 [eWeLink] Plugin [v3.17.1] initialised. Syncing with eWeLink...
08/12/2020, 16:45:15 Bridge is running on port 51826.
08/12/2020, 16:45:22 [eWeLink] [1] eWeLink devices loaded from the Homebridge cache.
08/12/2020, 16:45:22 [eWeLink] [1] primary devices loaded from your eWeLink account.
08/12/2020, 16:45:22 [eWeLink]  → [Device384dd3] could not be initialised as accessory.addCharacteristic is not a function.
08/12/2020, 16:45:22 [eWeLink] eWeLink sync complete. Don't forget to ⭐️  this plugin on GitHub if you're finding it useful!
08/12/2020, 17:23:28 (node:641) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'displayName' of undefined
08/12/2020, 17:23:28 at eWeLinkPlatform.deviceUpdateError (/home/hoobs/.hoobs/node_modules/homebridge-ewelink/lib/index.js:754:65)
08/12/2020, 17:23:28 at deviceThermostat.internalOnOffUpdate (/home/hoobs/.hoobs/node_modules/homebridge-ewelink/lib/device/thermostat.js:60:21)
08/12/2020, 17:23:28 (Use `node --trace-warnings ...` to show where the warning was created)
08/12/2020, 17:23:28 (node:641) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
08/12/2020, 17:23:28 (node:641) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
08/12/2020, 17:23:43 [eWeLink] [Device384dd3] could not be refreshed as Cannot read property 'externalUpdate' of undefined.
08/12/2020, 18:37:53 + homebridge-ewelink@3.17.2
updated 1 package in 8.703s

**Comment by bwp91** [comment]
Hi @urmo53 please try the just released v3.17.3

**Comment by urmo53** [comment]
Unfortunately still can't read the temperature. it is still 0.0
but switching the "thermostat" works.

**Comment by urmo53** [comment]
now does not display the temperature at all even if it is not set to thermostat

**Comment by bwp91** [comment]
And are you sure the temperature just doesn't happen to be 0.0 right now? 😛 

Can I message you directly on my discord channel?
https://discord.gg/cMGhNtZ3tW

**Comment by bwp91** [comment]
Reopening this as it may be possible now!

**Comment by bwp91** [comment]
A fully working implementation of using a TH10/16 device as a thermostat is now available in the latest beta.

You can use the home app to choose a target temperature and the plugin will automatically turn ON the switch if the current temperature falls below this target temperature. The plugin will turn OFF the switch once the current temperature reaches the target temperature.

The plugin will use and setup the 'Auto' mode of the eWeLink app to do the above.

This can be useful if you have a heater connected to the TH device.

The previous configuration option `thAsThermostat` has been removed, and the thermostat can now be set up using an Accessory Simulation (via the Homebridge UI) or by adding directly to your config.json in the ewelink section:

```json
"groups": [
   {
      "deviceId": "1000#####",
      "type": "thermostat"
   }
]
```

Please remember this is still experimental (I continue to test this myself with my new TH16) but any feedback would be great!
