### ISSUE TITLE
You are breaking Homebridge "Verified" plugin rules

### ISSUE THREAD

**Issue by kremik** [bwp91/homebridge-ewelink#162]
Latest update of ewelink plugin (https://github.com/bwp91/homebridge-ewelink) requires Node.js 14 only, but it is breaking Homebridge Verified plugin rules which state:
"The plugin must run on all supported LTS versions of Node.js, at the time of writing this is Node.js v10, v12 and v14."

**Comment by bwp91** [comment]
Hi, 
The latest versions of this plugin will indeed work with node 10, 12 and 14.
i recommend mode 14 since this is what I use with development.
Any messages regarding incompatibilities are warnings, not errors. They can be ignored.

**Comment by Zacknetic** [comment]
Hahahahahaha

**Comment by Zacknetic** [comment]
Well this is awkward.

**Comment by kremik** [comment]
So now I see the problem. In English update message is that Node 14 is recommended, but in Czech version of this message is that Node 14 is required.

**Comment by Zacknetic** [comment]
I honestly can’t begin to understand what you hope to gain from this @kremik.

**Comment by kremik** [comment]
@Zacknetic I honestly don't understand what you don't understand. I have Homebridge in Czech language version (offical support). It says that Node version 14 is REQUIRED to run ewelink plugin. And this is breaking the rules of HomeBridge Verifed plugin, because the compatibility with versions 10, 12 and 14 is one of the core rules for stating the plugin as "Verified". Any more questions?

**Comment by Zacknetic** [comment]
>  Any more questions?
Oh one more. Don't you have anything better to do?
