### ISSUE TITLE
Camera not supporting

### ISSUE THREAD

**Issue by rashmendis** [bwp91/homebridge-ewelink#163]
https://github.com/bwp91/homebridge-ewelink/wiki/How-to-set-up-Sonoff-Camera#1-find-the-ip-and-password-for-your-camera

There are no "More Settings" as mentioned under my Camera settings to get the RTSP password. Any other way?

![image](https://user-images.githubusercontent.com/11315372/102058250-3e932c80-3e15-11eb-8d4f-d2946da179d2.png)

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 
Yes

* Which version of Homebridge/HOOBS do you have?
1.1.1 

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?
3.9.0 

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.
Camera

* Do you use your main eWeLink credentials or do you use a secondary eWeLink account for Homebridge?
Main

```

```

**Comment by bwp91** [comment]
Hi @rashmendis 
You don't appear to have the Sonoff Camera model `GK-200MP2B`? Your model shows as `BIT-EYE-GL` so perhaps this is why the "More Settings" option doesn't appear?

**Comment by bwp91** [comment]
Are you using the ewelink android camera app?

**Comment by rashmendis** [comment]
Yes. But using ewelink main app on iOS



Rashmi Mendis
Software Engineer, Calcey® Technologies
+94710482158 | rashmi@calcey.com | www.calcey.com

**Comment by rashmendis** [comment]
That is the only model shown in my app.
Yes, the camera app on Android. But using eWelink main app on iOS and the video streaming is working with the eWelink app

**Comment by bwp91** [comment]
The instructions are for the Sonoff camera, the actual camera device.
I’m not sure if it is possible to support the ewelink camera app. With your help I’d be able to see if it is possible? 
If you have time to help, could you join my discord server so we can message?
https://discord.gg/cMGhNtZ3tW
