### ISSUE TITLE
WS login failed [Unknown parameters received

### ISSUE THREAD

**Issue by kamaruszamanjufri** [bwp91/homebridge-ewelink#164]
### What issue do you have? Please be as thorough and explicit as possible.

WS login failed [Unknown parameters received

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 

with config-ui

* Which version of Homebridge/HOOBS do you have?

1.2.4

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

3.18.0

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

-

* Do you use your main eWeLink credentials or do you use a secondary eWeLink account for Homebridge?

main eWeLink account

### Please paste any relevant logs below.

[12/15/2020, 9:04:40 AM] [eWeLink] WS login failed [Unknown parameters received
{
  "error": 406,
  "apikey": "bc9043e0-133a-4ab6-8775-d59166a0ab84",
  "sequence": "1607994280429",
  "actionName": "userOnline"
}].
```

```

**Comment by bwp91** [comment]
Hi,
I (and others) have seen this message before when running multiple instances of Homebridge/HOOBS with the ewelink configured, ie, multiple homebridges logging into the same ewelink account.
Perhaps even an old instance of homebridge that is running without you remembering?
Thanks

**Comment by kamaruszamanjufri** [comment]
Hi,

Currently only one is installed. I gave a restart. Will update again.
Got warning error.

[12/15/2020, 11:16:35 PM] [eWeLink] eWeLink sync complete. Don't forget to ⭐️  this plugin on GitHub if you're finding it useful!
(node:376) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 shutdown listeners added to [HomebridgeAPI]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
[12/15/2020, 11:16:45 PM] [Homebridge UI] Homebridge Config UI X v4.36.0 is listening on :: port 8080

**Comment by bwp91** [comment]
This warning may or may not be caused by ewelink plugin.
Do you have any other plugins installed?

**Comment by kamaruszamanjufri** [comment]
Yes. Homebridge Camera FFmpeg.

**Comment by bwp91** [comment]
And you used to hoobs? is hoobs definitely stopped and not still running in the background?

**Comment by kamaruszamanjufri** [comment]
I am using homebridge in dockers on synology. 
Looks like no more error prompted after restarting.
