### ISSUE TITLE
Error: getaddrinfo ENOTFOUND eu-long.coolkit.cc eu-long.coolkit.cc:8080

### ISSUE THREAD

**Issue by migabc** [bwp91/homebridge-ewelink#17]
Hi,

As of today I started getting these errors:

Apr 18 11:15:57 raspberrypi homebridge[574]: { Error: getaddrinfo ENOTFOUND eu-long.coolkit.cc eu-long.coolkit.cc:8080
Apr 18 11:15:57 raspberrypi homebridge[574]: at errnoException (dns.js:28:10)
Apr 18 11:15:57 raspberrypi homebridge[574]: at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
Apr 18 11:15:57 raspberrypi homebridge[574]: code: 'ENOTFOUND',
Apr 18 11:15:57 raspberrypi homebridge[574]: errno: 'ENOTFOUND',
Apr 18 11:15:57 raspberrypi homebridge[574]: syscall: 'getaddrinfo',
Apr 18 11:15:57 raspberrypi homebridge[574]: hostname: 'eu-long.coolkit.cc',
Apr 18 11:15:57 raspberrypi homebridge[574]: host: 'eu-long.coolkit.cc',
Apr 18 11:15:57 raspberrypi homebridge[574]: port: '8080' } }
Apr 18 11:15:57 raspberrypi homebridge[574]: WebSocketClient: retry in 5000ms 1006
Apr 18 11:15:57 raspberrypi homebridge[574]: [4/18/2018, 11:15:57 AM] [eWeLink] WebSocket was closed. Reason [1006]

What is causing this?
Was something changed on the ITEAD servers?
P.S: My Authorization Bearer did not change

**Comment by Stuart-Richards** [comment]
I'm getting the exact same thing but for the US version  Error: getaddrinfo ENOTFOUND us-long.coolkit.cc us-long.coolkit.cc:8080. 

Also this morning there were a load of pop up notifications on my iPhone from the ewelink app, but they were all in Chinese :-(

**Comment by migabc** [comment]
Yes, I also received those notifications in Chinese
Seems that they have changed something in the ITEAD servers.

Btw, some time ago I reached out to them about Homekit and they told be that they are working on native Homekit support but they did not tell me when it will be available

**Comment by cwmyers** [comment]
Yeah, same here.  And same with the Chinese character notifications

**Comment by Joni-Pekka** [comment]
Same here. Running a couple of Sonoffs with stock firmware through Homebridge, but this morning I had a couple of ewelink notifications in chinese on my iPhone and now none of the Sonoffs work through Homebridge (they do work with the ewelink app). Homebridge is running fine and other non-Sonoff-devices work through it. I used Charles Proxy to see if the token had changed, but it hadn't.

Logs are showing:
[2018-4-18 11:12:00] [eWeLink] WebSocket was closed. Reason [1006]
WebSocketClient: reconnecting...
WebSocketClient: error { '0':
   { Error: getaddrinfo ENOTFOUND eu-long.coolkit.cc eu-long.coolkit.cc:8080
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
     code: 'ENOTFOUND',
     errno: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'eu-long.coolkit.cc',
     host: 'eu-long.coolkit.cc',
     port: '8080' } }

**Comment by luchobene** [comment]
my too

**Comment by senux1988** [comment]
Replace eu-long.coolkit.cc  to eu-pconnect3.coolkit.cc and problem solved. :-)

**Comment by migabc** [comment]
Yes. :-)
Now it's working again

Thx a lot

**Comment by sebbo187** [comment]
That was the solution indeed. Thanks for your advice, how did you find out?

**Comment by senux1988** [comment]
I sniff connections ewelink app and find this server name in dns request.

**Comment by Stuart-Richards** [comment]
Awesome! Thank you senux1988! I replaced the US version with us-pconnect3.coolkit.cc and it's now working again.

**Comment by Joni-Pekka** [comment]
Fantastic! Thank you!!

**Comment by migabc** [comment]
Great :-)

Byw, some time ago I reached out to ITEAD about Homekit compatibility and they told me that they are working on native Homekit support but they did not tell me when it will be available
Does anybody know something about this?

**Comment by luchobene** [comment]
Fantastic! Thank you!!

**Comment by i3laze** [comment]
Shit.. eu-pconnect3.coolkit.cc is hosted in AWS (Amazon Web Services).
It's currently blacklisted in Russia (!#)@*+_)!
