### ISSUE TITLE
Sonoff B05 light bulb: actual brightness is much lower when set to 100% in Home app compared to 100% set in eWeLink app

### ISSUE THREAD

**Issue by vatrushka** [bwp91/homebridge-ewelink#170]
### What issue do you have? Please be as thorough and explicit as possible.

If I set the brightness of my Sonoff B05-B-A60 in eWeLink, it shines much brighter compared to setting 100% brightness for the same light bulb in Home app

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 

Homebridge

* Which version of Homebridge/HOOBS do you have?

homebridge-config-ui-x v4.36.0

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

homebridge-ewelink v3.18.1

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

Sonoff B05-B-A60

* Do you use your main eWeLink credentials or do you use a secondary eWeLink account for Homebridge?

I use my main eWeLink credentials

### Please paste any relevant logs below.

```

Below is what I see in logs when I set the brightness to 100% in Home app. No errors
{
  "deviceid": "**hidden**",
  "params": {
    "switch": "on",
    "ltype": "color",
    "color": {
      "r": 222,
      "g": 126,
      "b": 32,
      "br": 100
    },
    "online": true,
    "updateSource": "WS"
  }
}

```

**Comment by bwp91** [comment]
Hi, 
Please could you send a log of the message received when you use the ewelink app to change the brightness to 100%?

**Comment by vatrushka** [comment]
Hi! 

```
{
  "deviceid": "**hidden**",
  "params": {
    "switch": "on",
    "ltype": "white",
    "white": {
      "br": 100,
      "ct": 26
    },
    "updateSource": "LAN",
    "online": true
  }
}
```
I just noticed that it's only shines bright if I set brightness to 100% in "White" mode in eWeLink (see screenshot attached). 100% brightness in "Color" mode is low, similar to 100% in Home app. Apparently there are two separate brightness settings for "White" and "Color" mode and the latter allows for lower actual brightness. So when if I set brightness to 100% in Home app it sets it in "Color" mode even if I used "Temperature" color wheel.

**Comment by bwp91** [comment]
Ah. This is because the plugin doesn't support white mode for certain colour bulbs:
https://github.com/bwp91/homebridge-ewelink/wiki/Supported-Devices#-light-bulbs
It's something I could perhaps look into with your help?

**Comment by bwp91** [comment]
Could I message you on my discord server?
https://discord.gg/cMGhNtZ3tW

**Comment by bwp91** [comment]
I have purchased this bulb and get it properly implemented in the next version.
Will close this issue on here and be in contact on discord. thanks
