### ISSUE TITLE
For a multi channel device, show the per-channel name in Homekit

### ISSUE THREAD

**Issue by shanelilley** [bwp91/homebridge-ewelink#172]
On a two channel device, you have overall device name, and you can also give each channel a descriptive name. In HomeKit the two channels appear (if you separate the tiles) but they share the same overall device name. Would be great to see the per-channel names used instead. Not sure how this could be achieved though. Anyways, just an idea! 👍

**Comment by bwp91** [comment]
This is a homekit thing and is out of my control. You'd be best to buy separate ewelink devices to have them properly separated in homekit.
Accessory simulations are the best I can do for these multi-channel different accessory types :)
