### ISSUE TITLE
Unexpected token '>='

### ISSUE THREAD

**Issue by manuelreis** [bwp91/homebridge-ewelink#175]
### What issue do you have? Please be as thorough and explicit as possible.

I'm getting the following logs when trying to use your plugin:

```
[30/12/2020, 12:05:04] [eWeLink] Plugin [v3.18.1] initialised. Syncing with eWeLink...

[30/12/2020, 12:05:05] [eWeLink] *** Disabling plugin [v3.18.1] ***

[30/12/2020, 12:05:05] [eWeLink] Unexpected token '>='
```

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 

Homebridge (with config-ui)

* Which version of Homebridge/HOOBS do you have?

1.1.6

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

v3.18.1
This is the first time using this plugin.

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

SONOFF DW2-Wi-Fi

* Do you use your main eWeLink credentials or do you use a secondary eWeLink account for Homebridge?

I use the main ones

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @manuelreis 
Could you turn on “Debug Logging” in the plugin settings, then restart Homebridge?
This should hopefully display a more substantial/helpful error message. 
Thanks

**Comment by manuelreis** [comment]
Hi @bwp91,

Thank you for the quick response. As requested here are the debug logs:

![FA2A9C55-856B-4790-81B7-8653AFD46D0B](https://user-images.githubusercontent.com/4721640/103353043-ab5a2800-4a9f-11eb-86cb-831b41fd74d3.jpeg)

**Comment by bwp91** [comment]
Thanks. Which version of node and npm do you use?

**Comment by manuelreis** [comment]
@bwp91 here are the requested versions:

```
homebridge@raspberrypi:/var/lib/homebridge $ node -v
v14.15.1
homebridge@raspberrypi:/var/lib/homebridge $ npm -v
6.14.8
```

**Comment by bwp91** [comment]
I cannot seem to recreate this error.
Which platform are you running Homebridge with config-ui on? Is all other relevant software up to date?

**Comment by manuelreis** [comment]
Hi, here is some additional information regarding versioning and config:

Plugins:
- homebridge-config-ui-x v4.36.0
- @milo526/homebridge-tuya-web v0.4.8
- homebridge-alexa v0.5.19
- homebridge-ewelink v3.18.1
- homebridge-yeelight v0.0.21

OS: Raspbian GNU/Linux Buster (10)

_config.json_ without sensitive configurations
```
{
    "bridge": {
        "name": "Homebridge ",
        "username": "",
        "port":,
        "pin": ""
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "TuyaWebPlatform",
            "options": {
                "username": "",
                "password": "",
                "countryCode": "",
                "platform": "smart_life"
            },
            "defaults": [
                {
                    "device_type": "form"
                }
            ],
            "scenes": false,
            "platform": "TuyaWebPlatform"
        },
        {
            "name": "Alexa",
            "username": "",
            "password": "",
            "pin": "",
            "routines": false,
            "blind": false,
            "door": false,
            "debug": false,
            "deviceListHandling": "allow",
            "platform": "Alexa"
        },
        {
            "platform": "yeelight",
            "name": "yeelight"
        },
        {
            "name": "eWeLink",
            "countryCode": "",
            "username": "",
            "password": "",
            "debug": true,
            "platform": "eWeLink"
        }
    ]
}
```

**Comment by bwp91** [comment]
Have you tried uninstalling and reinstalling the plugin?

**Comment by manuelreis** [comment]
yes

**Comment by bwp91** [comment]
What method did you use to install/update node.js on your system?
Can I suggest using `hb-service` to update your node to the latest version (at the moment 14.5.3) - 
```bash
sudo hb-service update-node 14.15.3
```
