### ISSUE TITLE
4 Irrigation Valves | Accessory Simulations | Sonoff 4CH/PRO

### ISSUE THREAD

**Issue by MTry** [bwp91/homebridge-ewelink#182]
Thank you for an awesome plugin!

Would it be possible to expose all 4 channels as irrigation valves rather than limit it to 2? That would make a fantastic 4-channel irrigation control system with a product like [4CHPROR3](https://www.itead.cc/sonoff-4ch-r3-pro-r3.html) running off 12/24V since it has dry contacts that could safely drive corresponding solenoids.

The plugin works **flawlessly** with 4CHPROR3 in the default multi channel mode exposing all channels as well as when using accessory simulation but limits to exposing only 2 valves under simulation.

I suppose this will add the functionality for all 4CH Sonoff devices.

With the 4CH devices priced around $20 I'm happy to solve my problem by buying an additional unit to fulfil my need of 4 valves, but if all 4 channels on a single device could be exposed by the plugin, it'd be awesome.

Please don't get me wrong and I'm not trying to jump queue on your set of priorities here, but if this is something in the works then I would rather spend that money as a device contribution or sponsorship towards this plugin as it helps the whole community of the plugin's users and enhances a device utilisation to the fullest.

Thanks!

**Comment by bwp91** [comment]
Hi @MTry 

Thanks for this suggestion.

Please update your plugin to beta version v4.2.3-1. Then restart Homebridge.

Next, change your configuration for the device, selecting the new "4 Irrigation Values option". Then restart Homebridge.

Next I would also suggest removing the device from the Homebridge cache, so it is re-added properly.

After all that, it _should_ appear as four valves.

This is untested, so please let me know how you get on, or if you need any assistance with the above steps.

Thanks!

**Comment by MTry** [comment]
Thanks for the prompt response! Updated to beta - replaced "valve_two" to "valve_four" - **did not** need to clear cache - and now is see 4 sprinklers! [BTW I'm on HOOBS]

You're the man Ben! Thanks a ton.. will wait for this to move to stable before reverting to the official stable release.

**Comment by MTry** [comment]
Will test a little more and report back..

**Comment by MTry** [comment]
Hi Ben - I can confirm that this is working as expected - all 4 channels show up as irrigation valves with 2/5/10 minute turn-on options and no automation possibilities in Home app(expected) - but with Eve or similar app,  one can get any automation going(tested).

Would like to point out though that while testing and rapidly toggling different channels through the home app, there were a few moments when the tiles just stayed "active" but "idle" - they never got to the "running" state. This resolved when I toggled them off and back on. However, since then I have not been able to repeat this observation and it seems to function normally every time so perhaps there was some issue at my end which ghosted! Attached pics for reference...

regards, Mayank
![IMG_2290](https://user-images.githubusercontent.com/69190960/104179359-bb73ef00-5431-11eb-8428-94f20462b0ac.jpg)
![IMG_2291](https://user-images.githubusercontent.com/69190960/104179365-bdd64900-5431-11eb-8dc7-e80fbaf7173e.jpg)

**Comment by bwp91** [comment]
Ah this is good news! Thanks for the feedback on this.

> Would like to point out though that while testing and rapidly toggling different channels through the home app, there were a few moments when the tiles just stayed "active" but "idle" - they never got to the "running" state.

I think this could be the case with any device type when using the Home app - at least for me sometimes it feels quite clunky and doing anything too fast can sometimes lead to tiles not quite doing the right thing. I guess through "normal use" everything will work as expected.

Got me thinking now what for other device types the 4CH could be useful for!
