### ISSUE TITLE
Remove excessive state logging.

### ISSUE THREAD

**Issue by joepool** [bwp91/homebridge-ewelink#183]
![Screenshot 2021-01-10 at 21 01 34](https://user-images.githubusercontent.com/65784403/104135258-0a187f00-5387-11eb-9cc1-bddb147154bd.png)
Would it be possible to remove the state logging as shown in the screenshot above? I see no real purpose and is is just making my logs a mess, full of unnecessary information.
If would be great if there was an option in the config to disable these logs, similar to what you have for debug logs.
Apart from that, this is an awesome plugin.

Cheers!

**Comment by bwp91** [comment]
Hi @joepool 
Please update to beta version v4.2.3-2 and set the new config option "Disable Device Logging" in Optional Settings to true. If you prefer editing the config.json directly, the entry is `"disableDeviceLogging": true,`.
This should stop the "messy" logging.
Hope this helps!

**Comment by joepool** [comment]
Thats awesome, and works great, thanks very much!
