### ISSUE TITLE
2nd Eachen GD-DC5 as garage.

### ISSUE THREAD

**Issue by MoTechnicalities** [bwp91/homebridge-ewelink#184]
* **Please explain your feature request in a one or two sentences.**
Please consider supporting at least a second Eachen GD-DC5 as a HomeKit garage, for 2 door operation under HomeKit.

* **Is your feature request related to a problem? Please describe.**
I Added a second Eachen to the Group array, but it displays as a switch in Single Tile mode, or as a switch and a garage in Separate Tiles mode.

* **Any particular eWeLink devices that this relates to?**
Eachen GD-DC5

* **Anything else?**

Group looks like this:

[
    {
        "deviceId": "10009d3eb7",
        "type": "garage_eachen",
        "setup": "oneSwitch",
        "operationTime": 120,
        "sensorId": "10009d3eb7"
    },
    {
        "deviceId": "1000873158",
        "type": "garage_eachen",
        "setup": "oneSwitch",
        "operationTime": 120,
        "sensorId": "1000873158"
    }
]

**Comment by bwp91** [comment]
Hi @MoTechnicalities 

To remove the switch accessory, you will need to remove the accessory from the cache. How to do this depends on how you run Homebridge (eg Homebridge with config-ui, Homebridge CLI, HOOBS...)
Please let me know if you need assistance with this.

Also, the `setup` and `sensorId` are not necessary with the Eachen device, you can change your `groups` array simply to this:

```
[
   {
      "deviceId": "10009d3eb7",
      "type": "garage_eachen",
      "operationTime": 120
   },
   {
      "deviceId": "1000873158",
      "type": "garage_eachen",
      "operationTime": 120
   }
]
```

**Comment by MoTechnicalities** [comment]
Yep, may need a little help. I am running HOOBS.

**Comment by bwp91** [comment]
Please add the eWeLink device ID of the device with the switch to the "Ignored Devices" settings entry:

<img width="300" alt="Screenshot 2021-01-13 at 06 52 58" src="https://user-images.githubusercontent.com/43026681/104416756-422ce700-556c-11eb-9f58-eae59b939b98.png">

Then click "Save Changes". If you watch the logs while HOOBS restarts, then you should see a message that says something like:

```
13/01/2021, 06:52:20 [eWeLink] [Device] has been removed from Homebridge.
```

Once it has been removed, you should return to the Configuration and remove the Device ID from the "Ignored Devices", Save Changes again and when HOOBS restarts the device should be readded without the switch.

**Comment by MoTechnicalities** [comment]
> Please add the eWeLink device ID of the device with the switch to the "Ignored Devices" settings entry:
> 

Excellent! It worked.
Thank you.
