### ISSUE TITLE
DW2 missing battery state and TH16R2 bug

### ISSUE THREAD

**Issue by LZee** [bwp91/homebridge-ewelink#186]
### What issue do you have? Please be as thorough and explicit as possible.
SONOFF DW2 - sensors battery status 0

SONOFF TH16R2 - If I toggle on the automatic mode in ewelink app, Homebridge change device switch state On, if I toggle Off the automatic mode in ewelink app, Homebridge change device switch state Off. Please separate the switch state and the automatic mode state.

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 
1

* Which version of Homebridge/HOOBS do you have?

homebridge-config-ui-x v4.36.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry 

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

homebridge-ewelink v4.4.4

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

SONOFF DW2

SONOFF TH16R2

### Please paste any relevant logs below.

[2021. 01. 24. 11:19:20] [eWeLink] [Kapu nyitás] current battery [undefined%].
[2021. 01. 24. 11:19:45] [eWeLink] [Bejárati ajtó nyitás] current battery [undefined%].
```

![sonoffdw2](https://user-images.githubusercontent.com/10674642/105628026-a2f4d300-5e3a-11eb-9b05-32d3132b9ce1.png)

**Comment by StuFull** [comment]
Hi LZee I see you have the TH16R2 working.  Can I ask how?

I have a TH16R2 on my network and in Ewelink but it doesn't show in Hoobs.

**Comment by bwp91** [comment]
Hi @LZee 

I'm gonna take these issues one at a time, first the DW2 battery problem as this was hopefully an easy fix.

Could you update the plugin to a beta version v4.4.5-0 to check it has been fixed?

Once verified it's working I'll look into the TH16R2 for both you and @StuFull

**Comment by LZee** [comment]
> Hi @LZee
> 
> I'm gonna take these issues one at a time, first the DW2 battery problem as this was hopefully an easy fix.
> 
> Could you update the plugin to a beta version v4.4.5-0 to check it has been fixed?
> 
> Once verified it's working I'll look into the TH16R2 for both you and @StuFull 

Hi @bwp91 
Thanks for the correction. DW2 device battery status now works.

**Comment by bwp91** [comment]
Great re the DW2.

Would either of you two @LZee @StuFull be able to share a TH16R2 device with me? I am unaware of this 'automatic mode' and to be able to potentially implement it, it would be really handy for me to see if for myself in the eWeLink app and be able to play around controlling it a couple of times.

Thanks

**Comment by LZee** [comment]
> Great re the DW2.
> 
> Would either of you two @LZee @StuFull be able to share a TH16R2 device with me? I am unaware of this 'automatic mode' and to be able to potentially implement it, it would be really handy for me to see if for myself in the eWeLink app and be able to play around controlling it a couple of times.
> 
> Thanks

My device controls the temperature of a greenhouse. Since it's winter, it's a bit risky. If @StuFull can't share, we'll sort it out somehow.

**Comment by bwp91** [comment]
Just so you know it would only take about 5 minutes and then you can unshare again!

**Comment by StuFull** [comment]
Yes I can share with you Ben.

**Comment by bwp91** [comment]
Thanks @StuFull 
Can I message you on my discord channel?
https://discord.gg/cMGhNtZ3tW

**Comment by bwp91** [comment]
@LZee I have released another beta version of the plugin, v4.4.6-0.

Hopefully I have fixed the plugin so the home app shows the correct state of the switch, rather than the state of automatic mode.

You're feedback would be appreciated so I know it's working as hoped!

**Comment by LZee** [comment]
> @LZee I have released another beta version of the plugin, v4.4.6-0.
> 
> Hopefully I have fixed the plugin so the home app shows the correct state of the switch, rather than the state of automatic mode.
> 
> You're feedback would be appreciated so I know it's working as hoped!

Thanks for the fix, now I think it works well.

**Comment by bwp91** [comment]
Ah this is good news!
I have released another beta with the option of using the TH device as a fully working thermostat... whether this is something that would be helpful for you with your use of the device... it's there to test

**Comment by LZee** [comment]
Please help me a little. What has changed?

**Comment by bwp91** [comment]
If you use the config option `thAsThermostat` or if you use the plugin UI settings it's in Device Settings > TH As Thermostat

...you can expose the TH device as a thermostat (rather than switch and sensors). It needs testing though... it's difficult for me to test it myself as I don't own a TH device.

In terms of the accessory in Homebridge it means that

* If the thermostat is off then the device will always be off
* If the thermostat is on and the current temperature is more than target temperature then the connected device will be off
* If the thermostat is on and the current temperature is less than the target temperature then the connected device will be on

**Comment by bwp91** [comment]
Gonna close this issue again, and keep the conversation about the TH device as a full thermostat in this issue:
https://github.com/bwp91/homebridge-ewelink/issues/161
Thanks
