### ISSUE TITLE
Device Request - SONOFF TH16R2

### ISSUE THREAD

**Issue by StuFull** [bwp91/homebridge-ewelink#187]
When using the plugin I don't see the SONOFF TH16R2 (FW PSA-BHA-GL V3.4.1), however I do see two other SONOFF POWR2 devices.

Hoobs Version 3.3.2

Is it possible to have support for these devices?

**Comment by bwp91** [comment]
Hi @StuFull 
Literally just moments ago another issue has been created by a user who is having an issue with this model, which means at least they have it added.

When you say you don’t see it, what appears in the logs when you restart Homebridge? An unsupported message? A problem message?

**Comment by StuFull** [comment]
@bwp91

I just don't see any mention of it Ben.  No errors at all.

**Comment by StuFull** [comment]
The only thing I do see is this, could it be relative?

"homebridge-ewelink" requires Node version of ^14.15.4 which does not satisfy the current Node version of v14.15.1. You may need to upgrade your installation of Node.

 {
            "platform": "eWeLink",
            "plugin_map": {
                "plugin_name": "homebridge-ewelink"
            },
            "name": "eWeLink",
            "mode": "auto",
            "countryCode": 44,
            "username": "Hidden",
            "password": "Hidden",
            "disableDeviceLogging": false,
            "debug": true,
            "disablePlugin": false
        }

**Comment by bwp91** [comment]
> "homebridge-ewelink" requires Node version of ^14.15.4 which does not satisfy the current Node version of v14.15.1. You may need to upgrade your installation of Node.

This won't affect the devices you see.

Another common scenario is when you use a shared ewelink account for Homebridge? Users often forget to share new devices to the homebridge-ewelink account?

**Comment by StuFull** [comment]
> Another common scenario is when you use a shared ewelink account for Homebridge? Users often forget to share new devices to the homebridge-ewelink account?

Well, how stupid do I feel!! 👍 

That's sorted, thanks mate.

Do you think it's worth me upgrading node?  I found this command from searching, would it be correct?

wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin —node 14.15.4

**Comment by bwp91** [comment]
How come you use a shared account? It isn’t necessary anymore and actually I recommend to users to use their main account. It doesn’t log you out of the ewelink app anymore.

And re Node, it’s a personal preference to have my stuff updated, that command is correct for updating node on hoobs, but it won’t make any difference to the plugin.

**Comment by StuFull** [comment]
> How come you use a shared account? It isn’t necessary anymore and actually I recommend to users to use their main account. It doesn’t log you out of the ewelink app anymore.

I guess back to the 'old days' where it logged you out.  No other reason.

**Comment by bwp91** [comment]
I'll close this issue now as you have your devices working!

Thanks
