### ISSUE TITLE
Sonoff RF Bridge sensors exposes wrong type

### ISSUE THREAD

**Issue by axelweichert** [bwp91/homebridge-ewelink#189]
### What issue do you have? Please be as thorough and explicit as possible.

Since the last Update the Sonoff RF Bridge sensors exposes all as Motion Sensors and not as Water Leak, Contact, and so.

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 

1

* Which version of Homebridge/HOOBS do you have?

1.1.7 with config-ui

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi Node.js v14.15.4

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

4.5.0

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

Sonoff RF Bridge

### Please paste any relevant logs below.

We have had this issue smoe releases ago. 

[28/01/2021, 16:36:44] [eWeLink] [Sonof RF Bridge 3] receiving update {"cmd":"trigger","rfTrig2":"2021-01-28T15:36:43.000Z","online":true,"updateSource":"WS"}.
```

```

**Comment by bwp91** [comment]
This has been fixed and will be available in the next release.
Thanks!
