### ISSUE TITLE
Accessory Simulation (1 Lock w/ single-channel)

### ISSUE THREAD

**Issue by lordsyncrus** [bwp91/homebridge-ewelink#191]
* **Please explain your feature request in a one or two sentences.**
When adding accessory simulations, accessory list must be refreshed.

* **Is your feature request related to a problem? Please describe.**
Adding a simulation to an existing device, makes that device double on HomeKit.

I figured out as follow:
1. Add a simulation to an existing device;
2. Disable the Ewelink plugin; (all Ewelink devices will be removed)
3. Enable the Ewelink plugin; (all Ewelink devices will be available, and those with simulation now well displayed in HomeKit).

* **Any particular eWeLink devices that this relates to?**
This simulation: 1 Lock (w/ single or multi-channel device)

* **Anything else?**
Siri can't manage the "unlocked" status with this simulation: "1 Lock (w/ single or multi-channel device)".
Siri says: "Can't open the gate" despite the gate has been unlocked correctly.
Using the iOS Home App, this simulation works perfectly.

I hope this helps you.

Thanks for your job.

**Comment by bwp91** [comment]
Hi @lordsyncrus 

You're right, a (slight) limitation of setting up these Simulations is that the accessories can double up. The easiest way of getting round this is simply by removing the old accessory from the Homebridge cache and the accessory will then be correctly setup as (just) the simulated accessory type.

I realise I need to document this better somewhere as removing from the cache sounds a lot easier then refreshing the ewelink device list each time 😛 

With regards to Siri and the lock, what are you asking? There could be a slight difference between for example:
* *Siri, open the gate*, and
* *Siri, unlock the gate*

**Comment by bwp91** [comment]
<img width="600" alt="Screenshot 2021-02-05 at 12 55 54" src="https://user-images.githubusercontent.com/43026681/107036430-8ef18f80-67b1-11eb-9b21-05325a4e32fe.png">

I'll add this to the new version of the plugin!

**Comment by lordsyncrus** [comment]
Hi Ben,

You are the man!

**Regarding to Siri and lock:**
I tried asking both forms (open / unlock).
Result is the same: "... I can't  open/unlock accessory", despite accessory has been properly unlocked.

Thanks for you work.

**Comment by bwp91** [comment]
Do you get this response _every_ time? or sometimes?

**Comment by lordsyncrus** [comment]
Unfortunately, I get this every time.

**Comment by bwp91** [comment]
I think I may have found the issue.
Could you try updating the plugin to the latest beta version 4.6.2-2 to see if this helps Siri with their response!
Thanks

**Comment by lordsyncrus** [comment]
Hi Ben,

Testing v4.6.2-2:

1. **UI bug: I see my simulation twice**
<img width="699" alt="Screenshot 2021-02-06 at 18 29 22" src="https://user-images.githubusercontent.com/30342384/107125464-7c0eb600-68aa-11eb-8b3f-ac64e2aa34d5.png">

2. **New flow with 1 Lock w/ single channel Simulation (inching time is 2sec):**
- Me: "Hey Siri, unlock/open the door";
- Door has been unlocked;
- Siri: "The door is closed"; (it's like it reports the locked status only");
- Home Kit push a new notification: "Door locked".

**Comment by bwp91** [comment]
**1**
Have you set up two devices in the plugin settings? The plugin **never** writes to your configuration, so at some point you _must_ have set the second up? As they have different device IDs?

**2**
When I use the Home app with this simulation, I get a 'door unlocked' notification immediately, then I get a 'door locked' notification after the operation time has elapsed (in my case 5 seconds).

I wonder if Siri is requesting the status after a few moments (ie in your case after 2 seconds) which is when in fact the lock is classed as 'locked' again. Perhaps try increasing the operation time for the purposes of testing Siri?

**Comment by lordsyncrus** [comment]
Hi ben,

**1.** You are right. I'm sorry;
**2.** I'm trying with an inching time of 5sec. Home Kit behaviour is correct (unlocked and after 5sec locked). Siri always reports the locked state only.

**Comment by bwp91** [comment]
I have made a couple of changes and pushed a new beta, 4.6.2-3. See if this changes anything with Siri. 

If it doesn't, I'm not sure if there is anything else I can do to get the Siri part to work :/

**Comment by lordsyncrus** [comment]
Hey Ben,

Tried many times and 2 times over 8, Siri gets the correct state: "Door is open" or "Done.".
I guess this is an important breakthrough! At least, Siri doesn't get/give a kind of negative response.

Thanks for your job, Ben!

**Comment by bwp91** [comment]
You might find... now... that if you increase the operationTime then Siri might return the correct response!

As I mentioned previously there is nothing more I can do with regards to Siri 😅

**Comment by lordsyncrus** [comment]
Thank you, Ben!
