### ISSUE TITLE
Multiple device types

### ISSUE THREAD

**Issue by Lui5Jacint0** [bwp91/homebridge-ewelink#193]
I have a sonoff mini connected to my garage door.

Could you please add an option to output a especific device type to expose in HomeKit?

garage door, sprinkler , etc?

**Comment by bwp91** [comment]
Hi,

Please see:
https://github.com/bwp91/homebridge-ewelink/wiki/Accessory-Simulations

Thanks!

**Comment by bwp91** [comment]
Also, if you use the Homebridge UI then these can be created field by field via the plugin settings rather than by having to edit the Homebridge config file directly.

Hope this helps!

**Comment by Lui5Jacint0** [comment]
How do i remove the old device from the cache?

**Comment by bwp91** [comment]
There are different methods depending on how you run Homebridge.

Do you use Homebridge UI? HOOBS?

**Comment by Lui5Jacint0** [comment]
I use homebridge UI on raspberry pi homebridge image.

**Comment by bwp91** [comment]
You can use the Homebridge UI section of this guide:

https://github.com/bwp91/homebridge-ewelink/wiki/How-to-remove-an-accessory-from-the-cache

Remove the accessory as a whole - then it will be re-added with just the service as defined in your config (for example garage door)
