### ISSUE TITLE
Thermostat KKMOON HC-T010-EWF

### ISSUE THREAD

**Issue by alexovchinnicov** [bwp91/homebridge-ewelink#194]
Can we add a new device: https://ewelinkcommunity.net/device-lists/heating/kkmoon-hc-t010-ewf/

**Comment by bwp91** [comment]
Hi @alexovchinnicov 
Do you own this device?
Would you be happy to share it to my ewelink account? It always makes adding new devices so much easier!
Thanks

**Comment by alexovchinnicov** [comment]
Yes. I bought it for water heater. What is your ewelink id?

**Comment by bwp91** [comment]
Could I message you on my discord server?
https://discord.gg/cMGhNtZ3tW

**Comment by bwp91** [comment]
Added in v4.7.0 :)
