### ISSUE TITLE
Unable to Hide Light/Switch Channels

### ISSUE THREAD

**Issue by ghost** [bwp91/homebridge-ewelink#196]
Plugin has been working perfectly, updated to 4.7.1 just now and I am unable to Hide Light/Switch Channels. I have attempted to remove, save, reboot and once rebooted enter the channels again but they remain visible within the Home app

### Details of your setup.
Homebridge (+ config-ui) on RPi 4

**Comment by bwp91** [comment]
Hi @ghost
I've just tested hiding a channel on my T2 device and it was removed successfully.
Please post your config if this is still an issue.
Thanks

**Comment by ghost** [comment]
Same problem. 

I am able to hide only one Light/Switch Channel. Added a , (just like before) the channel after the , is ignored

**Comment by bwp91** [comment]
Hi @ScttShrmn 
Please try v4.7.2.
Your info helped me find a small problem with the code that I have now fixed.
Thanks!

**Comment by ghost** [comment]
That fixed it, cheers Ben

**Comment by bwp91** [comment]
Fab. Gonna close this as original poster is now a 👻!

**Comment by ghost** [comment]
Hi Ben. Just updated to the latest version and I am unable to hide switches again? Has the option moved?

**Comment by bwp91** [comment]
Hi @ScttShrmn 
v5 introduced a lot of changes to the config designed to future proof the plugin and prevent any further changes needed to the config as I appreciate it is irritating.
Changes can be seen in the changelog, by the way, are you on HOOBS?

**Comment by ghost** [comment]
Nope, RPi 

Is there a way to hide these grouped switches?

**Comment by bwp91** [comment]
Yes there is, depending on which platform you use i can give you the best method to configure, do you use Homebridge UI then?

**Comment by ghost** [comment]
Thanks, yes I am using Homebridge UI (appreciate the quick replies)

**Comment by bwp91** [comment]
You can use the plugin settings section under “Multi Devices” to enter the device ID and the channels you wish to hide in the form `1,2` if you wanted to hide channels 1 and 2 for example

**Comment by ghost** [comment]
Brilliant, all sorted. Again thanks for the quick response

**Comment by bwp91** [comment]
Fab. As i said earlier this “big” change to the config is here to stay now so shouldn’t be any further problems in the future :)
