### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Stetocasa** [bwp91/homebridge-ewelink#197]
### What issue do you have? Please be as thorough and explicit as possible.

I'm on 3.9.0 version and hoobs inform me to update on 4.7.3
Process update seems complete fine but still in 3.9.0

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 
Hoobs

* Which version of Homebridge/HOOBS do you have?

3.3.2

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

3.9.0

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.
 

### Please paste any relevant logs below.

```

```

**Comment by Stetocasa** [comment]
15/2/2021, 09:15:10  WARN notsup Not compatible with your version of node/npm: homebridge-ewelink@4.7.3
15/2/2021, 09:15:10 
15/2/2021, 09:15:10 npm
15/2/2021, 09:15:10  ERR! code EEXIST
npm ERR! path /home/hoobs/.hoobs/node_modules/gtoken/node_modules/.bin/mime
15/2/2021, 09:15:10 npm
15/2/2021, 09:15:10 ERR! Refusing to delete /home/hoobs/.hoobs/node_modules/gtoken/node_modules/.bin/mime: is outside /home/hoobs/.hoobs/node_modules/gtoken/node_modules/mime and not a link
npm ERR! File exists: /home/hoobs/.hoobs/node_modules/gtoken/node_modules/.bin/mime
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.
15/2/2021, 09:15:10 
15/2/2021, 09:15:10 npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2021-02-15T08_15_10_806Z-debug.log
15/2/2021, 09:15:10 Plugin "homebridge-ewelink" updated.
15/2/2021, 09:15:10 Got SIGINT, shutting down Bridge...
15/2/2021, 09:15:10 Catching error on dropMembership: {"code":"ERR_SOCKET_DGRAM_NOT_RUNNING"}
15/2/2021, 09:15:10 Catching error on dropMembership: {"code":"ERR_SOCKET_DGRAM_NOT_RUNNING"}
15/2/2021, 09:15:17 Loaded plugin '@milo526/homebridge-tuya-web'
15/2/2021, 09:15:17 [2/15/2021, 1:15:17 AM] Registering platform 'milo526/homebridge-tuya-web.TuyaWebPlatform'

**Comment by bwp91** [comment]
Hi @Stetocasa 
What happens if you restart HOOBS?

**Comment by Stetocasa** [comment]
Solved. Needs to update the node
