### ISSUE TITLE
Simulation - Contact Sensor/Leak Sensor

### ISSUE THREAD

**Issue by quintanilha** [bwp91/homebridge-ewelink#198]
* **Please explain your feature request in a one or two sentences.**

Simulation between a contact sensor and a leak sensor 

* **Is your feature request related to a problem? Please describe.**

I made a rain sensor through a contact sensor. When the sensor is in the closed state, the system should consider it as a leak detected.  Like this: https://youtu.be/YFu2LZfrrqs?t=196

* **Any particular eWeLink devices that this relates to?**

DW2-Wi-Fi Door Window Sensor - https://sonoff.tech/product/wifi-smart-home-security/dw2

* **Anything else?**

**Comment by bwp91** [comment]
Hi @quintanilha 
Could I message you on my discord?
https://discord.gg/cMGhNtZ3tW

**Comment by bwp91** [comment]
This functionality of using a DW2 contact sensor as a leak sensor (via Accessory Simulation) will be available in the upcoming v5.0.0 release.

@quintanilha when you have a spare moment I hope we can message on discord to test this.

Thanks
