### ISSUE TITLE
NodeJS version compatibility

### ISSUE THREAD

**Issue by alonl** [bwp91/homebridge-ewelink#201]
Hi and thanks for the awesome plugin!
One question, if I may ask - 
Why do you keep updating the `engines.node` version in package.json to the latest *patch* version, all the time?
It requires the user to upgrade NodeJS for every new patch version, or otherwise click on "Update Anyway" when updating the plugin.
See [`homebridge-config-ui-x`'s package.json](https://github.com/oznu/homebridge-config-ui-x/blob/master/package.json) for example - they're compatible with `"node": ">=10.17.0"`... I'm pretty sure that this plugin will be compatible as well. 
What do you think? :)
Thanks again!

**Comment by bwp91** [comment]
Hey. Thanks for the question.

It's a personal preference. It's the node version I personally run and develop my plugins with. I'm of the opinion that it's good to keep everything updated to the latest versions.

It's also for user-awareness. Getting users into the habit of keeping their version of node up-to-date.

Homebridge UI has made it real easy to update node using `hb-service` so I expect a lot of users would see the message and therefore update - without the message they may not necessarily realise that an update is available.

This plugin does indeed support node v10, v12 & v14 and will continue to do so. There is no 'requirement' to keep the node version updated to what the plugin asks for. And as you have mentioned, it is still possible to use the 'Update Anyway' button to update the plugin.

**Comment by alonl** [comment]
Thanks for the kind and detailed answer.
For me it's not that straight forward to upgrade node, since I run it on raspberry pi, which requires an unofficial build for ARMv6. Therfore I can't upgrade it through the hb-service, and I find it a bit annoying to click on the "Update Anyway" button every time - it feels that I'm doing something wrong. 
And it is actually, and now I'll put my developer hat - I'm doing something that the developer of the plugin instructed not to do. The versions in the engines section in the package.json should indicate the required supported version, and it's just not accurate to say that one must have the latest node version in order to run this plugin...
Thanks anyway!
