### ISSUE TITLE
TH Temperature Offset seems not working since last update...

### ISSUE THREAD

**Issue by Dominik-1980** [bwp91/homebridge-ewelink#205]
Hello. Since the last update the TH Temperature Offset seems not working any more.
I configured it in config-ui-x. 

* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 

(1)

* Which version of Homebridge/HOOBS do you have?

tried with old Homebridge 1.2.5

than updated to Homebridge 1.3.1

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi 4 

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

Latest

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

Sonoff TH16

### Please paste any relevant logs below.

```
 "thDevices": [
                {
                    "deviceId": "1000aed21d",
                    "label": "Sonoff Wohnzimmer",
                    "offset": 2
                }
            ],
```

 I also tried

```
 "thDevices": [
                {
                    "deviceId": "1000aed21dSWX",
                    "label": "Sonoff Wohnzimmer",
                    "offset": 2
                }
            ],
```

**Comment by bwp91** [comment]
Hi @Dominik-1980 
I've just tried adding an offset to my TH device and it worked.
Do you have the device set up as a thermostat? Or the default temp sensor + switch?
Also, please double check the deviceid is correct for the TH device (ie not another device by mistake?)
Using the deviceId in the short form is correct ie `deviceId": "1000aed21d"`

**Comment by Dominik-1980** [comment]
Sorry Ben.

I unplugged the sensor, put it back in and it works...
Good work!
Can you delete this thread?

**Comment by bwp91** [comment]
All good! Glad it's working again 👍
