### ISSUE TITLE
Sonoff B05 light bulb:Type recognition error.

### ISSUE THREAD

**Issue by geekbx** [bwp91/homebridge-ewelink#206]
### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 

1

* Which version of Homebridge/HOOBS do you have?

homebridge-config-ui-x v4.39.1

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi 4b 
Node.js Version | v14.16.0
Npm Version | v6.14.11

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

V5.0.5 This is the first time I use this version of software to work with this hardware.

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

Sonoff B05-B-A60

### Please paste any relevant logs below.
The data received by the software when I use the ewelink app:

```
receiving update {"switch":"on","ltype":"color","color":{"r":218,"g":0,"b":254,"br":100},"online":true,"updateSource":"WS"}.
current state [on].
receiving update {"switch":"on","online":true,"updateSource":"WS"}.
receiving update {"switch":"on","ltype":"color","color":{"r":218,"g":0,"b":254,"br":100},"online":true,"updateSource":"WS"}.
```
Then, because the switch is displayed in home, only the switch data is sent. The following is the log when using home:
```
sending update {"switch":"on"}.
reverting to web socket as LAN mode is not supported for this device.
receiving update {"switch":"on","ltype":"color","color":{"r":218,"g":0,"b":254,"br":100},"online":true,"updateSource":"WS"}.
```

**Comment by bwp91** [comment]
Hi @geekbx 
I actually noticed this problem this morning with my own B05-B-A60 and had been meaning to fix this. Slipped my mind!
Please update to v5.0.6 and it should be working again.
Thanks for alerting me of this (actually reminding me!)

**Comment by geekbx** [comment]
Excellent!I just updated to 5.0.6 and the problem is solved! thank!
