### ISSUE TITLE
Impossible to hide devices

### ISSUE THREAD

**Issue by JacVid** [bwp91/homebridge-ewelink#207]
### What issue do you have? Please be as thorough and explicit as possible.
            "ignoredDevices": [
                "100080cce9SW0"
            ]

or

             "ignoredSwitches": [
                "100080cce9SW0"
            ]

The device is still available in Apple Home.

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 

(1) Homebridge (+ config-ui)

* Which version of Homebridge/HOOBS do you have?

v1.3.1

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi4

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

homebridge-ewelink v5.0.6

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

eWelink 2 ch switches

### Please paste any relevant logs below.

        {
            "platform": "eWeLink",
            "name": "Motorisation",
            "countryCode": "33",
            "username": "xxx@xxx.com",
            "password": "xxxxx",
            "mode": "lan",
            "disableDeviceLogging": true,
            "debug": false,
            "disablePlugin": false,
            "ignoredDevices": [
                "100080cce9SW0"
            ]
        },

100080cce9SW1 and 100080cce9SW2 are the only two devices that must be displayed as a switch...

**Comment by bwp91** [comment]
Hi @JacVid 
`ignoredDevices` is used for ignoring a device as a whole, there is a separate option for hiding individual switches.
Please update your config to this, it is helpful you have included your config here :)

```json
{
   "platform": "eWeLink",
   "name": "Motorisation",
   "countryCode": "33",
   "username": "xxx@xxx.com",
   "password": "xxxxx",
   "mode": "lan",
   "disableDeviceLogging": true,
   "debug": false,
   "disablePlugin": false,
   "multiDevices": [
      {
         "deviceId": "100080cce9",
         "hideChannels": "0"
      }
   ]
},
```

**Comment by JacVid** [comment]
Thank you ! It works perfectly :)
