### ISSUE TITLE
2ch switches to drive a gate and a wicket 

### ISSUE THREAD

**Issue by JacVid** [bwp91/homebridge-ewelink#208]
* **Please explain your feature request in a one or two sentences.**

Hello, up to now with your plugin i'm driving a motor for a gate and a wicket with my 2ch ewelink switches.

SW0 is hidden
SW1 is driving the gate in inching mode (a pulse opens when it is closed, or stops when it is opening or closing, or closes when it is opened)
SW2 is driving the wicket (a pulse opens when it is closed, or stops when it is opening or closing, or closes when it is opened)

My problem is that, as the two devices are displayed as switches, I must create scene in order for Siri to understand "Close the gate" or "Open the wicket".

* **Is your feature request related to a problem? Please describe.**

Is their any "Accessory Simulations" configuration which could solve that ? I'd tried the Lock feature, but I couldn't get two devices...

Thanks for your feedback.

Regards

**Comment by bwp91** [comment]
Could I message you on Discord?
https://discord.gg/cMGhNtZ3tW
