### ISSUE TITLE
Blind simulation different times for up and down

### ISSUE THREAD

**Issue by arneauvanheauf** [bwp91/homebridge-ewelink#209]
* **Please explain your feature request in a one or two sentences.**
My sunscreen uses different up and down times. (so it goes down in 35 secs and up in 43 secs) Is it possible to make that?

* **Is your feature request related to a problem? Please describe.**
Yes, now the blind does not go all the way up.

* **Any particular eWeLink devices that this relates to?**
I use the Sonoff Dual

* **Anything else?**

**Comment by bwp91** [comment]
Hi @arneauvanheauf 

Please update to the latest beta of the plugin, v5.0.7-3, and then update your ewelink config in the blind group setup, adding the line `"operationTimeDown": 350`, for example:

```json
{
   "deviceId": "100example",
   "type": "blind",
   "operationTime": 430,
   "operationTimeDown": 350
}
```

And let me know how you get on. I haven't tested what I have implemented but hopefully it will work!

**Comment by arneauvanheauf** [comment]
Hi @bwp91,

Thanks for the fast reply, tried it the way you said. But when I try to move it (up or down doesn't matter), I got this in my log file (see picture), Do you know what's going on? 

<img width="1680" alt="Schermafbeelding 2021-03-01 om 08 24 20" src="https://user-images.githubusercontent.com/79799478/109464851-9f6ef000-7a67-11eb-8b50-93fab5d1f690.png">

**Comment by bwp91** [comment]
Ah I see you’re on HOOBS. Did you manage to update successfully to the beta?
