### ISSUE TITLE
Charles all configured but not able to connect

### ISSUE THREAD

**Issue by daniel4099** [bwp91/homebridge-ewelink#21]
Hello

I’ve configured all as instructions on forum. 
Installed iOS certified and turn it on. 

But in Charles app I can see:
Address is invalaid on local machine. 

Here are photos:

https://ibb.co/m3j7wx
https://ibb.co/hAd0Gx
https://ibb.co/hxbbpH

**Comment by daniel4099** [comment]
<a href="https://ibb.co/m3j7wx"><img src="https://preview.ibb.co/cvukic/D8_D47_A77_691_E_45_CB_B8_EB_3_DADDA0_D4_A23.jpg" alt="D8_D47_A77_691_E_45_CB_B8_EB_3_DADDA0_D4_A23" border="0"></a>
<a href="https://ibb.co/hAd0Gx"><img src="https://preview.ibb.co/jD5Qic/0261_D773_4643_405_E_98_F8_7510190_AD0_CA.png" alt="0261_D773_4643_405_E_98_F8_7510190_AD0_CA" border="0"></a>
<a href="https://ibb.co/hxbbpH"><img src="https://preview.ibb.co/cfE7wx/7_AD8976_B_E85_D_4_E27_9435_F8_A671_A330_C9.png" alt="7_AD8976_B_E85_D_4_E27_9435_F8_A671_A330_C9" border="0"></a>

**Comment by daniel4099** [comment]
Can someone help me ?

**Comment by daniel4099** [comment]
Really noone help :( ?

**Comment by i3laze** [comment]
Charles top menu - Proxy - SSL Proxying Settings...
Enable SSL Proxying..
Add - ***** - OK - OK
