### ISSUE TITLE
Accessory Simulation in Hoobs

### ISSUE THREAD

**Issue by scuba86** [bwp91/homebridge-ewelink#210]
Hey, I am looking *to do an Accessory Simulation in hoobs but not quite sure what I'm doing or looking for, I have a relays working on my garage doors through the app but HomeKit picks it up as a switch and not a garage door. Where should I start? Thanks!

**Comment by bwp91** [comment]
Hi @scuba86 
Which device model are you using to control the garage door?

**Comment by scuba86** [comment]
I am using this device: https://www.robofactory.co.za/smart-switches/57-sonoff-gate-garage-wifi-smart-switch.html

**Comment by bwp91** [comment]
Paste this block of code into the “Groups” box on the ewelink plugin page (replacing the `[]` if it exists)

```
[
   {
      "deviceId": "1000abcde",
      "type": "garage",
      "setup": "oneSwitch",
      "operationTime": 200
   }
]
```

And replace the 1000abcde with the device id of the device, and replace the 200 with the time it takes to open/close the garage (multiplied by 10) eg 200= 20 seconds.

Make sure the garage is closed, save the config and restart HOOBS and it should then appear as a garage door.

Let me know how it goes!

**Comment by scuba86** [comment]
Works perfectly and added a few switches! Thanks a mil!
