### ISSUE TITLE
SONOFF B02 Problem

### ISSUE THREAD

**Issue by mowe7456** [bwp91/homebridge-ewelink#211]
Hi I'm from Czech Republic I am using your Plugin I have sonoff bulbs and I am causing problems.
I don't know if it's just me or the others. I'm attaching a picture of the error it writes it's LED6 and LED5.
I have to turn the lights off and on to work again.

![homebridge](https://user-images.githubusercontent.com/79868205/109542586-8432cd80-7ac5-11eb-8fc9-11b0f736c561.png)

**Comment by bwp91** [comment]
Hi @mowe7456 
Which version of the plugin are you using?
And, does the error happen when you do something specific? or randomly?
This might require a bit of debugging as I also have this bulb… with no problems on my end!
Thanks

**Comment by bwp91** [comment]
Hi @mowe7456 

I had to completely start again with my pi this morning which meant re-adding my B02 to Homebridge.

Good news (!) is that I am now receiving this error which makes it easy for me to get to the bottom of what is causing it!

**Comment by bwp91** [comment]
Should be fixed in v5.2.0

**Comment by mowe7456** [comment]
hi, thank you for the info i haven't been to a pc for a few days now.
so far, I've only noticed that when I want to control them, the bulbs report to me as OFFLINE and I have to turn them off and on manually. then it works again for 1 hour.

**Comment by bwp91** [comment]
The bulbs appear as offline in the Homebridge logs? In the ewelink app?

**Comment by mowe7456** [comment]
yes both in homebridge and in evelink are OFFLINE only helps to turn off and on the power supply from the bulbs.
now I have tried and attach a picture of the logo is LED05 LED06
after switching on with the button (long press) the Zigbee lights up and as I pressed (double press) they no longer go out and are OFFLINE but at the same time they are lit and in the Ewelink application they are also OFFLINE.
![homebridge](https://user-images.githubusercontent.com/79868205/110528135-16ffe780-8118-11eb-88ac-c2550713e940.png)

**Comment by bwp91** [comment]
the plugin takes all it's information from ewelink, so if it's showing offline in the ewelink app there is nothing i can do from within the plugin.

probably the device is dropping wifi connection?
