### ISSUE TITLE
Th16

### ISSUE THREAD

**Issue by orenasher** [bwp91/homebridge-ewelink#215]
* **Please explain your feature request in a one or two sentences.**

Supp
![62616838-CF7A-4018-8B26-DFDC91BB7FE3](https://user-images.githubusercontent.com/42657319/110248638-d323ab80-7f7a-11eb-854e-654a80f8d866.png)
ort for raising the temperature more than 30 degrees

* **Is your feature request related to a problem? Please describe.**

* **Any particular eWeLink devices that this relates to?**

* **Anything else?**

Support for raising the temperature more than 30 degrees, it is currently not possible to raise the temperature more than 30 degrees

**Comment by bwp91** [comment]
Hi @orenasher 
I'm looking into a way of making these minimum and maximum target temperatures user configurable.
I'll get back to you on this :)

**Comment by bwp91** [comment]
Please update to 5.2.0 and the option has been added (in `thDevices`) to add a custom minimum and maximum target temperature to display

**Comment by orenasher** [comment]
Wow
Tanks 😍
![Uploading E18CE7D2-1307-4B3D-92C2-31422873EAE9.png…]()
