### ISSUE TITLE
Eachen Garage accessory does not open from the main page

### ISSUE THREAD

**Issue by sushenmathur** [bwp91/homebridge-ewelink#216]
### What issue do you have? Please be as thorough and explicit as possible.

Since the addition of the door sensor accessory for the Eachen garage door, I cannot just tap on the garage door on the devices page on homekit app, when clicked it opens the accesory for you to toggle the switch, the functionality you only get when you force tap the accessory in homekit.
  
![homekit](https://user-images.githubusercontent.com/21048866/110553297-86abbc00-8184-11eb-9ed1-a9d66d74c1ff.jpg)

Perhaps we need to option to display the door and sensor as a seperate accesory 

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 

 Homebridge (+ config-ui)

* Which version of Homebridge/HOOBS do you have?

![image](https://user-images.githubusercontent.com/21048866/110553097-2f0d5080-8184-11eb-8385-65bda13c32d1.png)

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

v5.2.0

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

Eachen Garage door

### Please paste any relevant logs below.

```

```

**Comment by MoTechnicalities** [comment]
Uncheck this then restart Homebridge:
![image](https://user-images.githubusercontent.com/68468472/110553953-db5d2180-8107-11eb-833f-1bc60a64c35c.jpeg)

**Comment by sushenmathur** [comment]
But I want to continue using the sensor for eve app, but yet retain the standard functionality for opening the garage door.
I noticed that the door and sensor accesory are bundled together is there a way to display them as seperate tiles/accessory

**Comment by MoTechnicalities** [comment]
I helped to test this eve App feature. I don't know if Ben can do anything about it. He will have to answer that. But, if it is a history that is needed for my garage, I simply refer to the detailed notifications log as follows:
![image](https://user-images.githubusercontent.com/68468472/110555402-8e2e7f00-810a-11eb-9311-09a48eb2b0d4.png)

Hope it helps a little.

**Comment by sushenmathur** [comment]
@MoTechnicalities Thanks, but i clear my notification quite regularly.
Hoping this can be fixed in the future releases

**Comment by MoTechnicalities** [comment]
I agree. The HomeKit behavior is an oddity and I did point it out when testing.

If anyone can fix it Ben is the man!

**Comment by bwp91** [comment]
Can either of you (or both!) try out beta 5.2.1-1?

I've removed the contact sensor and seeing if the Eve characteristics work directly with the garage door opener service.

This, hopefully, means that the Eve history is still available, without the additional contact sensor, which in turn will fix this original issue of having to open the tile to open/close the garage.

Let me know

**Comment by MoTechnicalities** [comment]
Great job, Ben!

The Eve App shows data for both of my Eachen doors without separating the devices channels:
![image](https://user-images.githubusercontent.com/68468472/110631427-80addf00-8174-11eb-9e9f-fdc19a19c430.png)

**Comment by bwp91** [comment]
Do you have a screen where you can see the 'Last Open' and 'Times Opened' data?

**Comment by MoTechnicalities** [comment]
Not sure what page that is, as I never really got into the Eve App, and I probably need to collect more data, but maybe you mean this:
![image](https://user-images.githubusercontent.com/68468472/110632533-bbfcdd80-8175-11eb-9404-639136299d86.png)

**Comment by MoTechnicalities** [comment]
Also, HomeKit Home App works the way it should.

**Comment by bwp91** [comment]
Maybe you need to click on Edit at the top and unhide the options?

**Comment by MoTechnicalities** [comment]
Ok, maybe this:
![image](https://user-images.githubusercontent.com/68468472/110645472-fc635800-8183-11eb-8b78-df1b3589b441.png)

**Comment by bwp91** [comment]
That's it! This is good - a solution for all 👍

**Comment by bwp91** [comment]
@sushenmathur this issue will be fixed in the upcoming version 5.3, or to get this sooner please install the beta version of the plugin

**Comment by sushenmathur** [comment]
@bwp91 @MoTechnicalities 
Thanks guys really appreciate the quick action. Happy to wait for v5.3
