### ISSUE TITLE
Status does not Updates when ewelink-plugin is configured multiple times

### ISSUE THREAD

**Issue by matrad** [bwp91/homebridge-ewelink#218]
### What issue do you have? Please be as thorough and explicit as possible.

We configured the EWELINK Plugin twice:

```
{
            "name": "eWeLink Garage HOME",
            "countryCode": "39",
            "username": "xxxx",
            "password": "yyyy",
            "mode": "auto",
            "multiDevices": [
                {
                    "deviceId": "1000e6088e",
                    "label": "Garage EWLink",
                    "hideChannels": "3,4,0",
                    "ipAddress": "192.168.1.118"
                }
            ],
            "ignoredDevices": [
                "1000b72555"
            ],
            "singleDevices": [
                {
                    "deviceId": "10006ca5cc",
                    "label": "Lüfter HOME OG",
                    "ipAddress": "192.168.178.122"
                }
            ],
            "_bridge": {
                "username": "0E:F2:41:B5:A5:D8",
                "port": 59093
            },
            "platform": "eWeLink"
        },
        {
            "name": "eWeLink",
            "countryCode": "39",
            "username": "xxxx",
            "password": "yyyy",
            "mode": "auto",
            "singleDevices": [
                {
                    "deviceId": "1000b72534",
                    "label": "Licht Matthias",
                    "ipAddress": "192.168.178.134"
                },
                {
                    "deviceId": "10006ca5cb",
                    "label": "Lüfter HOME OG",
                    "ipAddress": "192.168.178.122"
                }
            ],
            "multiDevices": [
                {
                    "deviceId": "1000e6088e",
                    "label": "Garage EWLink",
                    "hideChannels": "3,4,0",
                    "ipAddress": "192.168.1.118"
                }
            ],
            "_bridge": {
                "username": "0E:AD:A0:EF:12:54",
                "port": 37628
            },
            "platform": "eWeLink"
        }
```

I configured both as "sub-bridge" to have the possibility to add both bridges to a separate Home, because on iOS we can only share the entire home, but not give permissions to separate homes.

This works perfectly - but as the device 1000e6088e is twice in our homebridge-system the status is updated only in one of both devices.

### Example

 - Open the Garage Door on the Device `1000e6088e` from EWELINK
 - Normally if I turn the switch ON, then after X seconds it should go off because the EWELINK only sends an impulse to the garage door. This also works if we configure the Plugin only once.
 - If we configure the Plugin twice as in the provided config the Status of the Output (Switch) is updated only in one Bridge, but not in both bridges.

We've the most current versions of homebridge, and ewelink.

**Comment by bwp91** [comment]
Hi @matrad 
To be honest, I have never tested multiple configurations of the plugin, and it's not something that I take into account when developing the plugin.
Do you use the same ewelink credentials for both configurations?
It could be worth while trying the second configuration with a separate eWeLink account - and sharing the devices you want in your second homebridge bridge from your main ewelink account to this secondary ewelink account via the ewelink app.

**Comment by matrad** [comment]
I‘m currently using the same credentials for both, but the credentials should not be relevant because I specified the LAN Address, so the control should happen all locally, not trough the cloud.

but I‘ve set now for test-reasons different credentials, and now it seems to work....

i‘ll try it for a while and report if it‘s working this way....

**Comment by bwp91** [comment]
If you enable debug mode on both instances you’ll be able to see exactly what device 'notifications' the plugin receives, from both lan and the cloud.

could be useful in testing, i mean, with the device that is on both instances, if you control it from one it could be useful to see what notifications the other instance gets
