### ISSUE TITLE
Add Alexa Echo 4 zigbee in EWeLink

### ISSUE THREAD

**Issue by Stetocasa** [bwp91/homebridge-ewelink#220]
Ben, to optimize the numbers of hubs zigbee in house, I'd like to use my 7 sonoff zigbee rz3 devices with Amazon Alexa echo 4 that works also as zigbee hub.
Alexa app recognize the devices and works fine, but I need to add devices also in EWeLink to permitting the interfaces with home bridge.

**Comment by Stetocasa** [comment]
Let me provide an overview:
In Italy Apple not deliver homepod.
I introduced Alexa as vocal assistants replacing Siri in my home.
All accessories has the same name in HomeKit that still the primarily home config.
Automation are based in HomeKit
All scenes are based in HomeKit (I can trigger scenes by Alexa using a homebridge dummy switch imported by Alexa plug-in).
I bought on Amazon the sonoff zigbee hub to control 7 devices.
My question was to remove this hub an use the zigbee hub from Alexa device (saving money and 1 device less in my router).
The sonoff hub could be improved in ewelink, the 7 devices are their sons.
I'm trying to understand if EWeLink could recognize Amazon Alexa echo 4 as zigbee hub. Any idea ?

**Comment by bwp91** [comment]
Hi @Stetocasa 

For any device to work with this plugin, it needs to be in your ewelink account (and for zigbee devices this means using the sonoff zigbee bridge).

so if the device isn’t connected to the sonoff zigbee bridge -> not in ewelink -> doesn’t work with this plugin.

i also am confident there is no way to show the alexa zigbee bridge in ewelink app. 

Perhaps there is another plugin that could expose alexa connected devices to homebridge?

**Comment by Stetocasa** [comment]
Alexa player plug-in expose Alexa devices as speakers (not a Hub)

**Comment by bwp91** [comment]
Unfortunately I don't think what you wish to achieve is possible. To keep your sonoff zigbee devices within Homebridge (at least using this plugin) you will need to continue using the sonoff zigbee hub :)
