### ISSUE TITLE
Password error 10001

### ISSUE THREAD

**Issue by ladvoc** [bwp91/homebridge-ewelink#221]
### Details of your setup.
* Homebridge (+ config-ui)
* Homebridge v1.3.4 (2020-03-16)

* Raspberry Pi

* Plugin: v5.5.0

### Please paste any relevant logs below.

```
***** No auth token received.
{
  "error": 10001,
  "msg": "password error!",
  "data": {}
}{. *****
```
I am able to login using the eWelink app to login without issue, however, when I use the same credentials in the plug-in, I get the above error.

**Comment by bwp91** [comment]
Hi @ladvoc 

Please do make sure you are using the correct ewelink password (for example not an old one, or copying and pasting it wrong, using the wrong passwords for wrong email account, etc)

This error message is very specific to the email/password combination bring wrong for your ewelink account

**Comment by ladvoc** [comment]
@bwp91, you're correct. Something weird is going on with the ewelink server. I can now no longer sign in through the app either with the same credentials I have been using. There is no issue with the plugin. Thank you.
