### ISSUE TITLE
Ikea light bulb...

### ISSUE THREAD

**Issue by dado5623** [bwp91/homebridge-ewelink#222]
### What issue do you have? Please be as thorough and explicit as possible.
-I was able to add a ikea light bulb, Tradfri bulb E14 W op/ch 400lm - firmware 2.3.68, to Sonoff Zigbee bridge and then to homebridge, but was not able to add the Tradfri bulb E14 W 600lm to homebridge.
[22/03/2021, 11:04:33] [eWeLink] [Light1] is not supported, please make a GitHub issue with the following info:
[22/03/2021, 11:04:33] [eWeLink] [1258] {"bindInfos":{"gaction":[]},"subDevId":"2e1516feffe20a68","parentid":"1001129a41","switch":"on","colorTemp":27,"brightness":100}

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 
(1) Homebridge (+ config-ui)

* Which version of Homebridge/HOOBS do you have?
-Homebridge 1.3.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
-Raspberry Pi
-Node.js Version v14.16.0
-Npm Version v6.14.11

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?
-homebridge-ewelink v5.5.1

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.
...

### Please paste any relevant logs below.

```[22/03/2021, 11:04:33] [eWeLink] [Light1] is not supported, please make a GitHub issue with the following info:
[22/03/2021, 11:04:33] [eWeLink] [1258] {"bindInfos":{"gaction":[]},"subDevId":"2e1516feffe20a68","parentid":"1001129a41","switch":"on","colorTemp":27,"brightness":100}

```

**Comment by bwp91** [comment]
Hi, thanks for opening this.

Need a couple of things:

1. What are the minimum and maximum values you can set the colour temperature to in the ewelink app, and
2. do you know the kelvin range of the bulb? Could be something like 2000-6000K

**Comment by dado5623** [comment]
1) ->Minimum: [1258] {"bindInfos":{"gaction":[]},"subDevId":"2e1516feffe20a68","parentid":"1001129a41","switch":"on","colorTemp":0,"brightness":100}
-> Maximum: [1258] {"bindInfos":{"gaction":[]},"subDevId":"2e1516feffe20a68","parentid":"1001129a41","switch":"on","colorTemp":100,"brightness":100}

2 -> 2200 - 4000k

**Comment by bwp91** [comment]
Thanks.
Please try beta version 5.5.2-1 for an initial attempt to add support for this device.
Let me know of any errors you may encounter (difficult for me to test as I don't own this device!)
Thanks

**Comment by dado5623** [comment]
Thank you! It is now added to Homebridge :)
