### ISSUE TITLE
Improve security, the ewelink password is visible, not encrypted or scrambled.

### ISSUE THREAD

**Issue by azagramac** [bwp91/homebridge-ewelink#223]
* **Please explain your feature request in a one or two sentences.**
The eWelink plugin password is in plain text and visible in the config.json file or directly in the Homebridge configuration editor. 
Wouldn't it be better if it was in base64 or some other kind of encryption instead of plain text, even in an encrypted file. 

* **Is your feature request related to a problem? Please describe.**
Security flaw by having the password visible in plain text instead of an encrypted or scrambled format.

* **Any particular eWeLink devices that this relates to?**
No

* **Anything else?**
No

* **Info version**
**Node.js:** v14.16.0
**npm:** v6.14.11
**Homebridge:** v1.3.4
**Homebridge UI:** homebridge-config-ui-x v4.41.0
**Homebridge Ewelink:** homebridge-ewelink v5.5.1

* **Example**
Current
```
         {
            "name": "eWeLink",
            "username": "yourmail@domain.com",
            "password": "HelloWorld1234",
            "mode": "auto",
            "platform": "eWeLink"
        }
```

 With hidden password in base64
```
         {
            "name": "eWeLink",
            "username": "yourmail@domain.com",
            "password": "SGVsbG9Xb3JsZDEyMzQK",
            "mode": "auto",
            "platform": "eWeLink"
        }
```

**Comment by bwp91** [comment]
Hi @AzagraMac 

Please try the latest beta v5.5.2-2, looking at these options here:

<img width="744" alt="base64 options" src="https://user-images.githubusercontent.com/43026681/112125156-09883a00-8bbb-11eb-9b15-4578681aeb6b.png">

If the option is set to true then the plugin will decode the given password from base64 into 'plain text'.

This is the most feasible way this can be done, ie, it will require the user to encode their password themselves.

Let me know what you think

**Comment by azagramac** [comment]
Encode the password in base64 first and put it in the login field of the plugin?

**Comment by bwp91** [comment]
Yes

**Comment by azagramac** [comment]
v 5.5.1
```
{
  "error": 10001,
  "msg": "password error!",
  "data": {}
}
```
I can't find the version v5.5.2-2

**Comment by bwp91** [comment]
v5.1.1 was released before and so doesn't decode the password.

It's something I have added to the beta version, you can use the "Install Previous Version" feature in homebridge-ui (the spanner icon on the plugins page) and you can select the top entry which should show 'v5.5.2-2 - beta' to install

**Comment by bwp91** [comment]
Don't forget you will also need to tick the "Encoded Password" setting so the plugin knows to decode your password (needed so it doesn't try to decode any user's password that hasn't been encoded in the first place)

**Comment by bwp91** [comment]
Did you get it to work? Do you think this would be a useful feature?

There isn't really a way that I can auto-encode the password when the user puts it in their config. I also think it would create a lot of confusion!

**Comment by azagramac** [comment]
Thansk for new upgrade!!!!

**Comment by azagramac** [comment]
Error, update 5.6.0.
config
```
{
            "name": "eWeLink",
            "username": "yourmail@domain.com",
            "password": "PASSWORD_ENCODE64",
            "encodedPassword": true,
            "mode": "auto",
            "platform": "eWeLink"
}
```
        
Log:
```
[3/26/2021, 8:30:24 AM] Homebridge v1.3.4 (HomebridgePi) is running on port 52182.
[3/26/2021, 8:30:25 AM] [eWeLink] ***** Disabling plugin [v5.6.0]. *****
[3/26/2021, 8:30:25 AM] [eWeLink] ***** No auth token received.
{
  "error": 10001,
  "msg": "password error!",
  "data": {}
}{. *****
```

**Comment by bwp91** [comment]
Hi @AzagraMac

This is working for me. First please verify you have the correct encoding of your password, perhaps using a site like this:

https://www.base64encode.org

**Comment by azagramac** [comment]
Yes, it is correct the password in bas64, checked in the web that you have facilitated me.
To pass it I do it from terminal.
`echo "your_password" | base64`

**Comment by bwp91** [comment]
and sorry have to check, you have restarted homebridge since updating the plugin and editing your config?

**Comment by azagramac** [comment]
Yes, I always restart homebridge after an upgrade or change.

**Comment by bwp91** [comment]
When I use the terminal to encode, I get a different result to the website I mentioned.

It seems terminal is adding a newline to the end of the string that is inputted, which will mean the result is incorrect.

**Comment by azagramac** [comment]
Right, when encoding the key in base64 by terminal, I get some characters at the end, specifically, these `Cg==`
However, when I copy the key in base64, it decodes it correctly even with those characters...

curious

**Comment by bwp91** [comment]
If you copy the terminal encoded string into the website and decode it, you’ll find that a new line is placed at the end (ie the cursor can go to the next line)

**Comment by azagramac** [comment]
I have set the key without those characters at the end, which I get by passing the key through the terminal, and it works perfectly.

**Comment by burkenyo** [comment]
Hi, @AzagraMac and @bwp91, noting here that base64 encoding is _not_ a form of encryption. It’s primary use-case is encoding arbitrary binary data (including possibly other text) into printable ASCII characters, especially for embedding that data in another text stream such as an [RFC 5322](https://tools.ietf.org/html/rfc5322)-compliant e-mail or a JSON text.

Do _not_ rely on Base64 encoding as a security measure!
