### ISSUE TITLE
Sonoff DW2

### ISSUE THREAD

**Issue by BaskaraR** [bwp91/homebridge-ewelink#225]
### What issue do you have? Please be as thorough and explicit as possible.

Sonoff DW2 battery life is very bad. Lasted almost a week only on average with brand new batteries. 

This issue has been there since 2months ago. Kept changing batteries after batteries, hoping that something can be done on this matter. No error logs shown. Low battery threshold shows a different reading compared to the eWeLink app. The sensor works as how it should until it goes offline and I know the battery is dead. Thanks

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 

Homebridge with raspberry pi4

* Which version of Homebridge/HOOBS do you have?
v1.3.4

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?
v5.6.0 

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

DW2-Wi-Fi

* Do you use your main eWeLink credentials or do you use a secondary eWeLink account for Homebridge?

Main credentials. 

### Please paste any relevant logs below.

```

```

**Comment by Zacknetic** [comment]
*rolls magic 8 ball* : “Try again”

**Comment by bwp91** [comment]
Hi @BaskaraR 

> Sonoff DW2 battery life is very bad. Lasted almost a week only on average with brand new batteries.

This plugin has nothing to do with the battery usage of the DW2. If you are concerned about this then you'd be best to contact Sonoff support directly. Using this plugin will not drain the battery any more than its normal use - this plugin communicates with eWeLink cloud and not the device itself.

> No error logs shown

I wouldn't expect any errors to show as there is no error here? 

> Low battery threshold shows a different reading compared to the eWeLink app

The low battery threshold in HomeKit can be changed using the 'Sensor Devices' configuration option, through the Homebridge UI you can easily set this up with the device ID of your DW2. I don't own a DW2 so I am not sure what the default (ie the threshold in the eWeLink app) is.

---

But yeah re the battery issue I would contact Sonoff directly :)

**Comment by BaskaraR** [comment]
> Hi @BaskaraR
> 
> > Sonoff DW2 battery life is very bad. Lasted almost a week only on average with brand new batteries.
> 
> This plugin has nothing to do with the battery usage of the DW2. If you are concerned about this then you'd be best to contact Sonoff support directly. Using this plugin will not drain the battery any more than its normal use - this plugin communicates with eWeLink cloud and not the device itself.
> 
> > No error logs shown
> 
> I wouldn't expect any errors to show as there is no error here?
> 
> > Low battery threshold shows a different reading compared to the eWeLink app
> 
> The low battery threshold in HomeKit can be changed using the 'Sensor Devices' configuration option, through the Homebridge UI you can easily set this up with the device ID of your DW2. I don't own a DW2 so I am not sure what the default (ie the threshold in the eWeLink app) is.
> 
> But yeah re the battery issue I would contact Sonoff directly :)


Ok. Thanks for your time!!! :)
