### ISSUE TITLE
iFan 03 not updating HOME App

### ISSUE THREAD

**Issue by deon-wentzel** [bwp91/homebridge-ewelink#226]
Hi,

I am using the iFan 03 with the latest OEM firmware. When I turn on the FAN in the EWELNK APP or the remote, it does not update HOME App, I have tried both AUTO and WAN Connection Mode. With the Light Switch T0 or T1 the HOME App is updated. HooBs and the EWELINK uses the same account.

I am using HOOBs on a Raspberry PI 4 (8G) with 16G storage.

Hoobs Version: 3.35
Node Version: 14.15.1
Plug-in Version: 5.6.0

If I look at the logs I see the FAN turned on and the percentage of the FAN speed.

Mar 27 22:55:55 hoobs hoobs[651]: [eWeLink] [Devicexxxxxx] current state [on].
Mar 27 22:55:55 hoobs hoobs[651]: [eWeLink] [Devicexxxxxx] current speed [66%]

Mar 27 22:57:38 hoobs hoobs[651]: [eWeLink] [Devicexxxxxx] current state [off].
Mar 27 22:57:38 hoobs hoobs[651]: [eWeLink] [Deviceexxxxx] current speed [33%]

I even close the HOME App and re-open it to see if there are any changes.

When I use the home to turn the FAN off and On it updates both HOME App and EWELINK

Mar 27 23:01:47 hoobs hoobs[651]: [eWeLink] [Devicexxxxxx] current state [on].
Mar 27 23:01:47 hoobs hoobs[651]: [eWeLink] [Devicexxxxxx] current speed [99%].
Mar 27 23:01:50 hoobs hoobs[651]: [eWeLink] [Devicxxxxxx] current state [off].
Mar 27 23:01:50 hoobs hoobs[651]: [eWeLink] [Devicexxxxxx] current speed [0%].

Any ideas?

**Comment by bwp91** [comment]
Hi @deon-wentzel 

Could you [follow these instructions](https://github.com/bwp91/homebridge-ewelink/wiki/Beta-Version#hoobs-ui) to update to the beta version I have just released, v5.6.1-1, to see if this has fixed your issue?

Thanks

**Comment by deon-wentzel** [comment]
Hi

That did the trick!! If I use the EWELink app or the remote, the changes are updated on the home app

Thanks!!

**Comment by bwp91** [comment]
Excellent. I will leave this issue open until v6 of the plugin is released which includes the fix for the fan.

**Comment by deon-wentzel** [comment]
Great, thanks
