### ISSUE TITLE
Change status on offline device.

### ISSUE THREAD

**Issue by LZee** [bwp91/homebridge-ewelink#227]
### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 
1

* Which version of Homebridge/HOOBS do you have?
homebridge-config-ui-x v4.41.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?
homebridge-ewelink v5.6.0

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

### Please paste any relevant logs below.

```

```
When I click on an offline device in homebridge, it changes state even though the log in prints that the device is offline.
It would be a good idea not to show as if you had managed to turn the device on or off.
![before](https://user-images.githubusercontent.com/10674642/112755218-08527500-8fe0-11eb-971a-f4359f2344c9.png)
![after](https://user-images.githubusercontent.com/10674642/112755226-0c7e9280-8fe0-11eb-8f3d-9fa318d2831f.png)
![log](https://user-images.githubusercontent.com/10674642/112755234-17d1be00-8fe0-11eb-9c16-b1f7c1189601.png)

**Comment by bwp91** [comment]
Hi @LZee I have added this status for **some** devices so far in the latest beta of the plugin

please check my latest comment in https://github.com/bwp91/homebridge-ewelink/issues/229.

**Comment by bwp91** [comment]
Closing this as id like to continue the conversation in the other issue posted above
