### ISSUE TITLE
WHAT DOES MEAN?

### ISSUE THREAD

**Issue by ddong3000** [bwp91/homebridge-ewelink#228]
WHAT DOES MEAN?
Seen every hour.

![제목 없음](https://user-images.githubusercontent.com/54649785/112775360-a34a5e00-9077-11eb-939d-40d9e4799f5e.png)

**Comment by bwp91** [comment]
This is a workaround for the issue you encountered at:
https://github.com/oznu/docker-homebridge/issues/364

The plugin is having to work around a problematic ewelink server (as-pconnect4.coolkit.cc) that is causing trouble for users based in the Asia continent.

Does the plugin eventually start working again?

**Comment by ddong3000** [comment]
Yes. this plugin is working.

**Comment by bwp91** [comment]
You can see more info about this here:
https://github.com/bwp91/homebridge-ewelink/issues/224

**Comment by ddong3000** [comment]
WOW! You are so kind! THANKS ALOT.
