### ISSUE TITLE
HomeKit On/Offline Status

### ISSUE THREAD

**Issue by Stetocasa** [bwp91/homebridge-ewelink#229]
Hi Ben,
In EWeLink app something devices goes offline, it's possible to notify this with a "no response" status in homekit?
I saw in your last Govee plug-in version that you fixed that

**Comment by bwp91** [comment]
It is something I am looking into for ewelink. in govee there are two different accessory types so implementation is easier.

In ewelink there are 41 different accessory type files so you can see it will take me much longer to change the code in each file!

**Comment by Stetocasa** [comment]
We definitely love your effort!
If you can start from Sonoff Zigbee Basiczbr3 switch really appreciated 😜

**Comment by bwp91** [comment]
Please check the newest beta, v6.0.0-0 and also the [changelog](https://github.com/bwp91/homebridge-ewelink/blob/latest/CHANGELOG.md#beta) for the latest homebridge/hoobs requirements.

Also note that the accessory will show as no response only when offline and **an attempt to control it has been made**.

**Comment by Stetocasa** [comment]
This is a good news, thanks!
Any chance in the future to have a "no response" message tile without tentative? I don't know with automatic refresh each 60 seconds double checking the status trough EWeLink app

**Comment by bwp91** [comment]
This would be a very complex task.

* Some devices support LAN mode, some don't
* Some devices could be online via LAN mode but offline via cloud, or vice versa
* Some users restrict to LAN only, some to cloud only

There are also some cases where a plugin cannot detect a device over local network (so plugin would think it were offline) but with a manual IP the device works as expected.

There are so many variations, the most straightforward being to just check when a device is controlled if it has been successful.

Also in my opinion I don't see why it would be useful to know if a device is online/offline if in any other situation that wanting to control it?

**Comment by Stetocasa** [comment]
Ben, let me try to explain my issue.
I have a sonoff zigbee hub with 7 zigbee devices connected. 
Sometime two devices goes offline an not come back online until I switch off and on the power on child devices offline.
I normally not showing EWeLink app but I spend more time in HomeKit. This request made to understand when the devices goes offline in order to understand when restart the devices

**Comment by bwp91** [comment]
Please try the latest beta, v6.0.0-2

**Comment by Stetocasa** [comment]
> Please try the latest beta, v6.0.0-2

I have hoobs. Which input I need to write in terminal to install the beta ?

**Comment by bwp91** [comment]
https://github.com/bwp91/homebridge-ewelink/wiki/Beta-Version#hoobs-ui

**Comment by bwp91** [comment]
Let me know if you get any errors. I don’t have any zigbee devices so need you to do the testing!

**Comment by Stetocasa** [comment]
> Let me know if you get any errors. I don’t have any zigbee devices so need you to do the testing!

Let me two hours, coming back at home

**Comment by Stetocasa** [comment]
> Let me know if you get any errors. I don’t have any zigbee devices so need you to do the testing!

Ben, fantastic works well. The status is identified without trying access on devices. This was the request

Now I’m coming back to normal version awaiting official release

**Comment by bwp91** [comment]
The official release won’t be for a while yet. There’s still a lot to do plus testing with different users with different device types. No harm in staying on the beta

**Comment by Stetocasa** [comment]
Ok I will remain on the beta

**Comment by bwp91** [comment]
when the “official” is released, it will appear as an update in hoobs

**Comment by LZee** [comment]
Thanks, it works well for me now.

**Comment by bwp91** [comment]
Excellent. I will leave this issue open until v6 of the plugin is released which includes the new 'offline' status.
