### ISSUE TITLE
CarPlay garage door  no response

### ISSUE THREAD

**Issue by vitaliy-kozlov** [bwp91/homebridge-ewelink#233]
Having issue with garage door in CarPlay Siri suggestions. So Garage door is shown in Siri suggestions but it's not working. it's only display card with message "no response". BUT the same door working fine from Apple home app.
I Tried to update iOS to latest version, delete cached accessory,still no luck. Issue is still persist. I don't know this is something from my side, Apple or plugin updates. A month ago all working fine(

Homebridge ltest 1.3.4
ConfigUI latest. 
iOS latest. ![image](https://user-images.githubusercontent.com/24417253/113920079-ff864e00-97ec-11eb-9fe5-15c4b0b91200.jpeg)

**Comment by vitaliy-kozlov** [comment]
I use sonoff dc device

**Comment by bwp91** [comment]
So just to confirm, on the apple home app on your phone the accessory doesn't show as no response... but on the carplay screen it does show as no response?

**Comment by vitaliy-kozlov** [comment]
Yes, exactly. Home app - all is ok, CarPlay - no response. It will be great to check someone else that issue is reproducible. Also I will try to downgrade eWeLink plugin and recheck this again. Thanks. > So just to confirm, on the apple home app on your phone the accessory doesn't show as no response... but on the carplay screen it does show as no response?

**Comment by bwp91** [comment]
This is strange. If it’s working from your phone but not car, this might suggest a connectivity issue between the home hub or your phone and your car.

I unfortunately have zero experience with CarPlay, I assume it connects to your phone?

**Comment by vitaliy-kozlov** [comment]
Seems to be that Apple issue. Just totally removed garage door and unpaired phone from the CarPlay and it's working again. So I close issue.Thanks > This is strange. If it’s working from your phone but not car, this might suggest a connectivity issue between the home hub or your phone and your car.
> 
> 
> 
> I unfortunately have zero experience with CarPlay, I assume it connects to your phone?
