### ISSUE TITLE
Problem with iFan03

### ISSUE THREAD

**Issue by DarkSyler21** [bwp91/homebridge-ewelink#234]
Hi
using HB with UI and the iFan03 and sonoff l1 led strip
after updating to the 6.X version of the plugin HB is now working and throwing a lot of errors.
with the ewelink app everything working good.

[12/04/2021, 17:11:40] [eWeLink] [LightFan] device update failed as WebSocket request was rejected by timeout (10000 ms). RequestId: 1618236690369 at PromiseController._handleTimeout (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/promise-controller/src/index.js:172:19) at connectionWS.sendUpdate (/usr/local/lib/node_modules/homebridge-ewelink/lib/connection/ws.js:340:15).
[12/04/2021, 17:11:52] [eWeLink] [LightFan] device update failed as WebSocket request was rejected by timeout (10000 ms). RequestId: 1618236702412 at PromiseController._handleTimeout (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/promise-controller/src/index.js:172:19) at connectionWS.sendUpdate (/usr/local/lib/node_modules/homebridge-ewelink/lib/connection/ws.js:340:15).
[12/04/2021, 17:29:12] [eWeLink] [Led Strip] device update failed as WebSocket request was rejected by timeout (10000 ms). RequestId: 1618237742639 at PromiseController._handleTimeout (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/promise-controller/src/index.js:172:19) at connectionWS.sendUpdate (/usr/local/lib/node_modules/homebridge-ewelink/lib/connection/ws.js:340:15).

Cheers,
Idan.

**Comment by bwp91** [comment]
Looks like an issue with the websocket connection. I have a couple of questions,

1. when you control a device does it physically respond even if the accessory in home app says no response?
2. Do you use your main ewelink credentials for the plugin? or a shared account?

**Comment by DarkSyler21** [comment]
thanks for the quick response
just to clarify when I reverted back to 5.6 all working perfectly again.
regarding the questions:
1. not consistent. Sometimes it does and other times nothing and says no response.
2. No, just changed and seems to be working fine :S

**Comment by DarkSyler21** [comment]
> thanks for the quick response
> just to clarify when I reverted back to 5.6 all working perfectly again.
> regarding the questions:
> 
> 1. not consistent. Sometimes it does and other times nothing and says no response.
> 2. No, just changed and seems to be working fine :S

however there is a "significant" delay now that weren't there before of about 2 seconds between controlling via HomeKit until there is any change

**Comment by bwp91** [comment]
The new version of the plugin is more thorough in waiting for an ‘success’ response from ewelink when a device is controlled. 

v5 updated the accessory in homekit immediately regardless of whether the command was actually received by ewelink

v6 waits for the ‘success’ from ewelink and then updates the accessory in homekit. 

the idea is to use your main ewelink credentials for the plugin, not a shared account, as using the main credentials is more reliable for receiving this ‘success’ response from ewelink.

So is v6 working if you use your main ewelink credentials?

**Comment by DarkSyler21** [comment]
> The new version of the plugin is more thorough in waiting for an ‘success’ response from ewelink when a device is controlled.
> 
> v5 updated the accessory in homekit immediately regardless of whether the command was actually received by ewelink
> 
> v6 waits for the ‘success’ from ewelink and then updates the accessory in homekit.
> 
> the idea is to use your main ewelink credentials for the plugin, not a shared account, as using the main credentials is more reliable for receiving this ‘success’ response from ewelink.
> 
> So is v6 working if you use your main ewelink credentials?

Yeah it's working well with the main account so I'll keep it that way.
Thanks for the explanation on the delay. It only disturb in regard of automation (when light on turn on.. etc) so there the delay is meaningful so I'll find a workaround on that.
Thanks for the quick help though! :)

**Comment by bwp91** [comment]
I could add a config option to ‘not wait’ and update the home app accessory immediately?
It would work the same way as v5, not waiting for the success message from ewelink. it works 99% of the time but there could be cases where the accessory shows as updated but actually the physical device hasn’t updated.

**Comment by DarkSyler21** [comment]
I never really had a problem with that at v5
If it’s not a hassle for you to add this button it might be nice but it’s
not that big of a deal because I can make a workaround that problem to
avoid the delay.
Up to you :)

**Comment by bwp91** [comment]
If you can make a workaround I'll leave it. Hope all is still working okay :)
