### ISSUE TITLE
Error with Led strip

### ISSUE THREAD

**Issue by vitorpt21** [bwp91/homebridge-ewelink#238]
### What issue do you have? Please be as thorough and explicit as possible.
Since version 6.1.0 of the plugin, I have an error with sonof led strip

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 
Hoobs

* Which version of Homebridge/HOOBS do you have?
3.3.5

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?
6.1.2

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.
Sonof L1

* Do you use your main eWeLink credentials or do you use a secondary eWeLink account for Homebridge?
Secondary

### Please paste any relevant logs below.

The write handler for the characteristic 'On' on the accessory 'Light Led' was slow to respond!
The write handler for the characteristic 'On' on the accessory 'Light Led' didn't respond at all!. Please check that you properly call the callback!

```

```

**Comment by bwp91** [comment]
Hi @vitorpt21 
The plugin works a faster and is more reliable if you use your main ewelink credentials instead of a secondary “shared” account.
Please try this!

**Comment by muriloscosta** [comment]
I had same issue, after changing it to main ewelink credentials, issue was solved.

**Comment by bwp91** [comment]
Here is the reasoning:
https://github.com/bwp91/homebridge-ewelink/issues/234#issuecomment-817874985
