### ISSUE TITLE
SNZB-02 as an Automation trigger

### ISSUE THREAD

**Issue by ultrasnail** [bwp91/homebridge-ewelink#242]
Hi,

should it be possible to use the SNZB-02 Temperature and Humidity sensor as a trigger sensor in automations?

My setup is a Sonoff ZBBRIDGE with the sensor connected via that bridge. 

The plug-in today reports the humidity and temperature perfectly, but it would be excellent if I could use it to initiate automations. Is this a configuration failure on my behalf, or something that is not supported today?

Many Thanks

Simon

**Comment by bwp91** [comment]
Hi @ultrasnail 

Temperature and humidity based automations cannot be made with the native Home app.

They need to be made with a third party HomeKit app like Eve.

https://www.imore.com/how-create-temperature-based-automation-homekit

^ This is a good guide.

Thanks
