### ISSUE TITLE
Concurrency issue with sonoff TX-T2 

### ISSUE THREAD

**Issue by alimans3** [bwp91/homebridge-ewelink#243]
### What issue do you have? Please be as thorough and explicit as possible.

I have a homekit automation to turn on 2 out of 3 switches in the sonoff 3 gang tx switch panels.
Randomly the following issue happens:
1- switch 1 on
2- switch 1 off switch 2 on

I suspect this is a concurrency issue due to both commands happening at the same time.

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 
(1) homebridge with config-ui

* Which version of Homebridge/HOOBS do you have?

1.3.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry pi 4
Node js v14.16.1

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?
Latest, no

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.
Sonoff TX T2 3 gang US style

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @alimans3 

Could you update to beta version 6.2.2-beta.4 and run this for a few days to see if I have been able to resolve this?

Thanks

**Comment by alimans3** [comment]
Hello @bwp91,

Thanks for your timely reply.
Sure I am glad I can help.

I will let you know when I test it.

**Comment by alimans3** [comment]
Hi @bwp91 ,

I tested the same scenario multiple times with the beta version and I can confirm that the issue is resolved.

Thank you
