### ISSUE TITLE
Smart meter

### ISSUE THREAD

**Issue by 40federico** [bwp91/homebridge-ewelink#244]
* **Please explain your feature request in a one or two sentences.**

is there any way to link into homebridge "emylo wifi smart meter"?

* **Is your feature request related to a problem? Please describe.**

* **Any particular eWeLink devices that this relates to?**
emylo wifi mart meter

* **Anything else?**

**Comment by bwp91** [comment]
Hi @40federico 

Does this device use the ewelink app to connect?

**Comment by bwp91** [comment]
I just had a look on Amazon and it looks like this is a smart life device, meaning it won't work with this plugin but maybe with

* [homebridge-tuya-web](https://github.com/milo526/homebridge-tuya-web), or
* [homebridge-tuya](https://github.com/iRayanKhan/homebridge-tuya)

**Comment by 40federico** [comment]
Ben, thanks. By the way I have tried and no luck.

It is emylo  smart wifi meter, I think I had a mistake with the item name.

**Comment by bwp91** [comment]
but this device uses the tuya app or smart life app right?

**Comment by 40federico** [comment]
Smart life, see attached.

**Comment by bwp91** [comment]
attaching through email doesn’t work on here.

but have you tried the homebridge-tuya-web plugin?

**Comment by 40federico** [comment]
@bwp91

The device is “emylo” brand. I use Smartlife to manage it. 

I use home bridge too, checked what you refered as possible solutions and no way. I think is a problem of the device due is not in the avail list of compatibility with homebridge-tuya or homebridge-tuya web. I have other emylo devices as switches and work perfectly with home bridge-tuya

**Comment by bwp91** [comment]
Ah I see.

You could always try asking on the homebridge-tuya github page to see if it could be added?
