### ISSUE TITLE
DUALR3 Motor Mode

### ISSUE THREAD

**Issue by Jer-emy** [bwp91/homebridge-ewelink#246]
### What issue do you have? Please be as thorough and explicit as possible.

In the eWeLink App, I have added my new device (Sonoff Dual R3) and configure it as a motor. I have also calibrate motor directly inside the app. My awning open and close well with eWeLink app.
Then, this device is detected by the plugin as we can see on following log: 

> 27/04/2021, 16:55:33] [eWeLink] LAN monitoring started.
[27/04/2021, 16:55:34] [eWeLink] [Awning] initialised and found locally with IP [192.168.1.73].
[27/04/2021, 16:55:34] [eWeLink] [Terrace Light] initialised and found locally with IP [192.168.1.65].

Then, in Home App, I can see the device but when I would like to act on it, nothing happens.
I have tried to configure this device as a multipledevice as mentionned in your configuration settings but nothing still happens.

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS?

(1) Homebridge (+ config-ui)

* Which version of Homebridge/HOOBS do you have?

v1.3.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi 4 Node.js v14.16.1 Npm v7.8.0

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

v6.2.2. I do not know if it works with an old version, I do not tried it

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

DUALR3

**Comment by bwp91** [comment]
Hi @Jer-emy 

motor mode of the dualr3 is not supported yet.

this is because i don’t own the device and also have not had access to one to be able to add this support.

if you would be happy to share this device to my ewelink account (and i would need to control it a couple of times) then please let me know and i can look at adding support.

thanks

**Comment by Jer-emy** [comment]
Yes I can share this device with you. Give me your eWeLink account and I will share it now.

**Comment by bwp91** [comment]
Which continent are you in?

**Comment by Jer-emy** [comment]
I'm in France. I need your country and your eWeLink account userID

**Comment by bwp91** [comment]
Ah good (i ask for the continent because you can’t share devices across different continents)

[redacted]

**Comment by Jer-emy** [comment]
Normally, it is shared with you

**Comment by bwp91** [comment]
Could you update to the beta version of the plugin and see how you get on? it's version 6.2.3-beta.1.

**Comment by bwp91** [comment]
Could you update to the beta version of the plugin and see how you get on? it's version 6.2.3-beta.1.

**Comment by Jer-emy** [comment]
It works fine, good job! Thanks a lot!

**Comment by bwp91** [comment]
Amazing.

It should work both ways ie
1. the obvious case that if you control through HomeKit it updates in the ewelink app, but also
2. if you use the ewelink app to control it, it will update in HomeKit once it has finished moving

Glad it's working :)
