### ISSUE TITLE
Web API to control devices through the plugin

### ISSUE THREAD

**Issue by aswathraja** [bwp91/homebridge-ewelink#247]
* **Please explain your feature request in a one or two sentences.**
Can we have a API server running along with the plugin to control the devices through the plugin?
* **Is your feature request related to a problem? Please describe.**
No. Can we have endpoints in the web API to get the status and control a device - for starters just to toggle on/off any. device.

Ex: 
/status/{ewelinkDeviceID} - returns the status of the device (either over LAN or WS)
/setstate/{ewelinkDeviceID} - sets the device state to ON and returns a success response

I know there is the Hombridge-UI API to do the same but when the cached accessories gets reset or after reboot of the host, the APIs can't find the device until manually logged in and the accessories page is loaded in the Homebridge-UI.

* **Any particular eWeLink devices that this relates to?**
No. Just for all devices supported by this plugin

**Comment by bwp91** [comment]
Hi @aswathraja 
Would be happy to chat to you on [discord](https://discord.gg/cMGhNtZ3tW) about this!

**Comment by aswathraja** [comment]
Tested and working fine for me with the release v6.5.0.

Thank you @bwp91 

Closing the issue here.
