### ISSUE TITLE
Authentication issues since config changes

### ISSUE THREAD

**Issue by levibuzolic** [bwp91/homebridge-ewelink#248]
### What issue do you have? Please be as thorough and explicit as possible.

Previously I was running version 4.7.x, which required a config with `countryCode` present without issue, however after upgrading to the latest 6.3.0 version I'm getting the following auth errors:

```
[04/05/2021, 10:26:05 am] [eWeLink] An error occurred during http login().
[04/05/2021, 10:26:05 am] [eWeLink] ***** Disabling plugin [v6.3.0]. *****
[04/05/2021, 10:26:05 am] [eWeLink] ***** Error: No auth token received.
{
  "error": 10003,
  "msg": "user does not exists",
  "data": {}
}
    at connectionHTTP.login (/usr/lib/node_modules/homebridge-ewelink/lib/connection/http.js:110:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at eWeLinkPlatform.pluginSetup (/usr/lib/node_modules/homebridge-ewelink/lib/index.js:462:24). *****
```

I noticed that `lib/connection/http.js` now has a hardcoded `countryCode` of `+44` which I though could be related as that doesn't match with the country code I use with my eWeLink account (`+61`). So I tried changing the `countryCode` in `lib/connection/http.js` but got the same error.

I've also tried the official `ewelink-api` package https://ewelink-api.vercel.app/docs/introduction which can login and get devices without issue.

### Details of your setup.

Name | Version
---|---
Node.js | v16.0.0
npm | v7.11.1
Homebridge | v1.3.4
Homebridge UI | v4.41.1
OS | Ubuntu 20.10

**Comment by levibuzolic** [comment]
After some further investigation and monitoring the traffic sent from `ewelink-api`, I noticed that the API region my account hits is `us-apia.coolkit.cc` rather than `eu-apia.coolkit.cc`.

Manually changing the host in `lib/connection/http.js` to `us-apia.coolkit.cc` *and* `countryCode` to `+61` I'm able to login without issue.

For whatever reason the eWeLink API isn't returning the `10004` error code that the region switching code in `http.js` is designed to handle.

I'm going to draft a PR allowing these values to be optionally configured.

**Comment by bwp91** [comment]
Hi @levibuzolic 
Thanks for the pr.
It's strange that in your case ewelink isn't reporting the correct error code. As I'm sure you can imagine, the `user does not exists` error normally means the email address being used doesn't have an account with ewelink. And when the incorrect region is used then ewelink normally reports the correct region back and the plugin takes care of the rest.
It feels like a step back again adding the manual http host and country code options, but if it's necessary for some users then of course I will leave the options there.
I made a couple of changes to the code (like parsing the country code in case a user doesn't add the '+' and made the available http hosts into a select box).
This is now already available in the beta version of the plugin, which also includes a lot of other changes so it's likely to be a little while before it's released, as I need some time to make sure that each and every device type is still working correctly!
Thanks again!

**Comment by levibuzolic** [comment]
Thanks, I’ll give the beta a go in the morning. 

Yeah I thought the behaviour was very weird and agree more config is not ideal, especially when it’s not clear when/why you would need to configure these options. 

I can try reporting this to eWeLink if I can find the correct avenue to do so.

**Comment by bwp91** [comment]
hey @levibuzolic 
i know this has been solved, but this has been bugging me for days still.
I realise the httpHost you need is the US server, out of interest, what happens if you manually put your country code to +1?
Could you try this out for me?
Thanks

**Comment by levibuzolic** [comment]
@bwp91 with just `"countryCode": "+1"` I get:

```json
{
  "error": 10003,
  "msg": "user does not exists",
  "data": {}
}
```

With `"countryCode": "+1"` and `"httpHost": "us-apia.coolkit.cc"` I also get:

```json
{
  "error": 10003,
  "msg": "user does not exists",
  "data": {}
}
```

The only configuration that seems to work for my eWeLink account is:

```json
{
  "countryCode": "+61",
  "httpHost": "us-apia.coolkit.cc"
}
```
