### ISSUE TITLE
devices doesn't respond over local and "break" homekit service

### ISSUE THREAD

**Issue by heyjhoow** [bwp91/homebridge-ewelink#252]
### What issue do you have? Please be as thorough and explicit as possible.
none of my sonoff devices show as "lan available", even if if appears available on app for lan usage.

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 
HB Service on win 10

* Which version of Homebridge/HOOBS do you have?
v1.3.4

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?
v6.5.1
the issue has appeared from the last 2 weeks or so

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.
sonoff basic r2
Sonoff TH16

* Do you use your main eWeLink credentials or do you use a secondary eWeLink account for Homebridge?
secondary account

### Please paste any relevant logs below.

[09/05/2021 19:01:30] [eWeLink] [Luminária Verde ] device update failed as WebSocket request was rejected by timeout (6000 ms). RequestId: 1620597684698 at PromiseController._handleTimeout (C:\Users\jroch\AppData\Roaming\npm\node_modules\homebridge-ewelink\node_modules\promise-controller\src\index.js:172:19) at connectionWS.sendUpdate (C:\Users\jroch\AppData\Roaming\npm\node_modules\homebridge-ewelink\lib\connection\ws.js:334:15).

**Comment by bwp91** [comment]
Hi @heyjhoow 

Please use your main ewelink credentials for the plugin. This should fix the timeout issues.

The lan discovery is a separate issue. If the plugin shows they are offline it means that the plugin for some reason can’t automatically discover the devices. You can use the configuration to set a fixed IP for the devices that support lan (the basicr2). Let me know if you need assistance with this.

Thanks

**Comment by heyjhoow** [comment]
After login-in with my first credentials the issue seem to be solved and the devices are working without any delay!
