### ISSUE TITLE
Issue with LAN control

### ISSUE THREAD

**Issue by alimans3** [bwp91/homebridge-ewelink#253]
### What issue do you have? Please be as thorough and explicit as possible.

When there is no internet connection, and I restart homebridge, the plugin cannot discover the devices and they cannot be controlled from Home app.

They can be controlled from the ewelink app in LAN mode
### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 
Homebridge with config-ui

* Which version of Homebridge/HOOBS do you have?

1.3.4

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

V6.6.0 - Not sure.

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

Multiple TX1/2/3 gang US version switches.
Multiple POWR2 switches.
Basically all ewelink devices in the home

* Do you use your main eWeLink credentials or do you use a secondary eWeLink account for Homebridge?
Main Ewelink

### Please paste any relevant logs below.
Config:

   {
            "name": "eWeLink",
            "username": "email",
            "password": "password",
            "language": "en",
            "mode": "auto",
            "singleDevices": [
                {
                    "deviceId": "ID",
                    "label": "Kitchen Lights",
                    "ipAddress": "192.168.1.92"
                },
                {
                    "deviceId": "ID",
                    "label": "Front Balcony Lights",
                    "ipAddress": "192.168.1.86"
                },
                {
                    "deviceId": "ID",
                    "label": "Rear Balcony Lights",
                    "ipAddress": "192.168.1.82"
                },
                {
                    "deviceId": "ID",
                    "label": "Living Lights",
                    "ipAddress": "192.168.1.85"
                },
                {
                    "deviceId": "ID",
                    "label": "Bedroom UPS Lights",
                    "ipAddress": "192.168.1.89"
                }
            ],
            "multiDevices": [
                {
                    "deviceId": "ID",
                    "label": "Bedroom Lights",
                    "ipAddress": "192.168.1.91"
                },
                {
                    "deviceId": "ID",
                    "label": "Hallway/Living UPS Lights",
                    "ipAddress": "192.168.1.87"
                },
                {
                    "deviceId": "ID",
                    "label": "Hallway Lights",
                    "ipAddress": "192.168.1.88"
                }
            ],
            "outletDevices": [
                {
                    "deviceId": "ID",
                    "label": "Bedroom AC",
                    "ipAddress": "192.168.1.93"
                },
                {
                    "deviceId": "ID",
                    "label": "Living AC",
                    "ipAddress": "192.168.1.80"
                },
                {
                    "deviceId": "ID",
                    "label": "Water Pump",
                    "ipAddress": "192.168.1.83"
                },
                {
                    "deviceId": "ID",
                    "label": "Heater",
                    "ipAddress": "192.168.1.84"
                }
            ],
            "thDevices": [
                {
                    "deviceId": "ID",
                    "label": "Pool Temperature",
                    "hideSwitch": true,
                    "offset": 0.5,
                    "minTarget": 10,
                    "maxTarget": 40
                }
            ],
            "platform": "eWeLink"
        }

```

```

**Comment by alimans3** [comment]
![Uploading EA0AB022-9132-4984-8E9F-9492F222FC04.jpeg…]()

a sample from my homebridge logs

**Comment by bwp91** [comment]
Hi @alimans3 
Internet connection is necessary when the plugin loads (eg after a homebridge restart).
This is because the plugin loads a device list from the ewelink server with device information, type, commands the device needs/provides etc.
If your internet connection is down and you restart homebridge, do you not get messages in the logs like trying to connect to ewelink?

**Comment by alimans3** [comment]
Actually even with internet, I am having trouble with the plugin. 
The devices are loaded correctly and lan ips are discovered, however I cannot control them from home app. There is this warning in the logs:
![Uploading F1CBE9CE-91A1-4C5C-86D6-F98212E4C19C.jpeg…]()

**Comment by alimans3** [comment]
It seems the problem is with my local network, and I didn’t know the internet need on startup thing.
Ill close this issue.
