### ISSUE TITLE
iFan03

### ISSUE THREAD

**Issue by kamaruszamanjufri** [bwp91/homebridge-ewelink#256]
Hi,

Whenever I turn on the fan switch, the light will always lit up but the fan is not spin.
I need to go to the menu and move the speed menu before it start spinning.

Can it be change? 

The automation doesn't work well with the scenario.

Regards.

**Comment by bwp91** [comment]
Hi @kamaruszamanjufri 

Are you able to try a beta version of the plugin to see if I have fixed this? It's v6.6.1-beta.3.

Thanks

**Comment by kamaruszamanjufri** [comment]
I will try it out.

**Comment by kamaruszamanjufri** [comment]
The light still turn on by default. However I manage to set the fan speed by having sleep timer. set speed at 33% and later 66%. I am not sure whether it is the Home App issues or what. Sometime it doesn't  execute at all.

**Comment by kamaruszamanjufri** [comment]
After a few testing, I need to set to a different state before it can kick off.
If current state is at 33% speed, I need to change to 66% before the fan move.
If current state is at 66% speed, I need to change to 33%.
To set to 33% I need to change to 66% and then 33%.
