### ISSUE TITLE
what can I do?could not be initialised

### ISSUE THREAD

**Issue by mikeinblue** [bwp91/homebridge-ewelink#259]
When I Accessory Simulations for garagedoor.There are some 'Yellow Words':

**[eWeLink] [车库门] could not be initialised as Cannot read property 'context' of undefined at new deviceGarageOne (/homebridge/node_modules/homebridge-ewelink/lib/device/simulation/garage-one.js:51:80).**

Just like this:
![屏幕截图 2021-05-26 155437](https://user-images.githubusercontent.com/62834868/119624538-d91f7f00-be3b-11eb-92d8-6d90c38623d1.png)
This is the setup:
![Screenshot_20210526-161007__01](https://user-images.githubusercontent.com/62834868/119626108-74652400-be3d-11eb-90df-19a395547e49.jpg)

And if I delete the Sensor,then restart ,it works.
So what shall I do ? Thx a lot.

**Comment by bwp91** [comment]
Hi @mikeinblue 

Could you paste the full ewelink section of your homebridge config? Just remove your username and password.

Thanks

**Comment by bwp91** [comment]
Also which version of the plugin are you using?

**Comment by mikeinblue** [comment]
![CC6B2FE6-0885-4F3B-B4E3-0CD3863D9446](https://user-images.githubusercontent.com/62834868/119629000-3289ad00-be40-11eb-99bd-753b23c50f02.jpeg)
![850A9B92-8FFD-4A7B-8601-85EFD2D7A37A](https://user-images.githubusercontent.com/62834868/119629018-361d3400-be40-11eb-8f42-84618a813f5d.jpeg)


There are 2 screenshots,one is with sensor which can't work.The other is without sensor works well.
The plugin is 6.7.0

Thank you.

**Comment by bwp91** [comment]
Do you get that message in the log everytime you restart homebridge? or just the first time after adding the sensor to the config?

i mean, if you add the sensor, then restart homebridge twice, does the message still appear?

**Comment by mikeinblue** [comment]
I've checked it out.Every time the message appears.

**Comment by bwp91** [comment]
Can you use the homebridge-ui to update to a beta version of the plugin, v6.7.1-beta.0?

Let me know if this helps?

**Comment by bwp91** [comment]
Is this the sensor that you are using for the garage?

<img width="563" alt="Screenshot 2021-05-26 at 12 15 36" src="https://user-images.githubusercontent.com/43026681/119650818-2855b780-be1c-11eb-8f69-8a8e6bb285a7.png">

**Comment by mikeinblue** [comment]
maybe I found the key,I didn't use my main account,and I use the Id on the sensor,not the ewelink ID in the photo.
![Screenshot_20210526-192239](https://user-images.githubusercontent.com/62834868/119652628-eeef6d00-be58-11eb-90a4-2d77253c7528.jpg)

**Comment by mikeinblue** [comment]
how can I remove the existing accessory from the cache?

**Comment by bwp91** [comment]
> how can I remove the existing accessory from the cache?

In the homebridge settings you can use the remove single accessory from cache setting

**Comment by mikeinblue** [comment]
I solved that question.But there is a new one.
![Screenshot_20210526-200400__01__01](https://user-images.githubusercontent.com/62834868/119656815-b3a36d00-be5d-11eb-9b63-7c54c022103e.jpg)
![Screenshot_20210526-200125](https://user-images.githubusercontent.com/62834868/119656957-ea798300-be5d-11eb-9b52-639148effc56.jpg)
It keep reading...

**Comment by bwp91** [comment]
Check in the eWeLink app if the device is shown as 'offline'.

The online/offline state of any device is reported by eWeLink to the plugin.

The 'LAN Status' of a DW2 sensor will always be offline since the device does not support LAN control

**Comment by mikeinblue** [comment]
![IMG_20210526_201755](https://user-images.githubusercontent.com/62834868/119658233-7c35c000-be5f-11eb-9784-f5565d1f35db.jpg)
The device in app is ok.  But the garagedoor keep reading ,never stop.

**Comment by bwp91** [comment]
Can you physically open/close the garage door to activate the sensor and see if any messages appear in the homebridge log?

**Comment by mikeinblue** [comment]
There is no message in log. I am going to try vertion 6.6.0

**Comment by mikeinblue** [comment]
Also this issue. I think the switch can' tread the sensor's state.

**Comment by bwp91** [comment]
The issue seems to be that the plugin isn’t receiving any status updates from ewelink.

can you restart your router so the dw2 has to reconnect to the internet?

Once the plugin receives these status updates, it updates the garage door accessory accordingly.

If the plugin doesn’t receive these updates then the garage door accessory won’t change from its previous state.

**Comment by mikeinblue** [comment]
I tried , but doesn't work. Anyway, thank you so much.

**Comment by mikeinblue** [comment]
I turned on debug logging, hope that can help.
![Screenshot_20210527-000216__01](https://user-images.githubusercontent.com/62834868/119694004-689a5180-be7f-11eb-8ff1-99b552d00abf.jpg)

**Comment by bwp91** [comment]
The log entries that need to be appearing are 
`receiving update…….` from the `2377f6` device. 

But there don’t seem to be any in your logs.

The fact that ewelink is marking the device as “offline” must have something to do with this. 

Does the contact sensor accessory appear in your Home app?

**Comment by mikeinblue** [comment]
Yes, in fact there is always the contact sensor in my homekit, whatever I choose hide or not hide the sensor. And the state of the sensor will change to open if the garagedoor is open.

**Comment by mikeinblue** [comment]
I create a new account,and these device again. Now, it can read the sensor's state. But my switch still spin. The DW2's name is 'sensor'.
![E67C589B-FCBE-4137-B7C7-C064D606DFC3](https://user-images.githubusercontent.com/62834868/119769348-e47eb300-beec-11eb-8a5a-7eee89626191.jpeg)

**Comment by bwp91** [comment]
From your latest logs it’s doesn’t look like the switch has been setup as a garage simulation, please verify your config, as the logs should include that the switch is setup as a garage

**Comment by bwp91** [comment]
can you turn on debug logging again and restart the plugin and show me the logs?

**Comment by mikeinblue** [comment]
![2C1DCD87-24A2-4A6A-9040-5D5D58B4BE56](https://user-images.githubusercontent.com/62834868/119777708-2150a700-bef9-11eb-8455-1fcc0b4acdf4.jpeg)

**Comment by mikeinblue** [comment]
![A47C8E0D-084D-4F42-ABCA-3D2134EB6A58](https://user-images.githubusercontent.com/62834868/119778104-ab007480-bef9-11eb-9b97-dc99321f9ede.jpeg)
![94A86E3A-1AF0-4666-AFF5-3B7CAACCF18C](https://user-images.githubusercontent.com/62834868/119778105-acca3800-bef9-11eb-9966-c182276329ee.jpeg)

I think maybe the sensor's state isn't '1',so the switch keeps reading for the '1' state?

**Comment by bwp91** [comment]
Did you also update your config with the correct id of the sensor?

Can you show me your ewelink config again? (remove phone number + password!)

**Comment by mikeinblue** [comment]
![E485DE09-0353-4704-AB76-4BB1F87B194C](https://user-images.githubusercontent.com/62834868/119781853-10566480-befe-11eb-9545-8ac777e69a26.jpeg)
![A15F8E10-5A96-410E-ACAD-B175F8C513AD](https://user-images.githubusercontent.com/62834868/119782089-57445a00-befe-11eb-97ff-7a20b24f223f.jpeg)
Yes,the id is correct.The version is v6.7.1-beta.1.

**Comment by bwp91** [comment]
I have just published another beta, v6.7.1-beta.2

It might take a few minutes for it to appear available in the homebridge-ui but please update and let me know if it has fixed anything.

**Comment by mikeinblue** [comment]
Ok,I will update and try. thank you for your time.

**Comment by mikeinblue** [comment]
Thank you so much.It works perfectly.The state is correct , the sensor can hide now. Thank you for your time.

**Comment by bwp91** [comment]
Excellent 👍 got there in the end!
