### ISSUE TITLE
Sonoff TH16 on/off crashes and reboots Homebridge server

### ISSUE THREAD

**Issue by vkogan2005** [bwp91/homebridge-ewelink#260]
Each time I'm trying to on / off Sonoff TH16 relays it causes the crash and reboot of Homebridge server. 

Details of setup.
Homebridge (+ config-ui) 1.3.4 on RPi Buster, Node.js v14.17.0. 
The version of this plugin (homebridge-ewelink) v6.7.0. 
eWelink device is TH16 (4 of them, S20 sockets and RF relay are working properly). 

[5/26/2021, 9:01:56 PM] [eWeLink] [GardenLight (ESP_32D9B7)] current state [on].
[5/26/2021, 9:02:01 PM] [eWeLink] [GardenLight (ESP_32D9B7)] device update failed as WebSocket request was rejected by timeout (6000 ms). RequestId: 1622052115888 at PromiseController._handleTimeout (/usr/lib/node_modules/homebridge-ewelink/node_modules/promise-controller/src/index.js:172:19) at connectionWS.sendUpdate (/usr/lib/node_modules/homebridge-ewelink/lib/connection/ws.js:339:15).
[5/26/2021, 9:02:03 PM] TypeError: Cannot read property 'updateCharacteristic' of undefined
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-ewelink/lib/device/sensor-ambient.js:111:22)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
[5/26/2021, 9:02:03 PM] Got SIGTERM, shutting down Homebridge...
[5/26/2021, 9:02:08 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[5/26/2021, 9:02:13 PM] [HB Supervisor] Restarting Homebridge...

**Comment by bwp91** [comment]
Hi @vkogan2005 

Thanks for bringing this to my attention. You’ve highlighted an issue with the code that i can fix with regards to the “recovery” on the event of a web socket timeout. So this will fix the homebridge restart.

However, this will not fix the fact you are receiving the web socket timeout in the first place. This itself is often due to using a “secondary” ewelink account. Is this the case for you?

**Comment by vkogan2005** [comment]
> Hi @vkogan2005
> 
> Thanks for bringing this to my attention. You’ve highlighted an issue with the code that i can fix with regards to the “recovery” on the event of a web socket timeout. So this will fix the homebridge restart.
> 
> However, this will not fix the fact you are receiving the web socket timeout in the first place. This itself is often due to using a “secondary” ewelink account. Is this the case for you?

Yes, this is secondary eWeLink account, but other 20 devices are working properly. The issues are with TH16s only.

**Comment by bwp91** [comment]
Yes, most likely the S20s and the rf bridge are making use of lan control and in this case it doesn’t matter if you use a secondary account or not. but the TH devices need to use the cloud, and these web socket timeout messages can occur when using secondary ewelink accounts.

**Comment by vkogan2005** [comment]
Thank you for detailed explanation) 
So if the server will not reboot each time, it’s no problem it there will be these WS errors, as far as I understand.

**Comment by bwp91** [comment]
I have just published a beta, v6.7.1-beta.1, which should stop the homebridge restarts.

But yes, the web socket error messages will most likely continue to appear whilst you're using the secondary ewelink account. And if you try to control the device it'll most likely show the "no response".

For this plugin I have always advised to use your main ewelink credentials for everything to work properly.

**Comment by vkogan2005** [comment]
Thanks a lot, will try to use my primary account. 
Could you please describe how can I install beta version?

**Comment by bwp91** [comment]
For the beta version you can use the homebridge-ui option:

https://github.com/bwp91/homebridge-ewelink/wiki/Beta-Version#homebridge-ui

Let me know how you get on!

**Comment by vkogan2005** [comment]
It shows “no response” but works perfectly on my secondary account. Thanks a lot)

**Comment by vkogan2005** [comment]
> Yes, most likely the S20s and the rf bridge are making use of lan control and in this case it doesn’t matter if you use a secondary account or not. but the TH devices need to use the cloud, and these web socket timeout messages can occur when using secondary ewelink accounts.

Couple of days TH16 received the new firmware 3.5.0 and LAN control vas enabled for them. But the same error occurred: [eWeLink] [GardenLight (ESP_32D9B7)] device update failed as WebSocket request was rejected by timeout (6000 ms). Yes, I'm using secondary eWeLink account, same as fo S20s, but for S20s everything is working good. I thought that with LAN control enabled TH16s will work too)

**Comment by bwp91** [comment]
Please install the beta version of the plugin. I have tried to “guess” the protocol for the lan mode for the TH10/16.

I am waiting for the new firmware to appear available for my TH16 device, until then I cannot test the lan mode myself

**Comment by vkogan2005** [comment]
Thanks a lot, will try!)

**Comment by bwp91** [comment]
Please let me know how you get on!

**Comment by bwp91** [comment]
The newest beta version, 6.7.2-beta.2, has working lan mode for the TH10/16, I have confirmed it with my own device

**Comment by vkogan2005** [comment]
Thanks a lot! I had no chance yet to update due to lack of RAM for homebridge) There are NodeRED and homebridge services running together on my RPi 3 and it is very slow(
