### ISSUE TITLE
When renamed in ewelink - not propagated to HB

### ISSUE THREAD

**Issue by kremik** [bwp91/homebridge-ewelink#261]
### What issue do you have? Please be as thorough and explicit as possible.

When I rename device in ewelink it is not propagated to HomeBridge. 

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 

Homebridge + config-ui

* Which version of Homebridge/HOOBS do you have?

1.3.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi 4B

Node.js  v14.17.0
Npm v6.14.13

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?
v6.7.1

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

Sonoff Basic

### Please paste any relevant logs below.

```

```

**Comment by MoTechnicalities** [comment]
I'm not sure I would want such propagation.
I like the ability to name devices separately for each service, EWeLINK, HomeBridge, and HomeKit. I can use all three in different ways and for different reasons. It is only the Device ID that should propagate in my opinion.

**Comment by bwp91** [comment]
Hi @kremik 

This isn’t something that is wrong with the plugin, this is expected behaviour.

Renaming a device in ewelink app will not reflect in homebridge/homekit.

The way to get around this is to remove any accessory from the homebridge cache and when it is then re-added it will take such new name from the ewelink app.

**Comment by kremik** [comment]
Hello @bwp91,
I understand that it might be wanted behaviour. It is strange because it is taken from ewelink when you add the device. Clearing the cache might be good solution - but can you give me a hint how to do that? Thank you.

**Comment by bwp91** [comment]
You can use the homebridge-ui to remove a single accessory from the cache, this will do the job.

Or you can enter the device id in the “ignored devices” config option and restart homebridge, this will remove the accessory from the cache, then you can remove the device id and restart homebridge and the device will be readded with the updated name.

Do bear in mind that either way, the accessory will be added to homekit back in the default homekit room, and any scenes/automations involving this accessory will be removed.

**Comment by MrTomAsh** [comment]
Witam,

ten adres e-mail z racji na niesamowita ilosc wiadomosci typu SPAM zostaje WY��CZONY. 

Pozdrawiamy serdecznie!
