### ISSUE TITLE
Display as Fan for Single Channel Divice

### ISSUE THREAD

**Issue by MoTechnicalities** [bwp91/homebridge-ewelink#262]
* **Please explain your feature request in a one or two sentences.**
I would like to be able to display a single channel device such as the Sonoff Basic or MINI as a Fan under HomeKit.

* **Is your feature request related to a problem? Please describe.**
I happen to have a WIMO Smart Plug that I attached to one of my Fans. In HomeKit device settings I was am able to set it to display as a Switch, Outlet, or as a **_Fan_** (ON/OFF only) icon.
I am currently unable to do this with my Sonoff devices and figured it would make a nice addition to this plugin.

* **Any particular eWeLink devices that this relates to?**
Sonoff Basic, Sonoff MINI, etc.

* **Anything else?**
Thanks for the great support you give to this plugin. This plugin is a game changer!

**Comment by bwp91** [comment]
Hi @MoTechnicalities 

The option to show a *Switch* accessory as a *Light* or *Fan* should already be available in the Home app for you to choose.

Does the option not appear for you?

**Comment by MoTechnicalities** [comment]
It does not.
Referencing my Sonoff basic, I notice in the Plugin config that I can set as a switch or as an outlet, but not as a fan. Without selecting any options, HomeKit shows the device as a switch and in the HomeKit device settings, no option to change the icon is available.

**Comment by MoTechnicalities** [comment]
Oops. Now I feel bad. Cancel. I found the fan icon.

**Comment by bwp91** [comment]
The reason the config offers between switch and outlet is that the home app does not allow to change the type between these two.

However for both switch and outlet devices, home app lets you choose the type to a light or a fan.

Hope this makes sense!

**Comment by MoTechnicalities** [comment]
Got it! You can close this. Thanks!
