### ISSUE TITLE
The plugin isn't working as expected

### ISSUE THREAD

**Issue by ks-node** [bwp91/homebridge-ewelink#265]
### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 
2
iMac, MacOS 10.12.6, Safari 12.1.2

* Which version of Homebridge/HOOBS do you have?
latest

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
RPI

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?
latest

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.
The plugin settings doesn't stay in place, it scrolls itself!!!
One row per sec!

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
hi @ks-node are you using homebridge-ui or hoobs?

**Comment by ks-node** [comment]
I am using homebridge-ui, not hoobs.

However no problems with your plugin settings using Chrome Version 91.0.4472.77 (Official Build) (x86_64) on MacOS 10.12.6


Also I experience the same bad behavior on Homebridge that runs on Synology.

**Comment by ks-node** [comment]
![Screen Shot 2021-06-13 at 12 04 55 PM](https://user-images.githubusercontent.com/79835165/121803013-bfee3f00-cc3f-11eb-8053-8f7f34e60a04.png)
![Screen Shot 2021-06-13 at 12 04 53 PM](https://user-images.githubusercontent.com/79835165/121803014-c381c600-cc3f-11eb-9c69-a283cb4a63fd.png)


See the screenshots takes +- 2" apart

**Comment by ks-node** [comment]
![Screen Shot 2021-06-13 at 12 09 43 PM](https://user-images.githubusercontent.com/79835165/121803167-8833c700-cc40-11eb-85b3-9d3a49a88f99.png)
![Screen Shot 2021-06-13 at 12 09 47 PM](https://user-images.githubusercontent.com/79835165/121803168-8964f400-cc40-11eb-81ff-43cd295fcb40.png)

See 2 screenshots taken 4' apart

**Comment by bwp91** [comment]
This could be something to do with your version of Safari.

The homebridge-ui only supports the latest two major versions of Safari.

**Comment by ks-node** [comment]
Safari 12.1.2 is the latest I could use on my 10+ years old splendid (with SSD drive) iMac (the plugin is the only one that causes problems on this version of Safari)

**Comment by bwp91** [comment]
The plugin uses a custom-ui as opposed to most of the other plugins that don’t. Its most likely an issue with how homebridge-ui renders these custom-uis in this version of safari.

There’s not much I can suggest except to use Chrome when using the ewelink plugin settings.

It would be interesting to see if you had the same issue with another plugin that uses a custom-ui, for example homebridge-govee (one of my other plugins). More plugins that use this custom-ui are here:

https://www.npmjs.com/browse/depended/@homebridge/plugin-ui-utils

**Comment by ks-node** [comment]
The feedback: The same with homebridge-govee on Safari 12.1.2

**Comment by ks-node** [comment]
and no problem on iPad Pro (10.5") running iOS 14.6
