### ISSUE TITLE
Support for POWR3 (especially power monitoing!)

### ISSUE THREAD

**Issue by shanelilley** [bwp91/homebridge-ewelink#269]
* **Please explain your feature request in a one or two sentences.**
Support for new POWR3 device.
Higher power (25A) allows finally to monitor energy usage of typical household inverts/heaters/etc that require 20amp circuits

I suspect this will work by default (I actually dont have any POWR2 devices) ? 

* **Is your feature request related to a problem? Please describe.**

Nope! Just a shiny new device to add :-)

* **Any particular eWeLink devices that this relates to?**

https://itead.cc/product/sonoff-powr3/ 
POWR3 device

* **Anything else?**

**Comment by bwp91** [comment]
I’d be able to add support for the device if i have one shared to my ewelink account!

**Comment by bwp91** [comment]
Gonna close this issue and will track in #271
