### ISSUE TITLE
Support for 3 gang switch

### ISSUE THREAD

**Issue by P1xellat3d** [bwp91/homebridge-ewelink#27]
Hi guys,

I've recently picked up three gang switches and was wondering if these can be supported also.

Currently, the switches are showing up as 2 gang (with one missing.

Here is some information displayed within HomeKit:

- Manufacturer: T1 3C
- Model: PSF-B04-GL (seems to be the same model as the 2 gang?)
- Firmware: 2.0.1

Hoping someone could help with this please!

Thanks
Kevin

**Comment by samkni** [comment]
You can just jump into the index.js file on your pi etc and add the two lines of code to the three applicable areas (the model is already there, just copy/paste the code from another model and modify to suit) and restart homebridge for it to work
