### ISSUE TITLE
DUALR2 and POWR2 not working

### ISSUE THREAD

**Issue by bcyng** [bwp91/homebridge-ewelink#272]
### What issue do you have? Please be as thorough and explicit as possible.

The DUALR2 and POWR2 switches show in Homekit but do nothing when turned on and off. 
works fine using ewe link app.
devices show in my devices tab of the settings in Homebridge ui correctly.

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 

(1) Homebridge (+ config-ui)

* Which version of Homebridge/HOOBS do you have?

v1.3.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi
Node.js Version: v14.17.0
NPM Version: v6.14.13

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

homebridge-ewelink v6.8.0
yes has worked in previous versions. 

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

DUALR2
POWR2

### Please paste any relevant logs below.

```
[27/06/2021, 9:30:26 pm] [eWeLink] Initializing eWeLink platform...
[27/06/2021, 9:30:26 pm] [eWeLink] [v6.8.0] initialised. Syncing with eWeLink.
[27/06/2021, 9:30:26 pm] [eWeLink] Sending HTTP login() request.
[27/06/2021, 9:30:29 pm] [eWeLink] New HTTP API host received [us-apia.coolkit.cc].
[27/06/2021, 9:30:29 pm] [eWeLink] Sending HTTP login() request.
[27/06/2021, 9:30:31 pm] [eWeLink] Sending HTTP login() request.

```

**Comment by bwp91** [comment]
Hi @bcyng 

Please could you turn on debug logging in the plugin settings, and paste here any logs that appear if you try to control the switch.

This will give me a better idea of what’s going on.

Thanks!

**Comment by bcyng** [comment]
I have and there are no debug log lines. those I have pasted are all the log lines against ewe link

**Comment by bwp91** [comment]
Are there any logs after the 

```
[27/06/2021, 9:30:31 pm] [eWeLink] Sending HTTP login() request.
```

line? In particular the list of devices and one saying the plugin setup is complete?

**Comment by bcyng** [comment]
nope. that is the last ewe link log line. seems it stops there?

**Comment by bwp91** [comment]
For some reason the plugin seems to be stopping before fully initialising. This is why the devices don’t work in homekit.

So need to find the reason why the plugin isn’t initialising.

I assume the plugin has worked for you at some point before?

**Comment by bcyng** [comment]
yea it was working reliably on previous versions

**Comment by bwp91** [comment]
could you roll back to a previous version to see if it works again? and tell me which version number if it does work.
The final line of the logs should be

```
[eWeLink] ✓ Setup complete...
```

for a proper initialisation.

**Comment by bcyng** [comment]
so ive tried rolling back all the way to v5.5.1. 
get same issue. maybe its something else. could there be something else that's not allowing it to init?

this is my config:
```
{
            "name": "eWeLink",
            "username": "XXXX@XXXX",
            "password": "XXXXXX",
            "mode": "auto",
            "countryCode": "+61",
            "httpHost": "auto",
            "debug": true,
            "bridgeSensors": [
                {
                    "type": "motion"
                }
            ],
            "groups": [
                {
                    "type": "null",
                    "operationTime": 100
                }
            ],
            "platform": "eWeLink"
        },
```

**Comment by bwp91** [comment]
Could you change the `httpHost` line to the following and see if this helps?

```
"httpHost": "us-apia.coolkit.cc",
```

**Comment by bcyng** [comment]
doesn't seem to make any difference

**Comment by bwp91** [comment]
How about if you completely remove the lines:?

```
            "countryCode": "+61",
            "httpHost": "auto",
```

If that doesn't work, could we message on discord instead?

https://discord.gg/cMGhNtZ3tW

**Comment by bcyng** [comment]
Sure. Will have to do that. Will contact you when I have some time. Thanks for the support so far.

**Comment by bcyng** [comment]
So I fixed this by uninstalling the plugin and removing config and reinstalling. I think it was an issue with the config because I had to remove it and start again to make it work.
Also reset the password.

I think can close this.

**Comment by bwp91** [comment]
Glad you got it sorted.

Out of interest, now you have it working, do you have the `httpHost` and `countryCode` config items set?

**Comment by bcyng** [comment]
No these aren’t set. Only the username and password are set
