### ISSUE TITLE
Mosquito Killer does not appear to Homekit

### ISSUE THREAD

**Issue by malditavibora** [bwp91/homebridge-ewelink#276]
I have the Konesky Mosquito Killer in the ewelink app but it's not exposed to Homekit using Homebridge, I cannot see 
any log for this device, so it seems it is ignored by the plugin. I've configured the device as a light device according to the documentation.

Using Homebridge 1.3.4 and latest ewelink plugin version.

Raspberry Pi
Node.js v14.16.1
Npm v6.14.12

I just got the device so I do not know if this was happening in earlier versions.

**Comment by bwp91** [comment]
Hi @danixque 

Could you share the device to my ewelink account?

which continent do you live in?

**Comment by malditavibora** [comment]
Im from Spain. Which is your ewelink account?

**Comment by bwp91** [comment]
Please share to:

country code 44 (reino unido)
email bwp91@icloud.com

thanks!

**Comment by malditavibora** [comment]
done

**Comment by bwp91** [comment]
it has appeared in my homekit fine, and i was able to control it too.

I tried turning off and on and changed brightness via home app, it showed the new state in ewelink,

I also tried turning off and on and changed brightness in ewelink app, and the changes appeared in home app.

possible reasons for it not appearing:

* Are you using a shared ewelink account and haven't shared this device to it?
* Are you using plugin in LAN mode? If so, this device won't appear as it isnt LAN-supported

Can you show me your ewelink config? (Remove your email + password)

**Comment by malditavibora** [comment]
you are right, it seems the device was added to my shared account instead of my account, im going to
changed it and retry again.
By the other hand this is my config:

 {
            "name": "eWeLink",
            "username": "...",
            "password": "...",
            "mode": "auto",
            "debug": true,
            "disablePlugin": false,
            "lightDevices": [
                {
                    "label": "MosquitoKiller",
                    "deviceId": "..."
                }
            ],
            "platform": "eWeLink"
        },

**Comment by bwp91** [comment]
You should ideally have all your devices added to one ewelink account and use **the same** account for this plugin

**Comment by malditavibora** [comment]
Working now! 

thanks.

**Comment by bwp91** [comment]
great! don’t forget to unshare 😃
