### ISSUE TITLE
Plugin is being disabled

### ISSUE THREAD

**Issue by dkrushev** [bwp91/homebridge-ewelink#277]
### What issue do you have? Please be as thorough and explicit as possible.
Plugin is disabled. Error is log below.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
(1) Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
v1.3.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?
v7.1.0 Not sure when it started

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

### Please paste any relevant logs below.

[21/07/2021, 16:36:53] [eWeLink] Initializing eWeLink platform...
[21/07/2021, 16:36:53] [eWeLink] Initialising plugin v7.1.0 | Node v14.17.2 | HB v1.3.4...
[21/07/2021, 16:36:54] [eWeLink] ***** Disabling plugin. *****
[21/07/2021, 16:36:54] [eWeLink] ***** Cannot read property 'includes' of undefined at /usr/lib/node_modules/homebridge-ewelink/lib/index.js:230:47. *****
```

```

**Comment by bwp91** [comment]
Hi,
In your ewelink config i think you may have some entries for `outletDevices` that need to be moved to `singleDevices`.

if you need assistance please post your ewelink config here (remove username and password) and i can make the needed change.

Thanks!

**Comment by dkrushev** [comment]
Thanks, that was it!
