### ISSUE TITLE
Garage simulation for DUALR3 (motor mode)

### ISSUE THREAD

**Issue by clemencov** [bwp91/homebridge-ewelink#279]
### What issue do you have? Please be as thorough and explicit as possible.

I'm using a DUALR3 in Motor Mode to control a roller shutter (which is my garage door).

The only values it has for `showAsMotor` option are: `blind`, `door`, and `window`. Changing the device model in Multi Channel Devices section, and selecting a different Show As (simulation) doesn't affect it anyhow.

Is it possible to simulate a Garage Door with a DUALR3 in Motor Mode?

### Details of your setup.

I'm using Homebridge 1.3.4 with `homebridge-ewelink` 7.1.0

**Comment by bwp91** [comment]
Hi @clemencov 

You’re right, at the moment a DUALR3 in motor mode can only be shown as a door, window or blind.

These HomeKit accessory types offer %-based positioning, whereas a garage door type HomeKit accessory only offers “open” and “closed”. This is why I haven’t added the garage door open… yet.

It would be possible to show as a garage door, and when open is pressed, it sets the dualr3 to fully open, and when close is pressed then fully close the dualr3.

My query would be how to show the status of the garage if for example the position is 1% (ie *almost* closed… would this be considered “open”’ or “closed” in homekit. Would it be best to show this as open or closed?

**Comment by clemencov** [comment]
Thank you for your quick answer!

As for my needs, not having precise control and showing it in opened state when it isn't 100% closed will work just fine for me.

**Comment by bwp91** [comment]
Can you update to beta version 7.1.1-beta.2 - you should then see garage door in the list in the config.

Then restart the plugin and see if it works - it's untested code as I don't have a dualr3 setup at the moment!

**Comment by clemencov** [comment]
@bwp91, Just tested the beta version. Works like a charm. Thank you!

**Comment by bwp91** [comment]
In the current state, i’m not sure if you'll get a home app notification if the garage is opened/closed externally, i mean if the device is controlled via the ewelink app or any button you may have setup.

Is this something you could try and let me know whether you get a notification?

**Comment by clemencov** [comment]
When closed and opening it from eWeLink it says "Closing...".
When open and closing it from eWeLink it says "Opening...".

After clicking on it in Home App it changes back to the right state.

**Comment by clemencov** [comment]
When the garage gets opened from eWeLink I'm getting a Homekit notification as well.

**Comment by bwp91** [comment]
I've added a couple of fixes in new beta v7.1.1-beta.4

Could you install this and just verify it's still working okay?

Thanks!

**Comment by clemencov** [comment]
Sorry for not responding, one of the channels of my DUALR3 got broken, and I've just received a new one. Everything works as expected now. Thank you!
