### ISSUE TITLE
No Notification on iOS - Sonoff Door Sensor DW1 RF

### ISSUE THREAD

**Issue by thetatae** [bwp91/homebridge-ewelink#281]
### What issue do you have? Please be as thorough and explicit as possible.
Once the DW1 RF is triggered and the Homebridge receives the device status changed as shown below, it's expected to see the real-time notification on iOS Home App. However, most of the time the status on Home App remains unchanged or sometimes the alarm shows up on Home App with significant delay (about 1 minute). The notification is turned on on Home App already. I have other PIR motion detection on the same RF bridge set up and receive real-time notification nicely without any problem though.

**_[7/30/2021, 11:55:01 AM] [eWeLink] [Side Door Sensor] current state [triggered]._**
[7/30/2021, 11:55:20 AM] [eWeLink] [Smart Plug 1st Floor] current power [10.02W] current voltage [229.55V] current current [0.05A].
[7/30/2021, 11:55:20 AM] [eWeLink] [Smart Plug 1st Floor] current power [10.02W] current voltage [229.55V] current current [0.05A].
**_[7/30/2021, 11:55:35 AM] [eWeLink] [PIR MFl] current state [not triggered]._**
[7/30/2021, 11:56:01 AM] [eWeLink] [Side Door Sensor] current state [not triggered].

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
(1) Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
Homebridge v1.3.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
* Synology
* Node.js Version: v14.17.1
* NPM Version: v6.14.13

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?
I just added this DW1 RF on ewelink recently with homebridge-ewelink version 7.1.0

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.
Sonoff DW1 RF with RF bridge version 3.5.0

### Please paste any relevant logs below.

Configuration is displayed below      
      "bridgeSensors": [
                {
                    "label": "Side Door Sensor",
                    "fullDeviceId": "10006f33a0SW11",
                    "type": "contact",
                    "overrideLogging": "standard"
                }
            ],
```

```

**Comment by bwp91** [comment]
Hi,

Does an entry appear in the homebridge log immediately when this sensor is triggered? Does the accessory icon on the homebridge accessories page show as triggered in real time then not triggered again?

**Comment by thetatae** [comment]
> Hi,
> 
> Does an entry appear in the homebridge log immediately when this sensor is triggered? 
Yes immediately

Does the accessory icon on the homebridge accessories page show as triggered in real time then not triggered again?
When it is triggered the icon changed to OPEN in real time (but no notification on Home App) and then few seconds later the it's not triggered the icon remains OPEN for about 60 seconds then changed to CLOSE
I don't receive notification on Home App for all the process mentioned above though.

**Comment by bwp91** [comment]
and do you get notifications is the other sensor is triggered?

**Comment by thetatae** [comment]
I have 2 Sonoff RF PIR motion detectors connected to the same RF Bridge and another Sonoff WiFi DW2. All of these are on the same ewelink account. And I got the real time notification from these devices without any problem. 
I’m wondering why the only Sonoff RF DW1 is having the issue.

**Comment by bwp91** [comment]
the plugin doesn’t treat the dw1 any differently to other rf devices… and since it’s updating correctly in homebridge… makes me think perhaps it’s more likely to be some kind of network issue.

Can you try rebooting your raspberry pi (or whatever homebridge is running on) and then your apple home hub (ipad/appletv/homepod)?

Also do check you have the home app notifications turned on for this device (double check!)

Does any of this help?

**Comment by thetatae** [comment]
I removed cached accessories for ewelink devices and now DW1 notification starts working.
Thanks a lot for your help for your help.

**Comment by bwp91** [comment]
Glad you got this resolved!

**Comment by thetatae** [comment]
I noticed some unexpected behavior of DW1 on homebridge. Once the alarm triggers, the status of the DW1 remains “Open” for the duration of sensorTimeLength value. For example, if sensorTimeLength is at Default value. The triggered status will last for 60seconds no matter when you untrigger sooner or later than 60sec. Another example is when I modified sensorTimeLength to 5 sec, and the door will show “Open” for 5 sec no matter the door is close or not.
Is this the limitation of DW1 RF?
Is it possible to display the actual Open or Close status without the setting of sensorTimeLength?

**Comment by bwp91** [comment]
This is a limitation of the device (in fact any RF device). With the DW1, it only transmits to the RF bridge (and so to the plugin) when the two parts are separated. Not when they are put back together.

Meaning, the plugin never actually knows when the door/window is closed. It only knows when it has *just* been opened.

This is why the `sensorTimeLength` is used to display some sort of length of time for the home app icon. But it doesn't have any real function in the case of a DW1.

You may want to look into the DW2-Wifi or the Zigbee Contact Sensor.

Haven't heard the greatest reviews of the DW2, users have had more success with the zigbee contact sensor. But both these devices provide the plugin with a "contact detected" and a "contact not detected" status, hence removing the need for the `sensorTimeLength`.

Hope this helps

**Comment by thetatae** [comment]
I’ve actually been using DW2 WiFi and it works really great showing the actually contact and not-contact status perfectly in real time.
The thing is that I just found DW1 RF I bought long time back and never got a chance to try to set it up. Now it turns out I will actually have to put it back in my drawer again 😉
Thanks a lot for your clarification. I got it now!

Sent from my iPhone

On 31 Jul 2021, at 18:24, Ben ***@***.***> wrote:

﻿

This is a limitation of the device (in fact any RF device). With the DW1, it only transmits to the RF bridge (and so to the plugin) when the two parts are separated. Not when they are put back together.

Meaning, the plugin never actually knows when the door/window is closed. It only knows when it has just been opened.

This is why the sensorTimeLength is used to display some sort of length of time for the home app icon. But it doesn't have any real function in the case of a DW1.

You may want to look into the DW2-Wifi or the Zigbee Contact Sensor.

Haven't heard the greatest reviews of the DW2, users have had more success with the zigbee contact sensor. But both these devices provide the plugin with a "contact detected" and a "contact not detected" status, hence removing the need for the sensorTimeLength.

Hope this helps
