### ISSUE TITLE
Sonoff DC Switches stop displayed as Garage doors

### ISSUE THREAD

**Issue by vitaliy-kozlov** [bwp91/homebridge-ewelink#282]
Hi. After update to latest plugin version my switches no more displayed as garage doors,only as switches. Also I can't find settings to enable this feature anymore. Please suggest how to fix this. I really liked to use my sonoff devices as garage doors in HomeKit. 

HomebridgeUI latest
sonoff dc switch

**Comment by vitaliy-kozlov** [comment]
Oh,I missed that there are some changes in the device simulation settings. I added switches to configuration file with "showAs" parameter,also enabled "no response" fix cleared accessories and viola - garage doors available again.Sorry for confusion. Please close issue :-)

**Comment by bwp91** [comment]
Yep there were some config changes last version, hopefully making the setup more straightforward. Glad you’re sorted 👍🏻
