### ISSUE TITLE
Problem in homekit "accessory not responding" 

### ISSUE THREAD

**Issue by motogon** [bwp91/homebridge-ewelink#284]
### What issue do you have? Please be as thorough and explicit as possible.

Problem in homekit "accessory not responding" 
In ewelink apps the switch is available and working

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
3

* Which version of Homebridge/HOOBS do you have?

HOOBS 3.3.12

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Linux Ubuntu 20.04.2 LTS 
Node Version  14.17.2

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?
8.0.2

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.
![IMG_5267](https://user-images.githubusercontent.com/12997195/129597828-35fa2fa8-9bb8-4dfe-9b89-72ddae7eb48e.PNG)

### Please paste any relevant logs below.

```
hoobs -d  |grep "eWeLink"
[16.08.2021, 19:34:13] Registering platform 'homebridge-ewelink.eWeLink'
[eWeLink] Initializing eWeLink platform...
[eWeLink] Initialising plugin v8.0.2 | Node v14.15.1 | HB v1.3.4 | HOOBS v3...
[eWeLink] Config entry [debugReqRes] is unused and can be removed.
[eWeLink] Config entry [sensorTimeLength] is unused and can be removed.
[eWeLink] Config entry [sensorTimeDifference] is unused and can be removed.
[eWeLink] Config entry [valveTimeLength] is unused and can be removed.
[eWeLink] Config entry [hideTHSwitch] is unused and can be removed.
[eWeLink] Config entry [hideZBLDPress] is unused and can be removed.
[eWeLink] Config entry [disableHTTPRefresh] is unused and can be removed.
[eWeLink] Config entry [inUsePowerThreshold] is unused and can be removed.
[eWeLink] Config entry [lowBattThreshold] is unused and can be removed.
[eWeLink] Config entry [resetRFBridge] is unused and can be removed.
[eWeLink] Plugin initialised. Setting up accessories....
[eWeLink] Sending HTTP login() request.
[eWeLink] Web socket host received [eu-pconnect6.coolkit.cc].
[eWeLink] Sending WS login request.
[eWeLink] LAN discovery starting.
[eWeLink] WS login successful.
[eWeLink] LAN discovery complete.
[eWeLink] LAN monitoring started.
[eWeLink] [Кухня] initialising with options {"logging":"debug","showAs":"default"}.
[eWeLink] [Кухня] initialised and found locally with IP [192.168.3.12].
[eWeLink] [Спальня с балконом] initialising with options {"brightnessStep":1,"logging":"debug"}.
[eWeLink] [Спальня с балконом] initialised and LAN mode unavailable as not discovered/supported.
[eWeLink] ✓ Setup complete. This plugin has been made with ♥ by bwp91 from the UK!
[eWeLink] [Кухня] receiving update {"switch":"on","online":true,"updateSource":"LAN"}.
[eWeLink] [Кухня] current state [on].

```

**Comment by bwp91** [comment]
Hi @motogon 

One of the things I added to v8 of the plugin was showing an accessory as 'No Response' if it is reported offline by eWeLink. It will also show as no response while the plugin is restarting. The status will be removed when the accessory comes back online but sometimes you need to restart the Home app for the status to be updated there.

You can see in the logs when eWeLink reports an accessory as online/offline with messages like

```
[eWeLink] [device] has been reported [online/offline].
```

You can also disable this with 'Disable No Response' option in 'Optional Settings':

<img width="637" alt="Screenshot 2021-08-17 at 07 36 46" src="https://user-images.githubusercontent.com/43026681/129675902-e798f786-bbe5-4e66-95a5-ecd618b5d3f2.png">

An accessory will also be shown as 'No Response' if it is controlled through the Home app but the command fails. In this case the 'No Response' will be removed after a couple of seconds, but a home app restart may be required to remove the status there.

If none of these situations apply, then let me know so I can look into this further.

**Comment by motogon** [comment]
hi @bwp91 

enabled the 'Disable No Response' option
Rebooted the hoobs. 

log at the moment of starting HOOBS :

17.08.2021, 11:48:34 [eWeLink] LAN monitoring started.
17.08.2021, 11:48:34 [eWeLink] [Kitchen] initializing with options {"logging": "standard", "showAs": "default"}.
17.08.2021, 11:48:34 [eWeLink] [Kitchen] has been reported [offline] via WS.
17.08.2021, 11:48:34 [eWeLink] [Kitchen] [Kitchen] initialized and LAN mode unavailable as not discovered/supported.

The problem remained, in applekit the switch is in 'Disable No Response' status 

In apps eWeLink this switch is available and working 

On my home network, the switch is pinged 

In the logs I see the status of the switch changes , when I turn it on and off from eWeLink apps.

17.08.2021, 11:56:19 [eWeLink] [Kitchen] current status [on].
17.08.2021, 11:57:32 [eWeLink] [Kitchen] current state [off].

log in debug mode : 

17.08.2021, 11:59:44 [eWeLink] Web socket host received [eu-pconnect3.coolkit.cc].
17.08.2021, 11:59:45 [eWeLink] Sending WS login request.
17.08.2021, 11:59:45 [eWeLink] LAN discovery starting.
17.08.2021, 11:59:45 [eWeLink] WS login successful.
17.08.2021, 11:59:48 [eWeLink] LAN discovery complete.
17.08.2021, 11:59:48 [eWeLink] LAN monitoring started.
17.08.2021, 11:59:48 [eWeLink] [Kitchen] initializing with options {"logging": "debug", "showAs": "default"}.
17.08.2021, 11:59:48 AM [eWeLink] [Kitchen] initialized and found locally with IP [192.168.3.12].
17.08.2021, 11:59:50 [eWeLink] ✓ Setup complete. Join the plugin's Discord community! https://discord.gg/cMGhNtZ3tW
17.08.2021, 12:02:20 [eWeLink] [Kitchen] receiving update {"switch": "on", "online":true, "updateSource": "LAN"}.
17.08.2021, 12:02:20:20 [eWeLink] [Kitchen] current state [on].
17.08.2021, 12:02:30 AM [eWeLink] [Kitchen] receiving update {"switch": "off", "online":true, "updateSource": "LAN"}.
17.08.2021, 12:02:30 [eWeLink] [Kitchen] current state [off].

**Comment by bwp91** [comment]
Do you have other plugins installed in HOOBS? Are you getting the no response for other plugin accessories?

From the ewelink plugin, are you having the same issue with the `Спальня с балконом` accessory?

I see `17.08.2021, 11:48:34 [eWeLink] [Kitchen] has been reported [offline] via WS.`... is this device blocked from accessing the internet? Or have times when it disconnects from the internet?

**Comment by motogon** [comment]
Yes, there is also a dimmer ( Спальня с балконом ) that works correctly. 

the switch ( Кухня ) with which there is a problem has access to the internet (otherwise it would not be available in the eWeLink apps)
The monitoring of the entire network is running on zabbix , there have been no reports of loss of connection to the switch ( Кухня ) in the entire time.

**Comment by motogon** [comment]
ping 192.168.3.12
PING 192.168.3.12 (192.168.3.12): 56 data bytes
64 bytes from 192.168.3.12: icmp_seq=0 ttl=128 time=17.065 ms
64 bytes from 192.168.3.12: icmp_seq=1 ttl=128 time=4.416 ms
64 bytes from 192.168.3.12: icmp_seq=2 ttl=128 time=152.943 ms
64 bytes from 192.168.3.12: icmp_seq=3 ttl=128 time=70.124 ms
64 bytes from 192.168.3.12: icmp_seq=4 ttl=128 time=3.128 ms
64 bytes from 192.168.3.12: icmp_seq=5 ttl=128 time=2.569 ms
64 bytes from 192.168.3.12: icmp_seq=6 ttl=128 time=2.724 ms
64 bytes from 192.168.3.12: icmp_seq=7 ttl=128 time=1.779 ms
64 bytes from 192.168.3.12: icmp_seq=8 ttl=128 time=1.930 ms
64 bytes from 192.168.3.12: icmp_seq=9 ttl=128 time=1.696 ms
64 bytes from 192.168.3.12: icmp_seq=10 ttl=128 time=1.697 ms
64 bytes from 192.168.3.12: icmp_seq=11 ttl=128 time=2.542 ms
64 bytes from 192.168.3.12: icmp_seq=12 ttl=128 time=1.902 ms
64 bytes from 192.168.3.12: icmp_seq=13 ttl=128 time=1.620 ms
64 bytes from 192.168.3.12: icmp_seq=14 ttl=128 time=1.960 ms
64 bytes from 192.168.3.12: icmp_seq=15 ttl=128 time=2.275 ms
64 bytes from 192.168.3.12: icmp_seq=16 ttl=128 time=1.721 ms
64 bytes from 192.168.3.12: icmp_seq=17 ttl=128 time=1.974 ms
64 bytes from 192.168.3.12: icmp_seq=18 ttl=128 time=1.725 ms
64 bytes from 192.168.3.12: icmp_seq=19 ttl=128 time=2.764 ms
64 bytes from 192.168.3.12: icmp_seq=20 ttl=128 time=1.650 ms
64 bytes from 192.168.3.12: icmp_seq=21 ttl=128 time=1.665 ms
64 bytes from 192.168.3.12: icmp_seq=22 ttl=128 time=1.755 ms
64 bytes from 192.168.3.12: icmp_seq=23 ttl=128 time=1.696 ms
64 bytes from 192.168.3.12: icmp_seq=24 ttl=128 time=1.786 ms
64 bytes from 192.168.3.12: icmp_seq=25 ttl=128 time=1.742 ms
64 bytes from 192.168.3.12: icmp_seq=26 ttl=128 time=1.695 ms
^C
--- 192.168.3.12 ping statistics ---
27 packets transmitted, 27 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 1.620/10.761/152.943/30.786 ms

**Comment by motogon** [comment]
You were right, the problem was in the internet access, in the nat table for the ip of the problem switch. Rebooted nat . The switch is now available in applekit. 

Thanks for the help. 

ps when the connection method is AUTO, if the WAN method is not available there is no automatic switch to the LAN method?

**Comment by bwp91** [comment]
> which there is a problem has access to the internet (otherwise it would not be available in the eWeLink apps)

The eWeLink app also tries to use LAN mode so even if the device is blocked/disconnected from the internet, if the ewelink app is running on a device connected to the same network then it will be able to control the device.

> ps when the connection method is AUTO, if the WAN method is not available there is no automatic switch to the LAN method?

In auto mode, the plugin will always attempt to control via LAN first. If this fails then it will revert to WAN.

I'm glad you found the issue -- I was starting to really wonder what the issue was!
