### ISSUE TITLE
Add support for new device (Woolley Wlan Switch Smart Home)

### ISSUE THREAD

**Issue by hashbou** [bwp91/homebridge-ewelink#287]
* **Please explain your feature request in a one or two sentences.**

I have bought the "Woolley Wlan Switch Smart Home DIY Modul mit on/off Taster" but it is not working with this plug-in. The log messages show "[Gerät378c0c] is not supported, do create a GitHub issue with the following info:"

Link: https://www.amazon.de/gp/product/B097M87VJH/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1 

* **Is your feature request related to a problem? Please describe.**

The mentioned device seems not being supported.

* **Any particular eWeLink devices that this relates to?**

"Woolley Wlan Switch Smart Home DIY Modul mit on/off Taster"

* **Anything else?**

The full log message. 

```json
[Gerät378c0c] is not supported, do create a GitHub issue with the following info:
[138] {
  "bindInfos":{
    "gaction":[
      "{UUID}_ewelinkGoogleHome"
    ]
  },
  "version":8,
  "rssi":-54,
  "fwVersion":"1.0.0",
  "switches":[
    {
      "switch":"off",
      "outlet":0
    },
    {
      "switch":"off",
      "outlet":1
    },
    {
      "switch":"off",
      "outlet":2
    },
    {
      "switch":"off",
      "outlet":3
    }
  ],
  "configure":[
    {
      "startup":"off",
      "outlet":0
    },
    {
      "startup":"off",
      "outlet":1
    },
    {
      "startup":"off",
      "outlet":2
    },
    {
      "startup":"off",
      "outlet":3
    }
  ],
  "pulses":[
    {
      "pulse":"off",
      "switch":"off",
      "outlet":0,
      "width":0
    },
    {
      "pulse":"off",
      "switch":"off",
      "outlet":1,
      "width":0
    },
    {
      "pulse":"off",
      "switch":"off",
      "outlet":2,
      "width":0
    },
    {
      "pulse":"off",
      "switch":"off",
      "outlet":3,
      "width":0
    }
  ],
  "remoteCtrlList":[
    {
      "outlet":0,
      "addr":[]
    },
    {
      "outlet":1,
      "addr":[]
    },
    {
      "outlet":2,
      "addr":[]
    },
    {
      "outlet":3,
      "addr":[]
    }
  ],
  "lightScenes_0":[],
  "lightScenes_1":[],
  "lightScenes_2":[],
  "lightScenes_3":[],
  "sledOnline":"on",
  "ssid":"---",
  "bssid":"---"
}
```

**Comment by bwp91** [comment]
Hi @hashbou 

Does this device have just one channel that you can control?

Thanks

**Comment by bwp91** [comment]
Please update to v8.2.0 of the plugin. This device should start working.

**Comment by hashbou** [comment]
Hey, wonderful thank you it works like a charm!
Kind regards
Hicham
