### ISSUE TITLE
King q1 - garage door

### ISSUE THREAD

**Issue by carlosptf** [bwp91/homebridge-ewelink#288]
* **Please explain your feature request in a one or two sentences.**

any predictions for king-q1? today it is misrecognized as a window curtain.

* **Is your feature request related to a problem? Please describe.**

* **Any particular eWeLink devices that this relates to?**

King-Q1 - garage door

* **Anything else?**

**Comment by bwp91** [comment]
Hi @carlosptf 

Can you share a webpage link to the device you have? I have never heard of this device.

If it is like the KingArt King-Q4 then this device is a blind/curtain type.
https://www.globalsources.com/Smart-curtain/WiFi-roller-shutter-switch-curtain-blinds-switch-1174334804p.htm#1174334804

**Comment by carlosptf** [comment]
Hi, here on EWeLink it is listed as model king-Q1

https://a.aliexpress.com/_mLM6Dar
Em 23 de ago. de 2021 04:27 -0300, Ben ***@***.***> escreveu:

**Comment by bwp91** [comment]
And can you set the position anywhere between 0 and 100% or is just OPEN or CLOSED?

**Comment by carlosptf** [comment]
both, in EWeLink it lets you choose between 0% and 100%, but I only use the closed and open option. when I put, for example, 10%, every garage door is open
Em 23 de ago. de 2021 11:08 -0300, Ben ***@***.***> escreveu:

**Comment by bwp91** [comment]
This should be possible. With these garage door devices for security reasons, I consider 0% to be closed and 1-100% to be open, this is how the state would be relayed in homekit. 

I will get back to you…

**Comment by bwp91** [comment]
HomeKit does not allow for %-based positioning for garages, it is simply OPEN or CLOSED.

**Comment by bwp91** [comment]
Or, with the latest beta of the plugin you can change the accessory type from a window blind to a door (separate homekit accessory type from garage door), which allows for %-based positioning. I will still work on a garage door implementation and let you know when ready to test

**Comment by carlosptf** [comment]
I installed the beta version, but it doesn't work. I believe it should be an open and closed implementation only, (in Ewelink the % does not work). The difference of the KING - Q1 is that it has an open and closed sensor.
Thank you for your support ;)
Em 23 de ago. de 2021 12:32 -0300, Ben ***@***.***>, escreveu:

**Comment by bwp91** [comment]
I am unsure how ewelink would report the status of the sensor to the plugin.

I would need you to share the device to my ewelink account... at a time when you're home obviously since it's a garage door... and for you to let me open/close the door a few times so I can see how the sensor state is reported to the plugin.

Would you be happy to do this? Happy to message on discord if it's easier.

https://discord.gg/cMGhNtZ3tW

**Comment by bwp91** [comment]
> I installed the beta version, but it doesn't work.

You would need to configure the device to show as a different accessory type...

<img width="698" alt="Screenshot 2021-08-24 at 09 04 15" src="https://user-images.githubusercontent.com/43026681/130580304-26a04040-2f0b-4687-a95d-6e2929153d4b.png">
