### ISSUE TITLE
Use temperature value as an automation start

### ISSUE THREAD

**Issue by cristian5th** [bwp91/homebridge-ewelink#289]
* **Please explain your feature request in a one or two sentences.**
Hello.
Is it possible to use the temperature value of a Sonoff sensor as an automation start within the Home app?
The idea is to be able to launch some automation when the measured temperature is higher or lower to some threshold.

* **Is your feature request related to a problem? Please describe.**
No problem.

* **Any particular eWeLink devices that this relates to?**
This would be applicable at least to the TH10/16.

* **Anything else?**
Thank you for this magnificent plug-in!!

**Comment by bwp91** [comment]
Hi,

HomeKit automations triggered by temperature values are possible in HomeKit, however not from the Home app.

You can use a different HomeKit app like the Eve app (this is what I use) to create such automations:

https://www.evehome.com/en/eve-app

You don't need to own an Eve accessory to use their app!

**Comment by cristian5th** [comment]
Thank you. I will give it a try!
