### ISSUE TITLE
Issue in Homebridge

### ISSUE THREAD

**Issue by sballoz** [bwp91/homebridge-ewelink#291]
### What issue do you have? Please be as thorough and explicit as possible.
[07/09/2021, 11:44:22] [eWeLink] An error occurred during http login().
[07/09/2021, 11:44:22] [eWeLink] An error occurred during http login().
[07/09/2021, 11:44:22] [eWeLink] ***** Disabling plugin. *****
[07/09/2021, 11:44:22] [eWeLink] ***** password error! [10001]. *****

but the password is correct
I have noticed that if I try to connect to Ewelink web it asks me to upgrade to a paid account

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

Homebridge CLI

* Which version of Homebridge/HOOBS do you have?

Last 1.3.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry pI3
Node.js | v14.17.6
num v6.14.15

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

8.3.1

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

Sono Mini

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @sballoz 

Try changing your password in the ewelink app then using the new password in the config.

This has nothing to do with whether you have a paid account or not.

**Comment by sballoz** [comment]
it worked like a charm!
Thanks a lot
