### ISSUE TITLE
Meaning of the response.power.state field on a device in the internal API

### ISSUE THREAD

**Issue by mike-lerch** [bwp91/homebridge-ewelink#292]
I've enabled the internal API and am trying to query a single device like this: 

```
% curl --user "<redacted>" --basic http://<redacted>:8582/get/10003cc444SWX

{"success":true,"response":{"status":{"wan":true,"lan":true,"ip":"<redacted>"},"services":["switch","power"],"switch":{"state":"on"},"power":{"state":"010004010500010407010408010500010503010504010504010504010503010501010500010504010401010507010509010508010506010508010600010600010601010601010600010507010508010602010603010603010603010605010401010601010604010607010606010606010607010600010603010608010607010608010608010700010608010607010700010702010702010702010700010700010609010704010705010704010706010706010701010609010702010705010707010707010702010701010703010706010706010704010707010707010706010704010709010708010707010706010707010705010702010702010702010704010706010706010703010702010708010709010608010708010707010703010703010701010705010706010704"}}}
```

How do I decipher that long string of numbers? It seems to consistently be 400 characters but I do not see how to decode them.

**Comment by bwp91** [comment]
Hi, this is raw power data per day in kWh for the last 100 days, it's exactly how it is reported to the plugin by ewelink.

I’ve found an example on how to decode it in js:
https://github.com/skydiver/ewelink-api/blob/5a07f6b6152d603c71266012177cc4b47d533bf9/src/parsers/parsePowerUsage.js#L8

i haven’t tested this myself, i might give it a try in a minute!

**Comment by bwp91** [comment]
Ah, so the code example only gives power usage for the current month. But it's helped me understand how the raw data works, actually it seems to be 600 characters in length, corresponding to 6 characters each for the last 100 days.

Using your example data, the first 6 characters correspond to **today** - `010004`, this is split into three parts, `01` `00` `04`, take the last digit from each and this leads to a daily consumption for today of `1.04`kWh. The next six digits in the data correspond to yesterday, `010500` -> `1.50`kWh. And so on for the last 100 days.
