### ISSUE TITLE
Issue on garage door response

### ISSUE THREAD

**Issue by hjg2005** [bwp91/homebridge-ewelink#294]
### What issue do you have? Please be as thorough and explicit as possible.

My garage door switch when operated from home kit is opening then stop responding and reflecting the actual garage door status, I visited other post here and try whats suggested but not working. Its still operated normally when operated from ewelink app.
I used 
Note: I used showas function to change it from switch to garage door
Also i used my main user login as suggested.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

Homebridge ui-x

* Which version of Homebridge/HOOBS do you have?

4.41.2

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Homebridge on Raspberry 3+

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

8.3.3

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

Simple garage door with sensor, door condition reflected as switch status on or off (off mean close and on mean open)

WiFi Smart Switch Garage Door Controller Compatible Garage Door Opener Smart Phone Remote Control APP "eWeLink" Timing Function

https://a.aliexpress.com/_mt18EgJ

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi,

Can you try setting the device model to Eachen GD-DC5 and see if this works better? Looks like a similar product.

<img  alt="Screenshot 2021-09-20 at 15 33 51" src="https://user-images.githubusercontent.com/43026681/134020712-aa78bcc1-5278-44aa-bc40-64624908ec2c.png">

Let me know if this works better...

**Comment by hjg2005** [comment]
I’ve tried but same problem.

**Comment by hjg2005** [comment]
One thing more, when I operate the switch using ewelink app, the home app notification appear correctly.

**Comment by bwp91** [comment]
Can you explain again exactly what’s happening?
So you use home app to open or close the garage door… and then it immediately shows no response? or after a few seconds? does the physical device open/close? do any messages appear in the homebridge log showing any signs of error?

**Comment by hjg2005** [comment]
I will explain in more detail.
If I open the garage door from home app, the door will open and the status will show open garage door.
If close it again the door is not closing (door will no longer respons) but door status in home app will show close ( door still open)
If I open the door again from home app, again the door will not respons, but door status in home app will show door is open

in the other side if I use ewelink app to open or close the door will response normally and door status in home app will change but will not match the actual door condition as its already not syncronized.

the ewelink switch is equipped with magntic switch, which will change the switch value it self to on or off, off mean door is close and on mean door is open. The switch having .5 sec inching in firmware it self and cant be changed.

and there is no error in log

Thanks
![IMG_0029](https://user-images.githubusercontent.com/76535462/134215710-ce619fa8-25f5-4dd8-badc-4880d8cb7b15.png)

**Comment by bwp91** [comment]
For the Eachen GD-DC5 devices, the status is reported by ewelink to the plugin as follows:

`switch:on` means the door is opening/opened/closing
`switch:off` means the door is closed

It also reports a very quick off->on->off literally as the door is almost closed and is flicking past the magnetic sensor and the plugin takes this into account.

The plugin SENDS a

`switch:on` to open the door, and
`switch:off` to close the door.

When opening the door, the plugin will use the defined operation time in the config to wait until changing from OPENING to OPEN.

When closing the door, the plugin will show CLOSING until the 'flicker' I described above is reported by ewelink to the plugin and will then show as CLOSED.

I assumed that this device would be identical to the GD-DC5, even though it has a different model.

Do you think this device has a different method of working?

**Comment by bwp91** [comment]
have you set an operation time in the config? this is vital for these devices to work properly

**Comment by hjg2005** [comment]
Thanks, i think its operating exactly as you said.
However the on/off condition of the switch will be changed base on magnetic switch to refect the actual condition of the door, I am not sure if the plug in read this to reflict the door condition

i did not set a time with this device type, i will try to set once I back home and let you know the result.

**Comment by bwp91** [comment]
I think you should time how long your door closes accurately and set this as the operation time, and see if this improves things.

let me know!

**Comment by hjg2005** [comment]
I had set a time for opening and closing but still same issue.

I am just wondering, if the plug in will read the switch status and reflect this as door status, then why its changing the door status to close while switch status in ewelink is still open

**Comment by bwp91** [comment]
With the door initially closed, can you turn on plugin debug mode via the plugin settings, and restart.

Then use the ewelink app to open the door fully and then close the door fully.

And post here all the logs that appear from opening and closing

**Comment by hjg2005** [comment]
here is what I get, please note that door initial condition is closed, when I open from ewelink app the log shows closed and when I close from ewelink app log shows open
![IMG_0031](https://user-images.githubusercontent.com/76535462/134351084-22dc58b6-4460-47ae-94d7-bc88407f6739.jpeg)

**Comment by bwp91** [comment]
But there should be some extra logging for the updates that the plugin receives for this device?

Are you able to copy and paste the logs rather than a screenshot?

Can you copy and paste **all** the logs that appear from restarting the plugin?

Thanks

**Comment by hjg2005** [comment]
This a full log after restarting the server
[homebridge.log](https://github.com/bwp91/homebridge-ewelink/files/7211051/homebridge.log)

**Comment by bwp91** [comment]
The device isn’t being setup correctly as the eachen type model, can you also post your ewelink config here (remove your username and password)

**Comment by hjg2005** [comment]
There is the setting
![IMG_5234](https://user-images.githubusercontent.com/76535462/134354420-c38ee557-697e-45bb-8842-0
![IMG_5235](https://user-images.githubusercontent.com/76535462/134354495-72abc93f-bbe4-4b7f-9e1c-3340ca04a3e2.jpeg)
278324d4ca7.png)

![IMG_5236](https://user-images.githubusercontent.com/76535462/134354546-b7825646-f36d-4548-ac82-b5315fdb3199.png)

Please note inching is set off but value is .5 sec, but the device did actually inch as I think this some thing set embedded in the firmware or hardware ( I can here clearly the relay sound open and close)

**Comment by bwp91** [comment]
Sorry I should have been clearer, i mean the ewelink section of your homebridge config

**Comment by hjg2005** [comment]
Sorry, I thought you mean ewelink app, here is

![IMG_0032](https://user-images.githubusercontent.com/76535462/134355698-ee71fc7b-e448-4609-bbee-9c58526658c3.png)
![IMG_0033](https://user-images.githubusercontent.com/76535462/134355770-bf30982b-069a-4799-ba8a-5b92c6005dc6.png)

**Comment by bwp91** [comment]
What I think you might need to do, is change the model back to sonoff basic, and then in the "show as" field that appears, set this back to "None". Then change the model back to GD-DC5. Then save and restart.

What needs to show is your current log line when the plugin initialises

```
[22/09/2021, 16:26:25] [eWeLink] [Garage door ] initialising with options {"logging":"standard","operationTimeDown":120,"operationTimeUp":115,"showAs":"garage"}.
```

needs to be at the end
```
"showAs":"garage_eachen"
```

**Comment by hjg2005** [comment]
Oh, that was very helpful, know its working just fine.

really thankfully for your help.

**Comment by bwp91** [comment]
This is good news! I hadn’t thought that this could be the problem here!

**Comment by hjg2005** [comment]
Many thanks for your patient, this was really helpful.
