### ISSUE TITLE
S20 Plug doesn’t work

### ISSUE THREAD

**Issue by henkyfoo** [bwp91/homebridge-ewelink#295]
* **Please explain your feature request in a one or two sentences.**

The plug doesn't work at all in the homekit,
It does not respond to my command both home app or voice command through homepod 

* **Is your feature request related to a problem? Please describe.**

* **Any particular eWeLink devices that this relates to?**
S20 plug

* **Anything else?**

The log

eWeLink BridgeERROR[eWeLink Bridge 1FA8@On] The write handler for the characteristic 'On' on the accessory 'Device487411' was slow to respond!
27/09/2021, 9:39:28 PMeWeLink BridgeeWeLinkWARNING[Device487411] device update failed as WebSocket request was rejected by timeout (6000 ms). RequestId: 1632753562718 at PromiseController._handleTimeout (/var/lib/hoobs/ewelinkbridge/node_modules/promise-controller/src/index.js:172:19) at connectionWS.sendUpdate (/var/lib/hoobs/ewelinkbridge/node_modules/homebridge-ewelink/lib/connection/ws.js:346:15).

**Comment by bwp91** [comment]
Are you by chance using separate ewelink credentials from your main account?

**Comment by henkyfoo** [comment]
No, i'm using my main acc.
Everything worked fine yesterday and it just suddenly stop doing whatever it did

**Comment by bwp91** [comment]
have you tried restarting homebridge?

**Comment by henkyfoo** [comment]
Yap that was the first thing i do

**Comment by bwp91** [comment]
I assume this didn’t work? Do you have other devices that are or aren’t working? Is the device itself actually plugged in and online, like, can you control it via the ewelink app?

**Comment by henkyfoo** [comment]
Yap it didn't work.
I have quite a lot of devices such as S26 plug and tons of R2 breaker
All working fine and flawless

And yeah i could control it via ewelink app

Should i do a reset on this plug?

**Comment by bwp91** [comment]
It's not shared from another ewelink account into the account you use for the plugin? This

```
WebSocket request was rejected by timeout (6000 ms)
```

error is normally due to the homebridge ewelink credentials not being the "owner" of the device. This error can also appear when the device is not connected to wifi.

Yes, do try resetting it to see if this works...

**Comment by henkyfoo** [comment]
No i am only using 1 account for my ewelink

Let me try resetting this tonight and i'll get back to you

**Comment by henkyfoo** [comment]
I tried resetting
It worked once and then go into error again

Here is the new log

ERROR[eWeLink Bridge 1FA8@On] The write handler for the characteristic 'On' on the accessory 'Device487411' was slow to respond!
eWeLink BridgeeWeLinkWARNING[Device487411] device update failed as WebSocket request was rejected by timeout (6000 ms). RequestId: 1632837584097 at PromiseController._handleTimeout (/var/lib/hoobs/ewelinkbridge/node_modules/promise-controller/src/index.js:172:19) at connectionWS.sendUpdate (/var/lib/hoobs/ewelinkbridge/node_modules/homebridge-ewelink/lib/connection/ws.js:346:15).

**Comment by bwp91** [comment]
Do you know if your device supports lan mode?

**Comment by henkyfoo** [comment]
I think LAN is not supported

Here's the log regarding LAN

[Device487411] initialising with options {"inUsePowerThreshold":0,"logging":"standard","showAs":"default"}.
eWeLink BridgeeWeLink[Device487411] initialised and LAN mode unavailable as not discovered/supported.

**Comment by bwp91** [comment]
The newer error and your original error, the `WebSocket request was rejected by timeout (6000 ms)` are the same, basically that the plugin is sending the update to ewelink and waiting for a response. The plugin waits for 6 seconds for a response before giving up and showing the error.

Is the device itself turning on and off via homekit control even with these logs? If it isn't then it shows that ewelink cloud is having a problem connecting to the device (for whatever reason), which makes it strange that you can control via the ewelink app.

**Comment by bwp91** [comment]
if you disable the wifi on your phone, and open the ewelink app, can you control it?

**Comment by henkyfoo** [comment]
Yes i am able to control it via ewelink apps both wifi or cellular connection.

Which i found very strange
I never had this kind of issue with this plugin

**Comment by bwp91** [comment]
Can we message on discord?

https://discord.gg/cMGhNtZ3tW
