### ISSUE TITLE
Reports DW2 RF closed in Home notifications when it isn’t 

### ISSUE THREAD

**Issue by Dansinf** [bwp91/homebridge-ewelink#296]
### What issue do you have? Please be as thorough and explicit as possible.

Home notifies sensor as closed at whatever time ‘Sensor Time Length’ is set to.  Ie. If Sensor Time Length is set to 1 second, Home notifies the Sensor as open and 1 second later notifies as closed.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?

1.3.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi Zero W

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

8.3.5

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

Sonoff DW2-RF, Sonoff RF Bridge

### Please paste any relevant logs below.

```

```

**Comment by Dansinf** [comment]
Further reading and it looks like the RF version only sends an open signal, not closed.  Chucks them in the bin and buys the wifi  version…

**Comment by bwp91** [comment]
Hi @Dansinf yes you are correct. The RF versions only send an alert to the plugin when the two parts are separated, not when put back together.

The Wifi version will be able to correctly show open or closed status :)
