### ISSUE TITLE
Trigger or setting to change the gate status (for automatically closing gates)

### ISSUE THREAD

**Issue by Alkalinaty** [bwp91/homebridge-ewelink#298]
* **Please explain your feature request in a one or two sentences.**
Firstly thank you for creating this great plugin. It is possible to add a toggle or setting for gates that automatically close after a set time. In my case I just need the status of the gate to change from open to closed after X seconds. I don't need the gate to be triggered just the status of the gate to be changed after the time period. Let me know if this would be possible. 

* **Is your feature request related to a problem? Please describe.**
No

* **Any particular eWeLink devices that this relates to?**
1Channel inching self locking switch

* **Anything else?**

**Comment by bwp91** [comment]
Hi @Alkalinaty 

Have you used the plugin settings at all to change the type of accessory that this device shows as in homekit?

**Comment by Alkalinaty** [comment]
Thank you for the quick response.  Yes I have changed the type of accessory
to be Garage in homekit and it looks great.
The only issue I have is that our gate automatically closes after 10
seconds no there is no need to push or trigger the close gate.
I wanted to know if there is a way in the plugin or code to change the
status of the garage to close automatically after 10 sec?

Please let me know if this is possible.

Thanks

**Comment by bwp91** [comment]
It’s currently possible with the “lock” type accessory. I know a few users who have the same scenario with a gate, and with this accessory type you can set up an “operation time” to show from unlocked to locked again after X seconds (without the plugin sending any command to the device).

Never thought of doing this with garage door type, but i can look into it as it would certainly be possible

**Comment by Alkalinaty** [comment]
Thank you for the feedback and your help! You really did a great job with
the plugin.

Have a good weekend.

**Comment by bwp91** [comment]
Please update to the beta version of the plugin, v8.3.7-beta.0.

You should see in the "Show As" list a new option "Gate (As Garage Door)".

You can also set an operation time for how long the door should show as open for.

**Comment by Alkalinaty** [comment]
Thank you the update works great!!!
