### ISSUE TITLE
Device with wrong name

### ISSUE THREAD

**Issue by petrocino** [bwp91/homebridge-ewelink#299]
Hi there.

I have a RP4 with the latest version of Homebridge and latest version of **homebridge-ewelink (v8.3.6)**

When I'm adding new devices at ewelink app (iOS), the normal behavior is to have a pre-defined name of this new device, ok.
But when I modify this device name, it not reflects at homebridge-ewelink.

I tried to found some way to share some screenshots over here, but didn't found how.

Anyone has an idea of how to fix it?

**Comment by bwp91** [comment]
When the plugin first adds an accessory to homebridge, it will use the name from the ewelink app. After this, device names do not sync between the ewelink app and homebridge.

You can change the name of an accessory in the home app. But the homebridge log will always show the original name of the accessory.

If you want to change the accessory name in the log, then you will need to name the device in ewelink app how you want it shown, then use the homebridge UI to remove the accessory from the cache.

This way, the accessory is then *added* to Homebridge again with the name from the ewelink app

**Comment by petrocino** [comment]
AWESOME!
You've nailed it! Tks a lot!
Now I can see it with the correct name.
I also restarted HB after remove the cached accessory.
