### ISSUE TITLE
Sonoff Micro-CFH is working with homebridge-ewelink

### ISSUE THREAD

**Issue by warenext** [bwp91/homebridge-ewelink#301]
As the title says, I've just installed a Sonoff Micro-CFH inline Wi-Fi USB switch and I can confirm it is working with homebridge-ewelink.  Very responsive actually.  Thanks!  The "My Devices" tab shows it's working both with Cloud and LAN, so you might want to update the Supported Devices on the wiki to remove the ⁉️.

**Comment by bwp91** [comment]
Updated to 🟢! Thanks for taking the time to let me know and glad it's working well!
