### ISSUE TITLE
LIGHTS | Fade in / out 

### ISSUE THREAD

**Issue by TonnyCS** [bwp91/homebridge-ewelink#302]
Hello,

would it be possible to implement some kind on fade in / out on turning off and on lights?

**Comment by bwp91** [comment]
Hi, which light model(s) do you have?

**Comment by TonnyCS** [comment]
Hi,
first of all, thanks for your response. 
I have 2 Sonoff L1 models.

**Comment by bwp91** [comment]
Hi @TonnyCS 

Sorry it's taken a long time to get back to you! I own an L1 model now and noticed that when changing brightness or when turning on, it fades already? It's just when turning off that it doesn't fade?

Do your light strips do the same?
