### ISSUE TITLE
Sonoff RF Bridge not work in Lan mode (without internet connection)

### ISSUE THREAD

**Issue by juanfc** [bwp91/homebridge-ewelink#303]
### What issue do you have? Please be as thorough and explicit as possible.
Sonoff RF Bridge not work in Lan mode (without internet connection)

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
1

* Which version of Homebridge/HOOBS do you have?
v1.3.5

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry pi 4

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?
homebridge-ewelink v8.4.1

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.
Sonoff RF Bridge

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @juanfc what do you mean exactly by not working?

are there errors in the homebridge log?

**Comment by juanfc** [comment]
Hi @bwp91  ! Is working fine now! 
If it fails again I will send you the log.
Thanks!
