### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by Raptor0014** [bwp91/homebridge-ewelink#305]
Just tried to update the plugin.

My Pi is running:
Node.js Version -  v16.13.0
NPM version - v8.1.0

I get this when I try to update:

USER: pi
DIR: /usr/local
CMD: sudo -E -n npm install -g homebridge-ewelink@latest

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/agent.js:114:44)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/index.js:5:33)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/make-fetch-happen/lib/agent.js:161:25)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)

Command failed. Please review log for details.

Any ideas?

**Comment by bwp91** [comment]
Run these commands in the homebridge terminal:

```
sudo hb-service update-node 14.18.1
```

```
sudo npm i -g npm
```

```
sudo hb-service update-node 16.13.0
```

**Comment by bwp91** [comment]
This should fix the issue with npm and then let you update the plugin.

You will most likely otherwise find that you get this error updating any plugin.

**Comment by bwp91** [comment]
I actually had the same error and have created an issue on homebridge about it:

https://github.com/homebridge/homebridge/issues/3002

**Comment by Raptor0014** [comment]
Just trying now, thank you for the swift response

**Comment by Raptor0014** [comment]
using sudo hb-service update-node 16.13.0 resets the NPM to 8.1.0?

Running  sudo npm I -g npm again just gives this:

removed 2 packages, changed 14 packages, and audited 219 packages in 7s

10 packages are looking for funding
  run `npm fund` for details

3 moderate severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

**Comment by bwp91** [comment]
Yes, but now the npm issues should be fixed and you should be able to update the plugi.

**Comment by Raptor0014** [comment]
No, I get thew same original problem

**Comment by Raptor0014** [comment]
I've rolled back to 14.18.1 & 6.14.15

No issues with updating the plugin then

**Comment by bwp91** [comment]
Strange. Which plugins do you have installed?

**Comment by Raptor0014** [comment]
![Screenshot 2021-10-31 at 12 45 40](https://user-images.githubusercontent.com/72652615/139583945-266d1b27-25ed-4b53-9b67-c8edee62a386.png)

Just these

**Comment by bwp91** [comment]
> Run these commands in the homebridge terminal:
> 
> ```
> sudo hb-service update-node 14.18.1
> ```
> 
>  ```
> sudo npm i -g npm
> ```
> 
>  ```
> sudo hb-service update-node 16.13.0
> ```

did you run all these commands in order?

**Comment by Raptor0014** [comment]
> > Run these commands in the homebridge terminal:
> > ```
> > sudo hb-service update-node 14.18.1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > sudo npm i -g npm
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > sudo hb-service update-node 16.13.0
> > ```
> 
> did you run all these commands in order?

Yes ran them in the order you had sent them.

**Comment by lamatuzzi** [comment]
> Run these commands in the homebridge terminal:
> 
> ```
> sudo hb-service update-node 14.18.1
> ```
> 
>  ```
> sudo npm i -g npm
> ```
> 
>  ```
> sudo hb-service update-node 16.13.0
> ```

It Works for me your instructions ! Thank you !

**Comment by bwp91** [comment]
@Raptor0014 are you still having issues updating node? updating the plugin? which version of node are you on now?

**Comment by Raptor0014** [comment]
Hi,

I’ve updated the plug-in no problem. I can update the node but not the npm 🤷🏼‍♂️

So I’ve left it as is for now as the plug-ins are working and up to date. 

No idea why I can’t do the npm update. If I update that first it works fine. 

But then when I update the node it rolls the npm back and then won’t allow it to update.

**Comment by bwp91** [comment]
If you want to try again with the steps

```
sudo hb-service update-node 14.18.1
sudo npm i -g npm
sudo hb-service update-node 16.13.0
sudo npm i -g npm
```

and paste any outputs here that are showing errors, then I am happy to take a look.

Or if you are happy to leave it as it is then I can look into closing this issue.

**Comment by Raptor0014** [comment]
Hi,

Get the same problem as before when trying to update the npm after going to 16.13.0

This is what comes up after running the final command.

pi@homebridge:/var/lib/homebridge $ sudo npm i -g npm

removed 2 packages, changed 14 packages, and audited 219 packages in 7s

10 packages are looking for funding
  run `npm fund` for details

3 moderate severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
pi@homebridge:/var/lib/homebridge $

**Comment by bwp91** [comment]
Thats a normal output meaning the npm update has been successful…

**Comment by Raptor0014** [comment]
Before when it did that the npm version disappeared. But it's updated to 8.1.2 now so will see how it goes. 

Thanks for all your help.
