### ISSUE TITLE
error 401

### ISSUE THREAD

**Issue by brunokelo** [bwp91/homebridge-ewelink#31]
My plugin just stopped working, it displays the following error message.

[eWeLink] An error was encountered while requesting a list of devices. Response was [{"error": 401}]

plus someone with the same problem
?

thanks

**Comment by brunokelo** [comment]
I managed to resolve my authenticationToken changed, will this occur frequently?

**Comment by scorpioRED** [comment]
Got same problem twice on this week :(

**Comment by guisua** [comment]
In my experience the token changes **about once a month**.

Keep in mind to always use the `Bearer [use_this_token]` token in the HTTP Header and **not** the `apiKey` in the query string. Always happens to me.
