### ISSUE TITLE
Two doors garage doors doesn’t works with 7V-32V 2CH switch

### ISSUE THREAD

**Issue by maxymkov** [bwp91/homebridge-ewelink#310]
The issue:
Two doors garage doors doesn’t works with 7V-32V 2CH switch

The setup.
Homebridge UI-X V. 1.3.6
OrangePi; Node v16.13.0; npm v8.1.0
homebridge-ewelink v8.5.0

Description:
I'm customising 2 ch switch to open garage door. The garage door have two switches to be opened full or partially. When I setting up switch as default switches everything is fine, if I setting switch as 1 garage door it also works, but if I setting two garage doors, then switch stop working and below error appears at log:

device update failed as Cannot read properties of undefined (reading 'updateCharacteristic') at deviceGarageTwo.internalUpdate (/usr/lib/node_modules/homebridge-ewelink/lib/device/simulation/garage-two.js:151:17).

/usr/lib/node_modules/homebridge-ewelink/lib/device/simulation/garage-two.js:223
      gdService.updateCharacteristic(this.hapChar.TargetDoorState, new this.hapErr(-70402))
                ^
TypeError: Cannot read properties of undefined (reading 'updateCharacteristic')
    at deviceGarageTwo.internalUpdate (/usr/lib/node_modules/homebridge-ewelink/lib/device/simulation/garage-two.js:223:17)
    at TargetDoorState.setHandler (/usr/lib/node_modules/homebridge-ewelink/lib/device/simulation/garage-two.js:93:14)
    at TargetDoorState.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1624:42)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at TargetDoorState.Characteristic.handleSetRequest (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:791:38)
    at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1768:29)

I'll be very pleased with any help about this error.
Many thanks in advance for yours assistance.

**Comment by bwp91** [comment]
Hi @maxymkov 

Please can you update to the beta version of the plugin, and let me know if this has fixed this error for the 2 garage simulation?

https://github.com/bwp91/homebridge-ewelink/wiki/Beta-Version#homebridge-ui

Thanks

**Comment by maxymkov** [comment]
> Hi @maxymkov
> 
> Please can you update to the beta version of the plugin, and let me know if this has fixed this error for the 2 garage simulation?
> 
> https://github.com/bwp91/homebridge-ewelink/wiki/Beta-Version#homebridge-ui
> 
> Thanks

Hello,
Many thanks for your kind help.
With beta installed, there are no errors appear anymore. However, only one switch is functional, the second one works with no effect, but no errors are shown in console.

**Comment by bwp91** [comment]
The 2-garage-dooor simulation works with a sonoff 4-channel device, with two channels being used for the first garage door and the other two channels being used for the second garage door.

https://github.com/bwp91/homebridge-ewelink/wiki/2-Garage-Doors-%28with-multi-channel-device%29

I've realised you have said you are using a two-channel device, so this is not going to work with this simulation.

What is your setup? Do you need to send a pulse to open each door and another pulse to close it again? I assume you are using one channel for each of your doors?

**Comment by maxymkov** [comment]
> The 2-garage-dooor simulation works with a sonoff 4-channel device, with two channels being used for the first garage door and the other two channels being used for the second garage door.
> 
> https://github.com/bwp91/homebridge-ewelink/wiki/2-Garage-Doors-%28with-multi-channel-device%29
> 
> I've realised you have said you are using a two-channel device, so this is not going to work with this simulation.
> 
> What is your setup? Do you need to send a pulse to open each door and another pulse to close it again? I assume you are using one channel for each of your doors?

Yes, exactly. Every of button press works as Open/Stop/Close.

**Comment by maxymkov** [comment]
I've solved my issue, with changing plugin settings to regular switches, and installation of dummy garage doors switches, then linking them by automatisation in Home App. 

Again, many thanks for help.
