### ISSUE TITLE
Add TV/AVR as simulated device type?

### ISSUE THREAD

**Issue by tiimjcb** [bwp91/homebridge-ewelink#311]
Hello,
I do have a basic Sonoff switch that is connected to an AVR. Is it possible to add a simulated type "AVR" (and it's even possible to add a TV type), with only the On/Off switch? No need of sources, or remote control since the Sonoff can only turn on/off the device.

Thanks! Have a great day.

**Comment by bwp91** [comment]
Hi @Poufii 

This is how it would look.

Really not much different from a normal switch/outlet?

![IMG_5594](https://user-images.githubusercontent.com/43026681/142727533-9b81bb24-587b-4b1c-a5d5-d762a3787215.jpg)
![IMG_5595](https://user-images.githubusercontent.com/43026681/142727535-512b2cfe-3455-42c8-aec2-81a88577f83e.jpg)
![IMG_5596](https://user-images.githubusercontent.com/43026681/142727537-2ec98863-7d72-4846-9295-6395b8364a98.jpg)

**Comment by Poufii** [comment]
> Hi @Poufii 
> 
> 
> 
> This is how it would look.
> 
> 
> 
> Really not much different from a normal switch/outlet?
> 
> 
> 
> ![IMG_5594](https://user-images.githubusercontent.com/43026681/142727533-9b81bb24-587b-4b1c-a5d5-d762a3787215.jpg)
> 
> ![IMG_5595](https://user-images.githubusercontent.com/43026681/142727535-512b2cfe-3455-42c8-aec2-81a88577f83e.jpg)
> 
> ![IMG_5596](https://user-images.githubusercontent.com/43026681/142727537-2ec98863-7d72-4846-9295-6395b8364a98.jpg)
> 
> 
> 
> 

Exactly. It looks so better in the Home App, better distinction from the other reals switches, and it's better with Siri (at least in my case). 
Do it only if it's easy for you! I don't want to bother you with this stuff, because that is honestly not the most useful enhancement. 
But thanks!

**Comment by tiimjcb** [comment]
Exactly. It looks better in the home app, it's better distinguished from regular switches, and it works better with Siri (at least for me). 
But do it only if it's easy for you! I don't want to bother you with this stuff since it's not the most useful improvement.

It would look like this on an AVR (cause it's in audio receiver in my case), but without the sources.
Thanks for your answer!
 ![image](https://user-images.githubusercontent.com/75161532/142728901-30024880-ca6d-43b8-9332-90bba7d07872.jpeg)

**Comment by bwp91** [comment]
If you update to the beta version of the plugin, you should see in the plugin settings an option to expose a switch as a television service...

However the icon in the home app doesn't seem to be changeable?

**Comment by tiimjcb** [comment]
The house icon means that there's a bug in the config file for the TV. Like if homekit does not understand it's a TV (i saw this somewhere i don't remember, probably on reddit or on a discord server 😅), so normally, it should be a Blue TV icon when turned on. Also, my device is an audio reciever, which is a type supported by HomeKit. Is it possible to integrate it? It works the same way as the TV type.
Thanks for working on it, appreciate it so much! :)

**Comment by bwp91** [comment]
Do you know which service type the audio receiver is?

https://developers.homebridge.io/#/

**Comment by tiimjcb** [comment]
I don't find it on this list. But i know a plugin that integrates an audio receiver to homekit, and it works. Maybe you can give a check to the code of the plugin to identify which service type it is.

https://github.com/nitaybz/homebridge-yamaha-receiver#readme
Here's the plugin.

**Comment by bwp91** [comment]
Can you install the latest beta?

You will need to adjust the config for the device to show as an audio receiver.

You will also need to add the accessory manually to the home app, using the code that will be shown in the homebridge log. Publishing as an external accessory is the only way I can get this icon to show as is.

**Comment by MoTechnicalities** [comment]
Ben, in case you missed it. I sent you a Discord message.

**Comment by bwp91** [comment]
> Ben, in case you missed it. I sent you a Discord message.

I replied yesterday :)

**Comment by bwp91** [comment]
While I'm at it, in the latest beta I added options for all of 'Audio Receiver', 'Set Top Box' and 'Streaming Stick'!

**Comment by tiimjcb** [comment]
ok! it's working, tysm! you replied and act so fast, i'll consider donation 2€ next month!
thanks again!😁

**Comment by bwp91** [comment]
I’m glad it’s working! It’s always nice to offer some different icons in the home app… although these three things are very particular to their use case!
