### ISSUE TITLE
DeprecationWarning: Unhandled promise rejections are deprecated for RF Bridge

### ISSUE THREAD

**Issue by kolobock** [bwp91/homebridge-ewelink#312]
### What issue do you have? Please be as thorough and explicit as possible.
There is a TypeError in the homebridge log [rf-bridge.js:164:51](https://github.com/bwp91/homebridge-ewelink/blob/latest/lib/device/rf-bridge.js#L164).
It appears after upgrading Homebridge to v1.3.8 from v1.3.6. 
There are alerts configured on RF433 and so once they triggered we can see errors in the log file.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
(1)

* Which version of Homebridge/HOOBS do you have?
v1.3.8

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi
npm: v8.1.4
node.js: v14.18.1

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?
v8.6.0

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.
Sonoff RF Bridge RFBridge433
fw: 3.5.0

### Please paste any relevant logs below.

```
[eWeLink] Initialising plugin v8.6.0 | Node v14.18.1 | HB v1.3.8...
[23.11.2021, 09:43:31] [eWeLink] [Свет] current state [button triggered].
[23.11.2021, 09:43:31] [eWeLink] [Свет] current state [button triggered].
[23.11.2021, 09:43:31] [eWeLink] [Кнопка Коридор] current state [triggered].
(node:27195) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'updateCharacteristic' of undefined
    at /usr/lib/node_modules/homebridge-ewelink/lib/device/rf-bridge.js:164:51
(Use `node --trace-warnings ...` to show where the warning was created)
(node:27195) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
(node:27195) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[23.11.2021, 09:44:31] [eWeLink] [Кнопка Коридор] current state [not triggered].
```

**Comment by bwp91** [comment]
I don't know why this particular line 164 is throwing an error when line 156 above it is using exactly the same constants.

I have tested with my own rf bridge using a button type and a ewelink alarm type, unfortunately cannot reproduce this issue.

I do think it's not working in your case because maybe you have over time added or removed subdevices from the rf bridge? the plugin can't detect these changes well so it may be that you need to use the "reset rf bridge" plugin option properly refresh the device list in the plugin.

**Comment by bwp91** [comment]
In beta version 8.6.1-beta.3 I have added a try/catch around the async code so that the errors are caught properly avoiding the `UnhandledPromiseRejectionWarning` message.
