### ISSUE TITLE
Light Strip

### ISSUE THREAD

**Issue by thepickpocket** [bwp91/homebridge-ewelink#313]
* **Please explain your feature request in a one or two sentences.**
Adding in support for Light Strip control through homebridge

* **Is your feature request related to a problem? Please describe.**
Currently not supported as per plugin logs.

* **Any particular eWeLink devices that this relates to?**
Sonoff Spider Z Light Strip Controller

* **Anything else?**
{"bindInfos":{"gaction":["88dc433f-6f8b-4a78-975d-b0935d388980_ewelinkGoogleHome"]},"version":8,"init":1,"fwVersion":"1000.2.1050","switch":"off","colorR":0,"colorG":11,"colorB":255,"mode":0,"bright":100,"light_type":1,"speed11":70,"bright11":60,"speed16":60,"bright16":60,"ssid":"Flight","bssid":"0:95:103:198:108:62","lineSequence":{"1":"b","2":"g","3":"r"},"timeZone":2}

**Comment by bwp91** [comment]
Hi @thepickpocket 

Would you be happy to share this device to my ewelink account so i can properly see how the data is given and the different modes, functions etc?

**Comment by thepickpocket** [comment]
@bwp91 I can definitely share it with you for a couple of days, just send me the ewelink account to share with :)

**Comment by bwp91** [comment]
Country code 44 (UK)
bwp91@icloud.com

**Comment by thepickpocket** [comment]
Shared :) Will revoke sharing on the 29th. Will that be enough time?

**Comment by bwp91** [comment]
Thanks, I see it!

Are you happy for me to turn it on/off and change brightness/colour a few times over the next hour or so?

**Comment by thepickpocket** [comment]
Absolutely :)

**Comment by bwp91** [comment]
Okay, if you want to update to the beta version of the plugin, 8.6.1-beta.4, this device should appear in homebridge/homekit after restarting and should be controllable (on/off, brightness and colour).

**Comment by thepickpocket** [comment]
Tested and works perfectly :) Thank you
![LightStrip](https://user-images.githubusercontent.com/8138355/143409190-72cf2f52-a72f-4c38-b2ea-bca51bb11f6a.jpeg)

**Comment by bwp91** [comment]
Excellent!

I noticed the strip has a couple of extra modes (apart from the first two rgb modes which I didn't know the difference between) - there is also the cct mode and some black/white mode? The cct mode didn't seem to offer a range of colours so I didn't implement this, and the other black/white mode I didn't know what it was for so didn't implement this either.

There's also the scenes and the music mode which I haven't implemented. Potentially possible to create HomeKit buttons so switch into these modes if that could be useful for you? But the configuration of the modes would still need to be done within the ewelink app.

**Comment by thepickpocket** [comment]
Thats perfect, it would be nice to have those buttons available but really not a trainsmash. The only thing that I noticed, is that if I change colours while the lights are off in homekit, and then switch it back on, the lightstrip does not change to the new colour. Maybe we just need to send a colour change signal every time its switched on?

**Comment by bwp91** [comment]
> if I change colours while the lights are off in homekit, and then switch it back on, the lightstrip does not change to the new colour

This should be fixed in 8.6.1-beta.5. It wasn't sending any colour change at all if the device was off.

The other buttons I will work on later today!

**Comment by thepickpocket** [comment]
Awesome! Thanks!

**Comment by bwp91** [comment]
is it okay to control your device again? need to put it to different scenes and modes...

**Comment by thepickpocket** [comment]
yeah sure go for it :)

**Comment by bwp91** [comment]
There are a lot of different scenes and music mode types, it is going to be _a lot_ of code to implement them all.

Are there any scenes in particular that you personally use? and any type of music mode that you use? I'm happy to implement perhaps a couple of scenes and a music mode to begin with... doing them all initially will be very time consuming 😆

**Comment by thepickpocket** [comment]
I really just use "Festi" scene and really dont use the music mode at all tbh :)

**Comment by bwp91** [comment]
Are you near the light now?

**Comment by thepickpocket** [comment]
Yes I am :)

**Comment by bwp91** [comment]
If you update to 8.6.1-beta.9 version, then (you will need the Eve HomeKit app) you should see another button inside the accessory called 'Festive Scene'.

If you turn it on it will make the light go to the festive scene, also if you use the ewelink app to turn on the festive scene, this button should show as on. Turning this button OFF won't do anything, to stop the scene you will need to choose a colour. But once you choose a colour, the button should turn off (to let you turn the scene ON again if you want).

I've implemented this in the same way I implement scenes in my homebridge-govee plugin, so you can follow this wiki entry here on how to get the scene to appear in the home app:
https://github.com/bwp91/homebridge-govee/wiki/Scene%2C-Music%2C-DIY-Modes#step-4-creating-homekit-scenes

**Comment by bwp91** [comment]
![IMG_5615](https://user-images.githubusercontent.com/43026681/143865888-80289b22-8547-4399-be2f-da9c8caaa5fc.jpg)

**Comment by thepickpocket** [comment]
Thanks so much! :D

**Comment by bwp91** [comment]
Are you able to confirm it working? Obviously I cannot see the physical device to see how the scene looks! 😝

**Comment by bwp91** [comment]
Also feel free to unshare the device. I think I have everything saved for future reference if I need to add more scenes/modes. Thank you for sharing it with me, makes everything a lot quicker!
