### ISSUE TITLE
Thermostat 

### ISSUE THREAD

**Issue by vitva** [bwp91/homebridge-ewelink#315]
Please add a mode switch for the thermostat: heating and cooling! convenient for automations at different times of the year when one socket is used for the heater and fan

**Comment by bwp91** [comment]
Hi @vitva 

Which thermostat device model are you referring to?

**Comment by vitva** [comment]
Hi Sonoff Th 16 for homebridge Ewelink 
Thanks

**Comment by MoTechnicalities** [comment]
This would be good!
For reference, The ecobee thermostat has the following four selections in HomeKit: [OFF, HEAT, COOL, AUTO].
So, If there was an accessory simulation for Sonoff Th 16 thermostat, wherein a couple of EweLink switches could be setup to be controlled by the Sonoff Th 16 for when the room needs to be heated or cooled, that would be awesome!
Then one Switch could control a Room Air Conditioner or a Fan, while another Switch could control a Space Heater.

**Comment by vitva** [comment]
Hello Ben! I just thought, what if it is implemented as an additional parameter in the settings? whoever needs it activates and will use it and by default do it as it is now

**Comment by bwp91** [comment]
What would be the functionality of the modes? Just to turn the device on?

**Comment by vitva** [comment]
the functionality will be the same as when just heating, control the temperature and maintain it ... but if I also need to cool, for example, with a fan and also control the temperature


let's say if there is heating, turn on the outlet with a heater; if there is cooling, turn on the outlet with a fan, well, this is an example. I think there will be a lot of different applications

maybe I'm not expressing my thoughts quite correctly

**Comment by bwp91** [comment]
I understand what you are saying, but I will explain my perspective of the feature I have implemented.

>  if there is heating, turn on the outlet with a heater

You can now expose this particular outlet as a heater, based on the temperature reading of another sensor.

> if there is cooling, turn on the outlet with a fan

You can also expose this separate outlet as a cooler, based on the **same** sensor as above.

So instead of having a "fake" thermostat which controls two outlets via automations, you can directly expose both outlets as heaters or coolers based on the temperature that the sensor reads.

Indeed this is just my opinion but does this not seem more simple? Because then you don't need the extra homekit automations.

**Comment by vitva** [comment]
I agree that this option will be easier, but when heating is needed, I don't think that cooling is also needed, and in this case that I suggest one entity controls the climate as a whole and not several ... that's why I proposed this implementation as an additional setting that needs to be activated. thereby expanding even more possibilities if the user needed them

**Comment by bwp91** [comment]
Hi @vitva please update to the beta version of the plugin.

Inside the "Thermostat Devices" section of the config, when selecting the TH10/16 as a model and thermostat "show as", you should see this new option "Show Heat/Cool Modes".

<img width="682" alt="Screenshot 2021-12-26 at 17 09 22" src="https://user-images.githubusercontent.com/43026681/147415336-c1f27776-b0bf-47c3-8083-45dfa9d24fe4.png">

Tick this box, then restart the plugin. You should then see both modes available in the home app...

**Comment by vitva** [comment]
Thanks to Ben for the implementation! Everything works exactly as I wanted 👍

**Comment by bwp91** [comment]
Feature has been released in v8.9.0 :)
