### ISSUE TITLE
Ewelink show group switch in Homekit?

### ISSUE THREAD

**Issue by Nastras** [bwp91/homebridge-ewelink#316]
Hello @bwp91,

i have two Sonoff micro USB switches that I have grouped together in the ewelink app. Is it possible to show this group switch in Homekit and hide the two individual devices that are shown by default?

Thank you!

King Regards!
Nastra

**Comment by bwp91** [comment]
Hi @Nastras 

What would be the difference between this approach you have suggested, and just using the config to hide one of the switches so one remains which effectively controls both anyway?

**Comment by Nastras** [comment]
Hey thanks for the quick reply. I think that I have not expressed myself correctly. I'll try it again to explain something more specific. 😉

So I have two micro USB devices in the Ewelink app. Both devices currently show up in Homekit as a standalone device in the form of a switch through your plugin.

I would like to display these two devices as one common switch in Homekit. 

In the Ewelink app there is the possibility to create a group. I have already done this for the two devices. This gave me an additional group switch in the Ewelink app. 

This additional group switch I would like to display through your plugin in homekit. 

Unfortunately, I have not yet found a function that allows this.


I hope it is now a little more understandable?

![F7196993-9940-4C45-A6D7-43F5EA5F111C](https://user-images.githubusercontent.com/27686185/144716232-4abc8201-4962-4ec2-b371-8480b2d59a2f.jpeg)

**Comment by MoTechnicalities** [comment]
Not that I need it, but I can see this as a powerful addition for the ability to control lighting or other switches under a grouped control. I think its a cool idea and that Ben can pull it off!

**Comment by Nastras** [comment]
Thanks for your comment! 
That would be my wish too 😉

**Comment by bwp91** [comment]
Obtaining a list of groups from your ewelink account and controlling them is not impossible - I've had a look at the ewelink API. There are some drawbacks however.

* It's not possible to send group status updates via the web socket connection which the plugin uses. Each command needs its own HTTP request to the cloud, meaning that local control would not be possible, also if your internet is down then the commands won't work. 
* The plugin won't receive real-time status updates for the group, meaning I would need to introduce HTTP polling to this plugin. The plugin currently works really well due to the instant status updates it gets, I have always tried to shy away from introducing HTTP polling into this plugin.

---

The same functionality could be achieved making use of a plugin using a dummy switch. And using HomeKit automations to control both individual devices when the dummy switch is turned on and off. Using this method would allow the plugin to continue to use the local control and/or the web socket connection for sending and receiving updates. It would also mean if the devices support local control then the control would continue to work if the internet was down for any reason. HomeKit would take care of the dummy switch status rather than needing http polling to continually request the status.

This is just my opinion. In short, better functionality could be achieved by using a dummy switch rather than implementing groups from your ewelink account.

**Comment by Nastras** [comment]
Thanks for your effort and the detailed answer.

Personally I would not mind if the queries for this function are done via HTTP. For me it would be a great feature even if it is not updated in real time.

Since I have over 300 Homekit devices already integrated I find it advantageous to create the group via your plugin. The idea with the dummy switch would also be a possibility. Where here the unneeded hardware devices continue to be displayed in Homekit without use. 

From my experience, the Homekit speed is greatly reduced by too many devices when opening the Home app. Therefore, I try to limit the number of dummy devices in the meantime.

Would it be possible or would you like to implement the group function via http independently of the current plugin structure and functionality?

I would be very happy about it!

Best regards
Nastras

**Comment by MoTechnicalities** [comment]
If I can add my 2 cents.
Considering all the functionality that the plugin has given us already, that has nothing to do with the EWeLINK App, I think it would be great if the plugin gave us the power to create switch simulations that allows us to display a switch in HomeKit that we can configure in the plugin's settings to control any number of devices added to a list. Those devices could be individually hidden from HomeKit but all work off the 1 switch via the plugin. It needn't have to do anything with the EWeLINK App.

**Comment by Nastras** [comment]
This idea would also be a very good approach 👍

**Comment by bwp91** [comment]
> The idea with the dummy switch would also be a possibility. Where here the unneeded hardware devices continue to be displayed in Homekit without use.

You know it is possible to create groups already within the home app, which could do exactly what you are asking to do in the first place…

**Comment by bwp91** [comment]
I am not trying to dismiss any idea at all, I just want to add functionality to the plugin where is isn’t possible otherwise…

**Comment by MoTechnicalities** [comment]
Your right. Sorry, I hadn't really explored that grouping in depth, not really having the need for it myself, but definitely recognizing the benefit. Thanks.

After testing this, I also note it as interesting that HomeKit's [Quick Press] for ON/OFF works just fine for any Tile that has grouped lights or switches, but only opens settings for Tiles that also run services, like the new WIZ bulb scenes settings.

**Comment by bwp91** [comment]
@Nastras 

Can you update to the beta version of the plugin? 8.7.2-beta.0

This should expose your ewelink group as a switch in homekit.

I've done a bit of testing - seems to work okay!

Let me know how you get on.

**Comment by Nastras** [comment]
Hey Cool that you have installed it after all. Thanks a lot!

I just tried it out. The group switch is displayed in HomeKit. But it does not switch the group. Nothing happens.

If I press the original group switch in the Ewelink app then it works.

**Comment by bwp91** [comment]
Are there any errors in the homebridge log?

**Comment by bwp91** [comment]
Actually i’ve just had a thought.

When the plugin loads, can you show me the log lines from the `device initialised …` for both your devices?

**Comment by Nastras** [comment]
No errors are displayed in the log. Attached is the image from the start of the instance.
![45DDAA7B-915B-4567-97B8-EAE8AB7798BA](https://user-images.githubusercontent.com/27686185/145952180-3af00d81-9c77-4b91-a4b2-064e2fcc262b.jpeg)

**Comment by bwp91** [comment]
Can you update again to 8.7.2-beta.1 and try this?

**Comment by Nastras** [comment]
Now it works. Super work 👍

Can you tell me if it is also possible to hide individual devices via your plugin in Homekit.
I would like to get only the group switch displayed.

Could not find anything in the readme 😅

**Comment by bwp91** [comment]
In the plugin settings screen, create entries for both devices in the “single channel devices” section, with a label and the device id of each one, and tick the “hide from homekit” option. then save and restart

**Comment by Nastras** [comment]
Can you give me an example of that?

Thanks!

**Comment by bwp91** [comment]
<img src="https://user-images.githubusercontent.com/43026681/145958871-3aaecdca-02d1-4d82-9b73-0e2e35ba14b8.jpeg" width="300">

**Comment by Nastras** [comment]
I meant as a manual entry in config.json.
Do not use config ui 😁

**Comment by bwp91** [comment]
```json
{
  "name": "eWeLink",
  "username": "%%%",
  "password": "%%%",
  "singleDevices": [
    {
      "label": "Device 1",
      "deviceId": "100065ad38",
      "ignoreDevice": true
    },
    {
      "label": "Device 2",
      "deviceId": "100065ad39",
      "ignoreDevice": true
    }
  ],
  "platform": "eWeLink"
}
```

**Comment by bwp91** [comment]
Have you managed to hide them like you wanted?

**Comment by Nastras** [comment]
No not yet am just on the road. 
Will test it right when I'm back and let you know.

**Comment by Nastras** [comment]
I have tested it now. Everything works as it should.
The devices are hidden and the group switch is displayed in HK.
Great thing! Thanks again for your efforts!

Can you tell me how long it takes for the plugin to detect when someone presses the group button in the Ewelink app?

**Comment by Nastras** [comment]
I only ask because I just noticed when I flip the group switch in the Evelink app he does not notice anything in HomeKit. I think that is the issue you have addressed above or?

Is for me but not too bad because I control it exclusively via HomeKit.

**Comment by bwp91** [comment]
No, I haven't introduced status polling for the groups, so if you change the status in ewelink app it won't update in homebridge. The only time it gets the actual status is when homebridge restarts and the plugin obtains the info about the group.

**Comment by Nastras** [comment]
I almost thought so. It's no big deal for me. I don't need polling for my application.

An additional question I would have to you, is it possible about your plugin a single switch like the new group switch a delay to preset?

**Comment by bwp91** [comment]
> is it possible about your plugin a single switch like the new group switch a delay to preset?

i don’t really understand your question. can you explain a use case?

**Comment by Nastras** [comment]
I was thinking of a delay function for switches.

I already use something like this with the homebridge- cmdtriggerswitch plugin. 

https://github.com/hans-1/homebridge-cmdtriggerswitch

There is the possibility to show a slider for the switch.
About this slider you can set the minutes to delay when the switch is turned off.

It is very helpful for many automations and applications. Homekit is unfortunately very limited in terms of delays.

I think that would be a great extension for your plugin. What do you think?

![61B8E6D1-3CB1-47EB-8920-E7A8D948842F](https://user-images.githubusercontent.com/27686185/146059220-8fce2a3b-dd95-420a-a291-c174480a61eb.jpeg)

**Comment by bwp91** [comment]
Is this not already possible using the inching feature in the ewelink app? 

ie turning a switch off after an X number of seconds/minutes?

**Comment by Nastras** [comment]
I just had a look. I can't find this feature in the app with my free account.

But it may well be that this function is available for the paid version?

**Comment by bwp91** [comment]
i don’t think that ewelink promote their premium account based on individual device features.

You don’t see any option for inching in the device settings? 

I don’t have the sonoff micro so i can’t test myself

**Comment by Nastras** [comment]
Now I have found the function 👍
But this is only available for individual devices. For groups this is not available 😆.
