### ISSUE TITLE
L2 supported?

### ISSUE THREAD

**Issue by patrikbelis** [bwp91/homebridge-ewelink#317]
I saw that L2 is supported so i bought it trying to setup and its says its not supported 

[TV LED] is not supported, do create a GitHub issue with the following info:
[137] {"bindInfos":{},"version":8,"init":1,"fwVersion":"1000.2.1050","switch":"on","colorR":255,"colorG":255,"colorB":0,"mode":0,"bright":100,"light_type":1,"timeZone":1,"ssid":"orange network","bssid":"0:95:103:148:45:159","lineSequence":{"1":"b","2":"g","3":"r"}}.

            "name": "eWeLink",
            "username": "myemail@gmail.com", <--- changed for privacy
            "password": "mypasswordhere", <--- changed for privacy
            "mode": "auto",
            "lightDevices": [
                {
                    "label": "TV LED",
                    "deviceId": "1001383063",
                    "deviceModel": "l2"
                }
            ],
            "platform": "eWeLink"

Homebridge 1.3.8

Latest plugin version

Sonoff L2 Led strip

**Comment by bwp91** [comment]
Hi @patrikbelis 

Please update to the beta version of the plugin

https://github.com/bwp91/homebridge-ewelink/wiki/Beta-Version#homebridge-ui

L2 should be working in this 😀

**Comment by bwp91** [comment]
Or update to the new release. L2 is supported in this!
