### ISSUE TITLE
PIR not triggering motion alert/signal in Homebridge - Red light flashes ok on Sonoff RF

### ISSUE THREAD

**Issue by currybeast** [bwp91/homebridge-ewelink#319]
### What issue do you have? Please be as thorough and explicit as possible.
PIR not triggering motion alert/signal in Homebridge - Red light flashes ok on Sonoff RF
Shows up ok as a motion sensor in your Plug-in (great plug-in by the way)
Green light fires on the PIR, RED light flashes on the RF module, but nothing in Home App.

### Details of your setup.
(1) Homebridge UI-X 

* Which version of Homebridge
1.3.8

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Ubuntu Focal Fossa (20.04.3 LTS)
Node v14.18.2
NPM v6.14.15

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

v8.7.1 - Has never worked

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.
PIR CT60M

### Please paste any relevant logs below.
Not getting any errors
```

**Comment by bwp91** [comment]
Hi @currybeast 

Can you put the plugin in debug mode from the plugin settings, restart, then wait for the plugin to load.

Then trigger the motion sensor, and show me all logs that appear in the homebridge log?

**Comment by currybeast** [comment]
Many thanks for responding so quickly, but I turned on logging on and performed the detection, but I cant find the log file anywhere??!!  Any clues?  Really sorry to waste your time.

**Comment by bwp91** [comment]
Log file is normally located at `/var/lib/homebridge/homebridge.log`.

**Comment by currybeast** [comment]
[homebridge.log](https://github.com/bwp91/homebridge-ewelink/files/7727385/homebridge.log)
[config.txt](https://github.com/bwp91/homebridge-ewelink/files/7727401/config.txt)

**Comment by bwp91** [comment]
From the logs there is no “notification” from ewelink that the sensor was activated, so this why the plugin isn’t marking it as activated. 

Could you try again?

Are you using the same credentials in the plugin config as the account that the rf bridge is added to? ie not a shared device?

**Comment by currybeast** [comment]
Thanks again, just checked it all, yes I operate 2 accounts as recommended as they get logged out.  So I have a primary account on the app on my phone, then all accessories are shared to a second account that is dedicated to Homebridge.   All accessories work ok, except the PIR on the RF Bridge, but the PIR shows shows up in Homebridge ok via the secondary account, but never triggers.  I suppose the debug is not showing as its not signalling at all.

**Comment by bwp91** [comment]
You should try configuring the plugin with your main ewelink account credentials.

I personally have never recommended using a “shared” account.

It doesn’t log you out of the ewelink app.

**Comment by currybeast** [comment]
Many thanks again.  I have changed Homebridge over to the primary account now.  Not sure where I read to do the sharing, but I do remember that when logging into the ewelink app concurrently on multiple devices, it used to log you out of the other.  But does not seem to do it now.  I have removed the RF bridge and PIR and re-added in the ewelink app and its the same.  They show up ok in Home app, red light flashes on RF Bridge when PIR is triggered, but no trigger in Homebridge.  There is no evidence of the PIR activity in the log either other than startup device detection, looks the same as before.  Have I not done something in the ewelink app?  Is there anything to configure in there first after adding the devices?

**Comment by bwp91** [comment]
Do you have the plugin set to any mode like auto or cloud or local?

**Comment by currybeast** [comment]
It's in Hybrid [Recommended] mode

**Comment by bwp91** [comment]
Any luck at all with incoming notifications the last few days? Sorry i’ve been busy and not really had a chance to look into this.

Happy new year!

**Comment by bwp91** [comment]
Hi,
Closing this just as been a little overwhelmed with issues recently.
If this is still an issue or a feature you would like implemented then please do re-open this ticket!
Thanks for your understanding!
