### ISSUE TITLE
Sonoff TX3? 

### ISSUE THREAD

**Issue by vitva** [bwp91/homebridge-ewelink#320]
Hi! The question is, if the ability to hide the switch in HomeKit turn off or turn on everything, like in the Ewelink app for sonoff tx3?

**Comment by bwp91** [comment]
Yes, you need to use the “Multi Channel Devices” config section to add an entry with a label and the device id.
Then in the “Hide Channels” option enter `0`, save and restart. This will hide the all on/off accessory.

**Comment by vitva** [comment]
Thanks! Everything works! It turned out to hide the switch

**Comment by bwp91** [comment]
👍🏻
