### ISSUE TITLE
can I hide devices?

### ISSUE THREAD

**Issue by HarryMcGill2022** [bwp91/homebridge-ewelink#321]
hi there
             i have got 2 devices that are shared with me but not in my home any help will be appreciated

**Comment by bwp91** [comment]
hey.
i’m a little confused because the title of your issue is about hiding devices but then you say the devices aren’t there in the first place?
Can you show startup logs of the plugin?

**Comment by HarryMcGill2022** [comment]
> 

what I mean is I have 2 devices that are shared with me that are at a different home but they are in my home kit app can I hide then,

**Comment by bwp91** [comment]
Yes you can use the plugin settings to hide/ignore specific devices.

Choose the correct device type section, add an entry with a label and the device id, and tick the “Hide from HomeKit” option.

**Comment by HarryMcGill2022** [comment]
i cant see that option anyware

**Comment by bwp91** [comment]
Closing this as I believe I saw on discord you found the option.
