### ISSUE TITLE
Heater Simulation (single channel device + separate temp sensor)

### ISSUE THREAD

**Issue by bwp91** [bwp91/homebridge-ewelink#323]
Something I plan to look into and adding here to keep track.
Also could do cooler simulation in the same way.

**Comment by MoTechnicalities** [comment]
Or One simulation to do the job of both.

![image](https://user-images.githubusercontent.com/68468472/145686778-f01926fd-8f85-4bad-ab5a-88ee8c3ba905.jpeg)

**Comment by vitva** [comment]
this is exactly what i wanted from sonoff th like in the picture above

**Comment by bwp91** [comment]
A device like the TH10/16 only has ON or OFF switch.

So i’m not really understanding what difference th me different modes would do, either way they would just turn the device on?

What’s the use case?

It is already possible to create automations using temperature.

**Comment by vitva** [comment]
automation by mode, when heating is in progress, then automation of heating is turned on when cooling, respectively, automation of cooling and temperature control ...

**Comment by MoTechnicalities** [comment]
@bwp91
I see your point.

The ecobee is a device with one thermostat with built in logic that controls two switches. One for heat and one for cold.

And the Sonoff TH10/16 is a device with one thermostat that controls one switch.

**Comment by vitva** [comment]
In other words, it greatly expands the usability of the Eve app, for example. and a bunch of useful automations

**Comment by bwp91** [comment]
This should now be possible with the latest beta version.

You can choose heater or cooler in the “show as” option for single channel devices, but you MUST then enter a device id of another ewelink (or indeed govee or meross) sensor that provides a current temperature reading.

However, I have hidden the “heat” and “cool” modes as I just think it makes it more confusing what’s actually going on.
