### ISSUE TITLE
Basic R2 plays hide and seek with HomeKit 

### ISSUE THREAD

**Issue by doctornakhare** [bwp91/homebridge-ewelink#325]
Hello,
Using homebridge-config-ui-x v4.41.4 on Windows10 running homebridge-ewelink v8.7.1 plug-in for Sonos BasicR2. 

The device disappears from HomeKit after a full day. All efforts removing & reading homebridge to HomeKit result in device being discovered and added only to have it disappear after setup is complete; but if I do the same thing in the morning it works fine. 

Additionally if I skip removing & reading HomeKit shows all devices offline while the Ewelink app and Tuya smart app shows devices to be online, even homebridge itself never loses any of the device but HomeKit keeps losing them overnight. 

Could you please help ?
Many thanks.

**Comment by bwp91** [comment]
hi @doctornakhare 

do you have devices on your homekit network on an older version of ios like 10 or 11?

I have seen before some strange behaviour with devices going “missing” on all devices when users have a device with an old version of ios.

Another question, when the accessory goes missing from homekit, is it still visible as an accessory in the homebridge ui?

**Comment by doctornakhare** [comment]
Hi @bwp91 ,

Thank you for responding so soon 🙏🏻

No I’m on the latest iOS & yes they are still visible in homebridge Accesories. 

I found out my problem ! I think !!

Parents kept turning off the AppleTV , the Tuya lights would still be visible in HomeKit but the sonos would disappear. 

Did I guess it correctly ?

**Comment by bwp91** [comment]
I don't necessarily mean your phone with an older iOS version, but _any_ device within your HomeKit network with an older version of iOS, like an old iPad laying around, or one of your parents phones.

If the accessories are still visible in the homebridge UI then this definitely indicates a HomeKit issue rather than a plugin issue. The accessories shouldn't disappear just because the appletv is being turned off.

**Comment by doctornakhare** [comment]
Yes , I do have an iPad Mini gen 1 just lying around. 

If this is the case do what do you recommend ? 

1. Sign off from the said iPad  Or
2. Is there a possible way to keep it signed in for Music and other purposes and remove it from HomeKit ?

**Comment by bwp91** [comment]
In the icloud settings you should just be able to turn off the 'Home' sync. 

Once you've done this, I would suggest restarting your home hub device (apple tv) and also homebridge. And see if this fixes this issue.
