### ISSUE TITLE
Sonoff SNpanel

### ISSUE THREAD

**Issue by Cvoju** [bwp91/homebridge-ewelink#326]
* **Please explain your feature request in a one or two sentences.**
Bonjour, je viens de m’équiper d'un Sonoff Ns panel
FW Name E32-MSW-NX 
Pas encore reconnu dans Homebridge

* **Is your feature request related to a problem? Please describe.**
Je commence a peine la programation, avez-vous quelques pistes pour m'aider ?

* **Any particular eWeLink devices that this relates to?**

onoff Ns panel
FW Name E32-MSW-NX

* **Anything else?**
Merci pour votre reponse

**Comment by bwp91** [comment]
Hi @Cvoju 

I don’t speak French, but I’ll write in English and you can google translate if you need to.

Are there any messages in the Homebridge log when the plugin starts about this device not being supported?

**Comment by Cvoju** [comment]
> Salut @Cvoju
> 
> Je ne parle pas français, mais j'écrirai en anglais et vous pourrez traduire sur Google si vous en avez besoin.
> 
> Y a-t-il des messages dans le journal Homebridge au démarrage du plug-in indiquant que cet appareil n'est pas pris en charge ?

Bonjour @bwp91, Merci pour vos reponses.
il n'y rien dans le journal

**Comment by bwp91** [comment]
Can you restart the plugin and copy and paste all the logs from the plugin setup that appear here?

**Comment by Cvoju** [comment]
> Pouvez-vous redémarrer le plugin et copier et coller tous les journaux de la configuration du plugin qui apparaissent ici ?

je pense qu'il n'est pas détecté. L’interrupteur du salon et le TH10/16 sont détectés

[12/16/2021, 6:29:51 PM] [eWeLink] [Salon] a été rapporté [online] via WS.
[12/16/2021, 6:30:37 PM] [eWeLink] [Corps de chauffe] température actuelle [50°C].

**Comment by bwp91** [comment]
Unfortunately if the plugin doesn’t detect the device, then it probably can’t be implemented.

But actually I don’t see how the nspanel would be useful in homebridge?

**Comment by bwp91** [comment]
Do you have the option in the ewelink app to share the device to another account?

**Comment by Cvoju** [comment]
> Avez-vous la possibilité dans l'application ewelink de partager l'appareil avec un autre compte ?

Oui je peux le partager, avec l'application ewelink vers un autre compte.
c'est une page en langue italienne, mais la personne a bien détaillé le plugin.
Si cela peut vous aider : https://lamiacasaelettrica.com/sonoff-nspanel/

**Comment by bwp91** [comment]
> Oui je peux le partager, avec l'application ewelink vers un autre compte.

Would you be happy to share to my ewelink account so I can see if I can see any data I can add to the plugin?
Which country do you live in?

**Comment by Cvoju** [comment]
> > Oui je peux le partager, avec l'application ewelink vers un autre compte.
> 
> Seriez-vous heureux de partager sur mon compte ewelink afin que je puisse voir si je peux voir des données que je peux ajouter au plugin ? Dans quel pays vis-tu?

France, j'ai whatsapp au cas ou
Oui je veux bien le partager et avoir de l'aide. merci

**Comment by Cvoju** [comment]
***@***.***é : 16 décembre 2021 à 20:04de : Ben ***@***.***>à : bwp91/homebridge-ewelink ***@***.***>cc : Cvoju ***@***.***>, Mention ***@***.***>objet : Re: [bwp91/homebridge-ewelink] Sonoff SNpanel (Issue #326) Oui je peux le partager, avec l'application ewelink vers un autre compte.Would you be happy to share to my ewelink account so I can see if I can see any data I can add to the plugin? Which country do you live in?—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by bwp91** [comment]
If you can share the device to this ewelink account:

This would be super helpful! I'm very happy to message on Discord:
https://discord.gg/cMGhNtZ3tW

**Comment by Cvoju** [comment]
> Si vous pouvez partager l'appareil avec ce compte ewelink :
> 
> Ce serait super utile ! Je suis très heureux d'envoyer un message sur Discord : https://discord.gg/cMGhNtZ3tW

C'est Fait

**Comment by bwp91** [comment]
Thanks, I can see the device in the homebridge data will be possible to add it.

However, I am not sure which accessory type to display it as? A temperature sensor? What do you think would be best?

**Comment by bwp91** [comment]
Also, whats your username on discord?

**Comment by Cvoju** [comment]
> Et quel est ton pseudo sur Discord ?

Creux6frrr

**Comment by Cvoju** [comment]
Solution trouvé par @bwp91 , le sonoff NSpannel fonctionne avec AppleHome. Actuellement j'utilise la version homebridge-ewelink v8.7.2-beta.16. Merci a Lui !
