### ISSUE TITLE
SONOFF SwitchMan Smart Wall Switch-M5 - 3 Gang, 86 Apple HomeKit

### ISSUE THREAD

**Issue by alsolaim94** [bwp91/homebridge-ewelink#328]
### What issue do you have? Please be as thorough and explicit as possible.

I had installed the new SONOFF SWITCHS (SONOFF SwitchMan Smart Wall Switch-M5 - 3 Gang, 86)
 It it working in eWeLink app however it doesn’t work with Apple HomeKit.
 
### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 
 
 HOOBS

* Which version of Homebridge/HOOBS do you have?

Version : 4.0.110
Node version :14.18.2

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

8.7.1 (latest)

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

* Do you use your main eWeLink credentials or do you use a secondary eWeLink account for Homebridge?

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @alsolaim94 

Can you update to the beta version of the plugin? Instructions for HOOBS here:
https://github.com/bwp91/homebridge-ewelink/wiki/Beta-Version#hoobs-4

This device **should** then start working.

Do you know if the device supports LAN mode?

**Comment by alsolaim94** [comment]
Hey @bwp91 ,

Thank you for your quick response and support.

I have had upgraded the eWeLink plug to the beta version and it worked in Apple HomeKit. However, it shows 3 Gang switch, instead of 1 Gang.

The log for the switch I have mentioned was 1 Gang switch not 3 Gang like what I wrote in the subject(SORRY, I have more than 40 switch).

Regarding your question"Do you know if the device supports LAN mode?"
Yes it does support LAN Mode.

**Comment by bwp91** [comment]
Do you own the 3 gang model too? If you do, can you show me the line in the log as you did for the 1 gang above?

**Comment by bwp91** [comment]
8.7.2-beta.18 should switch this from 3-gang to 1-gang. 

You will probably however need to remove the existing accessories from the cache as the plugin won't automatically remove them.

**Comment by alsolaim94** [comment]
Thank you very much.

I cleared the catch, however I noticed all my previous 63 switches including the new switch turn to "Accessories No Response"

Does clearing the catch will clear all previous configured devices?

**Comment by bwp91** [comment]
You only need to remove from the cache the 4 accessories created for this new wall switch.

Do you own the three gang version too?
