### ISSUE TITLE
Unable to uninstall

### ISSUE THREAD

**Issue by dorminyk** [bwp91/homebridge-ewelink#331]
> 

### What issue do you have? Please be as thorough and explicit as possible.
Unable to install plugin with HOOBS

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 
HOOBS

* Which version of Homebridge/HOOBS do you have?
1.3.4 / 4.0.110

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?
Had 8.9.0 and tried to uninstall plugin all the way down to 8.7.0

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.
NA

* Do you use your main eWeLink credentials or do you use a secondary eWeLink account for Homebridge?
na

### Please paste any relevant logs below.

9:46:52 AMyarn remove v1.22.10
9:46:52 AM[1/2] Removing module homebridge-ewelink...
9:46:52 AMerror This module isn't specified in a package.json file.
9:46:52 AMinfo Visit https://yarnpkg.com/en/docs/cli/remove for documentation about this command.

```

```

**Comment by bwp91** [comment]
Are you still having trouble installing this or did you manage it in the end?

**Comment by dorminyk** [comment]
I ended up ditching HOOBs and configured Homebridge…. 

I still have my HOOBs SD Card unchanged though…

**Comment by bwp91** [comment]
Ah, is it working okay on homebridge?

**Comment by dorminyk** [comment]
Haven’t installed on HomeBridge yet. At this point I don’t plan on installing it…
