### ISSUE TITLE
After the update, the problem with running the plugin

### ISSUE THREAD

**Issue by motogon** [bwp91/homebridge-ewelink#332]
### What issue do you have? Please be as thorough and explicit as possible.

After the update 8.9.1 , the problem with running the plugin .
All devices are no longer available 

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
(3) HOOBS

* Which version of Homebridge/HOOBS do you have?

HOOBS 3 версия | 3.3.12
Node Version | 14.18.1

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

linux

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

8.9.1 There were no problems before upgrading to version 8.9.1.

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

sonoff mini 

### Please paste any relevant logs below.

05.01.2022, 17:28:16 [eWeLink] Initializing eWeLink platform...
05.01.2022, 17:28:16 [eWeLink] ***** Disabling plugin. *****
```

```

**Comment by bwp91** [comment]
Hi,

Please can you try reinstalling the plugin?

**Comment by Stewart06** [comment]
Ce n’est pas vraiment une solution que de désinstaller le plugin et d’ensuite le réinstaller.
N’oublions pas que nous créerons des automatisations sur HomeKit avec les accessoires SonOff. Cela est compliqué de devoir tout recréer à chaque fois.

It's not really a solution to uninstall the plugin and then reinstall it.
 Remember, we'll be creating automations on HomeKit with SonOff accessories.  It's complicated to have to recreate everything each time.

**Comment by bwp91** [comment]
> It's not really a solution to uninstall the plugin and then reinstall it.
> Remember, we'll be creating automations on HomeKit with SonOff accessories. It's complicated to have to recreate everything each time.

Reinstalling doesn't mean you need to lose the accessory cache. It's possible to simply reinstall the plugin without uninstalling both via the Homebridge UI and the HOOBS UI.

I have seen this issue recently a couple of times in HOOBS where the plugin logs show

> 05.01.2022, 17:28:16 [eWeLink] Initializing eWeLink platform...
> 05.01.2022, 17:28:16 [eWeLink] ***** Disabling plugin. *****

Without any further info why the plugin is disabling. I am sure it is an issue with the installation of the plugin rather than the plugin itself. As a reinstalling has helped in every case I have seen.

**Comment by Stewart06** [comment]
J’ai actuellement changé la version du plugin sur la version précédente à l’aide de l’application HomeManager.

**Comment by motogon** [comment]
uninstalled the plugin and reinstalled it 
The problem remains . 

06.01.2022, 13:57:32 [eWeLink] Initializing eWeLink platform...
06.01.2022, 13:57:32 [eWeLink] ***** Disabling plugin. *****

**Comment by motogon** [comment]
hoobs -d  |grep eWeLink
[06.01.2022, 14:06:19] Registering platform 'homebridge-ewelink.eWeLink'
[eWeLink] Initializing eWeLink platform...
[eWeLink] ***** Disabling plugin. *****

there is nothing else in the logs ( debug mode )

**Comment by motogon** [comment]
returned the version 8.5.0
it all worked 

06.01.2022, 14:18:09 [eWeLink] Web socket host received [eu-pconnect4.coolkit.cc].
06.01.2022, 14:18:09 [eWeLink] Sending WS login request.
06.01.2022, 14:18:09 [eWeLink] LAN discovery starting.
06.01.2022, 14:18:09 [eWeLink] WS login successful.
06.01.2022, 14:18:12 [eWeLink] LAN discovery complete.
06.01.2022, 14:18:12 [eWeLink] LAN monitoring started.06.01.2022, 14:18:12 [eWeLink] [Кухня] FGS addWriter().
06.01.2022, 14:18:12 [eWeLink] [Кухня] FGH loading.
06.01.2022, 14:18:12 [eWeLink] [Кухня] FGS read file [/home/hoobs/.hoobs/etc/persist/denis-DH110_Кухня_persist.json].
06.01.2022, 14:18:12 [eWeLink] [Кухня] FGT new subscription.
06.01.2022, 14:18:12 [eWeLink] [Кухня] FGH registering events.
06.01.2022, 14:18:12 [eWeLink] [Кухня] initialising with options {"inUsePowerThreshold":0,"logging":"debug","showAs":"default"}.
06.01.2022, 14:18:12 [eWeLink] [Кухня] FGT addData() [{ status: 0, time: 1641467893 }] immediate [true].
06.01.2022, 14:18:12 [eWeLink] [undefined] FGT executeImmediateCallback().
06.01.2022, 14:18:12 [eWeLink] [Кухня] FG timer: callbackSwitch [{ time: 1641467893, status: 0 }] immediate [true].
06.01.2022, 14:18:12 [eWeLink] Starting global FGT [10 minutes].
06.01.2022, 14:18:12 [eWeLink] [Кухня] initialised and found locally with IP [192.168.3.12].
06.01.2022, 14:18:12 [eWeLink] [Спальня с балконом] initialising with options

**Comment by bwp91** [comment]
Please can you try beta version 8.9.2-beta.0?

https://github.com/bwp91/homebridge-ewelink/wiki/Beta-Version
There's instructions for HOOBS there too.

Thanks!

**Comment by motogon** [comment]
sudo npm install homebridge-ewelink@beta -g
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'homebridge-ewelink@8.9.2-beta.2',
npm WARN EBADENGINE   required: { homebridge: '^1.3.9', node: '^14.18.2 || ^16.13.1' },
npm WARN EBADENGINE   current: { node: 'v14.18.1', npm: '7.6.0' }
npm WARN EBADENGINE }

changed 46 packages, and audited 47 packages in 9s

**Comment by bwp91** [comment]
I have just released an official update, v8.10.0. Please use the HOOBS UI to update to this version when it appears available. Let me know if things are fixed :)

**Comment by motogon** [comment]
![изображение](https://user-images.githubusercontent.com/12997195/148637887-ddd590cd-5aaa-426f-8849-88d8cb6591fe.png)

The version available in ui HOOBS 
8.5.0 published 1/7/2022 - 14 hours ago

**Comment by bwp91** [comment]
Have you considered updating to HOOBS 4?

**Comment by bwp91** [comment]
Within HOOBS 3 you should be able to run the following to properly update the plugin:

First stop the HOOBS service. This is important!

Then using the HOOBS terminal run these commands separately:

```bash
cd ~/.hoobs/
npm install homebridge-ewelink@latest
```

Then start the HOOBS service again

**Comment by motogon** [comment]
> 

could not find how to update HOOBS to version 4.xx on linux , on GitHub HOOBS 4.xx - only for Raspberry Pi

**Comment by motogon** [comment]
> 

> Within HOOBS 3 you should be able to run the following to properly update the plugin:

successfully updated the plugin.
Everything works . 
Thank you 


08.01.2022, 17:30:08 [eWeLink] Web socket host received [eu-pconnect3.coolkit.cc].
08.01.2022, 17:30:09 [eWeLink] Sending WS login request.
08.01.2022, 17:30:09 [eWeLink] LAN discovery starting.
08.01.2022, 17:30:09 [eWeLink] WS login successful.
08.01.2022, 17:30:12 [eWeLink] LAN discovery complete.
08.01.2022, 17:30:12 [eWeLink] LAN monitoring started.
08.01.2022, 17:30:12 [eWeLink] [Кухня] initialising with options {"inUsePowerThreshold":0,"logging":"debug","showAs":"default"}.
08.01.2022, 17:30:12 [eWeLink] [Кухня] initialised and found locally with IP [192.168.3.12] [1:MINI].
08.01.2022, 17:30:12 [eWeLink] [Спальня с балконом] initialising with options {"brightnessStep":10,"logging":"debug"}.
08.01.2022, 17:30:12 [eWeLink] [Спальня с балконом] initialised and LAN mode unavailable as not discovered/supported [36:KING-M4].
08.01.2022, 17:30:14 [eWeLink] ✓ Setup complete. Have time to give this plugin a review? http://bit.ly/hb-ewelink-review

**Comment by bwp91** [comment]
There are some docs here that might help you if you wanted to move to HOOBS 4. But it would require a fresh install, which obviously would mean re-setting up the plugins and accessories. I'm posting the link for your info, obviously if you are happy on HOOBS 3 and everything is working then perhaps you would prefer to keep it this way!

https://support.hoobs.org/docs/60e9f2ecdea381a881af7237

Thanks!

**Comment by Stewart06** [comment]
A question HOOBS 4.0 is still in beta?

 When is the official version released?

 Cordially.

Une question HOOBS 4.0 est toujours en version bêta ?

C’est quand la sortie de la version officielle ?

Cordialement.

Le 8 janv. 2022 à 15:37, Ben ***@***.***> a écrit :

﻿

Closed #332<https://github.com/bwp91/homebridge-ewelink/issues/332>.

**Comment by bwp91** [comment]
@Stewart06 HOOBS v4 has been out for a few months!

https://github.com/hoobs-org/HOOBS/releases

**Comment by Stewart06** [comment]
Pourquoi elle n’est pas disponible dans mon interface dans HOOBS ?

Cordialement.

Why is it not available in my interface in HOOBS?

 Cordially.

Le 8 janv. 2022 à 17:52, Ben ***@***.***> a écrit :

HOOBS v4 has been out for a few months!

**Comment by bwp91** [comment]
> Pourquoi elle n’est pas disponible dans mon interface dans HOOBS ? Cordialement. Why is it not available in my interface in HOOBS? Cordially. Le 8 janv. 2022 à 17:52, Ben ***@***.***> a écrit : HOOBS v4 has been out for a few months!

I don't know to be honest. You would get better support if you raised an issue with HOOBS directly at 

https://github.com/hoobs-org/HOOBS/issues
