### ISSUE TITLE
Please add new device to plugin

### ISSUE THREAD

**Issue by AnIHULI** [bwp91/homebridge-ewelink#333]
Could you please add this device?

[Light] is not supported, do create a GitHub issue with the following info:
[33] {"bindInfos":{"alice":["276850ac-4115-4952-a13c-3eb8ce92f0d9_eWeLinkAliceSmartHome"],"miot":["276850ac-4115-4952-a13c-3eb8ce92f0d9_ewelink-miot-v1"]},"version":7,"switch":"off","bright":100,"colorR":215,"colorG":226,"colorB":255,"mode":1,"light_type":2,"fwVersion":"3.0.0","rssi":-63}.

**Comment by bwp91** [comment]
Will have a look. could you find a web link to this device so I know what it is?
And a screenshot of how it looks in the ewelink app?
Thanks!

**Comment by AnIHULI** [comment]
> 

It is light Mangotek model: RLD60COE27

![photo_2022-01-06_14-57-05](https://user-images.githubusercontent.com/50448341/148393801-8b4835b4-e541-4d4b-94e9-d2fb1ddf533d.jpg)

![photo_2022-01-06_14-59-40](https://user-images.githubusercontent.com/50448341/148394131-3808e1e9-ab58-4d0f-b812-3f6a1d1172da.jpg)

**Comment by AnIHULI** [comment]
![photo_2022-01-06_14-59-40](https://user-images.githubusercontent.com/50448341/148394131-3808e1e9-ab58-4d0f-b812-3f6a1d1172da.jpg)

**Comment by bwp91** [comment]
and the device control page screenshot?

**Comment by AnIHULI** [comment]
Sure
![photo_2022-01-06_15-08-06](https://user-images.githubusercontent.com/50448341/148395335-c5ff324e-49bd-49c6-a5d7-5ac3f4754506.jpg)
![photo_2022-01-06_15-08-07](https://user-images.githubusercontent.com/50448341/148395336-9f77d4be-ca09-4713-bec8-1e8709b25729.jpg)

**Comment by bwp91** [comment]
Could you use the ewelink app to set a colour temperature (the blue to orange slider) then restart homebridge and get me the log entry the plugin shows like in your original message?

**Comment by bwp91** [comment]
Ignore my previous (now deleted) comment.

Can you update to the beta version of the plugin, 8.9.2-beta.1, and see if the light works?

https://github.com/bwp91/homebridge-ewelink/wiki/Beta-Version

Let me know!

**Comment by AnIHULI** [comment]
Hi @bwp91 

Thank you. It works now.
Im new in homebridge (1st use yesterday) and checked only on/off func.

Thanks again for quick reply and help

**Comment by bwp91** [comment]
Once you’re setup in the home app do check brightness and colour control too!

**Comment by AnIHULI** [comment]
> Once you’re setup in the home app do check brightness and colour control too!

For check this I should to select one of the devices in the devices list in the Settings->Light Devices, right?
I didnt see my device in the dropdown list.

**Comment by AnIHULI** [comment]
I checked in apple home app on ios brightness and color selection and it works. Can I manually add a circle with my own light or RGB circle?

**Comment by bwp91** [comment]
You can’t add more circles, you only have the adaptive lighting (?) one and the five others which you can change to your own personal colours.

**Comment by AnIHULI** [comment]
> You can’t add more circles, you only have the adaptive lighting (?) one and the five others which you can change to your own personal colours.

Ok thank you for reply. Adaptive lighting appears on home app. Didn't use yet.
