### ISSUE TITLE
Cannot configure and start on HOOBS 4

### ISSUE THREAD

**Issue by Rosemaryisme** [bwp91/homebridge-ewelink#335]
### What issue do you have? Please be as thorough and explicit as possible.

I had this running really easily yesterday but had to reinstall HOOBS this morning, now the plugin will not start. It seems to launch but then seems to be missing a module.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

HOOBS

* Which version of Homebridge/HOOBS do you have?

HOOBS 4.1.21, Homebridge 1.3.9 and node 16.13.2 On a Raspberry Pi. - see gyazo screenshot in link below

https://gyazo.com/48bf18b8b36800e6ba077419572c3f6c

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

See above

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

8.10.0 ... also tried the beta

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

SONOFF ZBridge and temperature/humidity sensor

### Please paste any relevant logs below.

11/01/2022, 14:35:45eWeLink BridgeeWeLinkWARNING***** Cannot find module 'es-abstract/2021/IsCallable'
Require stack:
- /var/lib/hoobs/ewelinkbridge/node_modules/promise.prototype.finally/implementation.js
- /var/lib/hoobs/ewelinkbridge/node_modules/promise.prototype.finally/index.js
- /var/lib/hoobs/ewelinkbridge/node_modules/websocket-as-promised/src/requests.js
- /var/lib/hoobs/ewelinkbridge/node_modules/websocket-as-promised/src/index.js
- /var/lib/hoobs/ewelinkbridge/node_modules/homebridge-ewelink/lib/connection/ws.js
- /var/lib/hoobs/ewelinkbridge/node_modules/homebridge-ewelink/lib/index.js
- /usr/lib/hoobsd/node_modules/homebridge/lib/plugin.js
- /usr/lib/hoobsd/services/plugins.js
- /usr/lib/hoobsd/services/bridges.js
- /usr/lib/hoobsd/main.js
- /usr/bin/hoobsdRequire stack:. *****

```

**Comment by bwp91** [comment]
Hi @Rosemaryisme 

This looks like an issue with the installation of the plugin rather than the plugin itself.

Can you try reinstalling? Actually uninstall the plugin (and delete the bridge if it’s on its own) and start again?

Thanks

**Comment by Rosemaryisme** [comment]
Yes, it was the first thing I tried. I removed the plugin and bridge and tried again. Also I tried creating a bridge for the beta version of the plugin. It looks as if something is missing. To be sure I rebuilt HOOBs as well and even forced an update too but still exactly the same.

**Comment by bwp91** [comment]
Have you managed to get this fixed at all? If not please try the following:

* Delete the ewelink bridge
* Run the following from the hoobs terminal:
    ```
    sudo yarn cache clean
    ```
* Reinstall plugin to its own bridge

I hope this will get things working again :)
