### ISSUE TITLE
Isolate Ewelink Homes for separate Homebridge setups

### ISSUE THREAD

**Issue by iBaird44** [bwp91/homebridge-ewelink#336]
* **Please explain your feature request in a one or two sentences.**
I have 2 homes with Ewelink items and Homebridge running. I would prefer not to have all devices show up in HomeKit for each location.

* **Is your feature request related to a problem? Please describe.**

No, other than HomeKit showing devices from another home

* **Any particular eWeLink devices that this relates to?**
not in particular, more a general thing

* **Anything else?**
nope

**Comment by bwp91** [comment]
Hi @iBaird44 
Thanks for this suggestion.
Please update to the beta version of the plugin:
https://github.com/bwp91/homebridge-ewelink/wiki/Beta-Version
Then restart Homebridge. When the plugin loads, you will see a list of your ewelink homes along with the ID.
If you copy the id of the home you want to ignore, then go to the plugin settings and expand the 'Advanced Settings'.
You will see a new field called 'Ignore Homes'.
Paste the home id in that box then restart Homebridge again.
You should find the devices for that home are then removed from Homebridge.
Hope this helps!

**Comment by iBaird44** [comment]
That works great, thanks!
