### ISSUE TITLE
Device logged as offline but seems to work

### ISSUE THREAD

**Issue by iBaird44** [bwp91/homebridge-ewelink#337]
### What issue do you have? Please be as thorough and explicit as possible.

I've just added a DW2 WiFi door sensor to my eWelink devices, the Sensor works fine in the eWelink App and comes up on my iOS App but there is an error that comes up while home bridge boots up.

* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

I'm Running Homebridge version 1.3.9 on a Mac-Mini 
Node.js Version | v16.13.1

I just installed the Beta Version Today, 

Although the sensor seems to work this is the Log for the sensor...

[1/12/2022, 3:20:52 PM] [eWeLink] [Garage Entrance] initialising with options {"logging":"debug","lowBattThreshold":25,"showAs":"default"}.
[1/12/2022, 3:20:52 PM] [eWeLink] [Garage Entrance] has been reported [offline] via WS.
[1/12/2022, 3:20:52 PM] [eWeLink] [Garage Entrance] initialised and LAN mode unavailable as not discovered/supported [102:DW2-Wi-Fi].

```

**Comment by bwp91** [comment]
Hi @iBaird44 

I believe that these devices go into some sleep mode and 'wake up' when the contact status changes. It is during this sleep mode time that ewelink reports the device as offline, even though it isn't really.

The plugin is simply reporting the reported status of the device. For the DW2 and certain Zigbee devices (devices that are battery powered), this status the plugin status can't really be relied upon!

**Comment by iBaird44** [comment]
Thank you for taking the time to clarify, it was an oddity to me seeing how the device was working as intended yet coming up with an error.
