### ISSUE TITLE
EWeLink login error

### ISSUE THREAD

**Issue by Damianod27** [bwp91/homebridge-ewelink#338]
I have had a problem with the Ewelink plug for two days.  The problem occurs with versions: 8.10.0 and 8.11.0.  as well as on Node.js 16.3.1 and 16.3.2. Before that, there was never any problem.  I am sending photos below.

![C3CE5778-DC5A-4841-A4A2-6EE6F65284AA](https://user-images.githubusercontent.com/79320859/149595720-5bc2d077-5ee7-4c1b-964d-e87434acefad.jpeg)
![B68F36AA-2880-4CC6-8CF8-20287790883C](https://user-images.githubusercontent.com/79320859/149595725-d5119958-5865-4daa-9914-c6f66ab6f40a.jpeg)

**Comment by bwp91** [comment]
Hi @Damianod27 

I believe there has been issues with the ewelink servers the last couple of days. A lot of users reporting issues.

**Comment by Damianod27** [comment]
I made a report because the application works without any problems all the time.  If it were otherwise, I would not have made a report.  I didn't know about these problems with EWeLink servers.  Probably that's the reason.  Thank you

**Comment by antlaranjeira** [comment]
Hello, same in here since yesterday. 
home bridge can’t control EWeLink devices, but via app EWeLink they work perfect.()
![5E94609F-C1B1-46B8-B456-66D3B845B0A2](https://user-images.githubusercontent.com/97782721/149615743-c8a4ff0a-842c-4142-a4b0-dabf305ea350.png)

**Comment by Phoenix-DH** [comment]
Same here 🤷🏼‍♂️ Devices are working with ewelink app … but are also reportung there that they are offline.

**Comment by bwp91** [comment]
Gonna close this as I believe the server issues have been fixed, any further problems please let me know.

Thanks for reporting!
