### ISSUE TITLE
Can not determine Token

### ISSUE THREAD

**Issue by fiska1** [bwp91/homebridge-ewelink#34]
Hi. How do you determine the Token? I do everything according to the description, the Certificates are on the iPhone and MacBook. Charles sees the connection but in the eu-ota string.coolkit.cc: 8080 says "unknown". Maybe in Russia it is impossible to do? Write, can I that do not so? Thanks.

**Comment by rikray02** [comment]
Try with that:
        "apiHost" : "eu-api.coolkit.cc:8080",
        "webSocketApi" : "eu-pconnect3.coolkit.cc"
Richard

**Comment by br0wnskinnedb0y** [comment]
Hi, I cannot get the authenticationToken as well despite following all the instructions. It says 

Failure | Client SSL handshake failed - Remote host closed connection during handshake

**Comment by fiska1** [comment]
Hi. That didn't help either.. All conditions are met-there is no result..  Maybe there is another program for Mac OS defining Token ? Prompt.

**Comment by Caribsky** [comment]
@fiska1 
Try this config:
"apiHost": "eu-api.coolkit.cc:8080",
"webSocketApi": "eu-ruslong.coolkit.cc"

—
eu-pconnect3.coolkit.cc - not working in Russia (for me)

**Comment by fiska1** [comment]
Вы вводите в Чарли «webSocketApi»: «eu-ruslong.coolkit.cc» ? В какое меню настроек? Пробовал везде, результата нет..

**Comment by Caribsky** [comment]
@fiska1 
sorry, «webSocketApi»: «eu-ruslong.coolkit.cc» - это для homebridge 

**On  the device, set your HTTP proxy to use Charles, and then browse to http://www.charlesproxy.com/getssl to install the certificate.**

Нужно установить сертификат на iphone. Включить прокси на телефоне, и в браузере на телефоне перейти http://www.charlesproxy.com/getssl 
Согласиться установить сертификат. 

see
https://www.charlesproxy.com/documentation/faqs/
https://www.charlesproxy.com/documentation/using-charles/ssl-certificates/

**Comment by fiska1** [comment]
Thanks. I already did that right away.. Certificates are installed on the MacBook and IPhone, and Proxy SSL added eu-api.toolkit.cc: 8080 Charles sees the connection but writes-"unknown". SSL-enabled So I do not understand what could be the matter..

**Comment by fiska1** [comment]
eu-api.coolkit.cc:8080

**Comment by Caribsky** [comment]
Try this:
In Charles.. select https://eu-ota.coolkit.cc:8080 , click right mouse button, then select  "Enable SSL Proxying". 
Do same with eu-api.coolkit.cc:8080

**Comment by fiska1** [comment]
I did it immediately, in the SSL settings..

**Comment by fiska1** [comment]
br0wnskinnedb0y  the same situation and the same question

**Comment by Caribsky** [comment]
@fiska1 
Actually, I don't know… correct settings. 
Do you have antivirus software and/or firewall ? Try to disable it.
And last advice … close Charles, reboot iphone and try again

**Comment by Caribsky** [comment]
By the way.. check Charles certificate on iPhone 

![img_1386](https://user-images.githubusercontent.com/37780308/44950762-7d2d9480-ae61-11e8-9bcf-1bcd2b9196e3.PNG)

**Comment by fiska1** [comment]
There is no anti-virus program, the Firewall in the settings of the MacBook-turned off, rebooting the IPhone and MacBook-did... Before opening the question here read about Charlie (the links you gave me too) . Tomorrow I'll try to install Charlie on Windows and try.. I haven't.. The iPhone Trust is included..Thank you very much for your help!!

**Comment by fiska1** [comment]
I write through an interpreter.. You speak Russian?

**Comment by fiska1** [comment]
На Айфон сертификат установлен и доверие включено.. Об этом тут прочитал до открытия вопроса о своей проблеме..

**Comment by Caribsky** [comment]
@fiska1 
Yes I do, I am Russian, but other users who read this … not :)

ps. я такую проблему видел только из-за сертификата ещё на iOS 9. Видимо криво встал. Жесткая перезагрузка телефона исправила.

**Comment by fiska1** [comment]
I figured as much... Yes ,XP did.. The only thing that confuses me, on a MacBook and IPhone there are beta versions of firmwares..Maybe even because of that??

**Comment by Caribsky** [comment]
May be… I don't use the beta firmwares. So many problems

**Comment by fiska1** [comment]
So I will try on another IPhone and for Windows PCs . Experienced many times and different options, only this and remained..

**Comment by RafaleD** [comment]
Same problem for me. I can't access to my token. Every thing is "unknow"
