### ISSUE TITLE
Won't connect keeps saying reset hub which I've done

### ISSUE THREAD

**Issue by birdman100** [bwp91/homebridge-ewelink#340]
### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

* Which version of Homebridge/HOOBS do you have?

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @birdman100 

Gonna need a bit more info, when does this message appear? and where?
