### ISSUE TITLE
Option to disable timer for valve simulation

### ISSUE THREAD

**Issue by mpochin** [bwp91/homebridge-ewelink#342]
Homebridge UI-X. V 1.4.0. Raspberry Pi
Plugin Version 0.5.0. (homebridge-ewelink)

When setting a Single Channel device showAs="valve" somehow sets a timer of 120 seconds.
This value can not be edited in the settings of the accessory.
So when you turn on the Valve it turns off after 2 minutes.
After deleting the showAs parameter the 120 second timer not showing any more.

Marcelo

**Comment by bwp91** [comment]
Hi @mpochin 

The valve accessory type is normally used when needing to set a timer, for example the 120 seconds that is the default. This timer should be editable within the home app, there should be a selection of different time lengths.

Are you looking for simply an ON/OFF valve accessory type with no timer?

**Comment by mpochin** [comment]
hi @bwp91 
Correct, just on/off valve without timer.

Thanks

**Comment by bwp91** [comment]
@mpochin 

Are you able to update to the beta version of the plugin? and then restart.
https://github.com/bwp91/homebridge-ewelink/wiki/Beta-Version

Then in the plugin settings you should see underneath the simulation option, an option to disable the timer. Can you enable this and restart again?

I haven't tested this code change yet so I'm hoping it works first time without any errors! Keep an eye on the homebridge log for any errors that might appear.

Let me know how you get on!

**Comment by mpochin** [comment]
works great!!!!
steps
1. update to beta version
2.  setup single channel accessory and click to ignore timer
3.  changed showAs to valve
4.  clear all cachedaccesories from homebridge settings
5.  restart HB

Done

Thanks a lot
Marcelo

**Comment by mpochin** [comment]
Hi @bwp91 
I think there is a possible bug, the valve only reports when is running in HB.
The log only shows "current state [running]", it doesn't show when it stops.

Thanks

**Comment by bwp91** [comment]
How are you stopping the valve? Through the home app or through the ewelink app?

**Comment by mpochin** [comment]
ewe link app

**Comment by bwp91** [comment]
Hi @mpochin 

Can you update to the newest beta version to see if the logging has been fixed when turned off?

**Comment by mpochin** [comment]
Hi,
Now it shows the "current state [stopped]" twice.

Thanks
Marcelo

**Comment by bwp91** [comment]
In the new version of this plugin, it should now only log once when you turn it off from ewelink app.

**Comment by bwp91** [comment]
Closing this as I believe this is complete
