### ISSUE TITLE
Clear accessory

### ISSUE THREAD

**Issue by marcgrc** [bwp91/homebridge-ewelink#344]
can i delete only some accessories so as not to show them in the homebridge?

**Comment by MoTechnicalities** [comment]
> can i delete only some accessories so as not to show them in the homebridge?

Yes. Take note of the device ID, then look for the setting that is listed for each device.

![image](https://user-images.githubusercontent.com/68468472/152078712-db2165f5-3cb5-4a0d-86b9-ff1cfc291716.png)

**Comment by marcgrc** [comment]
Thank you

**Comment by bwp91** [comment]
thanks for helping here @MoTechnicalities 
gonna close this, assuming @marcgrc you got what you needed
