### ISSUE TITLE
Feature request - Hide fan light icon

### ISSUE THREAD

**Issue by viictor924** [bwp91/homebridge-ewelink#347]
Hi,

I'm using a Sonoff iFan04 to connect my Fan to homekit via the homebridge-ewelink plugin
https://www.amazon.com/dp/B09C21LX9R

Would it be possible to have a boolean in the config.json that will enable/disable interaction with the fan light? I've got hue bulbs in my ceiling fan so the fan light has to be on at all times to transmit power to the hue bulbs. However, it's confusing/redundant to have two light icons in the Home app: one for the hue bulbs and one for the ceiling fan light. I think Apple should give us the ability to show/hide icons in the Home app, but they don't. So I think a fix within the plugin is the only solution. 

It also makes the Home app show "Bedroom light on." at all times even though the hue bulbs are off.

![image](https://user-images.githubusercontent.com/23468631/153695775-c4a860b5-7b63-4ec9-98b7-3c9a6d9fe08b.png)

* **Please explain your feature request in a one or two sentences.**
Remove iFan's light icon from HomeKit. Light should always be set to ON so that the Hue bulbs always maintain power. 

* **Is your feature request related to a problem? Please describe.**
I've got hue bulbs in my ceiling fan so the fan light has to be on at all times to transmit power to the hue bulbs. However, it's confusing/redundant to have two light icons in the Home app: one for the hue bulbs and one for the ceiling fan light. I think Apple should give us the ability to show/hide icons in the Home app, but they don't. So I think a fix within the plugin is the only solution. 

* **Any particular eWeLink devices that this relates to?**
Sonoff iFan04
https://www.amazon.com/dp/B09C21LX9R

* **Anything else?**

**Comment by bwp91** [comment]
Hi @viictor924 

This option already exists :)

<img width="422" alt="Screenshot 2022-02-12 at 11 07 55" src="https://user-images.githubusercontent.com/43026681/153708879-7b0ccb6f-13c8-4f31-819a-ee6888baac50.png">

**Comment by viictor924** [comment]
Ah, I had checked the settings but there wasn't anything for "hide light" because I hadn't manually added the fan. The fan got added to HomeKit automatically when I installed the plug-in so I didn't know I had to add it manually in settings. 
<img width="779" alt="image" src="https://user-images.githubusercontent.com/23468631/153727074-c6ff1e00-5f81-47c5-aafb-2478b24ea416.png">

Anyway, I've added and enabled the hide light setting and now it's working like a charm! Thanks a bunch!

Easiest feature request resolution!

**Comment by bwp91** [comment]
Yes all devices will be added to homebridge, the config is only needed if you want to change these little settings per device.

The options are hidden at first so that a device id is definitely entered. A lot of people didn’t bother otherwise and wondered why it wasn’t working!

**Comment by bwp91** [comment]
Glad it’s working well!
