### ISSUE TITLE
MINIR3 + S-MATE

### ISSUE THREAD

**Issue by xnonim** [bwp91/homebridge-ewelink#351]
* **Please explain your feature request in a one or two sentences.**

I'm asking for support the new MiniR3 and the S-mate

* **Is your feature request related to a problem? Please describe.**

No

* **Any particular eWeLink devices that this relates to?**

Mini R3 + S-mate

* **Anything else?**

Thanks!!

**Comment by bwp91** [comment]
Difficult to know without someone owning this device and letting me know.

It should be possible to implement - unless you own the device I can't guarantee functionality.

**Comment by xnonim** [comment]
Well, I'm gonna buy a pair and see what's going on, thanks for the amazing plug-in!!

**Comment by bwp91** [comment]
Please let me know how you get on with the MINIR3 with the plugin!

**Comment by xnonim** [comment]
> Please let me know how you get on with the MINIR3 with the plugin!

I'm just waiting for it to arrive (I'm in South America so it will take a little), but be sure I'll tell you how it works.

**Comment by xnonim** [comment]
The package arrives just yesterday, I'm going to install it and tell...

**Comment by xnonim** [comment]
ok, im so sorry all the delay, too much work so...
I've installed the r3 and the s-mate, the r3 working as expected, the only thing im getting , sometimes it fails to communicate with homebridge, I have to restart hombridge to make it work again.

other hand, the s-mate doesn't even appear in the "my devices" tab, so there isn't too much to say.
In the ewe link app It appears as an individual device, but to add it to the app, it is necessary to have an r3, sonoff says in the future will be more devices compatibles to the s-mate.
![IMG_0402](https://user-images.githubusercontent.com/61104752/163527868-f24c1add-dd40-4e10-819c-8549ce55b297.jpg)

I think my "report" is very weak, so im open to any question from anybody. thanks for this amazing plugin

**Comment by bwp91** [comment]
When you restart Homebridge, look at the logs when your devices are listed out, you may see an entry for the S-Mate with some data saying please show the following info on github.

**Comment by xnonim** [comment]
Ok, here it is:

[4/15/2022, 2:54:38 AM] [eWeLink] [S-MATE centro] is not supported, do create a GitHub issue with the following info:
[177] {"bindInfos":{"scene":2},"subDevId":"8de20570","parentid":"100143a07d","bleAddr":"8DE20570","outlet":1,"key":0,"count":93,"actionTime":"2022-04-15T04:37:19.147Z"}.

**Comment by bwp91** [comment]
Thanks, are you able to now update to the beta version of the plugin and restart? The device should then appear and be added to Home app but will currently show as Unsupported.

Are you then able to use the ewelink app to control it a couple of times and show me the logs that appear in homebridge?

PS I've just sent you a message on Discord if you are still on there? might be easier?

**Comment by xnonim** [comment]
I've just update to 8.13.3 beta 0, exactly as you said, now it appear in my devices, and in the home app, it says incompatible.

About discord, yeah I don't use it regularly, but I have it open if it's easier for you, but I don't have any message.

**Comment by xnonim** [comment]
I've just update to 8.13.3 beta 0, exactly as you said, now it appear in my devices, and in the home app, it says incompatible.

About discord, yeah I don't use it regularly, but I have it open if it's easier for you, but I don't have any message. My user name is xnonim#7858

About using the s-mate in the eWeLink app, it is not possible, it's not like a button, it just save a log of when it is pressed down, that's all. I can't turn on or off the s-mate.
https://user-images.githubusercontent.com/61104752/163542386-ad8c17f9-5c42-46ef-858e-0ec6761b936d.MOV

**Comment by bwp91** [comment]
Ahh okay maybe I won’t be able to implement this device into homebridge after all. Since there is no real functionality except for the logs in the ewelink app, there’s no way to show this info in the home app.

With regards to the MINIR3, does this device work with the plugin?

**Comment by hpstuff** [comment]
hey @bwp91 I also have mini r3 and s-mate this device has a 3 channels (triggers) that are used in ewelink to trigger scene based on those triggers. Idk if we can use it like this in HomeKit.

**Comment by bwp91** [comment]
hi @hpstuff thanks for your input here.

So does the MINIR3 have different modes you can choose in the ewelink app?

I think it would help if I actually really understood how this device works and when paired with an S-Mate!

**Comment by hpstuff** [comment]
MINIR3 is just a regular relay (that include the ability to act as a remote gateway) s-mate is remote controller that has 3 lines of inputs (channels). You just connect the s-mate to the MINIR3 and then you can use those 3 lines (channels) to trigger scenes.

This is a scene setup example that I have in ewelink app. When channel1 is clicked to toggle to MINIR3.
![IMG_4708](https://user-images.githubusercontent.com/2339434/163577150-8c4a0577-d2b5-4d02-a782-e014fe00e76c.PNG)
 

and you can use the rest of the channels to trigger other scenes.

**Comment by bwp91** [comment]
I see, so the only way to trigger these scenes is within the ewelink app?

**Comment by xnonim** [comment]
> I see, so the only way to trigger these scenes is within the ewelink app? 

Yes, I think. As @hpstuff said, it need the r3 to use it as a gateway, but making scenes in the eWeLink app you can control other devices with the s-mate.

**Comment by bwp91** [comment]
It would probably be possible to expose 3 switches to homekit to activate these scenes.

@xnonim if you activate one of the scenes in the ewelink app, does anything appear in the homebridge log?

**Comment by hpstuff** [comment]
@bwp91 actually the only way to create those scenes is in within the app. They are triggered by the s-mate will be great if we have it in HomeKit so we can use it to trigger other things.

**Comment by bwp91** [comment]
Id definitely need to see logs when an s-mate scene is activated to know how to mimic is from the plugin

**Comment by xnonim** [comment]
> It would probably be possible to expose 3 switches to homekit to activate these scenes.
> 
> 
> 
> @xnonim if you activate one of the scenes in the ewelink app, does anything appear in the homebridge log?

Just checked and activated the debug mode in hb, but no, nothing logs when activate the scene in the app

**Comment by bwp91** [comment]
What happens if you try with wifi and bluetooth disabled on your phone?
I don't exactly know how these devices connect but I think this is worth a try!

**Comment by xnonim** [comment]
The s-mate as I understand send an RF signal to the r3 mini, and the r3 is who send the trigger via the eWeLink 
I had to go out of home so if you can wait me about one hour I can do what you ask me before

**Comment by hpstuff** [comment]
@xnonim I think is something like this. I try to shutdown my network and the s-mate still trigger the minir3 but do not trigger my RFR2 (that's probably happed over network)

**Comment by bwp91** [comment]
There is definitely info that ewelink can provide:

https://github.com/AlexxIT/SonoffLAN/issues/731#issuecomment-1095115689

But it’s getting exactly the format of the data when a scene is activated that I ideally need to be able to replicate it

**Comment by xnonim** [comment]
Ok, what I got:
If I create a scene to activate another device using one of the channel of the s-mate, this is what I got:

[4/15/2022, 3:53:34 PM] [eWeLink] [S-MATE centro] receiving update {"outlet":1,"key":0,"online":true,"updateSource":"WS"}.
[4/15/2022, 3:53:34 PM] [eWeLink] New Command Received:
[4/15/2022, 3:53:34 PM] [eWeLink] {"outlet":1,"key":0,"online":true,"updateSource":"WS"}
[4/15/2022, 3:53:49 PM] [eWeLink] [R3 sala nro 3] current state [on].
[4/15/2022, 3:53:49 PM] [eWeLink] [S-MATE centro] receiving update {"outlet":0,"key":0,"online":true,"updateSource":"WS"}.
[4/15/2022, 3:53:49 PM] [eWeLink] New Command Received:
[4/15/2022, 3:53:49 PM] [eWeLink] {"outlet":0,"key":0,"online":true,"updateSource":"WS"}
[4/15/2022, 3:53:49 PM] [eWeLink] [Mini pieza selena] current state [on].

NOTE: here I'm pressing 2 channel of the S-mate, first one activating the r3 itself, the second one activating another device via eWeLink

**Comment by bwp91** [comment]
New beta of the plugin should add three switches to this accessory. And maybe (?) activate the scenes? It’s completely untested code so there might be an error or so that I have missed.

**Comment by hpstuff** [comment]
@bwp91 I can see it as a sensor now but don't have a hub so I can set up automation from the Home app, maybe @xnonim can help with this.

**Comment by xnonim** [comment]
> @bwp91 I can see it as a sensor now but don't have a hub so I can set up automation from the Home app, maybe @xnonim can help with this.

Sorry, don't get what you're trying to do. What hub are you talking about?
The automation to use the s-mate must be done in the accessory itself, not the "automation" tab.
![image](https://user-images.githubusercontent.com/61104752/163986677-f5837488-a130-4e9b-8042-7212021ade82.png)

**Comment by hpstuff** [comment]
@xnonim yeah the same,  but it's required a home hub.
<img width="200px" src="https://user-images.githubusercontent.com/2339434/163993158-3fe81e40-667e-436a-8cc6-02dc13fe173b.PNG" />
however did you manage to set some actions?

**Comment by xnonim** [comment]
> @xnonim yeah the same,  but it's required a home hub.
> 
> <img width="200px" src="https://user-images.githubusercontent.com/2339434/163993158-3fe81e40-667e-436a-8cc6-02dc13fe173b.PNG" />
> 
> however did you manage to set some actions?

Mmm weird, I don't have any hub, just hb running on my Nas, and the plug-in itself, @bwp91 maybe a bug?

**Comment by xnonim** [comment]
> > @xnonim yeah the same,  but it's required a home hub.
> > 
> > <img width="200px" src="https://user-images.githubusercontent.com/2339434/163993158-3fe81e40-667e-436a-8cc6-02dc13fe173b.PNG" />
> > 
> > however did you manage to set some actions?
> 
> Mmm weird, I don't have any hub, just hb running on my Nas, and the plug-in itself, @bwp91 maybe a bug?

**Comment by xnonim** [comment]
> @xnonim yeah the same,  but it's required a home hub.
> 
> <img width="200px" src="https://user-images.githubusercontent.com/2339434/163993158-3fe81e40-667e-436a-8cc6-02dc13fe173b.PNG" />
> 
> however did you manage to set some actions?

Maybe this is a dumb question, but, do you have the plug-in as a child? Or in the main? (With the hombridge).

And if you have it as a child, do you have that bridge added to the home app?

**Comment by bwp91** [comment]
@hpstuff 
Unfortunately the plugin isn't able to control the S-Mate ie is not able to activate one of the channels.
The plugin can only detect when one of the channels has been activated by other means.

This is the reason for the change from 3 switches to this 'stateless programmable button' accessory type.

Single press corresponds to channel 1, double press to channel 2 and long press to channel 3 of the S-Mate.

You could then set up actions within the Home app to control other HomeKit devices when one of the channels of the S-Mate is activated. But unfortunately without a Home Hub this is not possible.

**Comment by xnonim** [comment]
@bwp91 what do you mean with a home hub? I don't have any kind of hub in my home, and I can assign actions, and I only have the plug-in installed in my Nas, that's all.

**Comment by bwp91** [comment]
> @bwp91 what do you mean with a home hub? I don't have any kind of hub in my home, and I can assign actions, and I only have the plug-in installed in my Nas, that's all.

One of these: https://support.apple.com/en-us/HT207057

**Comment by bwp91** [comment]
Hi,
Closing this just as been a little overwhelmed with issues recently.
If this is still an issue or a feature you would like implemented then please do re-open this ticket!
Thanks for your understanding!
