### ISSUE TITLE
device update failed as it is unreachable at /homebridge/node_modules/homebridge-ewelink/lib/index.js:1788:19

### ISSUE THREAD

**Issue by azagramac** [bwp91/homebridge-ewelink#352]
### What issue do you have? Please be as thorough and explicit as possible.
`[2/16/2022, 3:45:12 PM] [eWeLink] [SmartPlug] device update failed as it is unreachable at /homebridge/node_modules/homebridge-ewelink/lib/index.js:1788:19.`

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
**1**

* Which version of Homebridge/HOOBS do you have?
**v1.4.0** 

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
**Node.js: v16.14.0 
NPM: v8.3.1** 

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?
**v8.12.0** 

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @AzagraMac 

This usually means the device is unreachable. Depends on what mode you're in...

If you're in lan mode it means the plugin tried to control the device but it didn't work (wifi issue or device changed ip?)

If you're in wan mode means that even the cloud can't connect to your device, again maybe wifi issue?

If in hybrid mode (lan+wan) means basically any of the above.

Check the ewelink app does it show the device is online?

**Comment by azagramac** [comment]
Good, thanks for the answer, from the eWelink App, I reach the device perfectly, but not from Homebridge? 

it happens to me with all Sonoff S20 plugs, not so with Basic or S26.

**Comment by bwp91** [comment]
Do you have the plugin in LAN mode or in AUTO mode (using both lan and cloud)?
