### ISSUE TITLE
SONOFF SwitchMan Scene Controller  R5

### ISSUE THREAD

**Issue by MoTechnicalities** [bwp91/homebridge-ewelink#355]
@bwp91 ,

I've not purchased one yet, but would like to know what the potential of supporting the SONOFF SwitchMan Scene Controller  R5 in the plugin to use as a HomeKit Scene button. To me it looks much more aesthetic than any other Scene button out there, but it is evidently not functioning thru ZigBee or WiFi, but possibly something like Bluetooth and needing another device with an "eWeLink Remote Gateway".

![image](https://user-images.githubusercontent.com/68468472/158056306-f1dfb4db-21e6-43cd-b487-780d23f5ee74.png)

Please, let me know your thoughts about support. Thanks.

**Comment by bwp91** [comment]
Does this not work through wifi as well as some local communication?

**Comment by bwp91** [comment]
It’s very hard to tell whether it can be implemented without someone having the device to share

**Comment by MoTechnicalities** [comment]
It says it uses the "eWeLink-Remote gateway". That probably mean it connects to a gateway like ZigBee, z-wave and Thread devices do. Doubt it uses wifi itself to connect. The M5 switch is pictured as a device that provides the gateway for the R5.
I guess time will tell.

**Comment by bwp91** [comment]
Looks like this device is wifi too.
The plugin is alerted when a button is pressed: useful for adding extra automations in homekit.
However the plugin cannot simulate and “send” a command as if a button were pressed.
Hope this makes sense!

**Comment by bwp91** [comment]
Hi,
Closing this just as been a little overwhelmed with issues recently.
If this is still an issue or a feature you would like implemented then please do re-open this ticket!
Thanks for your understanding!
