### ISSUE TITLE
IOS 15.4 and siri

### ISSUE THREAD

**Issue by vitorpt21** [bwp91/homebridge-ewelink#356]
### What issue do you have? Please be as thorough and explicit as possible.
Can´t tell siri to turn off device in 10 minutes

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
* Hoobs

* Which version of Homebridge/HOOBS do you have?
4.0.104

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry
node 16.14.12

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?
8.13.0

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
what’s the response from siri?

**Comment by vitorpt21** [comment]
It says: Sorry but I can't schedule that to you.

**Comment by doctornakhare** [comment]
Greetings,

Yes I've tried doing that several times and thought it was not possible; only after reading this I now know that it can work.
Facing the same issue.

Details of setup:

Homebridge UI-X
Version - homebridge-config-ui-x v4.41.5

Windows 

Node js version v16.13.2.

Issue was from installation- came to know now

Which eWeLink device - Basic R2 [Firmware -3.5.1]

**Comment by vitorpt21** [comment]
With ios 15.4.1 it works again.
I've changed from hoobs to homebridge.
