### ISSUE TITLE
Status sensor

### ISSUE THREAD

**Issue by carlosptf** [bwp91/homebridge-ewelink#357]
* **Please explain your feature request in a one or two sentences.**

would it be possible to have an option to invert the status of a sensor?  I would like to simulate a socket with a contact sensor, but when it is on, show as sensor closed.

* **Is your feature request related to a problem? Please desc

* **Any particular eWeLink devices that this relates to?**

* **Anything else?**

**Comment by bwp91** [comment]
Hi @carlosptf which sensor in particular (model number) are you referring to?
