### ISSUE TITLE
SONOFF E27 bulb RGBW is not supported

### ISSUE THREAD

**Issue by DeltaFox0018** [bwp91/homebridge-ewelink#358]
### What issue do you have? Please be as thorough and explicit as possible.

SONOFF E27 bulb is not supported by plugin

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
1.4.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Ubuntu 20.04.4 LTS
Node 16.4.2
Npm 8.6.0

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?
version 8.13.2
is the first time I use this plugin and I have installed the latest version available

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.
SONOFF B05-BL-A60
Firmware BL1-ALL-LED version 1.4.1

### Please paste any relevant logs below.

[Lampada ale] is not supported, do create a GitHub issue with the following info:
[136] {"bindInfos":{"gaction":["9a2d075b-03ce-4736-b2ca-cd1471b3cbfd_ewelinkGoogleHome"]},"version":8,"rssi":-85,"fwVersion":"1.4.1","switch":"on","ltype":"color","white":{"br":100,"ct":0},"remoteCtrlList":[],"lightScenes":[],"ssid":"ZyXEL_SSID","bssid":"a0:e4:cb:8a:07:6a","mac":"7c:b9:4c:1c:3b:c3","only_device":{"ota":"success","ota_fail_reason":0},"color":{"br":61,"r":23,"g":0,"b":255},"timers":[{"mId":"c400ab2a-c340-d6e2-5e9e-41626ba9fd34","type":"repeat","at":"30 21 * * 0,1,2,3,4,5,6","coolkit_timer_type":"repeat","enabled":1,"do":{"switch":"off"}}]}.

**Comment by bwp91** [comment]
Hi @DeltaFox0018 

Since this is a new device type, would you be happy to come onto discord so i can gather more info about how it works?

https://discord.gg/cMGhNtZ3tW

Thanks!

**Comment by bwp91** [comment]
Hi @DeltaFox0018 

Are you still using this bulb with this plugin?

**Comment by DeltaFox0018** [comment]
Hi @bwp91 

Yes I am using the plugin and it works very well

**Comment by bwp91** [comment]
In the ewelink app do you have the option for LAN mode for this device?

Also, can you tell from the Homebridge log if the plugin is using LAN mode or cloud mode when controlling? If you have some time, could you put the plugin into debug mode then try controlling the colour of the bulb via the Home app and also the colour temperature via the home app and show me the logs that appear?

Thanks for quick reply!

**Comment by DeltaFox0018** [comment]
Hello, LAN mode for this device has been activated on both the ewelink app and homebridge

At the time when I had opened the issue then we had written about discord and I had sent you some screen calls that made the app ewelink towards the buld
Now you need homekit calls to HomeBridge?

I have the betà of ios 16 is a problem?

**Comment by bwp91** [comment]
I was trying to find our messages on discord to check but I couldn’t seem to find them 😅 can you tell me your username on there or send me another message?

**Comment by DeltaFox0018** [comment]
I send a message on discord
