### ISSUE TITLE
PCIE computer switch

### ISSUE THREAD

**Issue by Eric-Dane** [bwp91/homebridge-ewelink#366]
* **Please explain your feature request in a one or two sentences.**

my devices has 3 channels:
channel 0:(like channel2,can't turn off)
channel 1:turn on/off computer,but current state always show off
channel2:show current state
use plugin "Multi Channel Devices",hide channels "0,2",but how to show current state?I just wanna show one button.

could add a current state setting?think you!

* **Any particular eWeLink devices that this relates to?**
Brand:coolkit
Model (UIID):0285 (2)

* **Anything else?**

**Comment by xnonim** [comment]
What device are you using? Don't recognize that model

**Comment by Eric-Dane** [comment]
> What device are you using? Don't recognize that model

![Snipaste_2022-04-30_22-12-20](https://user-images.githubusercontent.com/80730279/166138550-0dff0d44-66a7-45bc-8fcb-d6aea6560add.png)

**Comment by bwp91** [comment]
Can you show a screenshot of how this device
looks in the ewelink app?

**Comment by Eric-Dane** [comment]
![IMG_8483](https://user-images.githubusercontent.com/80730279/166178682-6cfe86d1-759b-46fa-9028-a185990f88ec.png)
![IMG_8484](https://user-images.githubusercontent.com/80730279/166178689-44b5e34c-fdbf-4f37-bf7c-0c6778c0b255.png)
![IMG_8485](https://user-images.githubusercontent.com/80730279/166178696-7252186c-8967-47ae-991e-ee0c8631e1ea.png)

**Comment by bwp91** [comment]
Thanks, and just to confirm, you use channel 1 to turn on and off the computer (and the state always shows as off)
and channel 2 shows on and off corresponding to computer being on and off?

**Comment by Eric-Dane** [comment]
> Thanks, and just to confirm, you use channel 1 to turn on and off the computer (and the state always shows as off) and channel 2 shows on and off corresponding to computer being on and off?

yes

**Comment by bwp91** [comment]
Hi,
Closing this just as been a little overwhelmed with issues recently.
If this is still an issue or a feature you would like implemented then please do re-open this ticket!
Thanks for your understanding!
