### ISSUE TITLE
I can't ignore POW R3. I do not want it to appear in the homekit

### ISSUE THREAD

**Issue by romanu417** [bwp91/homebridge-ewelink#369]
### What issue do you have? 
I don't want POW R3 to show in the homekit, 

part of code, it doesn't work (
"ignoredHomes": "1001432a0b,1001432a0bSWX",

* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
Homebridge v1.4.1

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? 
MacOS

* Which version of this plugin (homebridge-ewelink) do you have? 
homebridge-ewelink v8.15.0

* Which eWeLink devices do you have that are causing issues? 
Model (UIID)	POWR3 (32)

**Comment by bwp91** [comment]
Hi @romanu417 did you find the correct setting?
