### ISSUE TITLE
Wrong humidity value in Zigbee sensor

### ISSUE THREAD

**Issue by ojoaosemtil** [bwp91/homebridge-ewelink#370]
Is there a way to add some sort of offset to humidity and temperature measurements?

In these sensors I notice the humidity is like 10% higher than what’s supposed to be, comparing to other sensors.
The idea is to have the chance in the plug-in to adjust the error and send that info to HomeKit. Even if in the eWeLink it has the “official” measurements.

ZigBee Temperature and Humidity Sensor

Thank u very much!

**Comment by bwp91** [comment]
Hi @ojoaosemtil did you find the correct setting?

**Comment by ojoaosemtil** [comment]
Yes I found it! That’s why I closed the issue, sorry!
And thank you!
