### ISSUE TITLE
simulate garage door with sensor of other plugin

### ISSUE THREAD

**Issue by xnonim** [bwp91/homebridge-ewelink#372]
### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 

-config-ui

* Which version of Homebridge/HOOBS do you have?

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

* Do you use your main eWeLink credentials or do you use a secondary eWeLink account for Homebridge?

### Please paste any relevant logs below.

```

```
Hi, Im using a R5V1C as a garage door with a DW2 door sensor. it works ok, but the wifi sensor fails many times, without mention act slow.
now im using Zigbee sensors with a son off dongle plus 3.0, and connecting it using Zigbee2Mqtt to home bridge,

It is possible to use some of this sensor, as a sensor inside the ewe link plugin? 
thanks

**Comment by bwp91** [comment]
Hi,
Closing this just as been a little overwhelmed with issues recently.
If this is still an issue or a feature you would like implemented then please do re-open this ticket!
Thanks for your understanding!
