### ISSUE TITLE
Sonoff iFAn03 and led strips problem when plugin first reload

### ISSUE THREAD

**Issue by DarkSyler21** [bwp91/homebridge-ewelink#373]
### What issue do you have? Please be as thorough and explicit as possible.

Every time I restarting Homebridge if its for update a plugin or installing a new one the plugin is loaded and it indicate that both iFan03 (light and fan) are turned on as well as my led strip on "ON" state. In reality only the led strip gets turned on while the iFan03 indicate as ON but it's actually off.
the problem persist for a while now and is happening 100% of the time I'm restarting Homebridge

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 

Homebridge (with config-ui)

* Which version of Homebridge/HOOBS do you have?

1.4.1

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

8.15 the issue started a while back

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

light led strip model L1
iFan03 for both light and fan

* Do you use your main eWeLink credentials or do you use a secondary eWeLink account for Homebridge?

main

thanks a lot!

**Comment by bwp91** [comment]
Hi,
Closing this just as been a little overwhelmed with issues recently.
If this is still an issue or a feature you would like implemented then please do re-open this ticket!
Thanks for your understanding!
