### ISSUE TITLE
hiding humidity for th sonoff

### ISSUE THREAD

**Issue by tiimjcb** [bwp91/homebridge-ewelink#375]
greetings everyone,
i have a simple question/request.
i have a sonoff th16, which is controlling my swimming pool lightning, and i am waiting for the temperature sensor to get delivered.
i already setup the plugin, but it's showing temperature AND humidity.
the problem is that my sensor is only a temp sensor (obvious reasons since it's supposed to be waterproof, i'll put it in the pool)

is it possible to hide the humidity? 

many thanks, have a great day!

**Comment by bwp91** [comment]
Hi, do you know the model of the sensor you have? 

to clarify, not the model of the sonoff device, the model of the sensor

**Comment by tiimjcb** [comment]
it's that one. it's a waterproof one, that obviously don't support humidity.

![image](https://user-images.githubusercontent.com/75161532/172678866-ac566fd3-779a-4f2c-a980-ac4468d891cb.png)

**Comment by bwp91** [comment]
Humidity should already be hidden for this sensor, could we message on discord?

https://discord.gg/cMGhNtZ3tW
