### ISSUE TITLE
Power report in Dual R3

### ISSUE THREAD

**Issue by Itay1787** [bwp91/homebridge-ewelink#376]
Hi, I bought a Dual R3 that has the option to see the power consumption. I can see its in the app (eWelink) and in the HomeBirdge log using the plugin. But I can't see it in HomeKit, Is it not possible? I tried to change the Show As to outlets, but it did not help.
What to do?

I'm in the newest version
1.9.0
And HomeBirdge 1.4.1

**Comment by bwp91** [comment]
Hi @Itay1787 

Power readings are not available in the Home app, this is just the nature of the app.

You should download another HomeKit app, I would recommend Eve for HomeKit. You can view power information via this app and also make HomeKit automation based on power info.

**Comment by bwp91** [comment]
please let me know if from the Eve app works if you can :)

**Comment by Itay1787** [comment]
> please let me know if from the Eve app works if you can :)

I will probably leave for now with the "original" (Home) app and if I need to see consumption data I will open eWeLink
The power consumption data are not very important to me, I just wanted to know if it is possible to view them in the Home app because I thought I did something wrong.
So I probably will not download Eve

**Comment by bwp91** [comment]
Eve is a HomeKit app so just as secure as the home app. And it’s free to download and no registration so it’s definitely something to try.
A lot of users prefer it to the home app.
Worth a try ;)
