### ISSUE TITLE
Multi Channel settings doesn’t work 

### ISSUE THREAD

**Issue by Jer-emy** [bwp91/homebridge-ewelink#377]
### What issue do you have? Please be as thorough and explicit as possible.

I would like to configure a multi Channel device (sonoff dualR3) as a faucet. When i configure it in the user interface, it appears correctly with « showAs » and « tap » in the script but after homebridge restart, the device is initialised with options « showAsmotor »:  « blind ».  

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

(1)

* Which version of Homebridge/HOOBS do you have?

1.4.1

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry pi4

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

9.0.1
I just received and configured it today so i don’t know if previous version can work 

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

Sonoff DUALR3

**Comment by bwp91** [comment]
Hi @Jer-emy 

In the ewelink app do you have this device configured in motor mode? or in the typical two channel switch mode?

**Comment by Jer-emy** [comment]
Hi !
This device is configured in motor mode in EWeLink app because I would like to control a solenoid valve which will allow the water flow.

**Comment by Jer-emy** [comment]
Hello,
To solve this request, is it possible to add 1 tap/faucet in selectable option when the device is configured as a dual R3 in motor mode?
I just would like to have the good icon in HomeKit in accordance with the way how I use this device. 
thanks ;)

**Comment by bwp91** [comment]
sorry for delay in response can definitely look into this

**Comment by bwp91** [comment]
any reason why you don’t use the device in switch mode?

**Comment by Jer-emy** [comment]
It’s preferable to have only one switch (tap/faucet in my case) instead of 2, one for the opening and one other for the closure. If I set the device in switch mode, I have to stop the opening first before requesting the closure. 
Then, with the motor mode, I can control the water flow by setting an intermediate position of the electric ball valve.

**Comment by bwp91** [comment]
Hi,
Closing this just as been a little overwhelmed with issues recently.
If this is still an issue or a feature you would like implemented then please do re-open this ticket!
Thanks for your understanding!
