### ISSUE TITLE
Timed and Repeating Notification for any Ewelink door/window/garage contact sensor. 

### ISSUE THREAD

**Issue by MoTechnicalities** [bwp91/homebridge-ewelink#378]
* **Please explain your feature request in a one or two sentences.**

HomeKit has no direct feature to offer repetitive notifications for contact sensors that have been left open. (i.e. door left open for 15 minutes then send a notification, then again if still open 15 minutes after that.)

I would like to see if it is possible to create this optional functionality within the plugin for eWeLink doors/sensors with these optons:
Notify after (X minutes) if the door/sensor state remains OPEN (optionally if the sensor state remains CLOSED).
And optionally Repeat this notification (Y times/optionally infinitely) as long as the sensor remains in that state.

My thought was that the plugin could monitor the true state of the sensor and simply **re-transmit the sensor's state change command to HomeKit if the state is the same as that requiring the notification**, and repeat at the desired interval and number of times, so that if the user has notifications activated for that particular door/sensor then it should prompt HomeKit to send the desired state messages.

This is a desired feature that people are looking for.

* **Is your feature request related to a problem? Please describe.**

HomeKit has no direct feature to offer repetitive notifications for contact sensors

* **Any particular eWeLink devices that this relates to?**
Doors
Garage Doors
Windows
Any contact sensor

* **Anything else?**
I do not know if HomeKit will accept repeated open sensor statements and still send the push notification without receiving a closed sensor statement. (i.e. OPEN, OPEN, OPEN vs. OPEN, CLOSED, OPEN)

**Comment by bwp91** [comment]
Hi @MoTechnicalities 

Can definitely look into this

**Comment by bwp91** [comment]
Hi,
Closing this just as been a little overwhelmed with issues recently.
If this is still an issue or a feature you would like implemented then please do re-open this ticket!
Thanks for your understanding!
