### ISSUE TITLE
New sonoff elite

### ISSUE THREAD

**Issue by WollyRDM** [bwp91/homebridge-ewelink#382]
Hi, 
congratulations on your plugins
are you going to add compatibility for the new sonoff elite th and pow too?

A thousand thanks

**Comment by bwp91** [comment]
Hi @WollyRDM thank you for your contribution 

The TH elite is supported in the beta version of the plugin.

The POW I don’t know whether it is currently supported, I don’t own the device. But it can definitely be supported if you own it.
