### ISSUE TITLE
Plug-in has randomly stopped working

### ISSUE THREAD

**Issue by Raptor0014** [bwp91/homebridge-ewelink#386]
****UPDATE** Now working again with V9.1.0**

I am using Homebridge which is V1.5.0 and the EweLink is V9.0.1

All my Basic R2 controllers for lights and the POWR2 controller for my immersion heater will not work. If i use them in the Ewelink app they work fine so it’s not an issue there.

They seemed to have stopped overnight after 0030 UK time as my immersion heater switched on, but did not switch off at 0230 as normal. And the lights worked last night before i went to bed at 2330 UK time.

I have tried restarting the plugin and homebridge, also restarted iOS device and the appleTV which acts as the home hub. Everything else works fine through homebridge. It is just the Ewelink Plugin that seems to have stopped.

Anyone any ideas?

Thanks

**Comment by bwp91** [comment]
Hi @Raptor0014 

Also please see my latest comment here https://github.com/bwp91/homebridge-ewelink/issues/385#issuecomment-1177983794
