### ISSUE TITLE
Since latest update release 9.1 all my devices deleted and wont come up anymore

### ISSUE THREAD

**Issue by HabibiRoadlite** [bwp91/homebridge-ewelink#387]
### What issue do you have? Please be as thorough and explicit as possible.

Since latest update release 9.1 all my devices deleted and wont come up anymore.
After downgrade to 9.01 still all devices deleted and wont come up anymore.
I am using this plugin for about 3 years without trouble until 9.01.
This issues comes up yesterday by updating to 9.1

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

1

* Which version of Homebridge/HOOBS do you have?

1.5.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

macOS
node.js=16.16.0
npm=8.13.2

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

9.1.0

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

King-Q4

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi @HabibiRoadlite 

Please see the release notes for the latest version of the plugin

https://github.com/bwp91/homebridge-ewelink/blob/latest/CHANGELOG.md

**Comment by HabibiRoadlite** [comment]
Thanks for you quick response. That only confirm my issue, but why these devices wont get initialized again by the version before?

**Comment by bwp91** [comment]
ewelink have made some changes which made the old versions stop working.

See my comment here about the latest beta version https://github.com/bwp91/homebridge-ewelink/issues/385#issuecomment-1177983794

**Comment by MoTechnicalities** [comment]
Bummer, my **Eachen GD-DC5 WI-FI Garage Door Openers** have been booted out of the plugin!
They both work in the eWeLink app.
My Sonoff Basic still works.
First time I've ever had HomeKit issues.
I hope there is a fix soon and we haven't permanently lost a good thing.
I'd hate to have to switch to a HomeKit Only device.

**Comment by MoTechnicalities** [comment]
I spoke too soon!
9.1.1-beta.1 🥇 🥇 🥇 
All is well. But I did have to set them up again in HomeKit!

**Comment by HabibiRoadlite** [comment]
Yes I can confirm, the beta 9.11 works well with the blind switch and yes I needed to create some new scenes on HomeKit
Thanks for the fast fix

**Comment by bo-2221** [comment]
> Ja, ich kann bestätigen, die Beta 9.11 funktioniert gut mit dem Blindschalter und ja, ich musste einige neue Szenen auf HomeKit erstellen. Danke für die schnelle Lösung

You have to create your plugins as a subbridge, then not all devices should be thrown out of the Homekit if there are problems. Homebridge makes a backup every evening, you could then import it too.
