### ISSUE TITLE
Sonoff DW2-Wi-Fi-L not supported

### ISSUE THREAD

**Issue by thetatae** [bwp91/homebridge-ewelink#388]
* **Please explain your feature request in a one or two sentences.**

Sonoff Model DW2-Wi-Fi-L is currently not supported by the plugin

* **Is your feature request related to a problem? Please describe.**

After adding the new device to ewelink app and having Homebridge restarted, I found the following error...

7/12/2022, 12:22:11 PM] [eWeLink] [Bedroom Door Sensor] is not supported, do create a GitHub issue with the following info:

[154] {"bindInfos":{"gaction":[]},"version":8,"init":1,"fwVersion":"1000.2.1122","mac":"d02702b91420","chipID":"2","type":"3","switch":"off","rssi":"-47","battery":"100","defense":0,"actionTime":1617825378000}.

* **Any particular eWeLink devices that this relates to?**

* **Anything else?**

**Comment by bwp91** [comment]
Hi @thetatae 

Please install the beta version of the plugin to see if this device now starts working?

Thanks!

**Comment by thetatae** [comment]
Thanks a lot for your help. I’ll let you know once I test it.
