### ISSUE TITLE
Load Older Version of Plugin

### ISSUE THREAD

**Issue by GeoffTwin** [bwp91/homebridge-ewelink#389]
Unfortunately, I had been running Hoobs version 3.3.5 using a few plugins including a version of eWeLink-max on a Raspberry Pi that was installed in the house that I bought in March 2021.  Everything was running fine until I very recently decided (June 2022) that I should update some of the software on the Raspberry Pi, starting with Hoobs itself to 3.3.12 and then to the current version 4 after the upgrade to version 3.3.12 started to cause problems.  In this state everything collapsed and the system was unable to operate effectively for any of the devices.  There was no apparent cause or clear solution to the problem, so I decided that the first step was to revert to a backup disk copy of the version that was operating originally (backup taken in April 2021).
This regretfully did not work, as for some reason that I do not understand, the backup disk image when installed and initiated on Raspberry Pi (Model 3B+) run showed that the version of the RPi (Raspberry Pi monitor) plugin that was installed was version 1.1.14 with a date of 18 June 2022, which did not seem possible since the backup image was taken on 20 April 2021.  This only seemed possible to me if the firmware of the Raspberry Pi had been changed through the update of the RPi plugin, but I have nothing that I am able to check that can verify this.  I have also been unable to uninstall RPi as when I attempt this it reports as failed, and the existing version 1.1.14 remains in place.  This version has a number of compatibility issues with Node so I am not sure if this is causing other problems, but it does seem to load and work as it should despite this warning report.
The major issue however is that the plugin eWeLink-max (which has not been updated since April 2021), is now unable to get an authorisation token from the eWeLink server for again an unexplained reason, as the same username and password work perfectly well through an Apple iPad and Goole Pixel 3 phone, which means that the Hoobs system cannot get login confirmation for the username from the eWeLink server.  This was working perfectly well before I started updating the Hoobs software and plugins
In the first instance, I would like to get the system running so that I can access and use all the devices installed, and then move on to upgrading the Raspberry Pi to the latest software at leisure rather than under pressure.  To this end I thought that if I could get a version of eWeLink that would run on Hoobs version 3.3.5, then I could at least be operational while I work on an upgrade.
It seems that Hoobs version 3.3.5 does not have the direct capability to load an older version of a plugin, although version 4 does, so I don't know how to get or load an older version of the eWeLink plugin for Hoobs version 3.3.5 that might allow me to move forward.

Is someone able to assist in providing information and load/install instructions to load a version of the eWeLink plugin that would work on Hoobs version 3.3.5, or help with what the problem might be with the updated system?

**Comment by Damianod27** [comment]
@GeoffTwin Currently, the oldest version that can be installed is v8.7.0.  So you won't install version 3.3.5 anymore because it's not available.  The key to avoiding any problems is to make a copy of the Micro SD card before each update or major change to the system, and not a copy directly from the Hoobs or Homebridge system.  Reinstall the system.  Homebridge is definitely a less problematic system than Hoobs.

**Comment by GeoffTwin** [comment]
﻿Thanks for this information.  I had done a direct copy of the SD card and had reloaded this but the problem persisted.  I had done some research in the meantime and discovered that my approach would not have worked anyway.  I received a reply from CoolKit support as follows:

Sorry for causing trouble to you. Let me explain the reason: 

The 'oevkj2lyfgnju5xutwisfw4utin4u9mq ' interface request credential (APPID) used by this plug-in is illegal. We have noticed this problem, so we provided legal appid to the author to replace it last year, but some developers ignored it. In order to protect the rights and interests of users who have used these plug-ins, By default, we allowed these community projects to continue to use for two years. Until recently, we found that this APPID took up too much of our server resources, and we disabled it after evaluation. 

The solution to this situation is: individuals can log in to the eWeLink developer platform, pass the developer authentication, create a legal appid, and then use it. Its permissions are limited, but there are only differences when logging in. You can contact the author to modify the project to apply to the appid of oAuth2.0 type.

The above implies that the old version of the plugin would have the same problem as the one I was using hence not viable.  I have also determined from the research that I should drop Hoobs and convert to the latest version of Homebridge, which I am in the process of doing.  From another raised issue, I also noticed that the latest version of the eWeLink plugin has resolved this particular issue.

I have only one other concern in this process in that I am also using the CBus plugin, which also has not been updated for some years.  My first attempt to update Hoobs to the most recent version also resulted in this plugin no longer working and causing all CBus devices to be deleted from the system. I had not focussed on this problem due to the issues with eWeLink and that the CBus plugin worked on the Hoobs version I was using, but this will now be something that needs to be cleared up when I complete the upgrade to homebridge and reload the plugins.  Fingers crossed.

Regards,
GeoffTwin

**Comment by bwp91** [comment]
Unfortunately, I only support the latest versions of node and hoobs, so with node 14/16 and hoobs 4.

You would need to update your versions of hoobs.
