### ISSUE TITLE
Blinds support

### ISSUE THREAD

**Issue by Jtrunzo** [bwp91/homebridge-ewelink#395]
* **Please explain your feature request in a one or two sentences.**
Cannot control Graywind Zigbee shades through sonoff zigbee bridge

* **Is your feature request related to a problem? Please describe.**

* **Any particular eWeLink devices that this relates to?**
Sonoff Zigbee Bridge 

* **Anything else?**

[7/25/2022, 11:17:56 AM] [eWeLink] [Device0100b2] is not supported, do create a GitHub issue with the following info:
[1514] {"bindInfos":{},"subDevId":"e4bf10c8ce38c1a4","parentid":"10016ad886","battery":86,"trigTime":"1658340967743","curPercent":0,"motorDir":"forward","motorClb":"normal","curtainAction":"open","openPercent":0}.

**Comment by bwp91** [comment]
Hi @Jtrunzo 

If you install the beta version of the plugin, this device should appear in HomeKit, most likely with a message saying Unsupported. This is just the first step to get a new device type working - I did not even realise that motor/shade devices via zigbee existed with ewelink.

If you can install the beta, confirm from the Homebridge logs that the device is added, then I will let you know what I need next in order to implement the window covering device type.

Thanks!

**Comment by Jtrunzo** [comment]
Hey man!

Much appreciate the reply. I installed the beta and it sees them but says unsupported like you expected.

Let me know what else you need and how I can help!

Thanks,

Jacob Trunzo

**Comment by bwp91** [comment]
Hi @Jtrunzo 
Apologies for the delay in response to this.
Is this still a device that you’d still want in homebridge?

**Comment by Jtrunzo** [comment]
no worries, yeah i would love that! 

Jacob Trunzo
813-215-9591
***@***.***

**Comment by bwp91** [comment]
Can you update to the new beta 10.1.1-beta.5, and verify that it appears as a window covering accessory?
It may or may not actually function straight away, 

let me know how you get on!

**Comment by Jtrunzo** [comment]
will do! i’m out on a tour right now but when i get back in town in a few days i’ll do it right away 


thanks so much! 
Jacob Trunzo
813-215-9591
***@***.***

**Comment by Jtrunzo** [comment]
Hey man!

I updated and it worked right away. I can control it forom homebridge UI but not in the home app on the phone though. Thats a home bridge issue correct?

Thanks man!

**Comment by Jtrunzo** [comment]
It says no LAN control, not sure if theres a way to fix that or not

**Comment by Jtrunzo** [comment]
Hey man!

"This plugin threw an error from the characteristic 'Target Position': Unhandled error thrown inside read handler for characteristic: this.hapErr is not a constructor. See https://homebridge.io/w/JtMGR for more info."

This is the error I’m getting.

I got it to work for a moment when I switched child bridges on and off and then it became unresponsive again

**Comment by bwp91** [comment]
Hi,
Closing this just as been a little overwhelmed with issues recently.
If this is still an issue or a feature you would like implemented then please do re-open this ticket!
Thanks for your understanding!
