### ISSUE TITLE
THR316 - Is this supported 

### ISSUE THREAD

**Issue by rionshin** [bwp91/homebridge-ewelink#396]
I installed the plugin and have one device THR316  - it is thermostat switch. 
Can i use it as summation selecting   
"thDevices": [
                {
                    "label": "Pool",
                    "deviceId": "10017703e6",
                    "deviceModel": "th",
                    "showAs": "default"
                }
            ],
<img width="795" alt="Screenshot 2022-07-29 at 17 41 23" src="https://user-images.githubusercontent.com/41396180/181784968-d20eb403-0323-4126-b664-e91f384fe5bc.png">
<img width="764" alt="Screenshot 2022-07-29 at 17 43 30" src="https://user-images.githubusercontent.com/41396180/181784984-5722fba3-6d11-4dc1-a614-f18585f3662f.png">

**Comment by bwp91** [comment]
Hi @rionshin 

Yes this device should be supported and you can use the existing Sonoff TH10/16 as the device model in the config.

In the next version of the plugin I will update this label to include the Sonoff THR316 and THR320.

Thanks!

**Comment by bwp91** [comment]
Hi,
Closing this just as been a little overwhelmed with issues recently.
If this is still an issue or a feature you would like implemented then please do re-open this ticket!
Thanks for your understanding!
