### ISSUE TITLE
Sonoff POW logging

### ISSUE THREAD

**Issue by migabc** [bwp91/homebridge-ewelink#4]
Hi,

I keep receiving this logs every 2 minutes

[eWeLink] WebSocket messge received:  {"action":"update","deviceid":"10001be297","apikey":"9ebb9ccc-6044-4d51-a404-d742bb063c64","userAgent":"device","ts":0,"params":{"rssi":-62,"power":"0","switch":"off"},"from":"device"}
[eWeLink] Update message received for device [10001be297]
[eWeLink] Updating recorded Characteristic.On for [Sonoff Pow 1] to [false]. No request will be sent to the device.
[eWeLink] Setting power state to [off] for device [Sonoff Pow 1]
[eWeLink] WebSocket messge received:  {"error":0,"deviceid":"10001be297","apikey":"9ebb9ccc-6044-4d51-a404-d742bb063c64","sequence":"1515326993473"}

This is happening only for the Sonoff POW and not for the Basic
Any idea why?
How can I turn off this logging?

Thanks.

**Comment by gbro115** [comment]
These messages are being sent from the Sonoff servers; they are not initiated by code in the plugin.

I'm a bit stretched at the moment & am not going to be adding much to this project in the foreseeable future.

All I can suggest is modifying the code of the module for your local installation.

Nonetheless, I will take this suggestion into consideration for a future update.

George

**Comment by migabc** [comment]
Any idea why it's only happening for Sonoff POW and not Sonoff Basic?
Is there anyway we can filter these messages?
Every 2 minutes is quite a lot as you can imagine.

**Comment by gbro115** [comment]
What I should do is modify the plugin such that output like this is suppressed, unless homebridge is running in debug mode.

Unfortunately it's going to be at least 3 weeks before I'm able to work on this.

**Comment by migabc** [comment]
That would be great.
Thanks.

**Comment by Reddyzinho** [comment]
Any new about this error? Now its in each 3 seconds :/ POW REV 2
