### ISSUE TITLE
auto reconnection after using creditiales on other device

### ISSUE THREAD

**Issue by JacekKac** [bwp91/homebridge-ewelink#400]
### What issue do you have? Please be as thorough and explicit as possible.

homebridge-ewlink is not properly reconnecting to ewlink cloud after using account on other devices/instances. Steps: 

1/ hb-ewlink connected properly
2/ loging to ewlink account on mobile phone
3/ hb-ewlink gives WS 406 Error and trying to reconnect
4/ Login out of the app 
5/ hb-ewlink still gives WS 406
6/ restarting hb solves the issue

Imho it should reconnect without restarting whole HB, and it should be done automaticly

```
WS 406 Error
12.08.2022, 10:35:47] [eWeLink] WS login failed [406] see http://bit.ly/hb-ewelink-errors
[12.08.2022, 10:35:47] [eWeLink] WS unknown command received.
{
  "error": 406,
  "apikey": "xxxxxxxxxxxxxxxxxxxxxxxx",
  "sequence": "1660293347288",
  "actionName": "userOnline",
  "params": {}
}
[12.08.2022, 10:35:47] [eWeLink] WS error event and will try to reconnect in 5 seconds [1000].




```### Details of your setup.
standard homebridge stable -

**Comment by bwp91** [comment]
Hi @JacekKac 

You need to use a separate ewelink account now.
Create a second ewelink account, share your devices to this account, but use your main ewelink account for the plugin and keep logged into the ewelink app with the second account

**Comment by JacekKac** [comment]
@bwp91 thank you, seems like good idea, but still is it not a bug that hb-ewlink is to able relogin sucesfully and restart is nesesery ?

**Comment by MoTechnicalities** [comment]
@JacekKac 
It's not a HB-EWeLINK bug.

The EWeLINK platform no longer allows multi device logins as part of their policy. It however does allow sharing an account with other users.

Therefore, the best solution available is to make User-EWeLINK accounts for each of the users and a HB-EWeLINK account that you share to your users needing device access through the platform.

There is no way around it. If you log into the HB-EWeLINK account from a phone or other device then you must restart Homebridge for the plugin to reconnect to that account again. EWeLINK will then disconnect you phone App if logged in to the HB-EWeLINK account.

**Comment by MoTechnicalities** [comment]
@JacekKac 
There is also no way for the plugin to first check if other users are logged out before attempting to log back in. So any auto reconnect would consistently knock your Phone App off if you were really trying to log into that account from it.

**Comment by JacekKac** [comment]
Seems like a dead end to me, I think good solution will be to add a option "force login" instead of manuall restart, maybe with some time setting.

**Comment by MoTechnicalities** [comment]
> add a option "force login" ... with some time setting.

I like that too.

**Comment by bwp91** [comment]
Hi,
Closing this just as been a little overwhelmed with issues recently.
If this is still an issue or a feature you would like implemented then please do re-open this ticket!
Thanks for your understanding!
