### ISSUE TITLE
ZB bridge pro and L3 LED strip support

### ISSUE THREAD

**Issue by wuhoo98** [bwp91/homebridge-ewelink#403]
Hello!

New devices in sonoff that should be popular soon: ZB bridge pro and L3 pro led strip.
It would be great if you could support them or maybe guide on how to contribute for adding new sonoff devices in your plugin. I have little experience in programming, but I am a big enthusiast.

Thanks!

**Comment by bwp91** [comment]
Hi @wuhoo98 

Zigbee pro bridge should be supported in the beta version of the plugin.

L3 too, though I need to do a bit more work on brightness and colour control

**Comment by bwp91** [comment]
Hi,
Closing this just as been a little overwhelmed with issues recently.
If this is still an issue or a feature you would like implemented then please do re-open this ticket!
Thanks for your understanding!
