### ISSUE TITLE
Fetching Devices, no devicesa are published to HomeKit - takes very long

### ISSUE THREAD

**Issue by axelweichert** [bwp91/homebridge-ewelink#407]
### What issue do you have? Please be as thorough and explicit as possible.
Since today, after a restart of the homebrige, no eWeLink devices are published to homekit anymore. After a while the message: [01/09/2022, 08:19:46] [eWeLink] Unable to reach eWeLink, retrying in 30 seconds [getHost() - ECONNABORTED]. is displayed and the devices will be discovered an provided to homekit. The eWeLink App is running fine instead.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
(1) Hombrige UI-X

* Which version of Homebridge/HOOBS do you have?
1.5.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi 4B 4 GB

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?
homebridge-ewelink v10.0.0

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.
All models

### Please paste any relevant logs below.

[01/09/2022, 08:11:01] [eWeLink] Fetching devices from eWeLink home/id [Wxxxxx] [xxxxxxxxxxxxxxxxxxxxxx].
[01/09/2022, 08:19:46] [eWeLink] Unable to reach eWeLink, retrying in 30 seconds [getHost() - ECONNABORTED].
```

```

**Comment by bwp91** [comment]
Hi,
Closing this just as been a little overwhelmed with issues recently.
If this is still an issue or a feature you would like implemented then please do re-open this ticket!
Thanks for your understanding!
