### ISSUE TITLE
Error: connect ECONNREFUSED 

### ISSUE THREAD

**Issue by sushenmathur** [bwp91/homebridge-ewelink#41]
Keep getting below error on connection, it connects some times and some time I keep getting this error 

Please help

WebSocketClient: reconnecting...
WebSocketClient: retry in 5000ms { Error: connect ECONNREFUSED 52.8.47.125:8080
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '52.8.47.125',
  port: 8080 }

**Comment by mofolo** [comment]
Same issue here!

**Comment by mofolo** [comment]
Found the problem.
The Read Me config has the old Web Socket URL.

Change this in your config file:
`"webSocketApi" : "us-ota.coolkit.cc"`
to:
`"webSocketApi" : "us-pconnect3.coolkit.cc"`

As per this
https://github.com/gbro115/homebridge-ewelink/issues/16
