### ISSUE TITLE
Gate Opening

### ISSUE THREAD

**Issue by Gambl2022** [bwp91/homebridge-ewelink#411]
* **Please explain your feature request in a one or two sentences.**
I have a gate which has 2 open settings which work with a Sonoff R2 set to inching mode one channel to fully open and one to partially open.

* **Is your feature request related to a problem? Please describe.**
If I use the 2 Garage option on a multi switch Sonoff R2 then one press switch 1 it activates channel 1 and then when you press the same switch again channel 2 operates. Press Switch 2 does nothing. If they are set up as default both work corectly but have a swutch as an icon rather than a gate/garage door. Would it be possible to have the ability to either change the icon or else have a facility where the 2 garage option acts like the 2 switch settting.

 as they self close on a timer use the time off option to change the status from open to close
* **Any particular eWeLink devices that this relates to?**
Sonoff Dual R2

* **Anything else?**

**Comment by bwp91** [comment]
Hi,
Closing this just as been a little overwhelmed with issues recently.
If this is still an issue or a feature you would like implemented then please do re-open this ticket!
Thanks for your understanding!
