### ISSUE TITLE
Sonoff light bulb B02 B-A60 expirience

### ISSUE THREAD

**Issue by ondrejkrivan** [bwp91/homebridge-ewelink#412]
Hi, my bulbs have a "Not repsonding" status in the home APP. However, they work quite well. I am able to control them through the Home App. With great delay. I understand that I can't expect miracles with wifi connected devices. Have you had the same experience? 

Thank you.

**Comment by bwp91** [comment]
Hi @ondrejkrivan are you using your main ewelink account with the plugin? or a shared account?

**Comment by ondrejkrivan** [comment]
Hi, shared account.

**Comment by bwp91** [comment]
This is the reason for the no response message and probably the delays. You should use your main ewelink account with the plugin. And use the shared account for the ewelink app

**Comment by ondrejkrivan** [comment]
Thank you. It seems to be working much more smoothly now.
