### ISSUE TITLE
Can't control anything today

### ISSUE THREAD

**Issue by dpamping** [bwp91/homebridge-ewelink#413]
Getting this error: 

eWeLink BridgeeWeLinkWARNINGUnable to reach eWeLink, retrying in 30 seconds [login() - EAI_AGAIN].
plugin site unavailable

yesterday all worked fine.

**Comment by bwp91** [comment]
please try restarting the bridge, it may be just a temporary connectivity issue?

**Comment by dpamping** [comment]
I’ve restarted the hub but no luck :(
On the eWeLink app, no problem

getting a long list of errors:

21/9/2022, 23:22:46eWeLink BridgeeWeLinkWARNINGUnable to reach eWeLink, retrying in 30 seconds [login() - EAI_AGAIN].
21/9/2022, 23:23:16eWeLink BridgeeWeLinkWARNINGUnable to reach eWeLink, retrying in 30 seconds [login() - EAI_AGAIN].
21/9/2022, 23:23:46eWeLink BridgeeWeLinkWARNINGUnable to reach eWeLink, retrying in 30 seconds [login() - EAI_AGAIN].
21/9/2022, 23:24:16eWeLink BridgeeWeLinkWARNINGUnable to reach eWeLink, retrying in 30 seconds [login() - EAI_AGAIN].
21/9/2022, 23:24:46eWeLink BridgeeWeLinkWARNINGUnable to reach eWeLink, retrying in 30 seconds [login() - EAI_AGAIN].
21/9/2022, 23:25:16eWeLink BridgeeWeLinkWARNINGUnable to reach eWeLink, retrying in 30 seconds [login() - EAI_AGAIN].
21/9/2022, 23:25:46eWeLink BridgeeWeLinkWARNINGUnable to reach eWeLink, retrying in 30 seconds [login() - EAI_AGAIN].
21/9/2022, 23:26:16eWeLink BridgeeWeLinkWARNINGUnable to reach eWeLink, retrying in 30 seconds [login() - EAI_AGAIN].
21/9/2022, 23:26:46eWeLink BridgeeWeLinkWARNINGUnable to reach eWeLink, retrying in 30 seconds [login() - EAI_AGAIN].
21/9/2022, 23:27:16eWeLink BridgeeWeLinkWARNINGUnable to reach eWeLink, retrying in 30 seconds [login() - EAI_AGAIN].
21/9/2022, 23:27:46eWeLink BridgeeWeLinkWARNINGUnable to reach eWeLink, retrying in 30 seconds [login() - EAI_AGAIN].
21/9/2022, 23:28:16eWeLink BridgeeWeLinkWARNINGUnable to reach eWeLink, retrying in 30 seconds [login() - EAI_AGAIN].
21/9/2022, 23:28:34WARNINGplugin site unavailable

**Comment by dpamping** [comment]
restored backup. I updated yesterday the plugin. now works

**Comment by dpamping** [comment]
working now but getting this error:
22/9/2022, 16:18:47eWeLink BridgeeWeLinkWARNINGWS login failed [406] see http://bit.ly/hb-ewelink-errors
22/9/2022, 16:18:47eWeLink BridgeeWeLinkWARNINGWS unknown command received.

**Comment by jurekjure** [comment]
I'm having a similar issue - everything worked fine, than I updated ewelink zigbee hub (I think this was the first thing), than it all stopped working. I updated the plugin, unistalled it, reinstalled it, restarted the bridge and homebridge (hoobs) numerous times, but no change:


22/09/2022, 18:42:36eWeLink HOOBSLoaded plugin 'homebridge-ewelink'
22/09/2022, 18:42:36eWeLink HOOBSLoading 1 platforms...
22/09/2022, 18:42:36eWeLink HOOBSeWeLinkundefined v10.0.0 | System linux | Node v16.17.0 | HB v1.5.0 | HAPNodeJS v0.10.2...
22/09/2022, 18:42:36eWeLink HOOBSeWeLinkPlugin initialised. Setting up accessories....
22/09/2022, 18:42:36eWeLink HOOBSBridge is running on port 51836.
22/09/2022, 18:42:36eWeLink HOOBSeWeLinkSending HTTP login() request.
22/09/2022, 18:42:37eWeLink HOOBSeWeLinkWARNINGUnable to reach eWeLink, retrying in 30 seconds [login() - EAI_AGAIN].
22/09/2022, 18:43:07eWeLink HOOBSeWeLinkSending HTTP login() request.
22/09/2022, 18:43:07eWeLink HOOBSeWeLinkWARNINGUnable to reach eWeLink, retrying in 30 seconds [login() - EAI_AGAIN].
22/09/2022, 18:43:37eWeLink HOOBSeWeLinkSending HTTP login() request.
22/09/2022, 18:43:37eWeLink HOOBSeWeLinkWARNINGUnable to reach eWeLink, retrying in 30 seconds [login() - EAI_AGAIN].
22/09/2022, 18:44:07eWeLink HOOBSeWeLinkSending HTTP login() request.
22/09/2022, 18:44:07eWeLink HOOBSeWeLinkWARNINGUnable to reach eWeLink, retrying in 30 seconds [login() - EAI_AGAIN].
22/09/2022, 18:44:37eWeLink HOOBSeWeLinkSending HTTP login() request.
22/09/2022, 18:44:37eWeLink HOOBSeWeLinkWARNINGUnable to reach eWeLink, retrying in 30 seconds [login() - EAI_AGAIN].
22/09/2022, 18:45:07eWeLink HOOBSeWeLinkSending HTTP login() request.
22/09/2022, 18:45:07eWeLink HOOBSeWeLinkWARNINGUnable to reach eWeLink, retrying in 30 seconds [login() - EAI_AGAIN].
22/09/2022, 18:45:37eWeLink HOOBSeWeLinkSending HTTP login() request.
22/09/2022, 18:45:37eWeLink HOOBSeWeLinkWARNINGUnable to reach eWeLink, retrying in 30 seconds [login() - EAI_AGAIN].
22/09/2022, 18:46:07eWeLink HOOBSeWeLinkSending HTTP login() request.
22/09/2022, 18:46:07eWeLink HOOBSeWeLinkWARNINGUnable to reach eWeLink, retrying in 30 seconds [login() - EAI_AGAIN].

**Comment by RemiWest** [comment]
?

24.09.2022, 20:15:14WARNINGplugin site unavailable
24.09.2022, 20:15:18WARNINGplugin site unavailable
24.09.2022, 20:15:18WARNINGplugin site unavailable
24.09.2022, 20:15:18WARNINGplugin site unavailable
24.09.2022, 20:15:18WARNINGplugin site unavailable
24.09.2022, 20:15:18WARNINGplugin site unavailable
24.09.2022, 20:15:18WARNINGplugin site unavailable
24.09.2022, 20:15:22eWeLink BridgeeWeLinkWARNINGUnable to reach eWeLink, retrying in 30 seconds [login() - EAI_AGAIN].
24.09.2022, 20:15:52eWeLink BridgeeWeLinkWARNINGUnable to reach eWeLink, retrying in 30 seconds [login() - EAI_AGAIN].
24.09.2022, 20:16:11WARNINGplugin site unavailable
24.09.2022, 20:16:22eWeLink BridgeeWeLinkWARNINGUnable to reach eWeLink, retrying in 30 seconds [login() - EAI_AGAIN].

**Comment by RemiWest** [comment]
<img width="665" alt="Zrzut ekranu 2022-09-24 o 20 32 12" src="https://user-images.githubusercontent.com/46202613/192113597-e8a1a099-9d26-43c1-9ca2-2d7a71b8c823.png">

**Comment by jurekjure** [comment]
So i figured kut that it is an underlying issue of the os. Open Terminal and run: sudo rm /etc/resolv.conf; sudo reboot

Explanation:

A recent Linux system update caused some DNS issues affecting HOOBS Box users running on model HSLF-1 as well as DIY installs on Raspberry Pi boards. If you are not able to install plugins or your plugins fail to connect to the internet after a System update, and your logs read "Plugin site unavailable",

**Comment by bwp91** [comment]
Hi,
Closing this just as been a little overwhelmed with issues recently.
If this is still an issue or a feature you would like implemented then please do re-open this ticket!
Thanks for your understanding!
