### ISSUE TITLE
NS Panel as termostat in Homekit. 

### ISSUE THREAD

**Issue by ondrejkrivan** [bwp91/homebridge-ewelink#414]
* **Please explain your feature request in a one or two sentences.**

How about to expose NS Panel as Termostat. 

* **Is your feature request related to a problem? Please describe.**

No.

* **Any particular eWeLink devices that this relates to?**

NS Panel, NS panel Pro

* **Anything else?**

**Comment by rascarvalho79** [comment]
Hi There!
Same question here! I'd like to know if it's possible to trigger an automation with NS Panel Thermostat. Thanks!

**Comment by ondrejkrivan** [comment]
I am using native app automation to trigger my floor heating. But it would be nice to adjust tempreautre in home app.

**Comment by bwp91** [comment]
Hi,
Closing this just as been a little overwhelmed with issues recently.
If this is still an issue or a feature you would like implemented then please do re-open this ticket!
Thanks for your understanding!
