### ISSUE TITLE
Ewelink offline - Unable to reach eWeLink, retrying in 30 seconds [login() - EAI_AGAIN].

### ISSUE THREAD

**Issue by cecildaniel2003** [bwp91/homebridge-ewelink#415]
Hi All, 
I am running Hoobs version 4.2.8 on raspberry pie and ewelink plugin seems to timeout. Running homebridge-plugin version 10.0.0, None of the devices are working on hoobs but directly working on ewelink app on the same account.

27/09/2022, 21:49:37eWeLink BridgeeWeLinkWARNINGUnable to reach eWeLink, retrying in 30 seconds [login() - EAI_AGAIN].
27/09/2022, 21:50:07eWeLink BridgeeWeLinkSending HTTP login() request.
27/09/2022, 21:50:07eWeLink BridgeeWeLinkSending HTTP login() request.

**Comment by bwp91** [comment]
Hi @cecildaniel2003 

Please try this here:
https://support.hoobs.org/topics/connectivity/plugin-site-unavailable

**Comment by cecildaniel2003** [comment]
> Hi @cecildaniel2003
> 
> Please try this here: https://support.hoobs.org/topics/connectivity/plugin-site-unavailable

Thank you worked like a charm. Much appreciated. All of my automations were down, this fixed it instantly.
