### ISSUE TITLE
Power Consumption Meter works only as a switch, no power readings

### ISSUE THREAD

**Issue by limneos** [bwp91/homebridge-ewelink#421]
* **Please explain your feature request in a one or two sentences.**

I recently bought this wifi rail switch:

https://www.banggood.com/2P-63A-eWelink-Single-Phase-Din-Rail-WIFI-Smart-Switch-Energy-Meter-Leakage-Protection-Remote-Read-KWh-Meter-Wattmeter-Works-with-Alexa-Google-p-1840501.html?rmmds=myorder&cur_warehouse=CZ

which provides power consumption readings in the Ewelink app. 

The plugin in HomeBridge appears to receive the readings :

> [10/11/2022, 12:52:05 AM] [eWeLink] [Power meter 1] current power [0.00W] current voltage [234.72V] current current [0.00A].
> [10/11/2022, 12:52:06 AM] [eWeLink] [Power meter 1] current power [0W] current voltage [234.71V] current current [0A].
> [10/11/2022, 12:52:06 AM] [eWeLink] [Power meter 1] current power [0.00W] current voltage [234.72V] current current [0.00A].
> [10/11/2022, 12:52:32 AM] [eWeLink] [Power meter 1] current power [0W] current voltage [235.31V] current current [0A].

* **Is your feature request related to a problem? Please describe.**
However, there is no indication of power readings in homebridge or Home.app and the device appears as a simple outlet/switch rather than a power meter/switch. 

* **Any particular eWeLink devices that this relates to?**
SMT003

* **Anything else?**
Kind request to add support for power readings as a HomeBridge accessory.

![IMG_9606](https://user-images.githubusercontent.com/239807/194959093-e4ac3f88-c819-420d-a7c8-887d7bf4181c.PNG)
<img width="795" alt="Screenshot 2022-10-11 at 01 03 50" src="https://user-images.githubusercontent.com/239807/194959496-847bc418-4c89-4133-a39f-90eb816a4cc7.png">

**Comment by bwp91** [comment]
Hi @limneos 

The Home app does not include functionality to see power information like voltage, wattage and current.

You will need to use another HomeKit app like the Eve app to see this information.

You can also use the Eve app to create HomeKit automations based on the power values.

This is a limitation that all homebridge plugins have - there is just no way of showing this info in the Home app itself.
