### ISSUE TITLE
Contact sensor automatically closes

### ISSUE THREAD

**Issue by euge1015** [bwp91/homebridge-ewelink#422]
Hi,

I am using the Sonoff DW2 RF Door/Window sensor and RF Bridge R2 443 so I can detect if the door is open or close.  The plugin seems to be working when I open the door and the state changes to open but it then automatically changed to the close state after a few seconds.

Is it possible for the contact sensor to stay in the open state while the door is open?

Thanks in advance.

<img width="527" alt="Screenshot 2022-10-19 at 20 17 27" src="https://user-images.githubusercontent.com/63866531/196773140-5e69bffa-200d-47d8-a656-0f80d1ff8c50.png">
<img width="673" alt="Screenshot 2022-10-19 at 20 15 20" src="https://user-images.githubusercontent.com/63866531/196773252-718b21e7-1df7-4e55-95ab-80d38e34cb72.png">

**Comment by bwp91** [comment]
Hi @euge1015 

Once this sensor has been activated (and so shows as open), it should then revert back to closed after 60 seconds as per your config. When you say *a few seconds* is it 60?

Via the eWeLink app, is it possible to see when a door closes after it opens?

**Comment by bwp91** [comment]
Hi,
Closing this just as been a little overwhelmed with issues recently.
If this is still an issue or a feature you would like implemented then please do re-open this ticket!
Thanks for your understanding!
