### ISSUE TITLE
Sonoff ns panel pro

### ISSUE THREAD

**Issue by mahmoodur** [bwp91/homebridge-ewelink#424]
* **Please explain your feature request in a one or two sentences.**
[NSPanel86PB] is not supported, do create a GitHub issue with the following info:

* **Is your feature request related to a problem? Please describe.**
unsupported device

* **Any particular eWeLink devices that this relates to?**
ns panel pro

**Comment by bwp91** [comment]
Hi @mahmoodur this should now be supported in the beta version of the plugin!

**Comment by bwp91** [comment]
Hi,
Closing this just as been a little overwhelmed with issues recently.
If this is still an issue or a feature you would like implemented then please do re-open this ticket!
Thanks for your understanding!
