### ISSUE TITLE
R5 And Stateless Programmable Switches

### ISSUE THREAD

**Issue by joaocreste** [bwp91/homebridge-ewelink#430]
Hey there

Thanks a lot for this plugin, it is great. I recently purchased a 6-button R5 scene switch, and I've been all weekend trying to figure out a way to make it work as a 6-button switch using the plugin, which recognizes it as only one button. The log info does provide different channel recognition, example:

{"outlet":5,"key":0,"actionTime":"2022-11-21T03:04:58.211Z","online":true,"updateSource":"WS"}

were the outlet and key change, but still can't manage to make it work for different buttons. It would be great maybe as a workaround for now to have the complete log - including the API request - so I could work a way around an HTTP server receiving such request as each key/click type should be the same URL.

Thanks!

**Comment by bwp91** [comment]
Hi @joaocreste 

This device still isn't supported properly - something I plan to do soon.

Out of interest, in the ewelink app, are you able to name each individual switch?

Would you be happy to share this device to my ewelink account so I can see how all the data is formatted?

**Comment by joaocreste** [comment]
Sure,

Could you please share you credentials for sharing with the eWeLink app?

in the app, it does show each button as a separate channel.

Best

**Comment by bwp91** [comment]
Can I give you credentials on discord?
https://discord.gg/cMGhNtZ3tW

**Comment by bwp91** [comment]
Hey @didaspl (and @joaocreste)

Please check the beta version of the plugin 10.3.1-beta.0

Chances are it won't work properly at first, this is still untested really.

**Comment by bwp91** [comment]
Hi,
Closing this just as been a little overwhelmed with issues recently.
If this is still an issue or a feature you would like implemented then please do re-open this ticket!
Thanks for your understanding!
