### ISSUE TITLE
showAs - doesn't seem to change device type e.g. garage 

### ISSUE THREAD

**Issue by PencilDH** [bwp91/homebridge-ewelink#431]
### What issue do you have? Please be as thorough and explicit as possible.

I tried chaniging showAs to many things as in the examples but it doesn't seem to have an effect on device type and always shows up as switch in homekit and homebridge.

### Details of your setup.
* Do you use (1) Homebridge UI-X
I use homebridge 1.5.1 with nodejs v16.18.1
hardware 4ch (can actuate - it works)
IOS16

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

rpi

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

v10.3.0

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

4CH

### Please paste any relevant logs below.

```
            "name": "eWeLink",
            "username": "xxx@xxx.xxx",
            "password": "yyy-zzz-zzz",
            "mode": "auto",
            "debug": true,
            "language": "en",
            "multiDevices": [
                {
                    "label": "Front Gate",
                    "deviceId": "1001722771",
                    "deviceModel": "4ch",
                    "showAs": "garage",
                    "ipAddress": "192.162.68.21",
                    "overrideLogging": "default"
                }
            ],
            "platform": "eWeLink"
```
![image](https://user-images.githubusercontent.com/19908009/203445924-03eb74d0-85a6-4de2-acfe-f94f04d8741b.png)

**Comment by bwp91** [comment]
Hi @PencilDH 

I assume that there is no change to the accessory type even after restarting Homebridge? and perhaps force closing and re-opening the Home app?

**Comment by PencilDH** [comment]
Hi Ben,

correct, no change, process followed…
1. Change accessory type in config
2. Restart homebridge 
3. Force close home.app on iPhone 

I would at least expect to see the correct accessory type in homebridge UI under accessories but it’s a switch there too

**Comment by PencilDH** [comment]
![Uploading B793C833-D62E-4AB7-9035-213338D4B8CC.png…]()

**Comment by PencilDH** [comment]
Few more questions:
1. should I do any special setup in the eWeLink app?
2. also tried to run the plunging as a child plugin but it still showed up as switches.

I will try a clean install of homebridge on a different server and see if this works maybe there is something messed up with my instance or rpi?

Any advice is welcomed



<img width="1371" alt="Screenshot 2022-11-23 at 07 45 04" src="https://user-images.githubusercontent.com/19908009/203494507-71215c49-079d-478c-97b9-22498cfa31d6.png">

**Comment by bwp91** [comment]
> should I do any special setup in the eWeLink app?

Nope
> also tried to run the plunging as a child plugin but it still showed up as switches.

Shouldn't make a difference.

I just tried this with my homebridge instance and a 4-channel device - shows up immediately as a garage on my accessory page.

- when you start the plugin, do you get any config warnings in the plugin setup logs?
- can you double check that you _absolutely definitely(!)_ have the device ID correct in the config and you haven't for example copied a different device id or mistyped a number?

**Comment by PencilDH** [comment]
On a clean instal on my mac it seems to work but has some problems when I change the device type.  I think the issue is that i need to purge.

```
./homebrige/accesories 
./homebrige/persits
./homebrige/homebridge-ewelink
```

and restart 2 times the homebridge service when making a change of the device type  "showAs": "xxx"
