### ISSUE TITLE
Sonoff basic

### ISSUE THREAD

**Issue by vitva** [bwp91/homebridge-ewelink#435]
Hey! is it possible to add the function of modeling the sonoff basic as a socket? I understand that functionally this will not affect the operation of the relay in any way ... the function is more of a cosmetic nature. I want everything in beauty)) if it doesn’t make it difficult and there is such an opportunity, it would be gorgeous

**Comment by MoTechnicalities** [comment]
That ability already exists.
In the homebridge-ewelink plugin settings (as shown below), set up the highlighted entries for your accessory.
Then in HomeKit's Accessory Settings for the Sonoff Basic set it to Display As [Outlet] (you can also choose [Fan] or [Light]).

![image](https://user-images.githubusercontent.com/68468472/204514091-848224ab-67c1-4080-b8fe-6bf2b07d8186.png)

**Comment by vitva** [comment]
wow thank you very much! already applied 👍
