### ISSUE TITLE
Showas option for sonoff D1 Dimmer

### ISSUE THREAD

**Issue by Nivlac7** [bwp91/homebridge-ewelink#436]
* **Please explain your feature request in a one or two sentences.**

I would like to have my sonoff D1 to show as a fan in Home app (used to control the fan speed of my fireplace)

* **Is your feature request related to a problem? Please describe.**

Not a problem as such, your plugin is great!

* **Any particular eWeLink devices that this relates to?**

Sonoff D1 

* **Anything else?**

**Comment by bwp91** [comment]
Never known this use case for a D1 but definitely something I can look into!

**Comment by Nivlac7** [comment]
Yes, the fan is max 70W and to be used with a dimmer, so D1 can easily be used for that purpose and sonoff is by far best price for it.
Thank you in advance, looking forward for it !

**Comment by bwp91** [comment]
Please install the beta version of the plugin and use the config 'Light Devices' section to expose the D1 as a fan type. I have not tested this as I do not have a D1, but it should work!

**Comment by Nivlac7** [comment]
Great! Perfectly working and I see it now under the climate part of Home App 👌🏼
Thanks you very much

**Comment by MoTechnicalities** [comment]
> Great! Perfectly working and I see it now under the climate part of Home App 👌🏼
> 
> Thanks you very much

Would you mind providing a model number of your fan for reference. I'm just curious about what fans might work with this. Thanks.

**Comment by Nivlac7** [comment]
Sure, it is the fan of the bodart & Gonay opti green: https://www.youtube.com/
It is replacing the ugly manual dimmer you see in the video @ 3:16 😉

**Comment by MoTechnicalities** [comment]
Got it! Great! Thanks!
![image](https://user-images.githubusercontent.com/68468472/206900166-9bb0179c-56db-4712-b642-ec941b4a81ac.png)
![image](https://user-images.githubusercontent.com/68468472/206900179-f79e1159-da0e-4cce-b271-25c7d93d2580.png)

**Comment by bwp91** [comment]
Hi,
Closing this just as been a little overwhelmed with issues recently.
If this is still an issue or a feature you would like implemented then please do re-open this ticket!
Thanks for your understanding!
