### ISSUE TITLE
[eWeLink] Server did not respond with an authentication token

### ISSUE THREAD

**Issue by migabc** [bwp91/homebridge-ewelink#437]
Hi,

I'm getting these errors:

```
Dec  3 20:35:59 raspberrypi homebridge[3226]: [12/3/2022, 8:35:59 PM] [eWeLink] HTTP API host received [eu-apia.coolkit.cc].
Dec  3 20:35:59 raspberrypi homebridge[3226]: [12/3/2022, 8:35:59 PM] [eWeLink] Sending HTTP login request.
Dec  3 20:36:01 raspberrypi homebridge[3226]: [12/3/2022, 8:36:01 PM] [eWeLink] ** eWeLink synchronisation error: **
Dec  3 20:36:01 raspberrypi homebridge[3226]: [12/3/2022, 8:36:01 PM] [eWeLink] Server did not respond with an authentication token. Please double check your eWeLink username and password in the Homebridge configuration.
Dec  3 20:36:01 raspberrypi homebridge[3226]: {
Dec  3 20:36:01 raspberrypi homebridge[3226]:   "error": 407,
Dec  3 20:36:01 raspberrypi homebridge[3226]:   "msg": "appid is unauthorized! xxxxxx",
Dec  3 20:36:01 raspberrypi homebridge[3226]:   "data": {}
Dec  3 20:36:01 raspberrypi homebridge[3226]: }
```

Any help is appreciated

Thanks,

**Comment by bwp91** [comment]
hi, are you using a custom appid in the config?

**Comment by bwp91** [comment]
Also which version of the plugin are you using?
I do not recognise some of the log text here from the current version of this plugin

**Comment by migabc** [comment]
No, I'm using the normal config

```
    "platforms": [
        {
            "platform": "eWeLink",
            "name": "eWeLink",
            "username": "xxx@xxxx.xxx",
            "password": "xxxxxxxxx",
            "countryCode": "xxx",
            "debug": "true",
            "disablePlugin": "false"
        },
```

**Comment by migabc** [comment]
I'm using homebridge-ewelink-sonoff
https://github.com/bwp91/homebridge-ewelink/issues/129#issuecomment-723661138

**Comment by migabc** [comment]
It was working fine up to about a month ago

**Comment by migabc** [comment]
Maybe some thing changed server side

**Comment by bwp91** [comment]
Ahh I remember.

Yes the appId that this plugin uses needed to change and now the only plugin and version that works is `homebridge-ewelink` v10.0.0 or above.

eWeLink stopped the old appId working.

**Comment by migabc** [comment]
That's a bummer, because I cannot install that new version because I'm running HomeBridge version of 0.4.53 (homebridge-knx@0.3.27 cannot run on higher version)

**Comment by migabc** [comment]
I can install the homebridge-ewelink-max and it seems to register fine in homebridge

```
Dec  3 21:49:29 raspberrypi homebridge[6055]: [12/3/2022, 9:49:29 PM] [eWeLink] Veranda Outlets Configure Accessory
Dec  3 21:49:29 raspberrypi homebridge[6055]: [12/3/2022, 9:49:29 PM] [eWeLink] DIMMER1 Configure Accessory
Dec  3 21:49:29 raspberrypi homebridge[6055]: [12/3/2022, 9:49:29 PM] [eWeLink] Christmas Tree Configure Accessory
Dec  3 21:49:29 raspberrypi homebridge[6055]: [12/3/2022, 9:49:29 PM] [eWeLink] Sonoff Basic 3 Configure Accessory
```

But these accessories are not responding in Homekit app

**Comment by bwp91** [comment]
The homebridge compatibility for the knx plugin shows as `"homebridge": ">=0.4.28"` which means homebridge v1.x will also be valid ?

**Comment by migabc** [comment]
Right, that's what it says on the repo page on homebridge-knx but it will not register on versions of homebridge higher than 0.4.53

**Comment by migabc** [comment]
I'm going to try to install the new version of homebridge-ewelink on another instance 
But first I need to remove the old sonoff accessories from the Homekit app - how can I do that?

**Comment by migabc** [comment]
since the homebridge-ewelink-sonoff stopped working I was not able to remove the accessories from the cache by using the disablePlugin flag in the config

But I managed to remove the stale ewelink accessories manually from the cachedAccessories file.

And now I have the latest plugin running on a another homebrige instance that does not have the knx dependency and it's working fine

**Comment by bwp91** [comment]
Hi,
Closing this just as been a little overwhelmed with issues recently.
If this is still an issue or a feature you would like implemented then please do re-open this ticket!
Thanks for your understanding!
