### ISSUE TITLE
Bulldog valve support

### ISSUE THREAD

**Issue by Mattman1291** [bwp91/homebridge-ewelink#440]
* **Please explain your feature request in a one or two sentences.** I would like to add support for the econet Wi-Fi bulldog valve.

* **Is your feature request related to a problem? Please describe.** no

* **Any particular eWeLink devices that this relates to?**
Econet Wi-Fi Bulldog Valve 

* **Anything else?**

**Comment by bwp91** [comment]
Hi @Mattman1291 

Do you already own this device? Do you have any messages in the homebridge log about this being a new device type? You may find this device is already supported.

**Comment by Mattman1291** [comment]
I do own it but haven’t set it up yet but I can if that would help. Yes I checked for it but couldn’t find anything

**Comment by bwp91** [comment]
Most likely it is supported already. Worth a try setting it up!

**Comment by bwp91** [comment]
Hi,
Closing this just as been a little overwhelmed with issues recently.
If this is still an issue or a feature you would like implemented then please do re-open this ticket!
Thanks for your understanding!
