### ISSUE TITLE
Sonoff POW R320 displaying incorrect consumption values

### ISSUE THREAD

**Issue by catanil** [bwp91/homebridge-ewelink#441]
### What issue do you have? Please be as thorough and explicit as possible.

**The consumption values are displayed with no decimals, eg 22522 Watts instead of 225,22 Watts.**

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

**-Homebridge UI-X**

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

**-Raspberry Pi 4, with Raspbian 10 (Buster), Node v18.12.1.**

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

**-homebridge-ewelink v10.3.0**

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

**-Sonoff Power Elite POWR320D**

### Please paste any relevant logs below.

[08/12/2022, 12:11:34] [eWeLink] [Contor] current power [22398W] current voltage [23867V] current current [148A]

```

```

**Comment by bwp91** [comment]
Hi @catanil 

Can you install the beta version of the plugin to see if this fixes these readings?
I have only applied a 'fix' to the outlet device type so if you have used the config to show this device as another accessory type this may not work.

Let me know!

**Comment by catanil** [comment]
Hi @bwp91, I can confirm it's fixed with the beta version, with the accessory type set as outlet. Below is a line from the logs.

Thank you!

**[09/12/2022, 09:17:39] [eWeLink] [Contor] current power [218W] current voltage [236V] current current [1A]**

**Comment by bwp91** [comment]
Hi,
Closing this just as been a little overwhelmed with issues recently.
If this is still an issue or a feature you would like implemented then please do re-open this ticket!
Thanks for your understanding!
