### ISSUE TITLE
Get garage switch door state from zigbee2mqtt

### ISSUE THREAD

**Issue by wladkolc** [bwp91/homebridge-ewelink#442]
* **Please explain your feature request in a one or two sentences.**
I have Sonoff SNZB-04 paierd over zigbee2mqtt, not sonoff zigbee bridge. I want to use sonoff garage switch SV (14) with Sonoff SNZB-04 connecter over zigbee2mqtt.

* **Is your feature request related to a problem? Please describe.**

* **Any particular eWeLink devices that this relates to?**
Sonoff SNZB-04
SV

* **Anything else?**
Can't use sensorId cause i dont have ewelinkID

**Comment by bwp91** [comment]
Hi @wladkolc 

Unfortunately this is not possible as the plugin cannot read state from accessories of different plugins.

**Comment by bwp91** [comment]
Hi,
Closing this just as been a little overwhelmed with issues recently.
If this is still an issue or a feature you would like implemented then please do re-open this ticket!
Thanks for your understanding!
