### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by jasonjcj** [bwp91/homebridge-ewelink#445]
### What issue do you have? Please be as thorough and explicit as possible.
Full functionality for over a year and suddenly no response to HK commands.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

HOOBS

* Which version of Homebridge/HOOBS do you have?

v 1.6

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

HOOBs Box

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?
v  10.3

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.
4 Channel Pro

### Please paste any relevant logs below.

```

```

**Comment by bwp91** [comment]
Hi,
Closing this just as been a little overwhelmed with issues recently.
If this is still an issue or a feature you would like implemented then please do re-open this ticket!
Thanks for your understanding!
