### ISSUE TITLE
Cannot install 10.3.0 in Homebridge 1.6.0.

### ISSUE THREAD

**Issue by ibatten** [bwp91/homebridge-ewelink#446]
### What issue do you have? Please be as thorough and explicit as possible.

Installation of ewelink plugin claims to complete (green popup says installation successful), but the plugin does not appear in the plugin UI.   The module appears as expected in /var/lib/homebridge/node_modules.   The install can be repeated multiuple times with the same message.   By adding the login information to the platform section of the config file I can coax it into life, but I do not have access to (for example) set the ewelink plugin to run as a child bridge, and performace of other plugins seems to drop away.

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 

Homebridge, config-ui.  Platform is Debian 11, latest packages, x86.  node is /opt/homebridge/bin/node v18.12.1.

* Which version of Homebridge/HOOBS do you have?

1.6.0

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

10.3.0.  I have also tried 10.2.0 and the beta, but the problem is the same.  I also have installed http-humidity, http-temperature, levoit-air-purifier, remote-air-quality-http, ring and tapo, all at the latest versions.  I have not had the same problem with those.

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

Install of plugin.

* Do you use your main eWeLink credentials or do you use a secondary eWeLink account for Homebridge?

Primary.

**Comment by ibatten** [comment]
Hmm, that's really weird.  A few hours later, the plugin is all present and working.  I put it into child mode and it's working fine.  I wonder what took the time?  note: as it happens, there are no devices available in LAN mode, the only device I am controlling happens to be on an isolated LAN and is controlled via the cloud service.  That seems like it might make a difference.

**Comment by bwp91** [comment]
Hi,
Closing this just as been a little overwhelmed with issues recently.
If this is still an issue or a feature you would like implemented then please do re-open this ticket!
Thanks for your understanding!
