### ISSUE TITLE
ISSUE with ewelink-max plugin (Sonoff TH16 with temp sensor)

### ISSUE THREAD

**Issue by stefanspurgin91** [bwp91/homebridge-ewelink#45]
Hi,

I'm making home automation system with sonoff switches. Every room has switch+sensor AM2301(temo+hum), and heating system, and door lock,itd…

I have a Homebridge running on Raspberry Pi3+, and im testing only one Sonoff switch with sensor connected. Im installed ewelink-max plugin, because is much beter then old ewelink plugin, no Charles, its all automatically. But I meaned, that when I run Ewelink plugin, that plugin get information from ewelink app(server) and use all switches and sensros I have on ewelink app, that must be on HomeApp. When I go to Home App, I have swtich, its perfectly working, but I have no widget for sensor, which is connected to Sonoff TH16 and activated in ewelink app. This plugin working in other way, I meaned that, plugin sending request from server(ewelink), and getting a list of devices(in debugger he saying that "getting list of devices"), but not, I only get a switch, no sensor in Home APP. 

Can anyone help me with this, how to change a code in plugin, or you plaining to update the plugin. What if I connect 8 Sonoff switch, all with sensor. What devices I will get in Home APP accessories? Can I get 8 switches at least, or just coded for one switch.

Thank in advance!

**Comment by stefanspurgin91** [comment]
#hmangnx
First i meaned that Ewelink-max not working at all, and when i run Home, no platform or acessory added, and i was started a homebridge debuger, and i saw that he actualy trying to connect to ewelink server, a saw request, and i get server response, that saying “not response from server”, and next request is “getting list od devices from ewelink server”, and error 402 and 401. In my server, a was not used phone number at all, only email and password. And in config.json, I just deleted phone number, and let only (platform, name, email, password and imei). Saved config and started homebridge and debbuger, and all working, connected to server, get response, in Home app automaticaly show new acessories, only sensor informationa i wasnt got, probably because is plugin is not have a codecfor this, i dont digging around a code, but it probably it. That’s why i created this Issue.

**Comment by hmangnx** [comment]
Interesting I tried using email instead of phone and I can’t get it to connect properly at all.

**Comment by stefanspurgin91** [comment]
Its important what you use to log into Ewelink app. If you use phone and password, then in config.json only put phone and password, not email. If you use to log in mail and password, then use this in config. Only one of them you have to put in config, email or phone, its depends of your user account. In europe i think only mail, but for Asia server working with phone number, without mail. Can you take some screen shoots of debugger or config.json, or something. 😊

**Comment by hmangnx** [comment]
For the last 3 days I couldn’t get it working. But for some odd reason after I installed the original ewelink and ran Charles to get my config. The “max” version started working... maybe human error and just a coincendent. But it works fine now for what I need.

**Comment by fiska1** [comment]
Hi. What is `imei` - This can be any valid UUID (or maybe any random string will do)"? Where to get it? Thanks.

**Comment by howanghk** [comment]
Hi all, thanks for all the comments and concerns about the [homebridge-ewelink-max](https://github.com/howanghk/homebridge-ewelink) fork of this plugin.

Recently marcelo-paredes contributed code to [support the TH-16](https://github.com/howanghk/homebridge-ewelink/pull/26), which have been merged in version 0.1.14, please give it a try:
```
npm install -g homebridge-ewelink-max@latest
```

@stefanspurgin91 @hmangnx  Regarding the login issues with homebridge-ewelink-max, please see the README for [examples on email login and phone number login](https://github.com/howanghk/homebridge-ewelink/tree/f2f57cf3f6f93135615c1fb9a9db42d5ffd9d0af#sample-configjson).

@fiska1 The imei is a parameter required by the ewelink server, which suppose to be different for each user device. You can get one with an [online generator](https://www.famkruithof.net/uuid/uuidgen?numReq=1&typeReq=4&uppercaseReq=true).

**Comment by John88a** [comment]
> Hi all, thanks for all the comments and concerns about the [homebridge-ewelink-max](https://github.com/howanghk/homebridge-ewelink) fork of this plugin.
> 
> Recently marcelo-paredes contributed code to [support the TH-16](https://github.com/howanghk/homebridge-ewelink/pull/26), which have been merged in version 0.1.14, please give it a try:
> 
> ```
> npm install -g homebridge-ewelink-max@latest
> ```
> 
> @stefanspurgin91 @hmangnx Regarding the login issues with homebridge-ewelink-max, please see the README for [examples on email login and phone number login](https://github.com/howanghk/homebridge-ewelink/tree/f2f57cf3f6f93135615c1fb9a9db42d5ffd9d0af#sample-configjson).
> 
> @fiska1 The imei is a parameter required by the ewelink server, which suppose to be different for each user device. You can get one with an [online generator](https://www.famkruithof.net/uuid/uuidgen?numReq=1&typeReq=4&uppercaseReq=true), it should look like this: `12D9BAB8-4B48-4A63-919C-C91D2219FA0F`.

Hi, Im using this plugin for few weeks and was working fine, but today it stopped working and in homebridge im getting this error:

[eWeLink] An error was encountered while requesting a list of devices while interrogating power status. Verify your configuration options. Response was [{"error":400,"msg":"params incomplete"}]

Any idea what can I do to solve this?

thank you

**Comment by howanghk** [comment]
Hi @John88a, the error you mentioned should be related to https://github.com/howanghk/homebridge-ewelink/issues/48 , which is fixed by https://github.com/howanghk/homebridge-ewelink/pull/49 . Installing version `0.1.16` or later should fix the issue for you.

**Comment by John88a** [comment]
Thank you very much, ill try tonight, so all i need to do is reinstall the plugin?
