### ISSUE TITLE
Add widget in Homekit for THR320 + TH16 etc

### ISSUE THREAD

**Issue by alexhall1986** [bwp91/homebridge-ewelink#450]
* **Please explain your feature request in a one or two sentences.**

Have seen another HomeKit integration for the Sonoff sensors, which provides a widget in HomeKit, ideal for heating, hot water etc. However the integration is unreliable and would rather use your plugin within HomeKit. I wonder how easy is it for you to add a widget similar to the screen shots shown in the attachments? and / or better show the temperature sensor as a tile within HomeKit (perhaps this is a HomeKit limitation?

* **Is your feature request related to a problem? Please describe.**

No problems reported. 

* **Any particular eWeLink devices that this relates to?**

THR320, but also other temperature / switch devices
<img width="505" alt="Screenshot 2023-01-14 at 14 15 02" src="https://user-images.githubusercontent.com/122186472/212476393-078f3376-b542-40e4-857a-a1f3f3cc26e1.png">
<img width="592" alt="Screenshot 2023-01-14 at 14 15 08" src="https://user-images.githubusercontent.com/122186472/212476396-6e11be62-302e-4cd4-8230-ca6a90858ba5.png">

* **Anything else?**

**Comment by bwp91** [comment]
Hi,
Closing this just as been a little overwhelmed with issues recently.
If this is still an issue or a feature you would like implemented then please do re-open this ticket!
Thanks for your understanding!
