### ISSUE TITLE
Devices tripled

### ISSUE THREAD

**Issue by GMTheDoctor** [bwp91/homebridge-ewelink#455]
Hi everyone,
as you can see in the attached picture, devices in my device list are tripled but not in home bridge accessories. I would prefer to not remove and reinstall the plugin because I have lots of devices, can someone help me?

### Details of your setup.
* I use homebridge, latest version. Latest version of Node.js and home bridge-ewelink plugin.
![Screenshot 2023-01-26 alle 00 48 11](https://user-images.githubusercontent.com/82093488/214720621-fab83755-542e-403e-b14f-3e46fbbd4212.png)

**Comment by bwp91** [comment]
Hi,
Closing this just as been a little overwhelmed with issues recently.
If this is still an issue or a feature you would like implemented then please do re-open this ticket!
Thanks for your understanding!
