### ISSUE TITLE
Asking Siri: "What is the status of (any device under the EweLink plugin)?" >>> Fails!

### ISSUE THREAD

**Issue by MoTechnicalities** [bwp91/homebridge-ewelink#457]
### What issue do you have? Please be as thorough and explicit as possible.
Asking Siri: "What is the status of (any device under the EweLink plugin)" >>> Fails!
I have a plethora of accessories under various Homebridge plugins as well as officially supported accessories. Today I took some time to carefully check which devices respond to status checks. To my surprise only (and all of) the EweLink accessories fail a status check.
Every time I ask about these devices, Siri responds with the message: "Some of your devices failed to respond."
There seem to be no problems executing any direct command or automation though.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Raspbian GNU/Linux Buster (10)
homebridge-config-ui-x v4.50.2

* Which version of Homebridge/HOOBS do you have?
homebridge-config-ui-x v4.50.2

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if you know.
Raspberry Pi 3b
Node.js Version | v16.19.0

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?
homebridge-ewelink v10.4.0

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.
Two GD-DC5
Sonoff MINI R2
Sonoff Basic

### Please paste any relevant logs below.

Unfortunately, even in debug mode, nothing is displayed in the log when a status check is requested.
```

```

**Comment by bwp91** [comment]
sorry - catching up - will get to look at this soon!

**Comment by MoTechnicalities** [comment]
Just dropping notes on this ongoing issue. **No Homebridge EWeLINK device allows a check status by Siri.**
Compare Siri's response with my GD-DC5 Garage Door to a response for one of my Lutron switches:

![image](https://user-images.githubusercontent.com/68468472/234754281-b3dfd3de-c002-4d97-b1d6-c10c68d5382b.jpeg)

![image](https://user-images.githubusercontent.com/68468472/234754306-8b8d2add-e590-46ee-9537-4a59ccba5d61.jpeg)

**Comment by MoTechnicalities** [comment]
@bwp91 Ben,

This started working now! So, maybe it was something on Apple'a end!😀
![image](https://github.com/bwp91/homebridge-ewelink/assets/68468472/dee0fd88-530e-42f4-a0bf-46555bb03fea)
