### ISSUE TITLE
An error was encountered while requesting a list of devices. Response was [{"error":401}]

### ISSUE THREAD

**Issue by Rens93** [bwp91/homebridge-ewelink#46]
Hi,

Nothing has changed but now I get this error:

An error was encountered while requesting a list of devices. Response was [{"error":401}]
Verify that you have the correct authenticationToken specified in your configuration. The currently-configured token is [916c85861b********************]

I have already tried to get a new token by Charles, but when I try to get a new token, I won't see the token:

Sent request. Waiting for response…

**Comment by mhermosi** [comment]
Same here....[eWeLink] An error was encountered while requesting a list of devices while interrogating power status. Verify your configuration options. Response was [{"error":401}]

**Comment by rikray02** [comment]
eWelink change token every 3 or 4 weeks.  So, the plugin stop to run. Try this:

1- Connect your iPhone to your wifi network
2- Configure mandatory connection for your wifi network on your iPhone like this
	-MODE:  manual
	-SERVER:  IP address of Charles Server
	-PORT:  8888 (for my Charles configuration)
	-AUTHENTIFICATION:  no
3- Start Charles and start capture
4- Start eWelink on your iPhone and stop capture after eWelink started
5- Find Token in Charles
	-Find:  https://eu-ota.coolkit.cc:8080
	-Find: otaother
	-Find:  app (cn.itead.ota.queryInfo)
	-Select: Contents et Headers
	-Find:  Authorization Bearer 998141e8959eb4a3091e35da1ce4b2a841ac4a06
6- Copy this code in config.json where Homebridge run
7- Stop Homekit
8- restart Homekit
9- Remove mandatory server option in your iPhone

Good Luck

**Comment by zkrige** [comment]
restart home bridge seems to get a new token just fine
