### ISSUE TITLE
HAM-container did not show data of my connected Sonoff DW2 WiFi

### ISSUE THREAD

**Issue by Volker1978** [bwp91/homebridge-ewelink#465]
Hi,
i added the homebridge-adapter to my existing IoBorker environment. But I dont get data in my ham-contanier.

![grafik](https://user-images.githubusercontent.com/124565231/216930873-f9d0fbf0-28de-4bf3-967b-0bf0f166f4bd.png)
This is my config in the adapter:
![grafik](https://user-images.githubusercontent.com/124565231/216932701-2ad7ef72-e251-41d4-8de6-81cf30ca04db.png)

And this in my ewelink:
![grafik](https://user-images.githubusercontent.com/124565231/216932829-bad62458-9941-42a0-b818-500e5188c431.png)

Dou you have got an idea, where I should search the error?
All adapters are up to date and no errors are shown in the reports. In my eweLink ios-app I can see my both adapters are working fine.

I hope, you will have a idea and many thanks from germany to you for your support.

Best regards
Volker

**Comment by bwp91** [comment]
Hi,
Closing this just as been a little overwhelmed with issues recently.
If this is still an issue or a feature you would like implemented then please do re-open this ticket!
Thanks for your understanding!
