### ISSUE TITLE
Add Security Panel from NSPanel Pro and Zigbe Birdge Pro

### ISSUE THREAD

**Issue by joshepw** [bwp91/homebridge-ewelink#473]
* **Please explain your feature request in a one or two sentences.**
The Panel NS Pro and the Zigbe Bridge Pro have the functionality of arming and disarming the security as if it were a security panel.

* **Is your feature request related to a problem? Please describe.**
Incomplete or pending functionality

* **Any particular eWeLink devices that this relates to?**
 Zigbe Bridge Pro and NS Panel Pro

* **Anything else?**
Maybe this works: https://github.com/MiguelRipoll23/homebridge-securitysystem#readme

**Comment by bwp91** [comment]
Hi,
Closing this just as been a little overwhelmed with issues recently.
If this is still an issue or a feature you would like implemented then please do re-open this ticket!
Thanks for your understanding!
