### ISSUE TITLE
After restart

### ISSUE THREAD

**Issue by Themaster312** [bwp91/homebridge-ewelink#483]
### Details of your setup.
* Do you use (1) Homebridge UI-X  4.50.2(2) Homebridge 

* Which version of Homebridge/HOOBS do you have? Homebridge 1.6

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
On a Raspberry 3b

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?
* 10.4.0

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.
Mini r3
Basic r2/r3
Touch
Mini r2
S26

after a restart of all EWeLink devices no response can only be solved by clearing the cache

**Comment by Themaster312** [comment]
With Homebridge 1.5.1 it Works But Not with 1.6

**Comment by bwp91** [comment]
Hi @Themaster312 
Gonna close this issue as i feel you have found it similar to
https://github.com/bwp91/homebridge-ewelink/issues/484 ?
If not please feel free to reopen
