### ISSUE TITLE
Suggestions for handling 406 Error

### ISSUE THREAD

**Issue by jayliao2025** [bwp91/homebridge-ewelink#488]
Hey, I notice that the plugin homebridge-ewelink does nothing just logs warning when receiving `406` error from WebSocket. In fact, `406` will be responded only if the `at` is invalid, expired mostly. **If so, server close the web socket connection immediately,** which leads to that client is caught in a loop of opening a connection, initiating a handshake, and connection being closed.

Thus, my suggestion is that client re-obtains `at` from login interface and re-establish the web socket connection, then do handshake.

**Comment by bwp91** [comment]
Hi @Jardaliao 

`406` warning also appears when a user who is using the same ewelink account for both the plugin and the ewelink app - logs back into the ewelink app.
i know that i suggest with this plugin to use separate accounts for the ewelink app and this plugin. but i am also hesitant to disturb any genuine login into the ewelink app since with your suggestion:

scenario: a user who uses the same credentials for the plugin and the ewelink app has homebridge running and _hardly ever_ uses the ewelink app. They then log into the ewelink app one day, which makes the plugin suddenly start throwing 406 errors in the websocket connection. If I were to implement re-establishing the websocket connection, then in this case the user would be immediately logged out of the ewelink app - with no explanation there as to why.

**Comment by bwp91** [comment]
and by the way i think this is a very reasonable suggestion - i am just hesitant about disrupting any user login into the ewelink app.

**Comment by jayliao2025** [comment]
Hi @bwp91 

> i am just hesitant about disrupting any user login into the ewelink app.

I totally agree with your point of view, my previous suggestion was inappropriate.

In fact, the server is bearing tens of millions of failed `userOnline` requests every day, which has brought us some additional costs. From feature analysis, most of the APIKEY uses this plugin.

So, I suggest adding processing for 406 in the `onClose` callback, such as not reconnecting after receiving 406, but giving the user a prompt. Because after receiving 406, using the same `at` to go online will definitely not succeed.

We will also make corresponding adjustments on the server to address this phenomenon in the future.

**Comment by bwp91** [comment]
Hi @Jardaliao 

> In fact, the server is bearing tens of millions of failed userOnline requests every day, which has brought us some additional costs. From feature analysis, most of the APIKEY uses this plugin.

Okay will try and sort this as soon as I can 😁

**Comment by bwp91** [comment]
thanks for bringing this to my attention

**Comment by bwp91** [comment]
the quickest immediate solution @Jardaliao would be for ewelink to allow a user to login to both the ewelink app and a second place at the same time 💪

**Comment by jayliao2025** [comment]
@bwp91 Thank you for your suggestion . I will present it in the next discussion.

**Comment by jayliao2025** [comment]
We originally planned to do multiple sign-on, so that the ewelink app could apply for multiple `at` at the same time, but it has not been included in the schedule yet. 
In the coming weeks, I will make some adjustments on the server to cope with frequent `userOnline` failure requests, which are not only from users using this plugin.

**Comment by bwp91** [comment]
Am i incorrect or is login in different places supported now with the same account?

**Comment by bwp91** [comment]
take that back, ewelink app just took a long time to log me out

**Comment by bwp91** [comment]
multiple logins for the same account would be easiest. i can make changes to the plugin, but i cannot force any older users to update

**Comment by jayliao2025** [comment]
> multiple logins for the same account would be easiest. i can make changes to the plugin, but i cannot force any older users to update

Multiple logins is on the way.

**Comment by bwp91** [comment]
oh it's like christmas is coming early!

Btw just for some feedback in general I could have probably pushed some more users towards using their own 'free developer' app key if it werent for:

- the fact that is doesn't support most device types (UIID)
- also it doesn't seem to support the get homes endpoint (https://github.com/bwp91/homebridge-ewelink/blob/256ad62924cd9270ba8364eb2dfea40c2947dedf/lib/connection/http.js#L145)

Anyway - multiple logins is super duper ✅ looking forward to this
