### ISSUE TITLE
[NEW DEVICE] Support for SONOFF SNZB-02D (New Temperature/Humidity Sensor)

### ISSUE THREAD

**Issue by vaasu117** [bwp91/homebridge-ewelink#494]
* **Please explain your feature request in a one or two sentences.**
Can you please add support for the new Sonoff Temperature and Humidity Sensor (SNZB-02D)?

https://sonoff.tech/product/gateway-and-sensors/snzb-2d/

* **Is your feature request related to a problem? Please describe.**
No

* **Any particular eWeLink devices that this relates to?**
SNZB-02D

* **Anything else?**
Nope

**Comment by bwp91** [comment]
Hi @vaasu117 is this device not already supported?

**Comment by eurisakella** [comment]
I have two of those and it doesn’t show them in homebridge.

**Comment by vaasu117** [comment]
Hi Ben.

This is the newer version of Sonoff’s Temperature and Humidity which is not
yet supported.

Thanks & Regards,
Sri

**Comment by bwp91** [comment]
Looks like this comment belongs here as it seems this is the matching model:

> [SNZB-02D] is not supported, do create a GitHub issue with the following info:
[1771] {"bindInfos":{"gaction":["1d958b77-3023-4333-8c68-8d2c6a8cc56c_ewelinkGoogleHome"],"smartThings":[]},"subDevId":"fd8377feff10fb301771","parentid":"10015e97c4","fwVersion":"1.0.9","tempComfortUpper":"2700","tempComfortLower":"1900","humiComfortLower":"4000","tempUnit":0,"ASYNC":2,"humidity":"6110","humiComfortStatus":2,"temperature":"2610","tempComfortStatus":0,"timeZone":3,"battery":100,"supportPowConfig":1,"trigTime":"1686605198800","humiComfortUpper":"6000"}.

Thanks for posting this!

**Comment by bwp91** [comment]
Posting for my benefit:

```json
{
  "bindInfos": {
    "gaction": [
      "1d958b77-3023-4333-8c68-8d2c6a8cc56c_ewelinkGoogleHome"
    ],
    "smartThings": []
  },
  "subDevId": "fd8377feff10fb301771",
  "parentid": "10015e97c4",
  "fwVersion": "1.0.9",
  "tempComfortUpper": "2700",
  "tempComfortLower": "1900",
  "humiComfortLower": "4000",
  "tempUnit": 0,
  "ASYNC": 2,
  "humidity": "6110",
  "humiComfortStatus": 2,
  "temperature": "2610",
  "tempComfortStatus": 0,
  "timeZone": 3,
  "battery": 100,
  "supportPowConfig": 1,
  "trigTime": "1686605198800",
  "humiComfortUpper": "6000"
}
```

**Comment by bwp91** [comment]
Can anyone update to the beta version of the plugin and check this device is now working?

https://github.com/bwp91/homebridge-ewelink/wiki/Beta-Version

**Comment by carlheinmostert** [comment]
Hi @bwp91 

Great plugin.  Thanks you.  Please post BTC wallet I would like to contribute.

I have installed the beta nd still get:

[Living Room Temp] is not supported, do create a GitHub issue with the following info:
```
[7014] {
  "bindInfos": {
    "ifttt": [
      "e5de4c63-f035-4a73-a42b-0266f00bca29_c7a1fe14a59d4ae58493540d644fbe6f"
    ],
    "smartThings": [
      "e5de4c63-f035-4a73-a42b-0266f00bca29_ewelink-smartthings-smart-home"
    ],
    "iftttTriggerCnt": 7,
    "gaction": [
      "e5de4c63-f035-4a73-a42b-0266f00bca29_ewelinkGoogleHome"
    ]
  },
  "subDevId": "4b3577feff10fb307014",
  "parentid": "10018edee7",
  "fwVersion": "1.0.9",
  "battery": 100,
  "trigTime": "1687805377000",
  "supportPowConfig": 1,
  "tempUnit": 0,
  "tempComfortLower": "1900",
  "tempComfortUpper": "2700",
  "humiComfortLower": "4000",
  "humiComfortUpper": "6000",
  "temperature": "1860",
  "ASYNC": 2,
  "tempComfortStatus": 1,
  "humidity": "3850",
  "humiComfortStatus": 1,
  "timeZone": 2
}.
```

Please let me know if I can assist further.  Keen to get this sorted as I am new in SONOFF and bought this device.

Many thanks

Carl

**Comment by bwp91** [comment]
@carlheinmostert hey, which device or model is this?

**Comment by bwp91** [comment]
@carlheinmostert anyway, question above was just out of interest for my records!

Please try the newest beta, this device should start working 👍

**Comment by carlheinmostert** [comment]
Regards,Carl0828219102On 28 Jun 2023, at 00:22, Ben ***@***.***> wrote:﻿
@carlheinmostert hey, which device or model is this?

**Comment by eurisakella** [comment]
I tried beta version and everything works great!

**Comment by carlheinmostert** [comment]
Hi @bwp91 

Thanks I have confirmed that my temp device is now working properly.  Many thanks!

Model: SNZB - 02D

Best regards,

Carl-Hein

**Comment by vaasu117** [comment]
Hi Ben.

The beta version is working fine and recognized my SNZB-02D. Thanks a
million.

Regards,
Sri
