### ISSUE TITLE
Unable to Reach eWeLink 

### ISSUE THREAD

**Issue by stanzani-r** [bwp91/homebridge-ewelink#499]
### What issue do you have? Please be as thorough and explicit as possible.
Stuck on getting error
[eWeLink] Unable to reach eWeLink, retrying in 30 seconds [login() - ENOTFOUND].

Updated Node.js, still not working.
Tried reinstalling plugin, and also going back to yesterday's backup (when it was all working) and still "unable to reach".

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge

* Which version of Homebridge/HOOBS do you have?
1.6.1

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Homebridge 1.6.1 on Windows Hyper VM
Node.js [v18.16.0]

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?
10.4

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.
Sonoff switches

**Comment by stanzani-r** [comment]
Hey guys,
I have changed to a LAN operation and it seems to have sorted out the problem, and lucky enough all of my switchers are LAN compatible. Apparently there are no downsides of using LAN only since my setup includes Apple TV as remote home access.
Thanks!

**Comment by bwp91** [comment]
Original error looks like a connection issue with the ewelink server, maybe it happened to be down at the time of your logs, or you have some firewall that was blocking it?

**Comment by bwp91** [comment]
You are correct in that LAN mode is _better_ if all your devices are compatible. 

You can even remove your ewelink credentials from the config:
https://github.com/bwp91/homebridge-ewelink/wiki/Connection-Methods#lan-mode-without-ewelink-credentials

**Comment by stanzani-r** [comment]
Absolutely. Actually I tried LAN mode on the plugin setup leaving my credentials and it kept returning "unable to reach" - maybe was still trying to reach ewelink servers. 
Then, after deleting my credentials from setup, it really started operating locally and worked normally.
Thanks so much Ben!

**Comment by bwp91** [comment]
Gonna close this as _for you_ this issue is resolved.
