### ISSUE TITLE
eWeLink network connectivity issues will cause the homebridge to crash

### ISSUE THREAD

**Issue by migabc** [bwp91/homebridge-ewelink#5]
If there are NW issues preventing the homebridge-ewelink from contacting the ITED servers the homebridge will crash with the following error:

Jan 11 00:02:16 raspberrypi homebridge[25602]: /usr/lib/node_modules/homebridge-ewelink/index.js:71
Jan 11 00:02:16 raspberrypi homebridge[25602]: if (body.hasOwnProperty('error')) {
Jan 11 00:02:16 raspberrypi homebridge[25602]: ^
Jan 11 00:02:16 raspberrypi homebridge[25602]: TypeError: Cannot read property 'hasOwnProperty' of undefined
Jan 11 00:02:16 raspberrypi homebridge[25602]: at /usr/lib/node_modules/homebridge-ewelink/index.js:71:25
Jan 11 00:02:16 raspberrypi homebridge[25602]: at Object.parseBody (/usr/lib/node_modules/homebridge-ewelink/node_modules/request-json/main.js:74:12)
Jan 11 00:02:16 raspberrypi homebridge[25602]: at Request._callback (/usr/lib/node_modules/homebridge-ewelink/node_modules/request-json/main.js:148:26)
Jan 11 00:02:16 raspberrypi homebridge[25602]: at self.callback (/usr/lib/node_modules/homebridge-ewelink/node_modules/request/request.js:187:22)
Jan 11 00:02:16 raspberrypi homebridge[25602]: at emitOne (events.js:96:13)
Jan 11 00:02:16 raspberrypi homebridge[25602]: at Request.emit (events.js:191:7)
Jan 11 00:02:16 raspberrypi homebridge[25602]: at Request.onRequestError (/usr/lib/node_modules/homebridge-ewelink/node_modules/request/request.js:813:8)
Jan 11 00:02:16 raspberrypi homebridge[25602]: at emitOne (events.js:96:13)
Jan 11 00:02:16 raspberrypi homebridge[25602]: at ClientRequest.emit (events.js:191:7)
Jan 11 00:02:16 raspberrypi homebridge[25602]: at TLSSocket.socketErrorListener (_http_client.js:358:9)
Jan 11 00:02:16 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Jan 11 00:02:16 raspberrypi systemd[1]: Unit homebridge.service entered failed state.

Can this be prevented?

**Comment by gbro115** [comment]
Hi @migabc,

That is a problem.

A check needs to be added in `this.webClient.get('/api/user/device', function(err, res, body) {} ` to verify that there was a valid response. 

As I've mentioned in other posts, I'm not going to be actively working on this for some time due to travel commitments. I'll take this into consideration for the next patch upgrade.

Thanks,

George

**Comment by gilbert76** [comment]
I have the same Problem. You have a soloution?
