### ISSUE TITLE
Dual R3 errors in homebridge

### ISSUE THREAD

**Issue by rafht** [bwp91/homebridge-ewelink#503]
I'm using Sonoff Dual R3 in the motor mode for the Garage door
I'm just getting this error message in the log every time

Setup:
Raspberry Pi 4 B v1.5, Homebridge 1.6.1, node.JS [18.16.1]
homebridge-ewelink version - 10.4.0

Config:
            "multiDevices": [
                {
                    "label": "Garage",
                    "deviceId": "1001d8eaeb",
                    "deviceModel": "dualr3_motor",
                    "showAsMotor": "garage",
                    "overrideLogging": "default"
                }

[02/07/2023, 18:58:53] [eWeLink] [Garage] receiving update {"current_00":0,"voltage_00":21131,"actPow_00":0,"online":true,"updateSource":"WS"}.
[02/07/2023, 18:58:53] [eWeLink] [Garage] device update failed as Cannot read properties of undefined (reading 'value') at default.externalUpdate (file:///var/lib/homebridge/node_modules/homebridge-ewelink/lib/device/motor.js:284:28).

**Comment by bwp91** [comment]
Hi @rafht 

Could you update to the beta version of the plugin to see if you still get this message in the logs?

https://github.com/bwp91/homebridge-ewelink/wiki/Beta-Version

Ideally you will no longer see this in the logs!

**Comment by rafht** [comment]
same with the beta version:
[04/07/2023, 20:44:49] [eWeLink] [Garage] receiving update {"current_00":0,"voltage_00":20915,"actPow_00":0,"online":true,"updateSource":"WS"}.
[04/07/2023, 20:44:49] [eWeLink] [Garage] device update failed as Cannot read properties of undefined (reading 'value') at default.externalUpdate (file:///var/lib/homebridge/node_modules/homebridge-ewelink/lib/device/motor.js:284:28).

<img width="1512" alt="image" src="https://github.com/bwp91/homebridge-ewelink/assets/60445291/80475f60-a347-41d6-a65b-8c00402153f4">
<img width="876" alt="image" src="https://github.com/bwp91/homebridge-ewelink/assets/60445291/d86c8d49-5524-4107-972b-71e05379307f">

**Comment by rafht** [comment]
Can you take a look, please? @bwp91 Thanks in advance

**Comment by bwp91** [comment]
@rafht your latest logs still show that the error is happening on line 284 of the file, which means that the beta version has not installed properly.

Please make sure that you have installed the beta version using the link I provided above and restart homebridge, and let me know if you still have the issue

**Comment by rafht** [comment]
<img width="1123" alt="image" src="https://github.com/bwp91/homebridge-ewelink/assets/60445291/18fbfd9c-1733-42e8-9b9d-2aacf0adece0">
<img width="1122" alt="image" src="https://github.com/bwp91/homebridge-ewelink/assets/60445291/4efee780-930d-4da5-b4b2-28e0d61ffdc2">

**Comment by rafht** [comment]
It's on beta @bwp91

**Comment by rafht** [comment]
<img width="759" alt="image" src="https://github.com/bwp91/homebridge-ewelink/assets/60445291/fcfb369d-2b5f-42e9-9782-1a1d2e86fe43">

**Comment by bwp91** [comment]
thanks for confirming @rafht 

can you try the newest beta?

**Comment by rafht** [comment]
Now it's like this @bwp91 
<img width="1134" alt="image" src="https://github.com/bwp91/homebridge-ewelink/assets/60445291/df9b9979-088f-4870-8188-072e4f5ea553">

**Comment by bwp91** [comment]
Hi @rafht 

Please try new beta 10.4.1-beta.12

Sorry this may be a bit of trial and error since I don't own this device

**Comment by rafht** [comment]
Hi @bwp91 I found what was the problem, I added my username and password of ewelink to the plugin and also by mistake added the device ID in multi-channel devices. I cleared added devices and now that error message is gone, but the Garage door is now replaced with a curtain 😆 (I mean R3 motor mode by default from ewelink showing as a curtain)

**Comment by bwp91** [comment]
You probably had it correct in the first place, but please still update to the new beta version.

Multi channel device config is correct for this device, you can add a config like this:

![Screenshot 2023-07-14 at 19 51 54](https://github.com/bwp91/homebridge-ewelink/assets/43026681/248f270b-aa74-4b65-a01e-c926160582c7)

and choose garage door

**Comment by rafht** [comment]
Now it works correctly, thank you very much! On the latest beta, everything is ok

**Comment by bwp91** [comment]
awesome good to hear it’s working!
