### ISSUE TITLE
Support Dw2-RF contact sensor as garage door sensor

### ISSUE THREAD

**Issue by zelik888** [bwp91/homebridge-ewelink#508]
Currently emulating garage door using multichannel sonoff and it works great, thank you. I also have a DW2-RF contact sensor to sense of garage is open or closed and it shows up in the plug-in/Homekit but cannot be used as sensor for the emulated garage (currently supports Wi-Fi or zigbee contact sensor). 

Could this support be added? Sensor shows up in the plug-in fine and works well as an independent HomeKit sensor.

**Comment by bwp91** [comment]
Hi @zelik888 

thanks for your suggestion.

this is something that wouldn't really be viable, let me explain why:

---

sensors like the DW2-wifi or other zigbee sensors offer two definite states at any time:
- `open` - ie the sensor isn't making contact, so this really can be considered 'not closed' (door could be open, opening, stopped, closing)
- `closed` - ie the sensor is making contact and so this can confirm that any door/garage/window is CLOSED ie none of the states above

From these states it is pretty reliable to determine at any time whether any door/curtain/window/garage etc is _closed_ or _not closed_, for this reason I have added the functionality of linking a switch or switches to expose as a grarage/window/door etc via the plugin settings

**Comment by bwp91** [comment]
However, the RF versions of these sensors do not offer this definite closed/not closed status.

They simply 'transmit' to the plugin when the contact has been broken, in other words:
- the plugin can determine when any door/window/garage has _just_ been opened
- the plugin cannot determine any other state after this

These RF devices do not report back to the plugin when the sensor contact has been made again, which makes it really difficult for the plugin to calculate the current state of the door/window/garage.

**Comment by bwp91** [comment]
And when it comes to 'critical' devices like doors/windows/garages I am hesitant to start trying to make workarounds which for example may work 50% of the time but are not reliable

**Comment by zelik888** [comment]
Thank you, I understand. I sadly purchased the RF after using the WIFI DW2 because the WIFI had such terrible battery life! I guess I must get the zigbee version then. I thank you so much for the plugin!
