### ISSUE TITLE
Pleaase add support for T5 wall switch (TX ultimate)

### ISSUE THREAD

**Issue by Shadowxrp** [bwp91/homebridge-ewelink#521]
* **Please explain your feature request in a one or two sentences.**

I would loove that you supported the T5 switch to control with homekit

Model: T5-1C-86 (209)
--

* **Is your feature request related to a problem? Please describe.**

Yes since it is not supported the plugin shows the T5 switch on homekit but it doesn’t work and shows no response

* **Any particular eWeLink devices that this relates to?**

Yes the T5 or tx ultimate : 

T5-1C-86 (209)
--

* **Anything else?**

**Comment by Shadowxrp** [comment]
Oh if you add support for this device I will of course sponsor to show my support for you in return :)

**Comment by bwp91** [comment]
Are you sure this device isn't working? It should be supported already.

Can you update to the beta version of the plugin, and then post some homebridge logs that appear when you try to control the device?

https://github.com/homebridge/homebridge/wiki/How-to-Install-Alternate-Plugin-Versions

**Comment by FWMatt** [comment]
Its working for me with 12.0.0. Any guidance on how to expose the light on the TX Ultimate to Homebridge?

**Comment by Shadowxrp** [comment]
> Are you sure this device isn't working? It should be supported already.
> 
> Can you update to the beta version of the plugin, and then post some homebridge logs that appear when you try to control the device?
> 
> https://github.com/homebridge/homebridge/wiki/How-to-Install-Alternate-Plugin-Versions

Hi and thank you for replying here is the log when i try to control : 

[22/11/2023, 21:14:49] [eWeLink] [Sono
Ff
Switch] sending n"}.
update {"switch":"
[22/11/2023, 21:14:51] [eWeLink] [Sono ff Switch] reverting to web socket as 400 at default. sendUpdate (file:///var
/lib/homebridge/node_modules/homebridg e-ewelink/lib/connection/lan.js:288:15
[22/11/2023, 21:14:51] [eWeLink]
[Sono
ff Switch] receiving update {"switches
": [ {"switch": "off"
"outlet":0}1, "onlin
e":true, "updateSource": "LAN" }.
[22/11/2023, 21:14:511 [eWeLink] [Sono ff Switch] device update failed as unk nown WS response [400] at default.send Update (file:///var/lib/homebridge/nod e_modules/homebridge-ewelink/lib/conne ction/ws.js:337:19) at default. sendUpd ate (file:///var/lib/homebridge/node_m odules/homebridge-ewelink/lib/connecti on/ws.js:341:15).
[22/11/2023, 21:14:511 [eWeLink]
[Sono
ff Switch] receiving update {"switches :[{"outlet" :0, "switch": "off"},{"out…….
![IMG_6175](https://github.com/bwp91/homebridge-ewelink/assets/148715233/c9d0705e-53e1-47a4-9acb-f2e5e81fcc0d)

**Comment by Shadowxrp** [comment]
I added it as a single channel device, in model there is no option for t5 so left it at none, dtatus by inching unchecked, connection mode (hybrid), cloud and lan status on “my devices” tab show online…

**Comment by bwp91** [comment]
Can you try the beta version of the plugin to see if this makes any difference?

https://github.com/homebridge/homebridge/wiki/How-to-Install-Alternate-Plugin-Versions

**Comment by Shadowxrp** [comment]
Yep the new beta version you released fixed it ! Thank you so much ! I just sent you a little thanks via paypal
