### ISSUE TITLE
Is this method still working?

### ISSUE THREAD

**Issue by fabiopedrosa** [bwp91/homebridge-ewelink#53]
I'm checking to see if this still works, but having issues connecting to the websocket server at `wss://eu-pconnect2.coolkit.cc:8080/api/ws`

Can anyone confirm this still works?

**Comment by MitchJackson94** [comment]
Not working for me

**Comment by waitingwaiting** [comment]
Me either

On 4 Jun 2019, at 8:45 am, Mitchell Jackson <notifications@github.com> wrote:

Not working for me
