### ISSUE TITLE
New fan speed settings aren't working properly

### ISSUE THREAD

**Issue by pickanothername** [bwp91/homebridge-ewelink#542]
### What issue do you have? Please be as thorough and explicit as possible.
The new fan speed configuration is not working properly for me. It shows as a 0-100% scale and I have to select by moving the slider a pixel up or down. My fan is broken in all automations, which wouldn't be a huge deal to fix except that the fan in all automations is still shown with the original 0%-33%-66%-99% setup, so I can only set it to off (0%) or full speed, since obviously 33% is above 3%. This persists even when I remove and re-add the accessory to the automations.
Attached is a photo of what my UI looks like.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
v1.7.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi
Node.js v20.12.0
NPM  v10.5.0

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?
v12.2.0, the issue began with this version.

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.
Sonoff iFan02

### Please paste any relevant logs below.
I haven't seen anything relevant in the logs, but I'll update this if I notice anything or if logs are requested.

<img width="285" alt="My UI" src="https://github.com/bwp91/homebridge-ewelink/assets/1732093/3595685e-1cea-4c79-98f4-3cd144fcc12c">

**Comment by manasagrawal** [comment]
I managed to get the new behavior by removing the cache for each fan:

Three Dots on top right.
Settings.
Scroll down and near the bottom is "Managed Cached Accessories"
Click on the box to the right of "Remove Single Cached Accessory"
A list will pop up listing each accessory. Click on the red trash can.

**Comment by pickanothername** [comment]
It seems in my case, I just needed to wait for my Homekit caches on each device (or the hub?) to clear. Or maybe Homebridge cleared its own cache automatically. In any case, the new behavior is now working for me as well.
Thanks for the tip!
