### ISSUE TITLE
[eWeLink] An error was encountered while requesting a list of devices while interrogating power status. Verify your configuration options. Response was [{"error":400,"msg":"params incomplete"}]

### ISSUE THREAD

**Issue by migabc** [bwp91/homebridge-ewelink#56]
Hi,

Today I started getting this error which causes homebridge to crash

`
Nov 28 20:42:50 raspberrypi homebridge[12796]: [11/28/2019, 8:42:50 PM] [eWeLink] An error was encountered while requesting a list of devices while interrogating power status. Verify your configuration options. Response was [{"error":400,"msg":"params incomplete"}] Nov 28 20:42:50 raspberrypi homebridge[12796]: [11/28/2019, 8:42:50 PM] TypeError: body.filter is not a function Nov 28 20:42:50 raspberrypi homebridge[12796]: at /usr/lib/node_modules/homebridge-ewelink/index.js:364:37 Nov 28 20:42:50 raspberrypi homebridge[12796]: at Object.parseBody (/usr/lib/node_modules/homebridge-ewelink/node_modules/request-json/main.js:74:12) Nov 28 20:42:50 raspberrypi homebridge[12796]: at Request._callback (/usr/lib/node_modules/homebridge-ewelink/node_modules/request-json/main.js:148:26) Nov 28 20:42:50 raspberrypi homebridge[12796]: at Request.self.callback (/usr/lib/node_modules/homebridge-ewelink/node_modules/request/request.js:187:22) Nov 28 20:42:50 raspberrypi homebridge[12796]: at Request.emit (events.js:193:13) Nov 28 20:42:50 raspberrypi homebridge[12796]: at Request.<anonymous> (/usr/lib/node_modules/homebridge-ewelink/node_modules/request/request.js:1044:10) Nov 28 20:42:50 raspberrypi homebridge[12796]: at Request.emit (events.js:193:13) Nov 28 20:42:50 raspberrypi homebridge[12796]: at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-ewelink/node_modules/request/request.js:965:12) Nov 28 20:42:50 raspberrypi homebridge[12796]: at IncomingMessage.emit (events.js:198:15) Nov 28 20:42:50 raspberrypi homebridge[12796]: at endReadableNT (_stream_readable.js:1139:12) Nov 28 20:42:50 raspberrypi homebridge[12796]: at processTicksAndRejections (internal/process/task_queues.js:81:17) Nov 28 20:42:50 raspberrypi homebridge[12796]: [11/28/2019, 8:42:50 PM] Got SIGTERM, shutting down Homebridge... Nov 28 20:42:55 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=143/n/a
`

Has the protocol changed on the server side?

Thanks,
Miguel

**Comment by migabc** [comment]
upgraded to homebridge-ewelink-max

https://github.com/howanghk/homebridge-ewelink

Problem solved

**Comment by mladjan** [comment]
I have the same issue. Will try another plugin...

**Comment by aladin2000** [comment]
what is the alternative plugin ?

**Comment by aladin2000** [comment]
what alternative ?

**Comment by aladin2000** [comment]
> I have the same issue. Will try another plugin...

what alternative  ?
