### ISSUE TITLE
It is recommended that you use websocket to get device status instead of requesting API

### ISSUE THREAD

**Issue by coolkit-carl** [bwp91/homebridge-ewelink#58]
Hello,

There are some problems in the way of getting the device status of your project. Although the request device list (/api/user/device) can get all the device status, too many requests for the interface will cause great pressure on the coolkit server. It is recommended to use websocket to monitor and get the latest status of the device in real time.

Relevant document address: [https://coolkit-technologies.github.io/apiDocs/findStatus_en.html](https://coolkit-technologies.github.io/apiDocs/findStatus_en.html)

It can improve your project and hope to adopt it.

Thank you!

**Comment by gbro115** [comment]
Hi @coolkit-carl ,

Thanks for your comments. Is the link provided valid? I'm unable to access the site.

Thanks!

**Comment by coolkit-carl** [comment]
> Hi @coolkit-carl ,
> 
> Thanks for your comments. Is the link provided valid? I'm unable to access the site.
> 
> Thanks!

Sorry，This is the correct url address：

[https://coolkit-technologies.github.io/apiDocs/findStatus_en.html](https://coolkit-technologies.github.io/apiDocs/findStatus_en.html)

**Comment by gbro115** [comment]
Thanks @coolkit-carl ,

The API documentation will be a welcome addition to those actively working on this project.

As mentioned in the readme of the original repo, I'm no longer maintaining this project. It would be best to pass this info on to the maintainers of the [homebridge-ewelink-max fork](https://github.com/ByronTudhope/homebridge-ewelink-max).

**Comment by coolkit-carl** [comment]
> Thanks @coolkit-carl ,
> 
> The API documentation will be a welcome addition to those actively working on this project.
> 
> As mentioned in the readme of the original repo, I'm no longer maintaining this project. It would be best to pass this info on to the maintainers of the [homebridge-ewelink-max fork](https://github.com/ByronTudhope/homebridge-ewelink-max).

OK, I see, thank you for your reply.

**Comment by gbro115** [comment]
@fabianoflnsp @ronnieroberts making you aware of this request to use the proper API to get device status.
