### ISSUE TITLE
homebridge-ewelink

### ISSUE THREAD

**Issue by bwp91** [bwp91/homebridge-ewelink#69]
Hi,
Is this package still maintained?
I would be interested in having the homebridge-ewelink name for my ewelink plugin.
@gbro115 is there a way I can contact you?
Thanks
Ben

**Comment by gbro115** [comment]
Hi @bwp91 ,

I no longer maintain this package. 

Would you like me to transfer ownership of the repository to you?

Thanks

**Comment by bwp91** [comment]
If you are happy to?
Please check my plugin homebridge-ewelink-sonoff it has verified status by homebridge.
I feel the homebridge-ewelink name would be more appropriate as there are also a number of non-sonoff devices (using ewelink) that I have added support for.
Thanks
Ben

**Comment by gbro115** [comment]
GitHub won't let me transfer the repo

> bwp91 already has a repository in the gbro115/homebridge-ewelink network

I've added you as a contributor. Let me know if you can see any way to take ownership.

**Comment by bwp91** [comment]
okay try again now?

**Comment by bwp91** [comment]
ive deleted the repo i had "in the gbro115/homebridge-ewelink network"

**Comment by bwp91** [comment]
thanks for sorting that out. would you also be able to transfer the package to me on npm? my username there is the same "bwp91".

**Comment by bwp91** [comment]
@gbro115 please let me know if you are happy to do the above and if there is anything else you need from me.
thanks!

**Comment by gbro115** [comment]
Hi @bwp91,

I've just sent through an invitation on npm.

Thanks!

**Comment by bwp91** [comment]
@gbro115 ive never done it like this before. i can see it my account list of packages but no "Settings" tab. Do I just publish over it?

**Comment by gbro115** [comment]
I was following https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account

I think that you should be able to publish over what is there

**Comment by bwp91** [comment]
`npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/homebridge-ewelink - You do not have permission to publish "homebridge-ewelink". Are you logged in as the correct user?`

**Comment by bwp91** [comment]
working now. perhaps there is a delay with npm.

**Comment by gbro115** [comment]
Great. Are you ready for me to remove myself as a maintainer?

Thanks!

**Comment by bwp91** [comment]
Yes of course.
I promise to look after your baby 🤞🏻 
Thank you so much!

**Comment by gbro115** [comment]
Thank you for taking it over!

Best of luck.
