### ISSUE TITLE
Can't find the Authentication Token in Charles

### ISSUE THREAD

**Issue by uc1dp** [bwp91/homebridge-ewelink#7]
Hy
I can't find the token.
I've read the Issue of Kohle81, but i still can't find the Token.

![ohne titel](https://user-images.githubusercontent.com/35506571/35012389-ee417eae-fb09-11e7-8499-456acbcce0ad.jpeg)

**Comment by 18066034545** [comment]
没有授权SSL成功

**Comment by uc1dp** [comment]
and how can i do this?

**Comment by 18066034545** [comment]
我在hass论坛发了帖子，你去看看搜索易微联就出来了

**Comment by uc1dp** [comment]
Can you give me the link of this forum?
Can‘t find it via google.

**Comment by 18066034545** [comment]
https://bbs.hassbian.com/forum.php?mod=viewthread&tid=2454&highlight=homebridge

**Comment by andreasok** [comment]
Found a fix? Have tried following the forum with SSL.. Still no hope..

**Comment by uc1dp** [comment]
No. I used instead of this plugin the Tasmota-http

**Comment by xMadelain** [comment]
Hi, @18066034545 
Try to follow your post 
register in Windows certificat
register in iPhone
....

I need to add  
![image](https://user-images.githubusercontent.com/36514795/37250468-ab7c376c-24fd-11e8-877b-a3b416931cad.png)
to get info from https site
But still have
![image](https://user-images.githubusercontent.com/36514795/37250479-ecacb84c-24fd-11e8-941f-63b2f30b3300.png)

Please help

**Comment by solognt** [comment]
You will have to:
- Enable SSL for the ewelink servers ("*.coolkit.cc:8080") in Charles using the "SSL Proxying settings".
- Now on your iPhone 
-- In Safari go to "http://www.charlesproxy.com/getssl" to install the certificate.
-- go to Settings > General > About > Certificate Trust Settings and trust the "Charles Proxy CA" certificate

Now restart the EWeLink app and you should be able to see the api calls including the Authentication Token :)

See for more info:
https://www.charlesproxy.com/documentation/proxying/ssl-proxying/
https://www.charlesproxy.com/documentation/faqs/ssl-connections-from-within-iphone-applications/
https://support.apple.com/en-us/HT204477

**Comment by xMadelain** [comment]
@solognt 
Thanks, forgot to trust Charles's certificate on iOs !
