### ISSUE TITLE
[solved] Sonoff switches lagging after moving to homebridge-ewelink

### ISSUE THREAD

**Issue by guanoplum** [bwp91/homebridge-ewelink#70]
**What issue do you have? Please be as thorough and explicit as possible.**

Hello, I have experienced some problems with that plugin after replacing the homebridge-ewelink-sonoff into the new ewelink plugin as advised in the description of an update I came across today.  Im not sure if that is caused only by the change or in general by updating to the newest version, but on the previous (dont remember exactly what version ive been using, but lets say it was actual like a week ago) everything was working smoothly, clicking in homebridge was turnin on/off my lights within a second, whereas now it takes at least 3-4s to change their state.  
...

**Details of your setup.**
Do you use Homebridge or HOOBS?

...

Which version of Homebridge/HOOBS do you have?

Homebridge v1.1.2
Node.js  v12.18.3
Npm v6.14.6

...

Which version of this plugin (homebridge-ewelink) do you have?

homebridge-ewelink v2.19.2
...

**Please paste any relevant logs below. It helps if you can turn `debug` and `debugReqRes` in the package settings for more thorough logging.**
> If you are posting an error then it is helpful for me to also see the previous few lines as this can show the cause of the error.

...

**Comment by bwp91** [comment]
This is indeed strange as I have made no changes to the connection between homebridge and ewelink in the last few updates.
I can suggest restarting Homebridge to see if this makes things any faster? This can really work sometimes.
Also, in the optional settings of the plugin do you have the connection mode set to "lan mode" or "web socket"?
I would recommend "lan mode" as this is generally faster for devices that support it.
Please give homebridge a restart and let me know if this makes things faster?

**Comment by guanoplum** [comment]
Ok it seems like that „lan mode” solved it ;) now it works smoothly like before. 

Thanks for your help!!

**Comment by bwp91** [comment]
Ah fab. Glad it's responsive again.
I'll actually keep this issue open for a while in case other people experience the same thing and this could be helpful.

**Comment by ozzyobr** [comment]
@bwp91 I've experienced the same behavior, switching to lan fixed the problem
