### ISSUE TITLE
Groups in homebridge

### ISSUE THREAD

**Issue by imtitanic** [bwp91/homebridge-ewelink#71]
**What issue do you have?** 

Well, this is not an issue (maybe, idk) but what's supposed to happen when I created a group? The device changes automatically to garage in home app? Is the Sonoff 5V compatible with this? 

**Details of your setup.
Do you use Homebridge or HOOBS?**

Homebridge 

**Which version of Homebridge/HOOBS do you have?**

V. 1.1.2

**Which version of this plugin (homebridge-ewelink) do you have?**

V. 2.19.2

**Please paste any relevant logs below. It helps if you can turn `debug` and `debugReqRes` in the package settings for more thorough logging.**
> If you are posting an error then it is helpful for me to also see the previous few lines as this can show the cause of the error.

...

**Comment by bwp91** [comment]
Hi,
The groups settings feature currently only supports exposing accessories as a window blind or garage door.
This is why your device has now appeared as a garage door!
Out of interest what were you hoping achieve from a group with your Sonoff 5V?

**Comment by imtitanic** [comment]
Hello hello would say Elton John

Well... I expected exactly that (I use the sonoff to open/close the garage door) but my device won't appears as a garage door! Still appears like a swith in Home app. I created the group but nothing changes.

**Comment by imtitanic** [comment]
> I see! I misunderstood your original post. Sorry!
> Please try removing the device from the Homebridge cache (in Homebridge settings) and then Homebridge will restart.
> Let me know if this works!

Yup, after doing that the device change to garage door!

**Comment by bwp91** [comment]
Ah fab.
Eventually I will get round to coding a better way but for now that's the solution.
I should really document it 😝

**Comment by imtitanic** [comment]
Hahaha 

I guess when the sensor comes I will need do it again.. I don't know.. We will see.

Thank you 😋

**Comment by bwp91** [comment]
Happy for me to close this issue? 😀
