### ISSUE TITLE
L1 sonoff lagging

### ISSUE THREAD

**Issue by muriloscosta** [bwp91/homebridge-ewelink#73]
**What issue do you have? Please be as thorough and explicit as possible.**
I have some sonoff devices at my home, TH16, T1 and L1. All of them are working fine with this plugin, except L1 that takes aprox 10 seconds to turn on/off
...
**Details of your setup.**
Do you use Homebridge or HOOBS?
Homebridge

Which version of Homebridge/HOOBS do you have?
Homebridge v1.1.2
Node.js v12.18.3
Npm v6.14.7

Which version of this plugin (homebridge-ewelink) do you have?
homebridge-ewelink v2.23.0

**Comment by bwp91** [comment]
Hi, 
I have just released an update that _might_ make things slightly faster for your L1. 
The TH16 and T1 support a mode called "lan mode" which makes their updates almost instantaneous.
The L1, however, does not support this mode and needs to update "through the cloud" which can cause a very slight delay.
Let me know if the update improves anything for you?
Please don't forget to restart Homebridge after you update, often this can make things faster anyway.
