### ISSUE TITLE
Ability to hide switch on Sonoff TH16

### ISSUE THREAD

**Issue by rwgunther** [bwp91/homebridge-ewelink#75]
Provide an option to hide the switch component of the Sonoff TH16 from HomeKit.
...

For people who only use the sensor on the TH16, it would be nice to be able to hide the switch portion. Right now, it takes some tricky naming to be able to request the temperature though Siri, for example, since by default the device status returned is the switch state.

**Comment by rwgunther** [comment]
That works! I found I had to dump the thermostat accessory from the Homebridge cache twice—maybe I did it out of order. But it's working great now. Thank you!

**Comment by bwp91** [comment]
Fab glad it's working :)
