### ISSUE TITLE
Can’t control LED strip

### ISSUE THREAD

**Issue by AAG97** [bwp91/homebridge-ewelink#76]
**What issue do you have? Please be as thorough and explicit as possible.**

I have the Sonoff led strip which I can control from the eWeLink application ... I can turn it off and on but can't change color etc like the eWeLink app plus there is a a very big waiting interval when I switch it unlike other devices which are instantaneous￼
...

**Details of your setup.**
Do you use Homebridge or HOOBS?

Hoobs
...

Which version of Homebridge/HOOBS do you have?
3.2.6
...

Which version of this plugin (homebridge-ewelink) do you have?
2.19.3
...

**Please paste any relevant logs below. It helps if you can turn `debug` and `debugReqRes` in the package settings for more thorough logging.**
> If you are posting an error then it is helpful for me to also see the previous few lines as this can show the cause of the error.

...

**Comment by AAG97** [comment]
Plus im trying to install a plug in called ewelink beta with the version 2.23.0 but tells me install plugin failed .. so not sure if im using the right plugin or the right version

**Comment by bwp91** [comment]
Please try uninstalling all ewelink plugins and then install this plugin called "homebridge-ewelink".
This plugin does support the L1 LED strip with colours and brightness.
If it's not working then I can look into it more.
thanks
Ben

**Comment by AAG97** [comment]
Sorry but I can't find such plug in![Uploading 91099042...]

**Comment by bwp91** [comment]
If you just search for “ewelink” does it appear in the list?

**Comment by AAG97** [comment]
No the same 4 plugins appear

**Comment by AAG97** [comment]
The beta version of yours is appearing  (2.23) and an old version of the main one (2.19.3)which when I enter it, it takes me to Github and says the projects has moved to another one (the one you are telling me to install 2.24) yet I can't find it through the plugin search
Is there a way to install it manually or something?

**Comment by AAG97** [comment]
Can it be because im using HOOBS ?

**Comment by bwp91** [comment]
Yes the ewelink-beta and ewelink-sonoff are old packages of mine.
ewelink-max is owned by someone else.
The package you indeed need to use is just ewelink (homebridge-ewelink) and i don’t understand why it’s not appearing in the list. I know other users who use HOOBS with this package.
There is a way of installing it manually but it’s very complicated and i wouldn’t recommend it.
HOOBS offer dedicated support for their platform and I would suggest getting in contact with them re why it isn’t appearing as this is something out of my control.

**Comment by AAG97** [comment]
so a guy on reddit gave me a solution and installed it... still the strip only shows on/off switch... i cant control the colors :/

**Comment by bwp91** [comment]
Just to clarify-
Are you talking about controlling the colours through HOOBS or apple home app?

**Comment by AAG97** [comment]
Apple home app

**Comment by bwp91** [comment]
Would you be happy to send me an email?
bwp91@icloud.com

**Comment by bwp91** [comment]
Fixed in v2.24.1
