### ISSUE TITLE
Lagging after last update 

### ISSUE THREAD

**Issue by tawagny** [bwp91/homebridge-ewelink#77]
homebridge-ewelink v2.24.0
homebridge-config-ui-x v4.26.0 on Docker
devices sonoff mini , Dual, 4ch po and s20 plugs
the Lan mode is enabled on all of my devices they respond after 2-3 seconds , Using Homeassistant also this lag is not  happening  there .
I know that now its by default lan then ws .. not really sure why this is happening

**Comment by bwp91** [comment]
Hi,
Sorry taken a few days for me to reply, I'm away at the moment so it's more difficult to get on a computer.
Are you still having lag issues?

**Comment by tawagny** [comment]
Well its gone for now 😄

**Comment by tawagny** [comment]
Appreciate what you are doing really.  Thank you

**Comment by tawagny** [comment]
not lagging now , I guess it was HB related , closing it
