### ISSUE TITLE
Problem with HOOBS iFan03: API reported an unknown status for device

### ISSUE THREAD

**Issue by Idan212** [bwp91/homebridge-ewelink#78]
**What issue do you have? Please be as thorough and explicit as possible.**
Keep getting this error on logs with HOOBS. seems to work but always with alert on Home app that Fan is not responding.
8/30/2020, 11:54:23 PM [eWeLink] API reported an unknown status for device [Fan]

seems everything is working good with the light side.

latest HOOBS version and latest plugin version.

Appreciate your help!

**Comment by bwp91** [comment]
Hi,
Please make sure you are using the latest version of the plugin.
The error you have described is not an error that is shown by the latest version - indeed it is an error shown by a previous version of this plugin.
Thanks

**Comment by Idan212** [comment]
> Hi,
> Please make sure you are using the latest version of the plugin.
> The error you have described is not an error that is shown by the latest version - indeed it is an error shown by a previous version of this plugin.
> Thanks

Thanks for comment
Yeah I’m with latest version. Just installed it actually :)

**Comment by bwp91** [comment]
I lack experience with HOOBS.
Please could you show a screenshot of the plugin version you have installed?

**Comment by Idan212** [comment]
> I lack experience with HOOBS.
> Please could you show a screenshot of the plugin version you have installed?

Yeah sure it’s the HOOBS certified
![E3FC2E74-2044-421C-A8A9-CBBE2BC83891](https://user-images.githubusercontent.com/68989255/91672484-9f814800-eb37-11ea-85ae-df06b9a916db.jpeg)

**Comment by bwp91** [comment]
Ah this is the issue here.
You have a different plugin installed.
You have ewelink-max installed this isn't my plugin!
