### ISSUE TITLE
Can't uninstall older version

### ISSUE THREAD

**Issue by LotharKnysna** [bwp91/homebridge-ewelink#79]
I wanted to upgrade to the latest release and you recommand:
"Please note you will need to uninstall any previous homebridge-ewelink plugins before installing this version. I would also recommend clearing the accessory cache if you had a previous homebridge-ewelink plugin installed."
Unfortunatley in my Hoobs list of plugins the button "Uninstall" is missing for this plugin. And in the log file I found

[homebridge-ewelink-sonoff.eWeLink] ** Could not load homebridge-ewelink-sonoff **
[homebridge-ewelink-sonoff.eWeLink] Make sure your eWeLink credentials are in the Homebridge configuration.

I can see the devices in Homekit, but I have no access to configuration.

Can you advise how to manually uninstall the old version?
Kind regards
Lothar
![screenshot1](https://user-images.githubusercontent.com/70701987/92115794-447b7980-edf3-11ea-87c4-9fdaccd34564.PNG)

**Comment by bwp91** [comment]
Hi,
I'm having issues with my plugin and HOOBS at the moment, issues im trying to sort out but are out of my control.
With regards to uninstalling the ewelink-sonoff plugin can I redirect you to HOOBS support as they will be much more knowledgable than me with this respect.
Let me know if you manage to uninstall it, and I will let you know when i've managed to get my plugin into HOOBS again.
Thanks

**Comment by bwp91** [comment]
I may have found a solution.
Are you on the homebridge discord?

https://discord.com/channels/432663330281226270/742733745743855627

Please create a direct chat with me on there my username is bwp91

thanks

**Comment by LotharKnysna** [comment]
Hi Ben,

Unfortunately, I was not on Discord. I created an account and used your link, but all I get I an empty page. Searching for Homebridge doesn’t find anything. 

And adding you as friend is not possible, its asking for a tag in addition to your username.

 

I am missing something here obviously.

Any idea?

Lothar

 

Von: Ben <notifications@github.com> 
Gesendet: Donnerstag, 3. September 2020 17:00
An: bwp91/homebridge-ewelink <homebridge-ewelink@noreply.github.com>
Cc: LotharKnysna <lothar@hoefle.co.za>; Author <author@noreply.github.com>
Betreff: Re: [bwp91/homebridge-ewelink] Can't uninstall older version (#79)

 

I may have found a solution.
Are you on the homebridge discord?

https://discord.com/channels/432663330281226270/742733745743855627

Please create a direct chat with me on there my username is bwp91

thanks

**Comment by bwp91** [comment]
Did you manage to register there? 
If so what is your username?

**Comment by LotharKnysna** [comment]
I did, username is Trumbidor#5984

 

I searched on Hoogs.org for a solution and the only I found was this:

https://github.com/hoobs-org/HOOBS/issues/660

 

to use

rm -fR ~/.hoobs/node_modules/homebridge-ewelink-sonoff

 

which doesn’t work. I have no idea why I can’t delete the directory. 

 

I can’t see the plugin here:

{

    "server": {

        "port": 80,

        "origin": "*",

        "autostart": 0,

        "home_setup_id": "X-HM://0023ISYWY7337",

        "polling_seconds": 5

    },

    "client": {

        "default_route": "status",

        "inactive_logoff": 30,

        "theme": "hoobs-dark",

        "locale": "de",

        "temp_units": "celsius",

        "country_code": "ZA",

        "postal_code": "6570",

        "latitude": "-34.083235",

        "longitude": "23.0569273"

    },

    "bridge": {

        "name": "HOOBS",

        "port": 51826,

        "pin": "031-45-154",

        "username": "CB:19:E2:74:3F:3A"

    },

    "description": "",

    "ports": {},

    "accessories": [

        {

            "accessory": "DummySwitch",

            "plugin_map": {

                "plugin_name": "homebridge-dummy",

                "index": 0

            },

            "stateful": false,

            "reverse": false,

            "time": 1000,

            "name": "Tor"

        }

    ],

    "platforms": []

}

 

 

 

Von: Ben <notifications@github.com> 
Gesendet: Samstag, 5. September 2020 00:07
An: bwp91/homebridge-ewelink <homebridge-ewelink@noreply.github.com>
Cc: LotharKnysna <lothar@hoefle.co.za>; Author <author@noreply.github.com>
Betreff: Re: [bwp91/homebridge-ewelink] Can't uninstall older version (#79)

 

Did you manage to register there?
If so what is your username?

**Comment by bwp91** [comment]
Please try this link for discord:

https://discord.gg/jsESWH

If that doesnt work then i'll give further instructions on here!

**Comment by LotharKnysna** [comment]
I am in the group. Worked!

 

 

Von: Ben <notifications@github.com> 
Gesendet: Samstag, 5. September 2020 10:03
An: bwp91/homebridge-ewelink <homebridge-ewelink@noreply.github.com>
Cc: LotharKnysna <lothar@hoefle.co.za>; Author <author@noreply.github.com>
Betreff: Re: [bwp91/homebridge-ewelink] Can't uninstall older version (#79)

 

Please try this link for discord:

https://discord.gg/jsESWH

If that doesnt work then i'll give further instructions on here!

**Comment by Raptor0014** [comment]
Is there any way the solution can be shared on here? I am having the same issue and con not remove the old 2.19.3 plugin.

**Comment by bwp91** [comment]
Hi @Raptor0014 which plugin are you looking to uninstall? `homebridge-ewelink` or `homebridge-ewelink-sonoff`?
or even `homebridge-ewelink-beta`?

**Comment by nejcklinc** [comment]
Hi @bwp91 I am trying to remove nest-cam2 plugin. Can you please tell us how we can do it?

**Comment by bwp91** [comment]
Hi @nejcklinc 

Assuming you're on hoobs, try (1) stopping hoobs and then (2) running this command in the terminal:

`npm uninstall homebridge-nest-cam2`

Then (3) start hoobs again.

If this doesn't work then you'll need to contact hoobs for support. This repo is for questions related to homebridge-ewelink.

Thanks
