### ISSUE TITLE
No Response [oneSwitch garagedoor with no sensor]

### ISSUE THREAD

**Issue by allanjeevan** [bwp91/homebridge-ewelink#80]
**What issue do you have? Please be as thorough and explicit as possible.**
When I open the garage door from the home app it opens the garage door but shows as unresponsive after it being opened then I have to close the home app and start it again for it to get resolved. 
...

**Details of your setup.**
Do you use Homebridge or HOOBS?
Homebridge
...

Which version of Homebridge/HOOBS do you have?
1.1.3
...

Which version of this plugin (homebridge-ewelink) do you have?
2.24.1
...

**Please paste any relevant logs below. It helps if you can turn `debug` and `debugReqRes` in the package settings for more thorough logging.**
> If you are posting an error then it is helpful for me to also see the previous few lines as this can show the cause of the error.

...

**Comment by bwp91** [comment]
Hi,
I'm going to need more info.
Which sonoff device do you use for your garage door?
And it would help me immensely if i could see homebridge logs so i can see what could be causing this issue.

**Comment by allanjeevan** [comment]
I don't know which sonoff device as it was fixed by another person and i
was not present at home but the manufacturer is New Smart and the model G1,
in the log much is not visible but when i click the open button it opens
the gate and after a few seconds it states as not responsive and when i
click it again it shows as closed when the gate is actually open.
i Have attached the log

**Comment by bwp91** [comment]
i can't see the logs, i think you have replied by email and the attachment hasn't been uploaded here.

**Comment by allanjeevan** [comment]
Sorry.
[Ewelink Log.docx](https://github.com/bwp91/homebridge-ewelink/files/5179826/Ewelink.Log.docx)

**Comment by bwp91** [comment]
Thank you. I see it really doesn't show anything going wrong.
Would you be able to copy and paste your config for this plugin, please remember to remove your username and password!

**Comment by allanjeevan** [comment]
Sure.
[Ewelink Config.pdf](https://github.com/bwp91/homebridge-ewelink/files/5179843/Ewelink.Config.pdf)

**Comment by bwp91** [comment]
Please would you try a pre-release version to see if the issue is fixed?
You can do this by running this command through the homebridge terminal:
```sudo npm install homebridge-ewelink@beta -g```
Then please restart Homebridge and see if anything has improved?
Thanks

**Comment by allanjeevan** [comment]
Sure. Right now I am not at home so I will try it tomorrow and let you know. 

Thank You

**Comment by bwp91** [comment]
Sure let me know how you get on!

**Comment by allanjeevan** [comment]
I tried but the plugin itself is not working tried to restart homebridge as well but no use.

**Comment by bwp91** [comment]
When you say the plugin itself isn't working, how do you mean?
Anything in the logs?

**Comment by allanjeevan** [comment]
Yeah it says it could not be updated because it's in use
![image](https://user-images.githubusercontent.com/70219499/92382494-51b5a280-f12a-11ea-8eb7-45091072dd0a.png)

**Comment by allanjeevan** [comment]
And by the way its just a request, i actually tried to find jaguar land rover app plugin found one but the preconditioning dosent work. So could you i mean if u are free make a plugin on it. I would love to try but i don't know how.

**Comment by bwp91** [comment]
Im afraid as I don't have a device I can even mimic as a garage door opener this is going to have to be a bit of trial and error.
Could you try my latest pre-release?
You'll need to run the command again:
`sudo npm install homebridge-ewelink@beta -g`
and then restart homebridge.
thanks

**Comment by allanjeevan** [comment]
I tried but it's still the same no response after the gate is open and sorry for the late reply

**Comment by bwp91** [comment]
Could I contact you on the homebridge discord?
https://discord.gg/WSbZSm

**Comment by allanjeevan** [comment]
Sure.

**Comment by bwp91** [comment]
let me know your username on there

**Comment by allanjeevan** [comment]
allan.__

**Comment by allanjeevan** [comment]
Its working perfectly thanks a lot..
