### ISSUE TITLE
Lock type accessory

### ISSUE THREAD

**Issue by csupi003** [bwp91/homebridge-ewelink#81]
I have an inching Sonoff device and I use it for my gate lock to open. Right now its only a switch which turns on for one sec and then off and would look nice if the icon would be a lock. Is it possible to add this feature ? 

Thanks in advance,

**Comment by bwp91** [comment]
Hi, i'll look into this!
Is it as simple as:
click the switch and it locks then
click the switch and it unlocks etc?

**Comment by csupi003** [comment]
Hello,
It's the other way around. Click the button to open the door. Since it's attached to a controller it works like a push button and I have no control over the lock function. 
[I achived it using HAA](https://github.com/RavenSystem/esp-homekit-devices/wiki/Lock-Mechanism) but because of cross-platform access it would be nice to have it with ewelink as well. 
![ezgif-6-96df49718ce0](https://user-images.githubusercontent.com/40438631/92415147-e1257a80-f157-11ea-9fcd-f85e4d509cb1.gif)

**Comment by bwp91** [comment]
Can I invite you to the homebridge discord channel to message you?
https://discord.gg/WSbZSm

**Comment by bwp91** [comment]
Lock accessory types will be available to all in the upcoming v2.25.0 release :)
