### ISSUE TITLE
v2.25.0 L1 Test

### ISSUE THREAD

**Issue by muriloscosta** [bwp91/homebridge-ewelink#83]
**What issue do you have? Please be as thorough and explicit as possible.**

My L1s worked fine with plugin homebridge-ewelink-sonoff@2.10.2, any newer plugin introduces lagging to L1s:

L1 response time using homebridge-ewelink-sonoff@2.10.2 - Instantaneous, independent of number of times i turn it on/off
L1 response time using homebridge-ewelink@2.25.0 - Instantaneous at first time, adds 1s to any next try. On 5th attempt it´s about 5 to 6 second to turn it on/off.

**Details of your setup.**
Do you use Homebridge or HOOBS?
Homebridge
...

Which version of Homebridge/HOOBS do you have?
Homebridge v1.1.6
Node.js v12.18.3
Npm v6.14.8
...

Which version of this plugin (homebridge-ewelink) do you have?
homebridge-ewelink v2.25.0
...

**Please paste any relevant logs below. It helps if you can turn `debug` and `debugReqRes` in the package settings for more thorough logging.**
> If you are posting an error then it is helpful for me to also see the previous few lines as this can show the cause of the error.

...

**Comment by bwp91** [comment]
Hi thanks for your feedback.
I'll have a look into the changes that I made after 2.10.2 to see what could be causing the lag and get back to you 👍

**Comment by bwp91** [comment]
Could I reach out to you on the homebridge discord channel?
https://discord.gg/WSbZSm

**Comment by muriloscosta** [comment]
I´ve tried https://discord.gg/WSbZSm by it says invitation has expired.

**Comment by bwp91** [comment]
https://discord.gg/aPC8aZ
The invitations last for 24 hours 😁

**Comment by MrAndersonMD** [comment]
I have a Sonoff L1 5m + 5m, with Homebridge 1.1.6 and Homebridge EweLink 2.25.2. It's working really fine, no bugs.

**Comment by bwp91** [comment]
@MrAndersonMD thanks for the feedback glad to hear it's working well!

@muriloscosta are you still having lagging issues?

**Comment by muriloscosta** [comment]
@bwp91

Just tested L1 with plugin 2.27.2, unfortunately the lagging issue persists, about 5s to get response from L1s. if i revert to 2.10.2, i have no issues

**Comment by muriloscosta** [comment]
@bwp91

Just installed you latest plugin 3.0 and it looks good so far, till now, no lagging in my L1s.

Thank you so much!

**Comment by bwp91** [comment]
Ah excellent! I was hoping at least one of the changes I made would have helped!

**Comment by bwp91** [comment]
Let me know in a couple of days if it's still working well and I can get this issue closed!

**Comment by bwp91** [comment]
@muriloscosta all still good with the L1?

**Comment by muriloscosta** [comment]
@bwp91 Yes!!!! All good with L1s, thank you!
