### ISSUE TITLE
LAN IP addresses

### ISSUE THREAD

**Issue by AQPSal** [bwp91/homebridge-ewelink#84]
Homebridge on RPI4, Ubuntu 20.04.1, nodejs 14

4 sonoff items, randomly one gets LAN address upon restart of homebridge service but the other three show as not LAN compatible. Latest update reports a change in LAN address to my router address. All sonoff items are in a separate VLAN. When trying to connect to the sonoff items using the router address, it fails as expected and changes connections to WS. 

May I suggest offering a configuration mode to hardcode the IP address of the switches/lights/etc?

**Comment by bwp91** [comment]
> May I suggest offering a configuration mode to hardcode the IP address of the switches/lights/etc?

This is something I could definitely implement. Give me some time and it's something I can do. I will be in contact.

When working with separate VLANs it makes it very hard to code and the easiest solution would be to implement hardcoded IPs via the config.

**Comment by bwp91** [comment]
Hi @AQPSal 
Please try updating to v2.25.1 and then adding this to the json config file in the appropriate place:
```json
"ipOverride": {
   "100012ab34": "192.168.1.14"
}
```
or for multiple devices
```json
"ipOverride": {
   "100012ab34": "192.168.1.14",
   "100012ab35": "192.168.1.15",
   "100012ab36": "192.168.1.16"
}
```
where the value on the left is the ewelink device id and the right value is (obviously!) the ip.
I'm assuming you're comfortable with editting the json directly... but let me know if you need more explanation.

Then restart Homebridge and ideally:
- the devices will be configured with the IP you have set in the config
- any "incorrect" future IP updates will be ignored by the plugin.

Let me know!

**Comment by AQPSal** [comment]
Seems to be working well. I have only tested it for a couple of minutes. I'll report back in a few days. Thank you!

**Comment by AQPSal** [comment]
After a few hours of testing, it works perfectly. Thank you again. Fantastic job1

**Comment by bwp91** [comment]
Ah glad it's worked for you. Maybe this feature will help others too :)
