### ISSUE TITLE
Lan mode

### ISSUE THREAD

**Issue by motogon** [bwp91/homebridge-ewelink#88]
The request to add a possibility manual additions ip

**Comment by bwp91** [comment]
Hi, just to clarify,
Are you looking to define a fixed IP address for a LAN device?

**Comment by motogon** [comment]
yes , I use static ip at each device

**Comment by bwp91** [comment]
This feature is already available. Please see the last configuration option `ipOverride`at
https://github.com/bwp91/homebridge-ewelink/wiki/Configuration#additional-configuration

You will need to edit the homebridge json configuration directly. Let me know if you need more help.
Thanks!

**Comment by bwp91** [comment]
did you get this working?
