### ISSUE TITLE
ZigBee Motion Sensor

### ISSUE THREAD

**Issue by edmarts** [bwp91/homebridge-ewelink#89]
**What issue do you have? Please be as thorough and explicit as possible.**

...The Zigbee Motion Sensor appears in my homebridge / Homekit but doesn't work. The zigbee door sensor is ok!!

**Details of your setup.**
Do you use Homebridge or HOOBS?

...Homebridge

Which version of Homebridge/HOOBS do you have?

...1.1.6

Which version of this plugin (homebridge-ewelink) do you have?

...2.26.0

**Please paste any relevant logs below. It helps if you can turn `debug` and `debugReqRes` in the package settings for more thorough logging.**
> If you are posting an error then it is helpful for me to also see the previous few lines as this can show the cause of the error.

...[Kitchen Sensor] found in eWeLink but LAN mode unavailable as unsupported/shared device.

**Comment by bwp91** [comment]
Hi, great to hear the door sensor is working.
Also great to have someone that has the zb motion sensor.

By any chance are you on the Homebridge discord website?

**Comment by edmarts** [comment]
> By any chance are you on the Homebridge discord website?

...No, i'm not

**Comment by bwp91** [comment]
Would you be happy to share your zigbee device with my ewelink account?

If so the details are:
country code 44
email ben_sa@thepotterfamily.uk

It would only need to be for a few minutes and it allows me to see how the data is passed from ewelink to homebridge.

If not then getting it to work would be a slower process but definitely possible.

**Comment by edmarts** [comment]
Ok, I just share to you.

**Comment by bwp91** [comment]
thats great thank you I have them in my home app now.
would you be able to activate the motion sensor?

**Comment by edmarts** [comment]
Ok, just did it

**Comment by bwp91** [comment]
and again please! i know this is a pain... once more should be enough :)

**Comment by edmarts** [comment]
No problem!! I did

**Comment by bwp91** [comment]
sorry -- and again please!

**Comment by edmarts** [comment]
Ok!!

**Comment by bwp91** [comment]
ok i have the motion sensor working now. i also would like to check the door sensor is still working as I have made changes to that area of the code.

any chance you could open and close the door sensor you have?

**Comment by edmarts** [comment]
ok!

**Comment by bwp91** [comment]
Please update to v2.26.1 and see if it is working better

**Comment by edmarts** [comment]
I just updated. Now it's working! He blinks informing that there was motion and immediately goes back without motion. Is this how it should work?

**Comment by bwp91** [comment]
The amount of time that the tile "lights up" for can be changed in the package settings in the "Optional" section. Its the "Sensor Length".

<img width="621" alt="Screenshot 2020-09-14 at 20 35 19" src="https://user-images.githubusercontent.com/43026681/93130073-e63f7800-f6c9-11ea-958b-e0ac20ffd9cd.png">

Perhaps change it to 60 seconds so it is consistent with the eWeLink app?
Don't forget to restart Homebridge after you make changes to the settings

**Comment by edmarts** [comment]
Ah ok, I change to 60 seconds now! It's works!!
Thanks!!

**Comment by bwp91** [comment]
Amazing! One more device that I now know is working!
Let me know if you ever decide to buy the [temperature sensor](https://www.itead.cc/sonoff-snzb-02-zigbee-temperature-and-humidity-sensor.html) 😂

**Comment by edmarts** [comment]
😂😂 You bet!!!
Thanks again!! 👏🏻

**Comment by martivax** [comment]
I have the Zigbee temp sensor!

Works fine.

Still having issues with the motion sen sor though

**Comment by bwp91** [comment]
What issues are you having with the motion sensor?

**Comment by martivax** [comment]
OK. I got it work by setting the 60 seconds as described above. But seems. abut intermittent. Does not detect movement all the time. (I am trying to control my bathroom light) I waved at it and 4 minutes later it turned the light on :/

**Comment by bwp91** [comment]
> If you need anything to confirm the temp/humidity sensors is working properly let me know.

Would you be happy to share the zigbee bridge with my ewelink account?
I haven't yet added EVE history for the zigbee temperature sensor (as I didn't know anyone that had it). But I would like to implement this... and would need it shared for a while so I can see whether the history is working.

**Comment by martivax** [comment]
> > If you need anything to confirm the temp/humidity sensors is working properly let me know.
> 
> Would you be happy to share the zigbee bridge with my ewelink account?
> I haven't yet added EVE history for the zigbee temperature sensor (as I didn't know anyone that had it). But I would like to implement this... and would need it shared for a while so I can see whether the history is working.

Sure. How do we do that?
Just let me know

**Comment by bwp91** [comment]
> Sure. How do we do that?
> Just let me know

Which country are you based in?

**Comment by martivax** [comment]
> > Sure. How do we do that?
> > Just let me know
> 
> Which country are you based in?

Portugal GMT+1

**Comment by bwp91** [comment]
Okay in the eWeLink app go to your zigbee bridge settings and click on "share".
Then share to:
country code 44 (united kingdom)
email: bwp91@icloud.com

**Comment by martivax** [comment]
> Okay in the eWeLink app go to your zigbee bridge settings and click on "share".
> Then share to:
> country code 44 (united kingdom)
> email: [bwp91@icloud.com](mailto:bwp91@icloud.com)

Done. I shared my pool motion sensor also (TH16) in case you are interested in that one too

**Comment by bwp91** [comment]
Thanks for that. The eve graphs seems to be working initially. it will be interesting to see tomorrow morning how they look if you're happy to keep the devices shared until tomorrow morning? at least we are in the same time zone!

also my reason for deleting your last comment is just because it has my email address in it :)

**Comment by martivax** [comment]
Makes sense. You can keep it as long as you need. You have my email address now from ewe link I believe so you can just iMessage me when you are done with it

**Comment by bwp91** [comment]
> iMessage me when you are done with it

will do!

**Comment by edmarts** [comment]
Hi! I have a question about the motion sensor:

When the sensor detect motion, the sensor flashes in the homekit right? But shouldn't it stay ON (blinks) while detecting motion and only turn OFF when there is no more motion? It just flashes for the time that was determined in the sensor length  and then goes off again.

For instance: if I create an automation that makes the kitchen light turn on when it detects motion, and turn off when there is no motion, it will turn off the lights after 60 seconds even though I am in the kitchen, right?

**Comment by martivax** [comment]
I am still  figuring it out. I just got it to work yesterday. 

But on the ewelink app it also just detects the motion and goes off. 

I can help you out more later

**Comment by bwp91** [comment]
I'm currently watching the logs of the zigbee motion sensors that are shared to my account, trying to work out at which point ewelink sends a message saying that motion is no longer detected. as it seems to vary.

@martivax dont suppose you're able to walk past one of your sensors? 🤣

**Comment by martivax** [comment]
Nope. I ain’t home right now ) 

Maybe a dog will walk by

**Comment by bwp91** [comment]
Your dogs are being very helpful indeed! Give them a treat when you get home!
Gonna put my thoughts into words and explain what I think...

**Comment by bwp91** [comment]
My implementation of the motion sensor was based on the [RF Bridge motion sensor](https://sonoff.tech/product/accessories/pir2) which does **not** send a "motion no longer detected" alert to this plugin, so I had to implement a configurable timer to turn the sensor off.

The ZB Bridge motion sensor **does** send a "motion no longer detected" alert to this plugin so my thought is to use this to turn the sensor off instead of the configurable timer (ie the 60 seconds).

With regards to this "motion no longer detected" alert, it seems it is sent from the device 60 seconds after detecting motion. For example if you were to briefly walk past the sensor then it would turn off 60 seconds later. If during this 60 seconds the sensor detects further motion then it seems to "restart" the 60 seconds, so in general the "motion no longer detected" alert will be sent to this plugin after 60 seconds of not detecting any motion.

This is based on what I have seen from the logs - unfortunately there is no sonoff documentation I can refer to.

So I can certainly change this plugin so it depends on the  "motion no longer detected" alert rather than the configurable 60 seconds. I think this makes sense.

> For instance: if I create an automation that makes the kitchen light turn on when it detects motion, and turn off when there is no motion, it will turn off the lights after 60 seconds even though I am in the kitchen, right?

With regards to creating an automation, yes, you could set it up as to turn a kitchen light on when the sensor detects motion. This is the straightforward part. When to turn the light off is the fiddly part! Also depends on where the sensor can detect motion. Example: you walk into the kitchen passing the sensor which turns the light on. If you're then cooking a meal in an area which the sensor can't "see", then the sensor will send the "motion no longer detected" alert to this plugin, thus turning the light off.

A bit like going to a restaurant toilet and having to wave around to turn back on the automatic light 🤣

Perhaps an alternative to
> and turn off when there is no motion
could be to use an automation shortcut for example

* if the sensor stops detecting motion
* then wait five minutes (or ten)
* then turn the light off

Just to give you a little more time if you don't activate the sensor while you're in the kitchen.

These are my thoughts.

**Comment by edmarts** [comment]
Yes I agree!
I sent this suggestion to ewelink, who could setup a time for not detecting motion.

As you said, we currently need to wave for the light to stay on. The ideal would be to determine that time really.
These are my thoughts too!

**Comment by bwp91** [comment]
> So I can certainly change this plugin so it depends on the "motion no longer detected" alert rather than the configurable 60 seconds. I think this makes sense.

This has been implemented in v2.27.0

Let me know how you get on with it!

**Comment by edmarts** [comment]
I created a scene on ewelink that when detecting motion turns on the light and when there is no motion it turns off the light. After 60 seconds, even when I'm in the same place, the light goes off. It must be an ewelink problem.

With this update, the door sensor was accusing that the battery is low. In my case, it's a new battery that I changed last week.

**Comment by bwp91** [comment]
> I created a scene on ewelink that when detecting motion turns on the light and when there is no motion it turns off the light. After 60 seconds, even when I'm in the same place, the light goes off. It must be an ewelink problem.

An alternative could be creating a shortcut automation through Home app:

![IMG_4332](https://user-images.githubusercontent.com/43026681/93265204-28d38400-f7a0-11ea-9d47-98784897b7f0.PNG)

and the shortcut is something like:

![IMG_4333](https://user-images.githubusercontent.com/43026681/93265255-3db01780-f7a0-11ea-8b5e-2282f86602d9.PNG)

where in this case the "Set Porch Bulb" is to set it to off.

**Comment by bwp91** [comment]
> With this update, the door sensor was accusing that the battery is low. In my case, it's a new battery that I changed last week.

Re this, would help if I could see the data of your device which would require sharing with my account again. Obviously something isn't quite right!

**Comment by bwp91** [comment]
Reopening this as there could be something going wrong :)

**Comment by edmarts** [comment]
Ok, tell me your email account to share you

**Comment by bwp91** [comment]
ben_sa@thepotterfamily.uk 
country code 55

**Comment by edmarts** [comment]
Ok. I did

**Comment by bwp91** [comment]
@edmarts thanks. got it. ill get back to you later!

**Comment by bwp91** [comment]
any chance your battery could be more like 80%?

**Comment by edmarts** [comment]
I put a new one about 10 days ago... how long does a zigbee battery life? A year?

**Comment by edmarts** [comment]
Sorry, I put a new battery in the door sensor!! The motion sensor be with the battery that come from sonoff

**Comment by edmarts** [comment]
I have the sensors about one month

**Comment by bwp91** [comment]
So the other three zigbee devices report the battery state as a number of out 100 - which seems the most obvious way of reporting it.
Your sensor is reporting the battery as 8.

One reason for this could be that the door/window sensor device reports the battery out of 10 rather than 100. So effectively your battery could be 8/10 = 80%.

Another reason could be that your device was shipped with a low battery in the first place? Could I suggest you change the battery to one you know is full (if you have a spare one?) just to see what the device then reports it as.

**Comment by edmarts** [comment]
It could be that the battery really came low. And the presence sensor is activated at all times. The door sensor only about 4 times a day. I don't have another battery to test, but 80% I think is correct

**Comment by bwp91** [comment]
I'm hesitant to change the code just in case the battery did come low.
Would you be able to try the motion sensor batteries in the door sensor? Or are they different?

**Comment by edmarts** [comment]
There are different... other size

**Comment by edmarts** [comment]
But it shows 80% must be correct and not 8% because as I said, I changed the battery for a new one 10 days ago only

**Comment by bwp91** [comment]
I'm in a difficult position and I found someone else with the door sensor and their battery said 72% so it must be out of 100 and not 10.
However, I've made a temporary solutions for now.
Please update to the version I have just released, v2.27.1.
Then in the Homebridge config, find the eWeLink plugin section and add 
`"ZBDWBatt": true,`
as a new line between the `"password": ***,` and `"debug": ***,` lines.
Then restart Homebridge. Your battery should then be reported as 80% (a multiplication of 10).

**Comment by edmarts** [comment]
It's works!! Now shows 80%

**Comment by bwp91** [comment]
Fab.
But please do be aware that that reading of 8 could genuinely be out of 100.
Which means you'll run into errors if one day you change the battery and the new reading is 100, then this will then be multiplied to give a Homebridge reading of 100x100 😅

**Comment by bwp91** [comment]
Closing as I do now believe everything in this issue in resolved!

**Comment by bwp91** [comment]
@edmarts would you be able to unshare your devices with me now that everything seems working well (?)
Thanks

**Comment by martivax** [comment]
Sure. 

Thanks!

**Comment by edmarts** [comment]
I've already unshared ... do the devices still appear on your ewelink?

**Comment by bwp91** [comment]
@edmarts i tagged the wrong person sorry!
Both of your devices are gone now!
