### ISSUE TITLE
Garage sensor

### ISSUE THREAD

**Issue by zelik888** [bwp91/homebridge-ewelink#90]
**Please explain your feature request in one sentence.**
...
Could we link the open close status to another sensor in homekit/homebridge? I see currently sonoff sensors are supported. 
**Is your feature request related to a problem? Please describe.**
...
No
**Any particular Sonoff devices that this relates to?**
...

**Anything else?**
...

**Comment by bwp91** [comment]
Hi, thanks for the suggestion.
Homebridge plugins can only access the status of their own accessories, ie, it isn't possible for this plugin to read the sensor status of another plugin.
So right now I cannot see a way of making this possible.
The only sonoff sensor that can be used this way is the DW2 device.

**Comment by williamccc** [comment]
I recently purchased the GD-DC5 garage opener. It can be shown as a Switch, and the status of the magnetic sensor is shown as On/Off status. Is there anyway to incorporate this into a Garage type but not a Switch type?

**Comment by bwp91** [comment]
> I recently purchased the GD-DC5 garage opener. It can be shown as a Switch, and the status of the magnetic sensor is shown as On/Off status. Is there anyway to incorporate this into a Garage type but not a Switch type?

I'd never heard of this device but I see it works with eWeLink so there *shouldn't* be any reason why I couldn't implement it.

Since it's a new device for me, it makes things a little more complicated. Ideally I would need you to share the device to my ewelink account so I can see how the data is passed. 

Would you be happy to do this at a time when you are home?

**Comment by zelik888** [comment]
> Hi, thanks for the suggestion.
> Homebridge plugins can only access the status of their own accessories, ie, it isn't possible for this plugin to read the sensor status of another plugin.
> So right now I cannot see a way of making this possible.
> The only sonoff sensor that can be used this way is the DW2 device.

Thank you, I didn't know that limitation, that is quite unfortunate. I guess I'll have to go get a sonoff sensor then!

**Comment by bwp91** [comment]
I have decided to close this issue as:
- No possibility to use garage doors with a sensor that isnt DW2
- GD-DC5 garage opener is a work in progress with a user I am in contact with on Discord

Thanks
