### ISSUE TITLE
Low Battery Notification

### ISSUE THREAD

**Issue by bwp91** [bwp91/homebridge-ewelink#92]
With the recent version 2.27, battery information has been added for zigbee devices and DW2 sensor.

I have currently hard coded the threshold to 25%, ie, if a battery level drops below this, then HomeKit will display a low battery status.

So I wanted some opinions on this value of 25%:

* Do you think it's too high? Would a value of eg 10% be better?
* Would you prefer the option to define this % value yourself via the config?

Ben 😃

**Comment by imtitanic** [comment]
I think 25% it's a good percent, I mean it's a necessary change but is not "urgent!!!" and you have enough time to prepare you for a change batteries (charge other ones, buy it, etc). Now, if is possible setting the % by the user, anyone can decide what is the crucial moment (of the battery) for itself and put it. **But, again, 25% it's a good standard for me.**

**Comment by bwp91** [comment]
Thanks for taking the time to give your feedback @imtitanic - I see we have the same idea with the 25%!
I have decided to go with the custom configuration (as not much feedback on here) so people can choose their own threshold. With a default of 25%.
This config option will be available in the upcoming 3.0 release.
