### ISSUE TITLE
"[eWeLink] [<deviceName>] could not be updated as improper configuration."

### ISSUE THREAD

**Issue by rodrigobongers** [bwp91/homebridge-ewelink#94]
Hello,

I'm trying to use Sonoff DUALR2 (PSF-B04-GL) configured as Blind Device Type with Two Switches without DW2 sensor and I get this message on the console: "[eWeLink] [<deviceName>] could not be updated as improper configuration." when I send the command to open/close.

The SW1 and SW2 doesn't turn off after 10seconds and I can't stop the blinds on 50% for example.

HomeBridge Version v1.2.2
homebridge-ewelink v2.27.2
Firmware Version v3.4.1

Any idea?
Thanks!

**Comment by bwp91** [comment]
Hi, please would you send me the homebridge-ewelink part of the homebridge config file... **taking out your username and password**.
This is to see where the `improper configuration` error is coming from.

Implementing blinds has always been a bit of guess work -- basically because Ive never had someone using the blinds tell me if it works or not!

But hope to get this working for you!

**Comment by rodrigobongers** [comment]
Thanks for the answer!

Below my config file:

{
    "bridge": {
        "name": "Homebridge EB89",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": 52977,
        "pin": "XXX-XX-XXX"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "platform": "config"
        },
        {
            "name": "eWeLink",
            "countryCode": "**",
            "username": "*****",
            "password": "*****",
            "debug": true,
            "debugReqRes": true,
            "sensorTimeLength": 60,
            "sensorTimeDifference": 120,
            "valveTimeLength": 20,
            "hideTHSwitch": false,
            "hideZBLDPress": false,
            "groups": [
                {
                    "deviceId": "<deviceId>",
                    "type": "blind",
                    "setup": "twoSwitch",
                    "operationTime": 100
                }
            ],
            "bridgeSensors": [
                {
                    "type": "motion"
                }
            ],
            "platform": "eWeLink"
        }
    ]
}

**Comment by bwp91** [comment]
And just to check as I saw the `"deviceId": "",` line is blank, have you removed the device id for the purposes of posting it here?

**Comment by rodrigobongers** [comment]
Yes!

**Comment by bwp91** [comment]
Could I message you on the Homebridge discord channel?
https://discord.gg/WmkGj4

**Comment by rodrigobongers** [comment]
Sure!
