### ISSUE TITLE
EACHEN 2ch switch recognized as valve

### ISSUE THREAD

**Issue by cibertribi** [bwp91/homebridge-ewelink#99]
Hello, thanks for this great plugin. I've bought and installed an Eachen 2CH switch using it in inching mode to open 2 electric door openers. It runs on ewelink app and I can see them in Homekit. However they are shown as water valves, so some automations are not posible (for example opening the door when I get home). The other thing is that when I get out of the LAN, homekit forgets the names of the switches ( I name them lateral door, and front door, they change to the name of the device which is door, so I don't know which one to press to open a certain door)
Well , I'm new here, sorry to bother. Let me know if I can help you with this.

**Comment by bwp91** [comment]
> I've bought and installed an Eachen 2CH switch using it in inching mode to open 2 electric door openers. It runs on ewelink app and I can see them in Homekit. However they are shown as water valves, so some automations are not posible (for example opening the door when I get home).

Hi, this is something I will be able to look into. Could you send me a link of the exact product you have?

> The other thing is that when I get out of the LAN, homekit forgets the names of the switches ( I name them lateral door, and front door, they change to the name of the device which is door, so I don't know which one to press to open a certain door)
I don't totally understand what you mean by this. When you add a new device, HomeKit will use the name of the device as it is in the eWeLink app, but then if you rename the device in HomeKit (eg Home app) then it should not change back as it is then independent of the device name in Homebridge and eWeLink app,

**Comment by cibertribi** [comment]
Thanks for your answer.
The switch is this one:

http://www.diymalls.com/2-Channel-DIY-SWITCH-WIFI-Wireless-Switch-Inching-Self-locking-Interlock-DC7-32V

EACHEN ST DC2

For the second issue, I guess it is a problem from homekit. When I add the homebridge hub to Home, i add the accesory and the name is DOOR. Then I go inside the settings of the device and split it into 2 accesories. Then I change the names , DOOR1 and DOOR2. It works fine, I see the 2 separate switches in Home. But at some moment something gets reset and the switches are named DOOR AND DOOR, so it's impossible to know what door you are opening.

But I think if the first issue is solved maybe then the second issue is solved too. Or they are completely unrelated....

So I propose  we focus on the first issue and leave the other one for later. 

Let me kmow if you need more info

Cheers!

**Comment by bwp91** [comment]
Could I talk to you on the homebridge discord channel?
https://discord.gg/7X36mdw
once youve logged in my username on there is "bwp91"

**Comment by cibertribi** [comment]
Solved with 3.1 , now device is recognized as switch.
